.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_draw_message
/* 17713C 8024E71C 27BDFFC8 */  addiu      $sp, $sp, -0x38
/* 177140 8024E720 8FA2004C */  lw         $v0, 0x4C($sp)
/* 177144 8024E724 AFB60030 */  sw         $s6, 0x30($sp)
/* 177148 8024E728 8FB60048 */  lw         $s6, 0x48($sp)
/* 17714C 8024E72C AFB00018 */  sw         $s0, 0x18($sp)
/* 177150 8024E730 0080802D */  daddu      $s0, $a0, $zero
/* 177154 8024E734 AFB1001C */  sw         $s1, 0x1C($sp)
/* 177158 8024E738 00A0882D */  daddu      $s1, $a1, $zero
/* 17715C 8024E73C AFB20020 */  sw         $s2, 0x20($sp)
/* 177160 8024E740 00C0902D */  daddu      $s2, $a2, $zero
/* 177164 8024E744 AFBF0034 */  sw         $ra, 0x34($sp)
/* 177168 8024E748 AFB5002C */  sw         $s5, 0x2C($sp)
/* 17716C 8024E74C AFB40028 */  sw         $s4, 0x28($sp)
/* 177170 8024E750 AFB30024 */  sw         $s3, 0x24($sp)
/* 177174 8024E754 000298C2 */  srl        $s3, $v0, 3
/* 177178 8024E758 30540001 */  andi       $s4, $v0, 0x1
/* 17717C 8024E75C 24020001 */  addiu      $v0, $zero, 0x1
/* 177180 8024E760 16820002 */  bne        $s4, $v0, .Lfilemenu_8024E76C
/* 177184 8024E764 32730001 */   andi      $s3, $s3, 0x1
/* 177188 8024E768 2652FFFE */  addiu      $s2, $s2, -0x2
.Lfilemenu_8024E76C:
/* 17718C 8024E76C 2E020100 */  sltiu      $v0, $s0, 0x100
/* 177190 8024E770 10400018 */  beqz       $v0, .Lfilemenu_8024E7D4
/* 177194 8024E774 2602FF5E */   addiu     $v0, $s0, -0xA2
/* 177198 8024E778 2C42004E */  sltiu      $v0, $v0, 0x4E
/* 17719C 8024E77C 1440000A */  bnez       $v0, .Lfilemenu_8024E7A8
/* 1771A0 8024E780 2A0200C6 */   slti      $v0, $s0, 0xC6
/* 1771A4 8024E784 0200202D */  daddu      $a0, $s0, $zero
/* 1771A8 8024E788 0220282D */  daddu      $a1, $s1, $zero
/* 1771AC 8024E78C 0240302D */  daddu      $a2, $s2, $zero
/* 1771B0 8024E790 0280382D */  daddu      $a3, $s4, $zero
/* 1771B4 8024E794 AFB60010 */  sw         $s6, 0x10($sp)
/* 1771B8 8024E798 0C093848 */  jal        filemenu_draw_char
/* 1771BC 8024E79C AFB30014 */   sw        $s3, 0x14($sp)
/* 1771C0 8024E7A0 08093A0C */  j          .Lfilemenu_8024E830
/* 1771C4 8024E7A4 00000000 */   nop
.Lfilemenu_8024E7A8:
/* 1771C8 8024E7A8 1440000A */  bnez       $v0, .Lfilemenu_8024E7D4
/* 1771CC 8024E7AC 2604FF3A */   addiu     $a0, $s0, -0xC6
/* 1771D0 8024E7B0 3C028015 */  lui        $v0, %hi(D_PAL_8014AE4C)
/* 1771D4 8024E7B4 8C42AE4C */  lw         $v0, %lo(D_PAL_8014AE4C)($v0)
/* 1771D8 8024E7B8 00021880 */  sll        $v1, $v0, 2
/* 1771DC 8024E7BC 00621821 */  addu       $v1, $v1, $v0
/* 1771E0 8024E7C0 00641821 */  addu       $v1, $v1, $a0
/* 1771E4 8024E7C4 00031880 */  sll        $v1, $v1, 2
/* 1771E8 8024E7C8 3C108025 */  lui        $s0, %hi(D_filemenu_80250804)
/* 1771EC 8024E7CC 02038021 */  addu       $s0, $s0, $v1
/* 1771F0 8024E7D0 8E100804 */  lw         $s0, %lo(D_filemenu_80250804)($s0)
.Lfilemenu_8024E7D4:
/* 1771F4 8024E7D4 06010016 */  bgez       $s0, .Lfilemenu_8024E830
/* 1771F8 8024E7D8 240400F3 */   addiu     $a0, $zero, 0xF3
/* 1771FC 8024E7DC 0220282D */  daddu      $a1, $s1, $zero
/* 177200 8024E7E0 0240302D */  daddu      $a2, $s2, $zero
/* 177204 8024E7E4 0280382D */  daddu      $a3, $s4, $zero
/* 177208 8024E7E8 AFB60010 */  sw         $s6, 0x10($sp)
/* 17720C 8024E7EC 0C093848 */  jal        filemenu_draw_char
/* 177210 8024E7F0 AFB30014 */   sw        $s3, 0x14($sp)
/* 177214 8024E7F4 92030000 */  lbu        $v1, 0x0($s0)
/* 177218 8024E7F8 240200FD */  addiu      $v0, $zero, 0xFD
/* 17721C 8024E7FC 1062000C */  beq        $v1, $v0, .Lfilemenu_8024E830
/* 177220 8024E800 0040A82D */   daddu     $s5, $v0, $zero
.Lfilemenu_8024E804:
/* 177224 8024E804 0220282D */  daddu      $a1, $s1, $zero
/* 177228 8024E808 0240302D */  daddu      $a2, $s2, $zero
/* 17722C 8024E80C 0280382D */  daddu      $a3, $s4, $zero
/* 177230 8024E810 92040000 */  lbu        $a0, 0x0($s0)
/* 177234 8024E814 26100001 */  addiu      $s0, $s0, 0x1
/* 177238 8024E818 AFB60010 */  sw         $s6, 0x10($sp)
/* 17723C 8024E81C 0C093848 */  jal        filemenu_draw_char
/* 177240 8024E820 AFB30014 */   sw        $s3, 0x14($sp)
/* 177244 8024E824 92030000 */  lbu        $v1, 0x0($s0)
/* 177248 8024E828 1475FFF6 */  bne        $v1, $s5, .Lfilemenu_8024E804
/* 17724C 8024E82C 02228821 */   addu      $s1, $s1, $v0
.Lfilemenu_8024E830:
/* 177250 8024E830 8FBF0034 */  lw         $ra, 0x34($sp)
/* 177254 8024E834 8FB60030 */  lw         $s6, 0x30($sp)
/* 177258 8024E838 8FB5002C */  lw         $s5, 0x2C($sp)
/* 17725C 8024E83C 8FB40028 */  lw         $s4, 0x28($sp)
/* 177260 8024E840 8FB30024 */  lw         $s3, 0x24($sp)
/* 177264 8024E844 8FB20020 */  lw         $s2, 0x20($sp)
/* 177268 8024E848 8FB1001C */  lw         $s1, 0x1C($sp)
/* 17726C 8024E84C 8FB00018 */  lw         $s0, 0x18($sp)
/* 177270 8024E850 03E00008 */  jr         $ra
/* 177274 8024E854 27BD0038 */   addiu     $sp, $sp, 0x38
