.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_pal_8024d6a0
/* 1760C0 8024D6A0 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1760C4 8024D6A4 AFB00018 */  sw         $s0, 0x18($sp)
/* 1760C8 8024D6A8 00A0802D */  daddu      $s0, $a1, $zero
/* 1760CC 8024D6AC AFB1001C */  sw         $s1, 0x1C($sp)
/* 1760D0 8024D6B0 00C0882D */  daddu      $s1, $a2, $zero
/* 1760D4 8024D6B4 3C04001F */  lui        $a0, (0x1F0055 >> 16)
/* 1760D8 8024D6B8 34840055 */  ori        $a0, $a0, (0x1F0055 & 0xFFFF)
/* 1760DC 8024D6BC AFBF0020 */  sw         $ra, 0x20($sp)
/* 1760E0 8024D6C0 0C0493E5 */  jal        func_PAL_80124F94
/* 1760E4 8024D6C4 0000282D */   daddu     $a1, $zero, $zero
/* 1760E8 8024D6C8 3C04001F */  lui        $a0, (0x1F0055 >> 16)
/* 1760EC 8024D6CC 34840055 */  ori        $a0, $a0, (0x1F0055 & 0xFFFF)
/* 1760F0 8024D6D0 240500C0 */  addiu      $a1, $zero, 0xC0
/* 1760F4 8024D6D4 00A22823 */  subu       $a1, $a1, $v0
/* 1760F8 8024D6D8 000517C2 */  srl        $v0, $a1, 31
/* 1760FC 8024D6DC 00A22821 */  addu       $a1, $a1, $v0
/* 176100 8024D6E0 00052843 */  sra        $a1, $a1, 1
/* 176104 8024D6E4 02052821 */  addu       $a1, $s0, $a1
/* 176108 8024D6E8 26260004 */  addiu      $a2, $s1, 0x4
/* 17610C 8024D6EC 240700FF */  addiu      $a3, $zero, 0xFF
/* 176110 8024D6F0 AFA00010 */  sw         $zero, 0x10($sp)
/* 176114 8024D6F4 0C049403 */  jal        func_PAL_8012500C
/* 176118 8024D6F8 AFA00014 */   sw        $zero, 0x14($sp)
/* 17611C 8024D6FC 8FBF0020 */  lw         $ra, 0x20($sp)
/* 176120 8024D700 8FB1001C */  lw         $s1, 0x1C($sp)
/* 176124 8024D704 8FB00018 */  lw         $s0, 0x18($sp)
/* 176128 8024D708 03E00008 */  jr         $ra
/* 17612C 8024D70C 27BD0028 */   addiu     $sp, $sp, 0x28
