.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024D9B0
/* 1763D0 8024D9B0 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1763D4 8024D9B4 0080402D */  daddu      $t0, $a0, $zero
/* 1763D8 8024D9B8 00A0482D */  daddu      $t1, $a1, $zero
/* 1763DC 8024D9BC 00C0502D */  daddu      $t2, $a2, $zero
/* 1763E0 8024D9C0 0100282D */  daddu      $a1, $t0, $zero
/* 1763E4 8024D9C4 8FA20038 */  lw         $v0, 0x38($sp)
/* 1763E8 8024D9C8 8FA3003C */  lw         $v1, 0x3C($sp)
/* 1763EC 8024D9CC 8FA40040 */  lw         $a0, 0x40($sp)
/* 1763F0 8024D9D0 0120302D */  daddu      $a2, $t1, $zero
/* 1763F4 8024D9D4 AFA70010 */  sw         $a3, 0x10($sp)
/* 1763F8 8024D9D8 0140382D */  daddu      $a3, $t2, $zero
/* 1763FC 8024D9DC AFBF0020 */  sw         $ra, 0x20($sp)
/* 176400 8024D9E0 AFA4001C */  sw         $a0, 0x1C($sp)
/* 176404 8024D9E4 0000202D */  daddu      $a0, $zero, $zero
/* 176408 8024D9E8 AFA20014 */  sw         $v0, 0x14($sp)
/* 17640C 8024D9EC 0C0935C4 */  jal        func_filemenu_8024D710
/* 176410 8024D9F0 AFA30018 */   sw        $v1, 0x18($sp)
/* 176414 8024D9F4 8FBF0020 */  lw         $ra, 0x20($sp)
/* 176418 8024D9F8 03E00008 */  jr         $ra
/* 17641C 8024D9FC 27BD0028 */   addiu     $sp, $sp, 0x28
