.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024DAA0
/* 1764C0 8024DAA0 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1764C4 8024DAA4 0080402D */  daddu      $t0, $a0, $zero
/* 1764C8 8024DAA8 00A0482D */  daddu      $t1, $a1, $zero
/* 1764CC 8024DAAC 00C0502D */  daddu      $t2, $a2, $zero
/* 1764D0 8024DAB0 0100282D */  daddu      $a1, $t0, $zero
/* 1764D4 8024DAB4 8FA20038 */  lw         $v0, 0x38($sp)
/* 1764D8 8024DAB8 8FA3003C */  lw         $v1, 0x3C($sp)
/* 1764DC 8024DABC 8FA40040 */  lw         $a0, 0x40($sp)
/* 1764E0 8024DAC0 0120302D */  daddu      $a2, $t1, $zero
/* 1764E4 8024DAC4 AFA70010 */  sw         $a3, 0x10($sp)
/* 1764E8 8024DAC8 0140382D */  daddu      $a3, $t2, $zero
/* 1764EC 8024DACC AFBF0020 */  sw         $ra, 0x20($sp)
/* 1764F0 8024DAD0 AFA4001C */  sw         $a0, 0x1C($sp)
/* 1764F4 8024DAD4 24040003 */  addiu      $a0, $zero, 0x3
/* 1764F8 8024DAD8 AFA20014 */  sw         $v0, 0x14($sp)
/* 1764FC 8024DADC 0C0935C4 */  jal        func_filemenu_8024D710
/* 176500 8024DAE0 AFA30018 */   sw        $v1, 0x18($sp)
/* 176504 8024DAE4 8FBF0020 */  lw         $ra, 0x20($sp)
/* 176508 8024DAE8 03E00008 */  jr         $ra
/* 17650C 8024DAEC 27BD0028 */   addiu     $sp, $sp, 0x28
