.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024DFDC
/* 1769FC 8024DFDC 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 176A00 8024DFE0 3C068015 */  lui        $a2, %hi(D_PAL_8014DD20)
/* 176A04 8024DFE4 24C6DD20 */  addiu      $a2, $a2, %lo(D_PAL_8014DD20)
/* 176A08 8024DFE8 3C058025 */  lui        $a1, %hi(D_filemenu_80251558)
/* 176A0C 8024DFEC 24A51558 */  addiu      $a1, $a1, %lo(D_filemenu_80251558)
/* 176A10 8024DFF0 AFBF0010 */  sw         $ra, 0x10($sp)
/* 176A14 8024DFF4 ACC500E0 */  sw         $a1, 0xE0($a2)
/* 176A18 8024DFF8 ACC500E4 */  sw         $a1, 0xE4($a2)
/* 176A1C 8024DFFC ACC500E8 */  sw         $a1, 0xE8($a2)
/* 176A20 8024E000 ACC500EC */  sw         $a1, 0xEC($a2)
/* 176A24 8024E004 90830003 */  lbu        $v1, 0x3($a0)
/* 176A28 8024E008 24020001 */  addiu      $v0, $zero, 0x1
/* 176A2C 8024E00C 1062000F */  beq        $v1, $v0, .Lfilemenu_8024E04C
/* 176A30 8024E010 28620002 */   slti      $v0, $v1, 0x2
/* 176A34 8024E014 10400005 */  beqz       $v0, .Lfilemenu_8024E02C
/* 176A38 8024E018 24020002 */   addiu     $v0, $zero, 0x2
/* 176A3C 8024E01C 10600009 */  beqz       $v1, .Lfilemenu_8024E044
/* 176A40 8024E020 24A20038 */   addiu     $v0, $a1, 0x38
/* 176A44 8024E024 0809381A */  j          .Lfilemenu_8024E068
/* 176A48 8024E028 00000000 */   nop
.Lfilemenu_8024E02C:
/* 176A4C 8024E02C 1062000A */  beq        $v1, $v0, .Lfilemenu_8024E058
/* 176A50 8024E030 24020003 */   addiu     $v0, $zero, 0x3
/* 176A54 8024E034 1062000B */  beq        $v1, $v0, .Lfilemenu_8024E064
/* 176A58 8024E038 24A20038 */   addiu     $v0, $a1, 0x38
/* 176A5C 8024E03C 0809381A */  j          .Lfilemenu_8024E068
/* 176A60 8024E040 00000000 */   nop
.Lfilemenu_8024E044:
/* 176A64 8024E044 0809381A */  j          .Lfilemenu_8024E068
/* 176A68 8024E048 ACC200E0 */   sw        $v0, 0xE0($a2)
.Lfilemenu_8024E04C:
/* 176A6C 8024E04C 24A20038 */  addiu      $v0, $a1, 0x38
/* 176A70 8024E050 0809381A */  j          .Lfilemenu_8024E068
/* 176A74 8024E054 ACC200E4 */   sw        $v0, 0xE4($a2)
.Lfilemenu_8024E058:
/* 176A78 8024E058 24A20038 */  addiu      $v0, $a1, 0x38
/* 176A7C 8024E05C 0809381A */  j          .Lfilemenu_8024E068
/* 176A80 8024E060 ACC200E8 */   sw        $v0, 0xE8($a2)
.Lfilemenu_8024E064:
/* 176A84 8024E064 ACC200EC */  sw         $v0, 0xEC($a2)
.Lfilemenu_8024E068:
/* 176A88 8024E068 3C048025 */  lui        $a0, %hi(D_filemenu_8024F124)
/* 176A8C 8024E06C 2484F124 */  addiu      $a0, $a0, %lo(D_filemenu_8024F124)
/* 176A90 8024E070 3C058025 */  lui        $a1, %hi(D_filemenu_8024F128)
/* 176A94 8024E074 24A5F128 */  addiu      $a1, $a1, %lo(D_filemenu_8024F128)
/* 176A98 8024E078 8C830000 */  lw         $v1, 0x0($a0)
/* 176A9C 8024E07C 8CA20000 */  lw         $v0, 0x0($a1)
/* 176AA0 8024E080 38660001 */  xori       $a2, $v1, 0x1
/* 176AA4 8024E084 24420001 */  addiu      $v0, $v0, 0x1
/* 176AA8 8024E088 AC860000 */  sw         $a2, 0x0($a0)
/* 176AAC 8024E08C ACA20000 */  sw         $v0, 0x0($a1)
/* 176AB0 8024E090 28420029 */  slti       $v0, $v0, 0x29
/* 176AB4 8024E094 50400001 */  beql       $v0, $zero, .Lfilemenu_8024E09C
/* 176AB8 8024E098 ACA00000 */   sw        $zero, 0x0($a1)
.Lfilemenu_8024E09C:
/* 176ABC 8024E09C 3C020026 */  lui        $v0, %hi(D_25C5A0)
/* 176AC0 8024E0A0 2442C5A0 */  addiu      $v0, $v0, %lo(D_25C5A0)
/* 176AC4 8024E0A4 3C038025 */  lui        $v1, %hi(D_802517E0)
/* 176AC8 8024E0A8 246317E0 */  addiu      $v1, $v1, %lo(D_802517E0)
/* 176ACC 8024E0AC 000632C0 */  sll        $a2, $a2, 11
/* 176AD0 8024E0B0 8CA40000 */  lw         $a0, 0x0($a1)
/* 176AD4 8024E0B4 3C050027 */  lui        $a1, %hi(D_2705A0)
/* 176AD8 8024E0B8 24A505A0 */  addiu      $a1, $a1, %lo(D_2705A0)
/* 176ADC 8024E0BC 00C33021 */  addu       $a2, $a2, $v1
/* 176AE0 8024E0C0 000422C0 */  sll        $a0, $a0, 11
/* 176AE4 8024E0C4 0C00A5AF */  jal        dma_copy
/* 176AE8 8024E0C8 00822021 */   addu      $a0, $a0, $v0
/* 176AEC 8024E0CC 8FBF0010 */  lw         $ra, 0x10($sp)
/* 176AF0 8024E0D0 03E00008 */  jr         $ra
/* 176AF4 8024E0D4 27BD0018 */   addiu     $sp, $sp, 0x18
