.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024DAF0
/* 176510 8024DAF0 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 176514 8024DAF4 AFB3001C */  sw         $s3, 0x1C($sp)
/* 176518 8024DAF8 0080982D */  daddu      $s3, $a0, $zero
/* 17651C 8024DAFC AFB00010 */  sw         $s0, 0x10($sp)
/* 176520 8024DB00 0000802D */  daddu      $s0, $zero, $zero
/* 176524 8024DB04 AFB20018 */  sw         $s2, 0x18($sp)
/* 176528 8024DB08 3C128025 */  lui        $s2, %hi(D_802517D0)
/* 17652C 8024DB0C 265217D0 */  addiu      $s2, $s2, %lo(D_802517D0)
/* 176530 8024DB10 AFB10014 */  sw         $s1, 0x14($sp)
/* 176534 8024DB14 3C118025 */  lui        $s1, %hi(D_filemenu_8024F120)
/* 176538 8024DB18 2631F120 */  addiu      $s1, $s1, %lo(D_filemenu_8024F120)
/* 17653C 8024DB1C AFBF0020 */  sw         $ra, 0x20($sp)
.Lfilemenu_8024DB20:
/* 176540 8024DB20 8E240000 */  lw         $a0, 0x0($s1)
/* 176544 8024DB24 26310004 */  addiu      $s1, $s1, 0x4
/* 176548 8024DB28 0C050015 */  jal        func_PAL_80140054
/* 17654C 8024DB2C 26100001 */   addiu     $s0, $s0, 0x1
/* 176550 8024DB30 0040202D */  daddu      $a0, $v0, $zero
/* 176554 8024DB34 24050080 */  addiu      $a1, $zero, 0x80
/* 176558 8024DB38 0C050D6C */  jal        func_PAL_801435B0
/* 17655C 8024DB3C AE440000 */   sw        $a0, 0x0($s2)
/* 176560 8024DB40 1A00FFF7 */  blez       $s0, .Lfilemenu_8024DB20
/* 176564 8024DB44 26520004 */   addiu     $s2, $s2, 0x4
/* 176568 8024DB48 24100004 */  addiu      $s0, $zero, 0x4
/* 17656C 8024DB4C 3C028025 */  lui        $v0, %hi(D_filemenu_8024F268)
/* 176570 8024DB50 2442F268 */  addiu      $v0, $v0, %lo(D_filemenu_8024F268)
.Lfilemenu_8024DB54:
/* 176574 8024DB54 AC530010 */  sw         $s3, 0x10($v0)
/* 176578 8024DB58 2610FFFF */  addiu      $s0, $s0, -0x1
/* 17657C 8024DB5C 0601FFFD */  bgez       $s0, .Lfilemenu_8024DB54
/* 176580 8024DB60 2442FFDC */   addiu     $v0, $v0, -0x24
/* 176584 8024DB64 3C048025 */  lui        $a0, %hi(D_filemenu_8024F1D8)
/* 176588 8024DB68 2484F1D8 */  addiu      $a0, $a0, %lo(D_filemenu_8024F1D8)
/* 17658C 8024DB6C 0C051AB8 */  jal        func_PAL_80146AE0
/* 176590 8024DB70 24050005 */   addiu     $a1, $zero, 0x5
/* 176594 8024DB74 82620004 */  lb         $v0, 0x4($s3)
/* 176598 8024DB78 82630005 */  lb         $v1, 0x5($s3)
/* 17659C 8024DB7C 00430018 */  mult       $v0, $v1
/* 1765A0 8024DB80 00003812 */  mflo       $a3
/* 1765A4 8024DB84 82620006 */  lb         $v0, 0x6($s3)
/* 1765A8 8024DB88 00000000 */  nop
/* 1765AC 8024DB8C 00E20018 */  mult       $a3, $v0
/* 1765B0 8024DB90 00002012 */  mflo       $a0
/* 1765B4 8024DB94 82620002 */  lb         $v0, 0x2($s3)
/* 1765B8 8024DB98 00000000 */  nop
/* 1765BC 8024DB9C 00620018 */  mult       $v1, $v0
/* 1765C0 8024DBA0 00001812 */  mflo       $v1
/* 1765C4 8024DBA4 00831821 */  addu       $v1, $a0, $v1
/* 1765C8 8024DBA8 82640001 */  lb         $a0, 0x1($s3)
/* 1765CC 8024DBAC 8E620008 */  lw         $v0, 0x8($s3)
/* 1765D0 8024DBB0 00641821 */  addu       $v1, $v1, $a0
/* 1765D4 8024DBB4 00431021 */  addu       $v0, $v0, $v1
/* 1765D8 8024DBB8 3C048016 */  lui        $a0, %hi(D_80158910)
/* 1765DC 8024DBBC 24848910 */  addiu      $a0, $a0, %lo(D_80158910)
/* 1765E0 8024DBC0 90420000 */  lbu        $v0, 0x0($v0)
/* 1765E4 8024DBC4 82630002 */  lb         $v1, 0x2($s3)
/* 1765E8 8024DBC8 A2620003 */  sb         $v0, 0x3($s3)
/* 1765EC 8024DBCC 3C018025 */  lui        $at, %hi(D_802517D4)
/* 1765F0 8024DBD0 AC2317D4 */  sw         $v1, %lo(D_802517D4)($at)
/* 1765F4 8024DBD4 808305A3 */  lb         $v1, 0x5A3($a0)
/* 1765F8 8024DBD8 24020001 */  addiu      $v0, $zero, 0x1
/* 1765FC 8024DBDC A48205AE */  sh         $v0, 0x5AE($a0)
/* 176600 8024DBE0 240200C0 */  addiu      $v0, $zero, 0xC0
/* 176604 8024DBE4 A48205B0 */  sh         $v0, 0x5B0($a0)
/* 176608 8024DBE8 24020019 */  addiu      $v0, $zero, 0x19
/* 17660C 8024DBEC A48205B2 */  sh         $v0, 0x5B2($a0)
/* 176610 8024DBF0 2402FFFF */  addiu      $v0, $zero, -0x1
/* 176614 8024DBF4 1062000B */  beq        $v1, $v0, .Lfilemenu_8024DC24
/* 176618 8024DBF8 248705AC */   addiu     $a3, $a0, 0x5AC
/* 17661C 8024DBFC 00031140 */  sll        $v0, $v1, 5
/* 176620 8024DC00 00441021 */  addu       $v0, $v0, $a0
/* 176624 8024DC04 94420010 */  lhu        $v0, 0x10($v0)
/* 176628 8024DC08 00021400 */  sll        $v0, $v0, 16
/* 17662C 8024DC0C 00021C03 */  sra        $v1, $v0, 16
/* 176630 8024DC10 000217C2 */  srl        $v0, $v0, 31
/* 176634 8024DC14 00621821 */  addu       $v1, $v1, $v0
/* 176638 8024DC18 00031843 */  sra        $v1, $v1, 1
/* 17663C 8024DC1C 0809370A */  j          .Lfilemenu_8024DC28
/* 176640 8024DC20 2463FFA0 */   addiu     $v1, $v1, -0x60
.Lfilemenu_8024DC24:
/* 176644 8024DC24 24030040 */  addiu      $v1, $zero, 0x40
.Lfilemenu_8024DC28:
/* 176648 8024DC28 3C120026 */  lui        $s2, %hi(D_25C5A0)
/* 17664C 8024DC2C 2652C5A0 */  addiu      $s2, $s2, %lo(D_25C5A0)
/* 176650 8024DC30 0240202D */  daddu      $a0, $s2, $zero
/* 176654 8024DC34 3C110027 */  lui        $s1, %hi(D_2705A0)
/* 176658 8024DC38 263105A0 */  addiu      $s1, $s1, %lo(D_2705A0)
/* 17665C 8024DC3C 0220282D */  daddu      $a1, $s1, $zero
/* 176660 8024DC40 3C108025 */  lui        $s0, %hi(D_802517E0)
/* 176664 8024DC44 261017E0 */  addiu      $s0, $s0, %lo(D_802517E0)
/* 176668 8024DC48 24020001 */  addiu      $v0, $zero, 0x1
/* 17666C 8024DC4C A4E30000 */  sh         $v1, 0x0($a3)
/* 176670 8024DC50 A2620000 */  sb         $v0, 0x0($s3)
/* 176674 8024DC54 3C018025 */  lui        $at, %hi(D_filemenu_8024F124)
/* 176678 8024DC58 AC20F124 */  sw         $zero, %lo(D_filemenu_8024F124)($at)
/* 17667C 8024DC5C 0C00A5AF */  jal        dma_copy
/* 176680 8024DC60 0200302D */   daddu     $a2, $s0, $zero
/* 176684 8024DC64 26440800 */  addiu      $a0, $s2, 0x800
/* 176688 8024DC68 0220282D */  daddu      $a1, $s1, $zero
/* 17668C 8024DC6C 0C00A5AF */  jal        dma_copy
/* 176690 8024DC70 26060800 */   addiu     $a2, $s0, 0x800
/* 176694 8024DC74 8FBF0020 */  lw         $ra, 0x20($sp)
/* 176698 8024DC78 8FB3001C */  lw         $s3, 0x1C($sp)
/* 17669C 8024DC7C 8FB20018 */  lw         $s2, 0x18($sp)
/* 1766A0 8024DC80 8FB10014 */  lw         $s1, 0x14($sp)
/* 1766A4 8024DC84 8FB00010 */  lw         $s0, 0x10($sp)
/* 1766A8 8024DC88 24020002 */  addiu      $v0, $zero, 0x2
/* 1766AC 8024DC8C 3C018025 */  lui        $at, %hi(D_filemenu_8024F128)
/* 1766B0 8024DC90 AC22F128 */  sw         $v0, %lo(D_filemenu_8024F128)($at)
/* 1766B4 8024DC94 03E00008 */  jr         $ra
/* 1766B8 8024DC98 27BD0028 */   addiu     $sp, $sp, 0x28
