.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024E0D8
/* 176AF8 8024E0D8 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 176AFC 8024E0DC AFB10014 */  sw         $s1, 0x14($sp)
/* 176B00 8024E0E0 0000882D */  daddu      $s1, $zero, $zero
/* 176B04 8024E0E4 AFB00010 */  sw         $s0, 0x10($sp)
/* 176B08 8024E0E8 3C108025 */  lui        $s0, %hi(D_802517D0)
/* 176B0C 8024E0EC 261017D0 */  addiu      $s0, $s0, %lo(D_802517D0)
/* 176B10 8024E0F0 AFBF0018 */  sw         $ra, 0x18($sp)
.Lfilemenu_8024E0F4:
/* 176B14 8024E0F4 8E040000 */  lw         $a0, 0x0($s0)
/* 176B18 8024E0F8 26100004 */  addiu      $s0, $s0, 0x4
/* 176B1C 8024E0FC 0C050D29 */  jal        func_PAL_801434A4
/* 176B20 8024E100 26310001 */   addiu     $s1, $s1, 0x1
/* 176B24 8024E104 1A20FFFB */  blez       $s1, .Lfilemenu_8024E0F4
/* 176B28 8024E108 00000000 */   nop
/* 176B2C 8024E10C 8FBF0018 */  lw         $ra, 0x18($sp)
/* 176B30 8024E110 8FB10014 */  lw         $s1, 0x14($sp)
/* 176B34 8024E114 8FB00010 */  lw         $s0, 0x10($sp)
/* 176B38 8024E118 03E00008 */  jr         $ra
/* 176B3C 8024E11C 27BD0020 */   addiu     $sp, $sp, 0x20
