.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024DA00
/* 176420 8024DA00 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 176424 8024DA04 0080402D */  daddu      $t0, $a0, $zero
/* 176428 8024DA08 00A0482D */  daddu      $t1, $a1, $zero
/* 17642C 8024DA0C 00C0502D */  daddu      $t2, $a2, $zero
/* 176430 8024DA10 0100282D */  daddu      $a1, $t0, $zero
/* 176434 8024DA14 8FA20038 */  lw         $v0, 0x38($sp)
/* 176438 8024DA18 8FA3003C */  lw         $v1, 0x3C($sp)
/* 17643C 8024DA1C 8FA40040 */  lw         $a0, 0x40($sp)
/* 176440 8024DA20 0120302D */  daddu      $a2, $t1, $zero
/* 176444 8024DA24 AFA70010 */  sw         $a3, 0x10($sp)
/* 176448 8024DA28 0140382D */  daddu      $a3, $t2, $zero
/* 17644C 8024DA2C AFBF0020 */  sw         $ra, 0x20($sp)
/* 176450 8024DA30 AFA4001C */  sw         $a0, 0x1C($sp)
/* 176454 8024DA34 24040001 */  addiu      $a0, $zero, 0x1
/* 176458 8024DA38 AFA20014 */  sw         $v0, 0x14($sp)
/* 17645C 8024DA3C 0C0935C4 */  jal        func_filemenu_8024D710
/* 176460 8024DA40 AFA30018 */   sw        $v1, 0x18($sp)
/* 176464 8024DA44 8FBF0020 */  lw         $ra, 0x20($sp)
/* 176468 8024DA48 03E00008 */  jr         $ra
/* 17646C 8024DA4C 27BD0028 */   addiu     $sp, $sp, 0x28
