.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024DC9C
/* 1766BC 8024DC9C 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1766C0 8024DCA0 AFB00010 */  sw         $s0, 0x10($sp)
/* 1766C4 8024DCA4 0080802D */  daddu      $s0, $a0, $zero
/* 1766C8 8024DCA8 AFB10014 */  sw         $s1, 0x14($sp)
/* 1766CC 8024DCAC 3C028025 */  lui        $v0, %hi(D_8025174C)
/* 1766D0 8024DCB0 8C42174C */  lw         $v0, %lo(D_8025174C)($v0)
/* 1766D4 8024DCB4 3C030004 */  lui        $v1, (0x40000 >> 16)
/* 1766D8 8024DCB8 AFBF001C */  sw         $ra, 0x1C($sp)
/* 1766DC 8024DCBC AFB20018 */  sw         $s2, 0x18($sp)
/* 1766E0 8024DCC0 92120003 */  lbu        $s2, 0x3($s0)
/* 1766E4 8024DCC4 00431024 */  and        $v0, $v0, $v1
/* 1766E8 8024DCC8 1040001C */  beqz       $v0, .Lfilemenu_8024DD3C
/* 1766EC 8024DCCC 0000882D */   daddu     $s1, $zero, $zero
.Lfilemenu_8024DCD0:
/* 1766F0 8024DCD0 92020001 */  lbu        $v0, 0x1($s0)
/* 1766F4 8024DCD4 2442FFFF */  addiu      $v0, $v0, -0x1
/* 1766F8 8024DCD8 A2020001 */  sb         $v0, 0x1($s0)
/* 1766FC 8024DCDC 00021600 */  sll        $v0, $v0, 24
/* 176700 8024DCE0 00022E03 */  sra        $a1, $v0, 24
/* 176704 8024DCE4 04A20015 */  bltzl      $a1, .Lfilemenu_8024DD3C
/* 176708 8024DCE8 A2000001 */   sb        $zero, 0x1($s0)
/* 17670C 8024DCEC 82020004 */  lb         $v0, 0x4($s0)
/* 176710 8024DCF0 82030005 */  lb         $v1, 0x5($s0)
/* 176714 8024DCF4 00430018 */  mult       $v0, $v1
/* 176718 8024DCF8 00003012 */  mflo       $a2
/* 17671C 8024DCFC 82020006 */  lb         $v0, 0x6($s0)
/* 176720 8024DD00 00000000 */  nop
/* 176724 8024DD04 00C20018 */  mult       $a2, $v0
/* 176728 8024DD08 00002012 */  mflo       $a0
/* 17672C 8024DD0C 82020002 */  lb         $v0, 0x2($s0)
/* 176730 8024DD10 00000000 */  nop
/* 176734 8024DD14 00620018 */  mult       $v1, $v0
/* 176738 8024DD18 8E030008 */  lw         $v1, 0x8($s0)
/* 17673C 8024DD1C 00001012 */  mflo       $v0
/* 176740 8024DD20 00821021 */  addu       $v0, $a0, $v0
/* 176744 8024DD24 00451021 */  addu       $v0, $v0, $a1
/* 176748 8024DD28 00621821 */  addu       $v1, $v1, $v0
/* 17674C 8024DD2C 92040003 */  lbu        $a0, 0x3($s0)
/* 176750 8024DD30 90620000 */  lbu        $v0, 0x0($v1)
/* 176754 8024DD34 1082FFE6 */  beq        $a0, $v0, .Lfilemenu_8024DCD0
/* 176758 8024DD38 00000000 */   nop
.Lfilemenu_8024DD3C:
/* 17675C 8024DD3C 3C028025 */  lui        $v0, %hi(D_8025174C)
/* 176760 8024DD40 8C42174C */  lw         $v0, %lo(D_8025174C)($v0)
/* 176764 8024DD44 3C030008 */  lui        $v1, (0x80000 >> 16)
/* 176768 8024DD48 00431024 */  and        $v0, $v0, $v1
/* 17676C 8024DD4C 1040001E */  beqz       $v0, .Lfilemenu_8024DDC8
/* 176770 8024DD50 00000000 */   nop
/* 176774 8024DD54 92060005 */  lbu        $a2, 0x5($s0)
/* 176778 8024DD58 82050005 */  lb         $a1, 0x5($s0)
.Lfilemenu_8024DD5C:
/* 17677C 8024DD5C 92020001 */  lbu        $v0, 0x1($s0)
/* 176780 8024DD60 24420001 */  addiu      $v0, $v0, 0x1
/* 176784 8024DD64 A2020001 */  sb         $v0, 0x1($s0)
/* 176788 8024DD68 00021600 */  sll        $v0, $v0, 24
/* 17678C 8024DD6C 00022603 */  sra        $a0, $v0, 24
/* 176790 8024DD70 0085102A */  slt        $v0, $a0, $a1
/* 176794 8024DD74 10400042 */  beqz       $v0, .Lfilemenu_8024DE80
/* 176798 8024DD78 24C2FFFF */   addiu     $v0, $a2, -0x1
/* 17679C 8024DD7C 82020004 */  lb         $v0, 0x4($s0)
/* 1767A0 8024DD80 00450018 */  mult       $v0, $a1
/* 1767A4 8024DD84 00001812 */  mflo       $v1
/* 1767A8 8024DD88 82020006 */  lb         $v0, 0x6($s0)
/* 1767AC 8024DD8C 00000000 */  nop
/* 1767B0 8024DD90 00620018 */  mult       $v1, $v0
/* 1767B4 8024DD94 00001812 */  mflo       $v1
/* 1767B8 8024DD98 82020002 */  lb         $v0, 0x2($s0)
/* 1767BC 8024DD9C 00000000 */  nop
/* 1767C0 8024DDA0 00A20018 */  mult       $a1, $v0
/* 1767C4 8024DDA4 00001012 */  mflo       $v0
/* 1767C8 8024DDA8 00621021 */  addu       $v0, $v1, $v0
/* 1767CC 8024DDAC 00441021 */  addu       $v0, $v0, $a0
/* 1767D0 8024DDB0 8E030008 */  lw         $v1, 0x8($s0)
/* 1767D4 8024DDB4 92040003 */  lbu        $a0, 0x3($s0)
/* 1767D8 8024DDB8 00621821 */  addu       $v1, $v1, $v0
/* 1767DC 8024DDBC 90620000 */  lbu        $v0, 0x0($v1)
/* 1767E0 8024DDC0 1082FFE6 */  beq        $a0, $v0, .Lfilemenu_8024DD5C
/* 1767E4 8024DDC4 00000000 */   nop
.Lfilemenu_8024DDC8:
/* 1767E8 8024DDC8 3C028025 */  lui        $v0, %hi(D_8025174C)
/* 1767EC 8024DDCC 8C42174C */  lw         $v0, %lo(D_8025174C)($v0)
/* 1767F0 8024DDD0 3C030001 */  lui        $v1, (0x10000 >> 16)
/* 1767F4 8024DDD4 00431024 */  and        $v0, $v0, $v1
/* 1767F8 8024DDD8 10400007 */  beqz       $v0, .Lfilemenu_8024DDF8
/* 1767FC 8024DDDC 00000000 */   nop
/* 176800 8024DDE0 92020002 */  lbu        $v0, 0x2($s0)
/* 176804 8024DDE4 2442FFFF */  addiu      $v0, $v0, -0x1
/* 176808 8024DDE8 A2020002 */  sb         $v0, 0x2($s0)
/* 17680C 8024DDEC 00021600 */  sll        $v0, $v0, 24
/* 176810 8024DDF0 04420001 */  bltzl      $v0, .Lfilemenu_8024DDF8
/* 176814 8024DDF4 A2000002 */   sb        $zero, 0x2($s0)
.Lfilemenu_8024DDF8:
/* 176818 8024DDF8 3C028025 */  lui        $v0, %hi(D_8025174C)
/* 17681C 8024DDFC 8C42174C */  lw         $v0, %lo(D_8025174C)($v0)
/* 176820 8024DE00 3C030002 */  lui        $v1, (0x20000 >> 16)
/* 176824 8024DE04 00431024 */  and        $v0, $v0, $v1
/* 176828 8024DE08 1040000C */  beqz       $v0, .Lfilemenu_8024DE3C
/* 17682C 8024DE0C 00000000 */   nop
/* 176830 8024DE10 92020002 */  lbu        $v0, 0x2($s0)
/* 176834 8024DE14 82030006 */  lb         $v1, 0x6($s0)
/* 176838 8024DE18 24420001 */  addiu      $v0, $v0, 0x1
/* 17683C 8024DE1C A2020002 */  sb         $v0, 0x2($s0)
/* 176840 8024DE20 00021600 */  sll        $v0, $v0, 24
/* 176844 8024DE24 00021603 */  sra        $v0, $v0, 24
/* 176848 8024DE28 0043102A */  slt        $v0, $v0, $v1
/* 17684C 8024DE2C 92030006 */  lbu        $v1, 0x6($s0)
/* 176850 8024DE30 14400002 */  bnez       $v0, .Lfilemenu_8024DE3C
/* 176854 8024DE34 2462FFFF */   addiu     $v0, $v1, -0x1
/* 176858 8024DE38 A2020002 */  sb         $v0, 0x2($s0)
.Lfilemenu_8024DE3C:
/* 17685C 8024DE3C 3C028025 */  lui        $v0, %hi(D_80251744)
/* 176860 8024DE40 8C421744 */  lw         $v0, %lo(D_80251744)($v0)
/* 176864 8024DE44 30424000 */  andi       $v0, $v0, 0x4000
/* 176868 8024DE48 1040000F */  beqz       $v0, .Lfilemenu_8024DE88
/* 17686C 8024DE4C 0000282D */   daddu     $a1, $zero, $zero
/* 176870 8024DE50 3C048025 */  lui        $a0, %hi(D_802517D4)
/* 176874 8024DE54 248417D4 */  addiu      $a0, $a0, %lo(D_802517D4)
/* 176878 8024DE58 82030002 */  lb         $v1, 0x2($s0)
/* 17687C 8024DE5C 8C820000 */  lw         $v0, 0x0($a0)
/* 176880 8024DE60 50620009 */  beql       $v1, $v0, .Lfilemenu_8024DE88
/* 176884 8024DE64 24110001 */   addiu     $s1, $zero, 0x1
/* 176888 8024DE68 90820003 */  lbu        $v0, 0x3($a0)
/* 17688C 8024DE6C 240400CA */  addiu      $a0, $zero, 0xCA
/* 176890 8024DE70 0C052219 */  jal        func_PAL_80148864
/* 176894 8024DE74 A2020002 */   sb        $v0, 0x2($s0)
/* 176898 8024DE78 080937A2 */  j          .Lfilemenu_8024DE88
/* 17689C 8024DE7C 24050001 */   addiu     $a1, $zero, 0x1
.Lfilemenu_8024DE80:
/* 1768A0 8024DE80 08093772 */  j          .Lfilemenu_8024DDC8
/* 1768A4 8024DE84 A2020001 */   sb        $v0, 0x1($s0)
.Lfilemenu_8024DE88:
/* 1768A8 8024DE88 82020004 */  lb         $v0, 0x4($s0)
/* 1768AC 8024DE8C 82030005 */  lb         $v1, 0x5($s0)
/* 1768B0 8024DE90 00430018 */  mult       $v0, $v1
/* 1768B4 8024DE94 00003012 */  mflo       $a2
/* 1768B8 8024DE98 82020006 */  lb         $v0, 0x6($s0)
/* 1768BC 8024DE9C 00000000 */  nop
/* 1768C0 8024DEA0 00C20018 */  mult       $a2, $v0
/* 1768C4 8024DEA4 00002012 */  mflo       $a0
/* 1768C8 8024DEA8 82020002 */  lb         $v0, 0x2($s0)
/* 1768CC 8024DEAC 00000000 */  nop
/* 1768D0 8024DEB0 00620018 */  mult       $v1, $v0
/* 1768D4 8024DEB4 00001012 */  mflo       $v0
/* 1768D8 8024DEB8 00821821 */  addu       $v1, $a0, $v0
/* 1768DC 8024DEBC 82040001 */  lb         $a0, 0x1($s0)
/* 1768E0 8024DEC0 8E020008 */  lw         $v0, 0x8($s0)
/* 1768E4 8024DEC4 00641821 */  addu       $v1, $v1, $a0
/* 1768E8 8024DEC8 00431021 */  addu       $v0, $v0, $v1
/* 1768EC 8024DECC 90420000 */  lbu        $v0, 0x0($v0)
/* 1768F0 8024DED0 A2020003 */  sb         $v0, 0x3($s0)
/* 1768F4 8024DED4 304200FF */  andi       $v0, $v0, 0xFF
/* 1768F8 8024DED8 1242001B */  beq        $s2, $v0, .Lfilemenu_8024DF48
/* 1768FC 8024DEDC 00000000 */   nop
/* 176900 8024DEE0 14A00003 */  bnez       $a1, .Lfilemenu_8024DEF0
/* 176904 8024DEE4 00000000 */   nop
/* 176908 8024DEE8 0C052219 */  jal        func_PAL_80148864
/* 17690C 8024DEEC 24042101 */   addiu     $a0, $zero, 0x2101
.Lfilemenu_8024DEF0:
/* 176910 8024DEF0 92040003 */  lbu        $a0, 0x3($s0)
/* 176914 8024DEF4 24020001 */  addiu      $v0, $zero, 0x1
/* 176918 8024DEF8 10820011 */  beq        $a0, $v0, .Lfilemenu_8024DF40
/* 17691C 8024DEFC 28820002 */   slti      $v0, $a0, 0x2
/* 176920 8024DF00 10400005 */  beqz       $v0, .Lfilemenu_8024DF18
/* 176924 8024DF04 24020002 */   addiu     $v0, $zero, 0x2
/* 176928 8024DF08 10800009 */  beqz       $a0, .Lfilemenu_8024DF30
/* 17692C 8024DF0C 00000000 */   nop
/* 176930 8024DF10 080937D2 */  j          .Lfilemenu_8024DF48
/* 176934 8024DF14 00000000 */   nop
.Lfilemenu_8024DF18:
/* 176938 8024DF18 10820009 */  beq        $a0, $v0, .Lfilemenu_8024DF40
/* 17693C 8024DF1C 24020003 */   addiu     $v0, $zero, 0x3
/* 176940 8024DF20 10820007 */  beq        $a0, $v0, .Lfilemenu_8024DF40
/* 176944 8024DF24 00000000 */   nop
/* 176948 8024DF28 080937D2 */  j          .Lfilemenu_8024DF48
/* 17694C 8024DF2C 00000000 */   nop
.Lfilemenu_8024DF30:
/* 176950 8024DF30 3C018015 */  lui        $at, %hi(D_PAL_8014AE4C)
/* 176954 8024DF34 AC20AE4C */  sw         $zero, %lo(D_PAL_8014AE4C)($at)
/* 176958 8024DF38 080937D2 */  j          .Lfilemenu_8024DF48
/* 17695C 8024DF3C 00000000 */   nop
.Lfilemenu_8024DF40:
/* 176960 8024DF40 3C018015 */  lui        $at, %hi(D_PAL_8014AE4C)
/* 176964 8024DF44 AC24AE4C */  sw         $a0, %lo(D_PAL_8014AE4C)($at)
.Lfilemenu_8024DF48:
/* 176968 8024DF48 3C028025 */  lui        $v0, %hi(D_80251744)
/* 17696C 8024DF4C 8C421744 */  lw         $v0, %lo(D_80251744)($v0)
/* 176970 8024DF50 30429000 */  andi       $v0, $v0, 0x9000
/* 176974 8024DF54 14400003 */  bnez       $v0, .Lfilemenu_8024DF64
/* 176978 8024DF58 24040038 */   addiu     $a0, $zero, 0x38
/* 17697C 8024DF5C 12200019 */  beqz       $s1, .Lfilemenu_8024DFC4
/* 176980 8024DF60 00000000 */   nop
.Lfilemenu_8024DF64:
/* 176984 8024DF64 3C108025 */  lui        $s0, %hi(filemenu_pal_80248018)
/* 176988 8024DF68 26108018 */  addiu      $s0, $s0, %lo(filemenu_pal_80248018)
/* 17698C 8024DF6C 0C051A8B */  jal        func_PAL_80146A2C
/* 176990 8024DF70 0200282D */   daddu     $a1, $s0, $zero
/* 176994 8024DF74 24040039 */  addiu      $a0, $zero, 0x39
/* 176998 8024DF78 0C051A8B */  jal        func_PAL_80146A2C
/* 17699C 8024DF7C 0200282D */   daddu     $a1, $s0, $zero
/* 1769A0 8024DF80 2404003A */  addiu      $a0, $zero, 0x3A
/* 1769A4 8024DF84 0C051A8B */  jal        func_PAL_80146A2C
/* 1769A8 8024DF88 0200282D */   daddu     $a1, $s0, $zero
/* 1769AC 8024DF8C 2404003B */  addiu      $a0, $zero, 0x3B
/* 1769B0 8024DF90 0C051A8B */  jal        func_PAL_80146A2C
/* 1769B4 8024DF94 0200282D */   daddu     $a1, $s0, $zero
/* 1769B8 8024DF98 3C058024 */  lui        $a1, %hi(func_filemenu_80247664)
/* 1769BC 8024DF9C 24A57664 */  addiu      $a1, $a1, %lo(func_filemenu_80247664)
/* 1769C0 8024DFA0 0C051A8B */  jal        func_PAL_80146A2C
/* 1769C4 8024DFA4 2404002D */   addiu     $a0, $zero, 0x2D
/* 1769C8 8024DFA8 16200002 */  bnez       $s1, .Lfilemenu_8024DFB4
/* 1769CC 8024DFAC 240400D6 */   addiu     $a0, $zero, 0xD6
/* 1769D0 8024DFB0 240400F1 */  addiu      $a0, $zero, 0xF1
.Lfilemenu_8024DFB4:
/* 1769D4 8024DFB4 0C052219 */  jal        func_PAL_80148864
/* 1769D8 8024DFB8 00000000 */   nop
/* 1769DC 8024DFBC 0C00CE04 */  jal        set_game_mode
/* 1769E0 8024DFC0 2404000D */   addiu     $a0, $zero, 0xD
.Lfilemenu_8024DFC4:
/* 1769E4 8024DFC4 8FBF001C */  lw         $ra, 0x1C($sp)
/* 1769E8 8024DFC8 8FB20018 */  lw         $s2, 0x18($sp)
/* 1769EC 8024DFCC 8FB10014 */  lw         $s1, 0x14($sp)
/* 1769F0 8024DFD0 8FB00010 */  lw         $s0, 0x10($sp)
/* 1769F4 8024DFD4 03E00008 */  jr         $ra
/* 1769F8 8024DFD8 27BD0020 */   addiu     $sp, $sp, 0x20
