.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_filemenu_8024DA50
/* 176470 8024DA50 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 176474 8024DA54 0080402D */  daddu      $t0, $a0, $zero
/* 176478 8024DA58 00A0482D */  daddu      $t1, $a1, $zero
/* 17647C 8024DA5C 00C0502D */  daddu      $t2, $a2, $zero
/* 176480 8024DA60 0100282D */  daddu      $a1, $t0, $zero
/* 176484 8024DA64 8FA20038 */  lw         $v0, 0x38($sp)
/* 176488 8024DA68 8FA3003C */  lw         $v1, 0x3C($sp)
/* 17648C 8024DA6C 8FA40040 */  lw         $a0, 0x40($sp)
/* 176490 8024DA70 0120302D */  daddu      $a2, $t1, $zero
/* 176494 8024DA74 AFA70010 */  sw         $a3, 0x10($sp)
/* 176498 8024DA78 0140382D */  daddu      $a3, $t2, $zero
/* 17649C 8024DA7C AFBF0020 */  sw         $ra, 0x20($sp)
/* 1764A0 8024DA80 AFA4001C */  sw         $a0, 0x1C($sp)
/* 1764A4 8024DA84 24040002 */  addiu      $a0, $zero, 0x2
/* 1764A8 8024DA88 AFA20014 */  sw         $v0, 0x14($sp)
/* 1764AC 8024DA8C 0C0935C4 */  jal        func_filemenu_8024D710
/* 1764B0 8024DA90 AFA30018 */   sw        $v1, 0x18($sp)
/* 1764B4 8024DA94 8FBF0020 */  lw         $ra, 0x20($sp)
/* 1764B8 8024DA98 03E00008 */  jr         $ra
/* 1764BC 8024DA9C 27BD0028 */   addiu     $sp, $sp, 0x28
