.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel draw_content_cant_increase_popup
/* 19CE04 80260CA4 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 19CE08 80260CA8 AFB00018 */  sw         $s0, 0x18($sp)
/* 19CE0C 80260CAC 00A0802D */  daddu      $s0, $a1, $zero
/* 19CE10 80260CB0 AFB1001C */  sw         $s1, 0x1C($sp)
/* 19CE14 80260CB4 00C0882D */  daddu      $s1, $a2, $zero
/* 19CE18 80260CB8 3C04001D */  lui        $a0, (0x1D00AB >> 16)
/* 19CE1C 80260CBC AFBF0020 */  sw         $ra, 0x20($sp)
/* 19CE20 80260CC0 0C0493F4 */  jal        func_PAL_80124FD0
/* 19CE24 80260CC4 348400AB */   ori       $a0, $a0, (0x1D00AB & 0xFFFF)
/* 19CE28 80260CC8 3C04001D */  lui        $a0, (0x1D00AB >> 16)
/* 19CE2C 80260CCC 348400AB */  ori        $a0, $a0, (0x1D00AB & 0xFFFF)
/* 19CE30 80260CD0 2442FFFF */  addiu      $v0, $v0, -0x1
/* 19CE34 80260CD4 00021040 */  sll        $v0, $v0, 1
/* 19CE38 80260CD8 3C068028 */  lui        $a2, %hi(D_PAL_80284618)
/* 19CE3C 80260CDC 00C23021 */  addu       $a2, $a2, $v0
/* 19CE40 80260CE0 84C64618 */  lh         $a2, %lo(D_PAL_80284618)($a2)
/* 19CE44 80260CE4 2402000F */  addiu      $v0, $zero, 0xF
/* 19CE48 80260CE8 26050010 */  addiu      $a1, $s0, 0x10
/* 19CE4C 80260CEC 240700FF */  addiu      $a3, $zero, 0xFF
/* 19CE50 80260CF0 AFA20010 */  sw         $v0, 0x10($sp)
/* 19CE54 80260CF4 AFA00014 */  sw         $zero, 0x14($sp)
/* 19CE58 80260CF8 24C60006 */  addiu      $a2, $a2, 0x6
/* 19CE5C 80260CFC 0C049403 */  jal        func_PAL_8012500C
/* 19CE60 80260D00 02263021 */   addu      $a2, $s1, $a2
/* 19CE64 80260D04 8FBF0020 */  lw         $ra, 0x20($sp)
/* 19CE68 80260D08 8FB1001C */  lw         $s1, 0x1C($sp)
/* 19CE6C 80260D0C 8FB00018 */  lw         $s0, 0x18($sp)
/* 19CE70 80260D10 03E00008 */  jr         $ra
/* 19CE74 80260D14 27BD0028 */   addiu     $sp, $sp, 0x28
/* 19CE78 80260D18 00000000 */  nop
/* 19CE7C 80260D1C 00000000 */  nop
