.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel draw_content_level_up_textbox
/* 19CD2C 80260BCC 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 19CD30 80260BD0 3C03800E */  lui        $v1, %hi(D_800D8C4C)
/* 19CD34 80260BD4 8C638C4C */  lw         $v1, %lo(D_800D8C4C)($v1)
/* 19CD38 80260BD8 24020008 */  addiu      $v0, $zero, 0x8
/* 19CD3C 80260BDC 10620008 */  beq        $v1, $v0, .LPAL_80260C00
/* 19CD40 80260BE0 AFBF0018 */   sw        $ra, 0x18($sp)
/* 19CD44 80260BE4 0062102A */  slt        $v0, $v1, $v0
/* 19CD48 80260BE8 1440002B */  bnez       $v0, .LPAL_80260C98
/* 19CD4C 80260BEC 28620011 */   slti      $v0, $v1, 0x11
/* 19CD50 80260BF0 10400029 */  beqz       $v0, .LPAL_80260C98
/* 19CD54 80260BF4 2862000F */   slti      $v0, $v1, 0xF
/* 19CD58 80260BF8 14400027 */  bnez       $v0, .LPAL_80260C98
/* 19CD5C 80260BFC 00000000 */   nop
.LPAL_80260C00:
/* 19CD60 80260C00 3C02800E */  lui        $v0, %hi(D_800D87E0)
/* 19CD64 80260C04 244287E0 */  addiu      $v0, $v0, %lo(D_800D87E0)
/* 19CD68 80260C08 80430048 */  lb         $v1, 0x48($v0)
/* 19CD6C 80260C0C 10600005 */  beqz       $v1, .LPAL_80260C24
/* 19CD70 80260C10 24020001 */   addiu     $v0, $zero, 0x1
/* 19CD74 80260C14 1062000B */  beq        $v1, $v0, .LPAL_80260C44
/* 19CD78 80260C18 3C04001D */   lui       $a0, (0x1D00AA >> 16)
/* 19CD7C 80260C1C 08098318 */  j          .LPAL_80260C60
/* 19CD80 80260C20 00000000 */   nop
.LPAL_80260C24:
/* 19CD84 80260C24 3C04001D */  lui        $a0, (0x1D00A8 >> 16)
/* 19CD88 80260C28 3C02802A */  lui        $v0, %hi(D_802A01A8)
/* 19CD8C 80260C2C 8C4201A8 */  lw         $v0, %lo(D_802A01A8)($v0)
/* 19CD90 80260C30 14400011 */  bnez       $v0, .LPAL_80260C78
/* 19CD94 80260C34 348400A8 */   ori       $a0, $a0, (0x1D00A8 & 0xFFFF)
/* 19CD98 80260C38 3C04001D */  lui        $a0, (0x1D00A9 >> 16)
/* 19CD9C 80260C3C 0809831E */  j          .LPAL_80260C78
/* 19CDA0 80260C40 348400A5 */   ori       $a0, $a0, (0x1D00A5 & 0xFFFF)
.LPAL_80260C44:
/* 19CDA4 80260C44 3C02802A */  lui        $v0, %hi(D_802A01AC)
/* 19CDA8 80260C48 8C4201AC */  lw         $v0, %lo(D_802A01AC)($v0)
/* 19CDAC 80260C4C 1440000A */  bnez       $v0, .LPAL_80260C78
/* 19CDB0 80260C50 348400A9 */   ori       $a0, $a0, (0x1D00A9 & 0xFFFF)
/* 19CDB4 80260C54 3C04001D */  lui        $a0, (0x1D00AA >> 16)
/* 19CDB8 80260C58 0809831E */  j          .LPAL_80260C78
/* 19CDBC 80260C5C 348400A6 */   ori       $a0, $a0, (0x1D00A6 & 0xFFFF)
.LPAL_80260C60:
/* 19CDC0 80260C60 3C02802A */  lui        $v0, %hi(D_802A01B0)
/* 19CDC4 80260C64 8C4201B0 */  lw         $v0, %lo(D_802A01B0)($v0)
/* 19CDC8 80260C68 14400003 */  bnez       $v0, .LPAL_80260C78
/* 19CDCC 80260C6C 348400AA */   ori       $a0, $a0, (0x1D00AA & 0xFFFF)
/* 19CDD0 80260C70 3C04001D */  lui        $a0, (0x1D00A7 >> 16)
/* 19CDD4 80260C74 348400A7 */  ori        $a0, $a0, (0x1D00A7 & 0xFFFF)
.LPAL_80260C78:
/* 19CDD8 80260C78 24030009 */  addiu      $v1, $zero, 0x9
/* 19CDDC 80260C7C 2402000A */  addiu      $v0, $zero, 0xA
/* 19CDE0 80260C80 00A32821 */  addu       $a1, $a1, $v1
/* 19CDE4 80260C84 24A50011 */  addiu      $a1, $a1, 0x11
/* 19CDE8 80260C88 240700FF */  addiu      $a3, $zero, 0xFF
/* 19CDEC 80260C8C AFA20010 */  sw         $v0, 0x10($sp)
/* 19CDF0 80260C90 0C049403 */  jal        func_PAL_8012500C
/* 19CDF4 80260C94 AFA00014 */   sw        $zero, 0x14($sp)
.LPAL_80260C98:
/* 19CDF8 80260C98 8FBF0018 */  lw         $ra, 0x18($sp)
/* 19CDFC 80260C9C 03E00008 */  jr         $ra
/* 19CE00 80260CA0 27BD0020 */   addiu     $sp, $sp, 0x20
