#message:1D:(Menus_Tutorial_SaveBlock) {
	[Style inspect]
	Hit this block to save your[BR]
	game progress.[BR]
	[Wait][Next]
	When the game is over, your[BR]
	status will return to what it[BR]
	was the last time you saved,[BR]
	and you can continue to play.[BR]
	[Wait][Next]
	When you find this block along [BR]
	the way, remember to hit it[BR]
	to save![Wait][End]
}

#message:1D:(Menus_Tutorial_HeartBlock) {
	[Style inspect]
	If you hit this block, your[BR]
	HP (Heart Points) will fully[BR]
	recover.[Wait][End]
}

#message:1D:(Menus_Tutorial_GotItem) {
	[Style inspect]
	You got an item![BR]
	[Wait][Next]
	You'll use items in this game[BR]
	to attack enemies, to recover[BR]
	your HP (Heart Points),[BR]
	and to do a few other things.[BR]
	[Wait][Next]
	Press [C-LEFT] to see what items[BR]
	Mario has now.[Wait][End]
}

#message:1D:(Menus_Tutorial_GotStarPiece) {
	[Style inspect]
	It's a glowing Star Piece![BR]
	Wait and see what this is for.[Wait][End]
}

#message:1D:(Menus_SavePrompt) {
	[Style inspect]
	Do you want to save?[BR]
	[Yield][End]
}

#message:1D:(Menus_SaveComplete) {
	[InputOff]
	[Pause 15][InputOn]
	[Next]
	Save completed.[Wait][End]
}

#message:1D:(Menus_GotKooperShell) {
	[DelayOff]
	[Style popup]
	[Color 0x2F]You got[BR]
	[Color 0x28]Kooper's Shell[Color 0x2F]![BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_Party_Goombario) {
	Goombario[End]
}

#message:1D:(Menus_Party_Kooper) {
	Kooper[End]
}

#message:1D:(Menus_Party_Bombette) {
	Bombette[End]
}

#message:1D:(Menus_Party_Parakarry) {
	Parakarry[End]
}

#message:1D:(Menus_Party_Goompa) {
	Goompa[End]
}

#message:1D:(Menus_Party_Watt) {
	Watt[End]
}

#message:1D:(Menus_Party_Sushie) {
	Sushie[End]
}

#message:1D:(Menus_Party_Lakilester) {
	Lakilester[End]
}

#message:1D:(Menus_Party_Bow) {
	Bow[End]
}

#message:1D:(Menus_Party_Goombaria) {
	Goombaria[End]
}

#message:1D:(Menus_Party_Twink) {
	Twink[End]
}

#message:1D:(Menus_Party_Peach) {
	Peach[End]
}

#message:1D:(Menus_Party_Mario) {
	Mario[End]
}

#message:1D:(Menus_StarPower_Focus) {
	Focus[End]
}

#message:1D:(Menus_StarPower_Refresh) {
	Refresh[End]
}

#message:1D:(Menus_StarPower_Lullaby) {
	Lullaby[End]
}

#message:1D:(Menus_StarPower_StarStorm) {
	Star Storm[End]
}

#message:1D:(Menus_StarPower_ChillOut) {
	Chill Out[End]
}

#message:1D:(Menus_StarPower_Smooch) {
	Smooch[End]
}

#message:1D:(Menus_StarPower_TimeOut) {
	Time Out[End]
}

#message:1D:(Menus_StarPower_UpAndAway) {
	Up & Away[End]
}

#message:1D:(Menus_StarPower_StarBeam) {
	Star Beam[End]
}

#message:1D:(Menus_StarPower_PeachBeam) {
	Peach Beam[End]
}

#message:1D:(Menus_StarPower_Peach_Focus) {
	Focus[End]
}

#message:1D:(Menus_StarPower_Twink_Dash) {
	Dash[End]
}

#message:1D:(Menus_StarPowerDesc_Focus) {
	Charge Star Energy.[End]
}

#message:1D:(Menus_StarPowerDesc_Refresh) {
	Recover HP & FP by 5. Also[BR]
	cures poisoning and Shrink.[End]
}

#message:1D:(Menus_StarPowerDesc_Lullaby) {
	Lull enemies to sleep with[BR]
	a tender lullaby.[BR]
	[End]
}

#message:1D:(Menus_StarPowerDesc_StarStorm) {
	Attack enemy with Star Storm. [BR]
	Attack Power: 7[End]
}

#message:1D:(Menus_StarPowerDesc_ChillOut) {
	If it works, will briefly lower[BR]
	enemy's attack power by 3.[End]
}

#message:1D:(Menus_StarPowerDesc_Smooch) {
	Recover HP by 20.[End]
}

#message:1D:(Menus_StarPowerDesc_TimeOut) {
	If it works, will keep enemy  [BR]
	from moving for a short time.[End]
}

#message:1D:(Menus_StarPowerDesc_UpAndAway) {
	Turn enemies into stars and[BR]
	blow them away.[End]
}

#message:1D:(Menus_StarPowerDesc_StarBeam) {
	It's believed to briefly stop[BR]
	Bowser's Star Rod power.[End]
}

#message:1D:(Menus_StarPowerDesc_PeachBeam) {
	Briefly stop Bowser's [BR]
	Star Rod power.[End]
}

#message:1D:(Menus_SpiritName_Eldstar) {
	Eldstar[End]
}

#message:1D:(Menus_SpiritName_Mamar) {
	Mamar[End]
}

#message:1D:(Menus_SpiritName_Skolar) {
	Skolar[End]
}

#message:1D:(Menus_SpiritName_Muskular) {
	Muskular[End]
}

#message:1D:(Menus_SpiritName_Misstar) {
	Misstar[End]
}

#message:1D:(Menus_SpiritName_Klevar) {
	Klevar[End]
}

#message:1D:(Menus_SpiritName_Kalmar) {
	Kalmar[End]
}

#message:1D:(Menus_SpiritDesc_Eldstar) {
	The elder of Star Haven,[BR]
	he's respected by all others.[BR]
	His power, Refresh,[BR]
	recovers HP & FP by 5.[End]
}

#message:1D:(Menus_SpiritDesc_Mamar) {
	Happy and kind hearted,[BR]
	she looks after the others.[BR]
	Her power, Lullaby, lulls[BR]
	all enemies to sleep.[End]
}

#message:1D:(Menus_SpiritDesc_Skolar) {
	Like most scholars,[BR]
	he's always studying.[BR]
	His power, Star Storm,[BR]
	strikes all enemies.[End]
}

#message:1D:(Menus_SpiritDesc_Muskular) {
	This young Star Spirit is[BR]
	always full of energy.[BR]
	His Chill Out power lowers[BR]
	enemy's attack power. [End]
}

#message:1D:(Menus_SpiritDesc_Misstar) {
	This young Star Spirit is[BR]
	pure hearted but strong.[BR]
	Her power, Smooch,[BR]
	recovers HP.[BR]
	[End]
}

#message:1D:(Menus_SpiritDesc_Klevar) {
	Young and very clever,[BR]
	he's always reading books.[BR]
	His power, Time Out,[BR]
	keeps enemies from moving.[End]
}

#message:1D:(Menus_SpiritDesc_Kalmar) {
	Very warm hearted, he hates[BR]
	fights or arguments.[BR]
	His power, Up & Away,[BR]
	turns all enemies into stars.[End]
}

#message:1D:(Menus_Hammer) {
	Hammer[End]
}

#message:1D:(Menus_Jump) {
	Jump[End]
}

#message:1D:(Menus_StarSpirits) {
	Star Spirits[End]
}

#message:1D:(Menus_RunAway) {
	Run Away[End]
}

#message:1D:(Menus_DoNothing) {
	Do Nothing[End]
}

#message:1D:(Menus_PartyMember) {
	Party Member[End]
}

#message:1D:(Menus_ChangeMember) {
	Change Member[End]
}

#message:1D:(Menus_Items) {
	Items[End]
}

#message:1D:(Menus_KeyItems) {
	Key Items[End]
}

#message:1D:(Menus_DoubleDip) {
	Double Dip    /  [End]
}

#message:1D:(Menus_TripleDip) {
	Triple Dip    /  [End]
}

#message:1D:(Menus_Strategies) {
	Strategies[End]
}

#message:1D:(Menus_Defense) {
	Defense[End]
}

#message:1D:(Menus_Abilities) {
	Abilities[End]
}

#message:1D:(Menus_ActLater) {
	Act Later[End]
}

#message:1D:(Menus_EndTraining) {
	End Training[End]
}

#message:1D:(Menus_Focus) {
	Focus[End]
}

#message:1D:(Menus_Dash) {
	Dash[End]
}

#message:1D:(Menus_Hammer_Centered) {
	[CenterX 50]Hammer[End]
}

#message:1D:(Menus_Jump_Centered) {
	[CenterX 50]Jump[End]
}

#message:1D:(Menus_StarSpirits_Centered) {
	[CenterX 50]Star Spirits[End]
}

#message:1D:(Menus_RunAway_Centered) {
	[CenterX 50]Run Away[End]
}

#message:1D:(Menus_DoNothing_Centered) {
	[CenterX 50]Do Nothing[End]
}

#message:1D:(Menus_ChangeMember_Centered) {
	[CenterX 50]Change Member[End]
}

#message:1D:(Menus_Items_Centered) {
	[CenterX 50]Items[End]
}

#message:1D:(Menus_Strategies_Centered) {
	[CenterX 50]Strategies[End]
}

#message:1D:(Menus_Defense_Centered) {
	[CenterX 50]Defense[End]
}

#message:1D:(Menus_Abilities_Centered) {
	[CenterX 50]Abilities[End]
}

#message:1D:(Menus_EndTraining_Centered) {
	[CenterX 50]End Training[End]
}

#message:1D:(Menus_Focus_Centered) {
	[CenterX 50]Focus[End]
}

#message:1D:(Menus_ActLater_Centered) {
	[CenterX 50]Act Later[End]
}

#message:1D:(Menus_Dash_Centered) {
	[CenterX 50]Dash[End]
}

#message:1D:(Menus_0058) {
	[Color 0x2F]You got the[BR]
	[Color 0x28][Var 0][Color 0x2F]![End]
}

#message:1D:(Menus_0059) {
	[Color 0x2F]You got the[BR]
	[Color 0x28][Var 0][Color 0x2F] Badge![End]
}

#message:1D:(Menus_005A) {
	[Color 0x2F]You got the[BR]
	[Color 0x28][Var 0][Color 0x2F]![End]
}

#message:1D:(Menus_005B) {
	[Color 0x2F]You got the[BR]
	[Color 0x28][Var 0][Color 0x2F] Badge![End]
}

#message:1D:(Menus_005C) {
	[Color 0x2F]You got the[BR]
	[Color 0x28][Var 0][Color 0x2F]![End]
}

#message:1D:(Menus_005D) {
	[Color 0x2F]You got 1 coin![End]
}

#message:1D:(Menus_005E) {
	[Color 0x2F]You got 3 [Color 0x28]Star Pieces[Color 0x2F]![End]
}

#message:1D:(Menus_005F) {
	[Color 0x2F]You threw away the[BR]
	[Color 0x28][Var 0][Color 0x2F]![End]
}

#message:1D:(Menus_0060) {
	You can't carry any more items![BR]
	Throw an item away to make room.[End]
}

#message:1D:(Menus_0061) {
	Use which item?[BR]
	[End]
}

#message:1D:(Menus_0062) {
	Use which item?[End]
}

#message:1D:(Menus_0063) {
	Switch to which[BR]
	member?[End]
}

#message:1D:(Menus_0064) {
	Throw away[BR]
	which one?[End]
}

#message:1D:(Menus_0065) {
	Sell which one?[End]
}

#message:1D:(Menus_0066) {
	Check which one?[BR]
	[End]
}

#message:1D:(Menus_0067) {
	Claim which one?[End]
}

#message:1D:(Menus_0068) {
	Don't Double Dip?[End]
}

#message:1D:(Menus_0069) {
	Don't Triple Dip?[End]
}

#message:1D:(Menus_006A) {
	Select a member[BR]
	to upgrade![End]
}

#message:1D:(Menus_006B) {
	You already have[BR]
	that partner![End]
}

#message:1D:(Menus_006C) {
	Read which [BR]
	page?[End]
}

#message:1D:(Menus_006D) {
	Read which [BR]
	letter?[End]
}

#message:1D:(Menus_006E) {
	Rank[End]
}

#message:1D:(Menus_006F) {
	Read which[BR]
	letter?[End]
}

#message:1D:(Menus_0070) {
	Trade for[BR]
	which one?[End]
}

#message:1D:(Menus_Merlee_IncreaseAttack) {
	The spell will increase[BR]
	your attack power![End]
}

#message:1D:(Menus_Merlee_DecreaseDamage) {
	The spell will decrease[BR]
	the damage you receive![End]
}

#message:1D:(Menus_Merlee_IncreaseStarPoints) {
	The spell will increase[BR]
	the Star Points you earn![End]
}

#message:1D:(Menus_Merlee_IncreaseCoins) {
	The spell will increase[BR]
	the number of coins you win![End]
}

#message:1D:(Menus_Merlee_Exhausted) {
	The spell's power has run out.[End]
}

#message:1D:(Menus_ChargeHammer) {
	Hammer's attack power will[BR]
	increase by [Var 0]![End]
}

#message:1D:(Menus_ChargeHammerMore) {
	Hammer's attack power will[BR]
	increase by [Var 0] more![End]
}

#message:1D:(Menus_ChargeJump) {
	Jump's attack power will[BR]
	increase by [Var 0]![End]
}

#message:1D:(Menus_ChargeJumpMore) {
	Jump's attack power will[BR]
	increase by [Var 0] more![End]
}

#message:1D:(Menus_ChargeMaxedOut) {
	You can't charge any more![End]
}

#message:1D:(Menus_EnemyMissed) {
	The enemy attack missed you![End]
}

#message:1D:(Menus_PartnerInjured) {
	You're injured--you can't move![End]
}

#message:1D:(Menus_ChargeGoombario) {
	Goombario's attack power will[BR]
	increase by 2![End]
}

#message:1D:(Menus_ChargeGoombarioMore) {
	Goombario's attack power will[BR]
	increase by 2 more![End]
}

#message:1D:(Menus_StarEnergyRecharged) {
	Star Energy is slightly charged![End]
}

#message:1D:(Menus_StarEnergyFilled) {
	Star Energy is fully charged![End]
}

#message:1D:(Menus_StarEnergyMaxedOut) {
	You can't charge any more![End]
}

#message:1D:(Menus_AttackUp) {
	Attack power will go up by [Var 0]![End]
}

#message:1D:(Menus_DefenseUp) {
	Defense power will go up by [Var 0]![End]
}

#message:1D:(Menus_0084) {
	[Var 0][End]
}

#message:1D:(Menus_0085) {
	[Var 0][End]
}

#message:1D:(Menus_EnemyTransparent) {
	The enemy's transparent![End]
}

#message:1D:(Menus_EnemyElectricCharge) {
	He gets an electric charge![End]
}

#message:1D:(Menus_PlayerDazed) {
	Mario's dazed![BR]
	He can't move right now!![End]
}

#message:1D:(Menus_PlayerPoisoned) {
	Mario's poisoned![BR]
	His HP is going down!![End]
}

#message:1D:(Menus_PlayerFrozen) {
	Mario's frozen![BR]
	He can't move right now!![End]
}

#message:1D:(Menus_PlayerAsleep) {
	Mario's fallen asleep![BR]
	He can't move right now!![End]
}

#message:1D:(Menus_PlayerShrunk) {
	Mario's been shrunk! His attack[BR]
	power is half of normal!![End]
}

#message:1D:(Menus_PlayerParalyzed) {
	Mario's paralyzed![BR]
	He can't move right now!![End]
}

#message:1D:(Menus_PlayerElectricCharge) {
	Mario's electrically charged![BR]
	He can electrify an enemy!![End]
}

#message:1D:(Menus_PlayerTransparent) {
	Mario's transparent![BR]
	Attacks won't strike him!![End]
}

#message:1D:(Menus_EnemyDazed) {
	Your enemy's dazed and[BR]
	can't move![End]
}

#message:1D:(Menus_EnemyPoisoned) {
	Your enemy's poisoned![End]
}

#message:1D:(Menus_EnemyFrozen) {
	Your enemy's frozen and[BR]
	can't move![End]
}

#message:1D:(Menus_EnemyAsleep) {
	Your enemy has fallen asleep![End]
}

#message:1D:(Menus_EnemyShrunk) {
	Your enemy's been shrunk! Its[BR]
	attack power is half of normal!![End]
}

#message:1D:(Menus_EnemyParalyzed) {
	Your enemy's paralyzed and[BR]
	can't move![End]
}

#message:1D:(Menus_EnemyElectrified) {
	Your enemy's electrified![End]
}

#message:1D:(Menus_EnemyCantMove) {
	Your enemy can't move now![End]
}

#message:1D:(Menus_WaterBlockBegin) {
	Mario will be protected by[BR]
	Water Block for a short time![End]
}

#message:1D:(Menus_WaterBlockEnd) {
	The Water Block's effect has [BR]
	worn off![End]
}

#message:1D:(Menus_CloudNineBegin) {
	Chances of being attacked [BR]
	will decrease![End]
}

#message:1D:(Menus_CloudNineEnd) {
	The effect of Cloud Nine has[BR]
	worn off![End]
}

#message:1D:(Menus_TurboChargeBegin) {
	Your attack power will go up[BR]
	for a short time![End]
}

#message:1D:(Menus_TurboChargeEnd) {
	Your attack power has[BR]
	returned to normal![End]
}

#message:1D:(Menus_ChillOutBegin) {
	Your enemy's attack power has[BR]
	gone down![End]
}

#message:1D:(Menus_NotEnoughFP) {
	You don't have enough FP![End]
}

#message:1D:(Menus_NotEnoughStarPower) {
	You don't have enough Star[BR]
	Energy![End]
}

#message:1D:(Menus_Action_ChangePartner) {
	You'll change your party member![End]
}

#message:1D:(Menus_Action_DoNothing) {
	You won't do anything during[BR]
	this turn![End]
}

#message:1D:(Menus_Action_RunAway) {
	You'll run away from the battle![End]
}

#message:1D:(Menus_Action_UseItem) {
	You'll use an item![End]
}

#message:1D:(Menus_LevelUp_HP) {
	Max HP will go up by 5.[BR]
	Select this to increase HP.[BR]
	[BR]
	[BR]
	[End]
}

#message:1D:(Menus_LevelUp_FP) {
	Max FP will go up by 5.[BR]
	Select this to use abilities often.[End]
}

#message:1D:(Menus_LevelUp_BP) {
	Max BP will go up by 3.[BR]
	Select this to use lots of Badges.[End]
}

#message:1D:(Menus_LevelUp_MaxedHP) {
	HP has reached maximum.[BR]
	You can't increase it anymore![End]
}

#message:1D:(Menus_LevelUp_MaxedFP) {
	FP has reached maximum.[BR]
	You can't increase it anymore![End]
}

#message:1D:(Menus_LevelUp_MaxedBP) {
	BP has reached maximum.[BR]
	You can't increase it anymore![End]
}

#message:1D:(Menus_CantIncrease) {
	You can't increase it anymore![End]
}

#message:1D:(Menus_PlayerFirstStrike) {
	[Color 0x0][Shake][DropShadow]You made the First Strike!![End]
}

#message:1D:(Menus_PartnerFirstStrike) {
	[Color 0x0][Shake][DropShadow]You made the First Strike!![End]
}

#message:1D:(Menus_EnemyFirstStrike) {
	[Color 0x0][Shake][DropShadow]You're hit by the First Strike![End]
}

#message:1D:(Menus_MoveTip_PressBeforeLanding) {
	Press    right before landing![End]
}

#message:1D:(Menus_MoveTip_PushLeftWithTiming) {
	Push    to the left and release[BR]
	it when    lights up![End]
}

#message:1D:(Menus_MoveTip_PressBeforeStriking) {
	Press    right before striking[BR]
	an enemy![End]
}

#message:1D:(Menus_MoveTip_PressRepeatedly) {
	Press     repeatedly![End]
}

#message:1D:(Menus_MoveTip_PushLeftRepeatedly) {
	Push    to the left repeatedly![End]
}

#message:1D:(Menus_MoveTip_PushLeftToAim) {
	Press    to the left and release[BR]
	it when aiming at    ![End]
}

#message:1D:(Menus_MoveTip_PressAsShown) {
	Press           as shown![End]
}

#message:1D:(Menus_MoveTip_NOT_USED_1) {
	(NOT USED ANY LONGER!)[End]
}

#message:1D:(Menus_MoveTip_PressAsLightsUp) {
	Press    as    lights up![End]
}

#message:1D:(Menus_MoveTip_NOT_USED_2) {
	(NOT USED ANY LONGER!)[End]
}

#message:1D:(Menus_MoveTip_PressBothRepeatedly) {
	Press       together repeatedly![End]
}

#message:1D:(Menus_MoveTip_HoldThenTap) {
	Hold then tap     to power up,[BR]
	but don't let it reach the edge.[End]
}

#message:1D:(Menus_MoveTip_HoldThenRelease) {
	Hold    down and release[BR]
	when    lights up![End]
}

#message:1D:(Menus_MoveTip_MoveToAim) {
	Move    with    and aim at    ![End]
}

#message:1D:(Menus_MoveTip_PressToRunAway) {
	Press    repeatedly to[BR]
	run away![End]
}

#message:1D:(Menus_MoveTip_PressToReduceDamage) {
	Press    repeatedly to[BR]
	reduce damage![End]
}

#message:1D:(Menus_MoveTip_NOT_USED_3) {
	(NOT USED ANY LONGER!)[End]
}

#message:1D:(Menus_Battle_NoTarget_Jump) {
	There's no enemy to jump on.[End]
}

#message:1D:(Menus_Battle_NoTarget_Hammer) {
	There's no enemy to hit with [BR]
	the Hammer.[End]
}

#message:1D:(Menus_Battle_NoTarget_Item) {
	You don't have an item[BR]
	you can use now![End]
}

#message:1D:(Menus_Battle_CantSelectNow) {
	You can't select it now![End]
}

#message:1D:(Menus_Battle_TargetMario) {
	Mario[End]
}

#message:1D:(Menus_Battle_TargetAllEnemies) {
	All Enemies[End]
}

#message:1D:(Menus_Battle_CantUseHammer) {
	You can't use a Hammer now![BR]
	[End]
}

#message:1D:(Menus_Battle_CantUseJump) {
	You can't jump now![End]
}

#message:1D:(Menus_Battle_CantUseItems) {
	You can't use any items now![BR]
	[End]
}

#message:1D:(Menus_Battle_CantSwitch) {
	Since you've already used your[BR]
	turn, you can't switch![BR]
	[End]
}

#message:1D:(Menus_Battle_CantMove) {
	[Var 0] can't move![End]
}

#message:1D:(Menus_Battle_CantSwitch2) {
	You can't switch now.[End]
}

#message:1D:(Menus_Battle_CantRunAway) {
	You can't run away![End]
}

#message:1D:(Menus_00CD) {
	Page [Var 0][End]
}

#message:1D:(Menus_00CE) {
	Luigi's Diary[End]
}

#message:1D:(Menus_00CF) {
	From [Var 0][End]
}

#message:1D:(Menus_00D0) {
	Letters for Mario[End]
}

#message:1D:(Menus_00D1) {
	Heart Points[End]
}

#message:1D:(Menus_00D2) {
	Flower Points[End]
}

#message:1D:(Menus_00D3) {
	Badge Points[End]
}

#message:1D:(Menus_00D4) {
	[Style inspect]
	It's empty.[Wait][End]
}

#message:1D:(Menus_00D5) {
	[Style inspect]
	You already have as many[BR]
	items as you can carry.[Wait][End]
}

#message:1D:(Menus_00D6) {
	Claim which one?[End]
}

#message:1D:(Menus_00D7) {
	Treasure Chest[End]
}

#message:1D:(Menus_00D8) {
	[Style inspect]
	[DelayOff]
	It's locked! You can't open it.[Wait][End]
}

#message:1D:(Menus_00D9) {
	[Style inspect]
	[DelayOff]
	You can't open it![Wait][End]
}

#message:1D:(Menus_00DA) {
	[Style upgrade pos=40,35 size=240,42]
	This is a Super Block.[BR]
	[Wait][Next]
	With this, you can upgrade [BR]
	one of your party members.[BR]
	[Wait][Next]
	The member you upgrade[BR]
	will gain attack power.[BR]
	[Wait][Next]
	The party member will also[BR]
	master a new ability. [BR]
	[Wait][Next]
	Which party member do you[BR]
	want to upgrade?[Wait][End]
}

#message:1D:(Menus_00DB) {
	[Style upgrade pos=40,35 size=240,42]
	With this, you can upgrade [BR]
	one of your party members.[BR]
	[Wait][Next]
	Which party member do you[BR]
	want to upgrade?[Wait][End]
}

#message:1D:(Menus_00DC) {
	[Style upgrade pos=40,35 size=240,42]
	You have no member you can[BR]
	upgrade now.[Wait][End]
}

#message:1D:(Menus_00DD) {
	[Style upgrade pos=40,35 size=240,42]
	[Var 0] is upgraded to[BR]
	Super-rank![Wait][End]
}

#message:1D:(Menus_00DE) {
	[Style upgrade pos=40,35 size=240,42]
	[Var 0] is upgraded to[BR]
	Ultra-rank![Wait][End]
}

#message:1D:(Menus_00DF) {
	[Style upgrade pos=40,35 size=240,42]
	Do you want to upgrade this[BR]
	member?[BR]
	[Yield][End]
}

#message:1D:(Menus_00E0) {
	He'll master Charge.[BR]
	His attack power will go up.[End]
}

#message:1D:(Menus_00E1) {
	He'll master Multibonk and be[BR]
	able to Headbonk consecutively.[BR]
	[End]
}

#message:1D:(Menus_00E2) {
	He'll master Dizzy Shell[BR]
	to paralyze enemies.[BR]
	[End]
}

#message:1D:(Menus_00E3) {
	He'll master Fire Shell[BR]
	to attack with a flaming shell.[BR]
	[End]
}

#message:1D:(Menus_00E4) {
	She'll master Power Bomb[BR]
	to attack all on-ground enemies.[End]
}

#message:1D:(Menus_00E5) {
	She'll master Mega Bomb[BR]
	to attack all enemies.[End]
}

#message:1D:(Menus_00E6) {
	He'll master Air Lift to[BR]
	carry an enemy from battle.[End]
}

#message:1D:(Menus_00E7) {
	He'll master Air Raid[BR]
	to attack all enemies.[End]
}

#message:1D:(Menus_00E8) {
	She'll master Spook to [BR]
	scare all enemies from battle.[End]
}

#message:1D:(Menus_00E9) {
	She'll master Fan Smack[BR]
	to attack with a fan.[End]
}

#message:1D:(Menus_00EA) {
	He'll master Turbo Charge to [BR]
	increase Mario's attack power.[End]
}

#message:1D:(Menus_00EB) {
	He'll master Mega Shock[BR]
	to paralyze all enemies.[End]
}

#message:1D:(Menus_00EC) {
	She'll master Water Block to[BR]
	increase Mario's defense power.[End]
}

#message:1D:(Menus_00ED) {
	She'll master Tidal Wave[BR]
	to attack all enemies.[End]
}

#message:1D:(Menus_00EE) {
	He'll master Cloud Nine[BR]
	to avoid enemy attacks.[End]
}

#message:1D:(Menus_00EF) {
	He'll master Hurricane to blow[BR]
	all enemies out of the battle.[BR]
	[End]
}

#message:1D:(Menus_00F0) {
	That one's already[BR]
	Super-ranked.[End]
}

#message:1D:(Menus_00F1) {
	That one's already[BR]
	Ultra-ranked.[BR]
	[End]
}

#message:1D:(Menus_00F2) {
	Toad Town[End]
}

#message:1D:(Menus_00F3) {
	It's the largest town in the[BR]
	Mushroom Kingdom. [BR]
	Princess Peach's Castle used to[BR]
	be just to the north of town.[BR]
	There are shops, a post office[BR]
	and other interesting sites.[BR]
	There's a station and a port[BR]
	to the south of town, too.[End]
}

#message:1D:(Menus_00F4) {
	It's the biggest town in the[BR]
	Mushroom Kingdom.[BR]
	Princess Peach's Castle is[BR]
	in the north of this town.[End]
}

#message:1D:(Map_PeachsCastleGrounds_Name) {
	Princess Peach's Castle[End]
}

#message:1D:(Map_PeachsCastleGrounds_DescBefore) {
	Princess Peach's Castle used to[BR]
	be right here, on this very spot. [BR]
	But then the evil King Bowser[BR]
	uprooted the castle--[BR]
	and kidnapped Princess Peach.[BR]
	 [BR]
	Only a big hole is left here now.[End]
}

#message:1D:(Map_PeachsCastleGrounds_DescAfter) {
	This castle is where our beloved[BR]
	Princess Peach lives.[BR]
	That evil King Bowser once stole[BR]
	the castle...[BR]
	But now it's back, and it's as[BR]
	beautiful as ever.[End]
}

#message:1D:(Map_ShootingStarSummit_Name) {
	Shooting Star Summit[End]
}

#message:1D:(Map_ShootingStarSummit_DescBefore) {
	They say this summit is the[BR]
	closest place to Star Haven.[BR]
	At the base of the summit live[BR]
	Merlow and Merluvlee.[BR]
	They're brother and sister.[End]
}

#message:1D:(Map_ShootingStarSummit_DescAfter) {
	They say this summit is the[BR]
	closest place to Star Haven.[BR]
	At the base of the summit live [BR]
	Merlow and Merluvlee.[BR]
	They're brother and sister.[End]
}

#message:1D:(Map_ToadTownTunnels_Name) {
	Toad Town Tunnels[End]
}

#message:1D:(Map_ToadTownTunnels_DescBefore) {
	The system of tunnels runs[BR]
	under Toad Town.[BR]
	There are many pipes inside--[BR]
	some of them are shortcuts.[End]
}

#message:1D:(Map_ToadTownTunnels_DescAfter) {
	The system of tunnels runs[BR]
	under Toad Town.[BR]
	There are many pipes inside--[BR]
	some of them are shortcuts.[End]
}

#message:1D:(Map_GoombaVillage_Name) {
	Goomba Village[End]
}

#message:1D:(Map_GoombaVillage_DescBefore) {
	Beaten by Bowser, Mario fell[BR]
	into the forest near here.[BR]
	Goombario's family lives here,[BR]
	and there's a Toad House, too.[End]
}

#message:1D:(Map_GoombaVillage_DescAfter) {
	Goombario's family lives here [BR]
	and there's a Toad House, too.[BR]
	The tree next to Goombario's [BR]
	house bears Goomnuts. [End]
}

#message:1D:(Map_GoombaRoad_Name) {
	Goomba Road[End]
}

#message:1D:(Map_GoombaRoad_DescBefore) {
	This road from Toad Town leads[BR]
	straight to Goomba Village.[End]
}

#message:1D:(Map_GoombaRoad_DescAfter) {
	This road from Toad Town leads[BR]
	straight to Goomba Village.[BR]
	There's a fortress built by [BR]
	the Goomba King on the way.[End]
}

#message:1D:(Map_PleasantPath_Name) {
	Pleasant Path[End]
}

#message:1D:(Map_PleasantPath_DescBefore) {
	This path links Toad Town and[BR]
	Koopa Village. [BR]
	Koopa Bros. Fortress is to the[BR]
	east.[End]
}

#message:1D:(Map_PleasantPath_DescAfter) {
	This path links Toad Town and[BR]
	Koopa Village. [BR]
	Koopa Bros. Fortress is to the[BR]
	east.[End]
}

#message:1D:(Map_KoopaVillage_Name) {
	Koopa Village[End]
}

#message:1D:(Map_KoopaVillage_DescBefore) {
	Many Koopas live in this village.[BR]
	 [BR]
	Lately, Fuzzies have been[BR]
	playing tricks on them.[End]
}

#message:1D:(Map_KoopaVillage_DescAfter) {
	Many Koopas live here, including[BR]
	Kolorado and Koopa Koot.[BR]
	Bob-ombs, refugees from Koopa[BR]
	Bros. Fortress, live here, too.[End]
}

#message:1D:(Map_KoopaBrosFortress_Name) {
	Koopa Bros. Fortress[End]
}

#message:1D:(Map_KoopaBrosFortress_DescBefore) {
	This is the fortress where the [BR]
	Koopa Bros. are holing up.[End]
}

#message:1D:(Map_KoopaBrosFortress_DescAfter) {
	One of the Star Spirits was [BR]
	held here by the Koopa Bros.[BR]
	This fortress was originally[BR]
	the home of the Bob-ombs.[End]
}

#message:1D:(Map_MtRugged_Name) {
	Mt. Rugged[End]
}

#message:1D:(Map_MtRugged_DescBefore) {
	It's a very rugged, rocky[BR]
	mountain.[BR]
	Dry Dry Railroad's Mt. Rugged[BR]
	Station is here.[BR]
	Dry Dry Desert is on the other [BR]
	side of Mt. Rugged.[End]
}

#message:1D:(Map_MtRugged_DescAfter) {
	It's a very rugged, rocky[BR]
	mountain.[BR]
	Dry Dry Railroad's Mt. Rugged[BR]
	Station is here.[BR]
	Dry Dry Desert is on the other [BR]
	side of Mt. Rugged.[End]
}

#message:1D:(Map_DryDryDesert_Name) {
	Dry Dry Desert[End]
}

#message:1D:(Map_DryDryDesert_DescBefore) {
	Like the name says, it's dry.[BR]
	Really dry.[BR]
	They say that the Dry Dry Ruins [BR]
	are somewhere around here.[End]
}

#message:1D:(Map_DryDryDesert_DescAfter) {
	Like the name says, it's dry.[BR]
	Dry Dry Ruins were found here.[End]
}

#message:1D:(Map_DryDryOutpost_Name) {
	Dry Dry Outpost[End]
}

#message:1D:(Map_DryDryOutpost_DescBefore) {
	It's a small desert town that has[BR]
	many inhabitants for its size.[BR]
	You'll find a Toad House and a[BR]
	shop here.[End]
}

#message:1D:(Map_DryDryOutpost_DescAfter) {
	It's a small desert town that has[BR]
	many inhabitants for its size.[BR]
	You'll find a Toad House and a[BR]
	shop here.[End]
}

#message:1D:(Map_DryDryRuins_Name) {
	Dry Dry Ruins[End]
}

#message:1D:(Map_DryDryRuins_DescBefore) {
	These ancient ruins appeared[BR]
	mysteriously in Dry Dry Desert.[BR]
	It seems that a Star Spirit is[BR]
	being held here by Bowser's men.[End]
}

#message:1D:(Map_DryDryRuins_DescAfter) {
	The ancient ruins appeared[BR]
	mysteriously in Dry Dry Desert.[BR]
	A Star Spirit was once held[BR]
	here by Tutankoopa.[End]
}

#message:1D:(Map_ForeverForest_Name) {
	Forever Forest[End]
}

#message:1D:(Map_ForeverForest_DescBefore) {
	Sunshine barely reaches the[BR]
	floor of this dense forest.[BR]
	They say that Boo's Mansion is[BR]
	somewhere deep inside.[End]
}

#message:1D:(Map_ForeverForest_DescAfter) {
	Sunshine barely reaches the[BR]
	floor of this dense forest.[BR]
	They say that Boo's Mansion is[BR]
	somewhere deep inside.[End]
}

#message:1D:(Map_BoosMansion_Name) {
	Boo's Mansion[End]
}

#message:1D:(Map_BoosMansion_DescBefore) {
	It's a mansion. For Boos, of[BR]
	course. Watch out for tricks! [BR]
	[End]
}

#message:1D:(Map_BoosMansion_DescAfter) {
	Lots of Boos live here.[BR]
	There's a shop in the basement.[End]
}

#message:1D:(Map_GustyGulch_Name) {
	Gusty Gulch[End]
}

#message:1D:(Map_GustyGulch_DescBefore) {
	Boos like to hang around this[BR]
	deserted gulch.[BR]
	On the ridge is the castle of[BR]
	the Invincible Tubba Blubba.[End]
}

#message:1D:(Map_GustyGulch_DescAfter) {
	Boos like to hang around this[BR]
	deserted gulch.[BR]
	On the ridge is the castle of[BR]
	the Invincible Tubba Blubba.[End]
}

#message:1D:(Map_TubbaBlubbasCastle_Name) {
	Tubba Blubba's Castle[End]
}

#message:1D:(Map_TubbaBlubbasCastle_DescBefore) {
	The Invincible Tubba Blubba lives[BR]
	in this castle.[End]
}

#message:1D:(Map_TubbaBlubbasCastle_DescAfter) {
	The Once-Invincible Tubba Blubba[BR]
	used to live in this castle.[End]
}

#message:1D:(Map_WindyMill_Name) {
	Windy Mill[End]
}

#message:1D:(Map_WindyMill_DescBefore) {
	This huge windmill is located at[BR]
	the bottom of Gusty Gulch.[BR]
	Invincible Tubba Blubba's secret[BR]
	is supposed to be hidden here.[End]
}

#message:1D:(Map_WindyMill_DescAfter) {
	It's a huge windmill located at[BR]
	the bottom of Gusty Gulch.[BR]
	Once-Invincible Tubba Blubba's[BR]
	heart was hidden deep inside.[End]
}

#message:1D:(Map_ShyGuysToyBox_Name) {
	Shy Guy's Toy Box[End]
}

#message:1D:(Map_ShyGuysToyBox_DescBefore) {
	There are Shy Guys inside.[BR]
	It's their hideout and base.[End]
}

#message:1D:(Map_ShyGuysToyBox_DescAfter) {
	Shy Guys are inside the box.[BR]
	It's their hideout and base.[BR]
	A Star Spirit was held here[BR]
	by Bowser's General Guy.[End]
}

#message:1D:(Map_JadeJungle_Name) {
	Jade Jungle[End]
}

#message:1D:(Map_JadeJungle_DescBefore) {
	The jungle on Lavalava Island [BR]
	is lush and green.[BR]
	All sorts of rare plants grow[BR]
	here.[End]
}

#message:1D:(Map_JadeJungle_DescAfter) {
	Many kinds of rare plants grow[BR]
	in this lush jungle.[BR]
	Raphael the Raven lives at the [BR]
	top of a big tree here.[End]
}

#message:1D:(Map_YoshisVillage_Name) {
	Yoshi's Village[End]
}

#message:1D:(Map_YoshisVillage_DescBefore) {
	Yoshis and Ravens live in this[BR]
	village on Lavalava Island.[BR]
	A Toad House and a shop have[BR]
	been built here.[End]
}

#message:1D:(Map_YoshisVillage_DescAfter) {
	Yoshis and Ravens live in this[BR]
	village on Lavalava Island.[BR]
	A Toad House and a shop have[BR]
	been built here.[End]
}

#message:1D:(Map_MtLavalava_Name) {
	Mt. Lavalava[End]
}

#message:1D:(Map_MtLavalava_DescBefore) {
	This huge volcano rises from[BR]
	Lavalava Island.[BR]
	Kolorado claims there's a [BR]
	treasure somewhere inside.[End]
}

#message:1D:(Map_MtLavalava_DescAfter) {
	This huge volcano rises from[BR]
	Lavalava Island.[BR]
	There was once a huge eruption,[BR]
	but it's calm now.[BR]
	A Star Spirit was held here[BR]
	by Lava Piranha.[End]
}

#message:1D:(Map_FlowerFields_Name) {
	Flower Fields[End]
}

#message:1D:(Map_FlowerFields_DescBefore) {
	The Flower Gate is the only[BR]
	entrance to Flower Fields.[BR]
	Many kinds of flower bloom in[BR]
	this aromatic garden region.[End]
}

#message:1D:(Map_FlowerFields_DescAfter) {
	The Flower Gate is the only[BR]
	entrance to Flower Fields.[BR]
	A Star Spirit was once[BR]
	imprisoned here by Huff N. Puff.[End]
}

#message:1D:(Map_CloudyClimb_Name) {
	Cloudy Climb[End]
}

#message:1D:(Map_CloudyClimb_DescBefore) {
	A strange cloud here blocks the[BR]
	sun from Flower Fields.[End]
}

#message:1D:(Map_CloudyClimb_DescAfter) {
	A Star Spirit was once held near[BR]
	here by Huff N. Puff.[End]
}

#message:1D:(Map_ShiverCity_Name) {
	Shiver City[End]
}

#message:1D:(Map_ShiverCity_DescBefore) {
	A path to Starborn Valley leads[BR]
	from this chilly penguin city.[End]
}

#message:1D:(Map_ShiverCity_DescAfter) {
	This chilly penguin city has[BR]
	a Toad House and a shop.[BR]
	A path leads to Starborn Valley[BR]
	and Shiver Mountain from here.[End]
}

#message:1D:(Map_ShiverSnowfield_Name) {
	Shiver Snowfield[End]
}

#message:1D:(Map_ShiverSnowfield_DescBefore) {
	This icy snowfield links Shiver[BR]
	City with Starborn Valley.[End]
}

#message:1D:(Map_ShiverSnowfield_DescAfter) {
	This icy snowfield links Shiver[BR]
	City with Starborn Valley.[BR]
	A path leads from the snowfield[BR]
	to Shiver Mountain.[BR]
	By going through the mountain,[BR]
	you can reach Crystal Palace.[BR]
	[End]
}

#message:1D:(Map_StarbornValley_Name) {
	Starborn Valley[End]
}

#message:1D:(Map_StarbornValley_DescBefore) {
	Star Kids are born in this [BR]
	sparkling valley.[BR]
	Frost T. and Ninjis take care[BR]
	of the newly born Star Kids.[BR]
	Merle's house and a Toad House [BR]
	are here, too.[End]
}

#message:1D:(Map_StarbornValley_DescAfter) {
	Star Kids are born in this [BR]
	sparkling valley.[BR]
	Frost T. and Ninjis take care[BR]
	of the newly born Star Kids.[BR]
	Merle's house and a Toad House [BR]
	are here, too.[End]
}

#message:1D:(Map_ShiverMountain_Name) {
	Shiver Mountain[End]
}

#message:1D:(Map_ShiverMountain_DescBefore) {
	A mountain path here links Shiver[BR]
	Snowfield with Crystal Palace.[End]
}

#message:1D:(Map_ShiverMountain_DescAfter) {
	A mountain path here links Shiver[BR]
	Snowfield with Crystal Palace.[End]
}

#message:1D:(Map_CrystalPalace_Name) {
	Crystal Palace[End]
}

#message:1D:(Map_CrystalPalace_DescBefore) {
	Once a special place to wish on[BR]
	stars, it's now deserted.[End]
}

#message:1D:(Map_CrystalPalace_DescAfter) {
	This deserted palace was first[BR]
	built for wishing on stars.[BR]
	A Star Spirit was once held[BR]
	here by the Crystal King.[End]
}

#message:1D:(Map_StarWay_Name) {
	Star Way[End]
}

#message:1D:(Map_StarWay_DescBefore) {
	This starry path links Shooting[BR]
	Star Summit with Star Haven.[End]
}

#message:1D:(Map_StarWay_DescAfter) {
	This starry path links Shooting[BR]
	Star Summit with Star Haven.[End]
}

#message:1D:(Map_StarHaven_Name) {
	Star Haven[End]
}

#message:1D:(Map_StarHaven_DescBefore) {
	In the haven of the stars,[BR]
	wishes really do come true.[BR]
	The palace of the Star Spirits,[BR]
	the Star Sanctuary, is here.[End]
}

#message:1D:(Map_StarHaven_DescAfter) {
	In the haven of the stars,[BR]
	wishes really do come true.[BR]
	The palace of the Star Spirits,[BR]
	the Star Sanctuary, is here.[End]
}

#message:1D:(Map_BowsersCastle_Name) {
	Bowser's Castle[End]
}

#message:1D:(Map_BowsersCastle_DescBefore) {
	It's the castle of the wicked[BR]
	King Bowser, of course.[BR]
	To kidnap Princess Peach, he[BR]
	stole the whole castle.[BR]
	Now Princess Peach's Castle[BR]
	teeters atop Bowser's Castle.[End]
}

#message:1D:(Map_BowsersCastle_DescAfter) {
	Bowser's Castle used to be[BR]
	right here! That evil Koopa[BR]
	stole Princess Peach's Castle[BR]
	and captured Princess Peach.[End]
}

#message:1D:(Map_PeachsCastle_Name) {
	Princess Peach's Castle[End]
}

#message:1D:(Map_PeachsCastle_DescBefore) {
	Princess Peach's Castle now[BR]
	rests atop Bowser's Castle.[BR]
	Peach, the princess in peril,[BR]
	is being held inside.[BR]
	[End]
}

#message:1D:(Map_PeachsCastle_DescAfter) {
	Princess Peach's Castle was[BR]
	once here atop Bowser's Castle.[BR]
	But now it's gone.[End]
}

#message:1D:(Map_MariosHouse_Name) {
	Mario's House[End]
}

#message:1D:(Map_MariosHouse_DescBefore) {
	Mario and Luigi live here, but[BR]
	Luigi looks after the house.[BR]
	Here you can recover HP and FP[BR]
	or read letters sent to Mario.[End]
}

#message:1D:(Map_MariosHouse_DescAfter) {
	Mario and Luigi live here, but[BR]
	Luigi looks after the house.[BR]
	Here you can recover HP and FP[BR]
	or read letters sent to Mario.[End]
}

#message:1D:(Menus_Inspect_Toybox) {
	[Style inspect]
	It's a Toy Box.[BR]
	[Pause 5]It looks like something's inside![Wait][End]
}

#message:1D:(Menus_Inspect_ChompStatue) {
	[Style inspect]
	It's a Chomp Statue.[BR]
	[Pause 5]Maybe you can put something[BR]
	inside it.[Wait][End]
}

#message:1D:(Menus_Inspect_Phonograph) {
	[Style inspect]
	It's a phonograph.[BR]
	[Pause 5]It would be nice if there[BR]
	were a record to play...[BR]
	[Wait][End]
}

#message:1D:(Menus_Inspect_RaphaelStatue) {
	[Style inspect]
	It's a statue of[BR]
	Raphael the Raven![BR]
	[Pause 5]Maybe you can put something[BR]
	inside it.[Wait][End]
}

#message:1D:(Menus_Inspect_Well) {
	[Style inspect]
	It's a well.[Wait][End]
}

#message:1D:(Menus_Inspect_Snowman) {
	[Style inspect]
	It's a snowman.[BR]
	[Pause 5][Wait][End]
}

#message:1D:(Menus_SAM09_PlaceItemTip) {
	[Style inspect]
	Here's a space where you [BR]
	can put something.[BR]
	[Pause 5][Wait][End]
}

#message:1D:(Menus_Inspect_PickUpPrompt) {
	[Style inspect]
	Do you want to pick up the[BR]
	[Color 0x7][Var 0][Color 0x0]?[BR]
	[Yield][End]
}

#message:1D:(Menus_Inspect_CantCarryMore) {
	[Style inspect]
	You can't carry any more[BR]
	items![Wait][End]
}

#message:1D:(Menus_SAM10_PlaceItemTip) {
	[Style inspect]
	Here's a space where you [BR]
	can put something.[BR]
	[Pause 5][Wait][End]
}

#message:1D:(Menus_ISK11_TakeItemPrompt) {
	[Style inspect]
	Do you want to take the[BR]
	[Color 0x7][Var 0][Color 0x0] out?[BR]
	[Yield][End]
}

#message:1D:(Menus_Inspect_DoesntOpen) {
	[Style inspect]
	It doesn't seem to open.[Wait][End]
}

#message:1D:(Menus_Inspect_FoundHammer) {
	[Style narrate]
	You found the Hammer![BR]
	[Pause 10]Mario can do the [BR]
	Hammer attack now![BR]
	[Wait][Next]
	[SavePos][SetPosX 10][InlineImage index=0]
	[RestorePos][SetPosX 70]You can smash a[BR]
	[SetPosX 70]yellow block[BR]
	[SetPosX 70]with this Hammer.[Wait][End]
}

#message:1D:(Menus_Sign_BewareOfGoombas) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 15]Beware of Goombas![BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_Sign_EatMushroomsTip) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 6]Eat a Mushroom[BR]
	[Down 6]to regain your energy![BR]
	[BR]
	[Down 6]When HP gets low,[BR]
	[Down 6]eat a Mushroom with [C-LEFT][BR]
	[BR]
	[DelayOn]
	[Wait][Scroll 4][DelayOn]
	[Wait][End]
}

#message:1D:(Menus_Sign_EatMushroomsTrap) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 6]Eat a Mushroom[BR]
	[Down 6]to regain your energy![BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_Sign_GoombaKingsFortress) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 6]Goomba King's Fortress Ahead[BR]
	[Down 6][Right 105][RIGHT][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_Inspect_DangerSealed) {
	[Style inspect]
	Danger![BR]
	It's been sealed for your safety.[Wait][End]
}

#message:1D:(Menus_Inspect_LockedFromInside) {
	[Style inspect]
	It won't open.[BR]
	[Pause 10]It must be locked from[BR]
	the inside.[Wait][End]
}

#message:1D:(Menus_016B) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 15]Private[BR]
	[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_016C) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Right 8][Down 6][STAR]  Today's Menu  [STAR][BR]
	[Right 1][Down 6]Sailor's Lunch Special[BR]
	[Down 4] [BR]
	[Right 8][STAR] Mushroom Pasta [STAR][BR]
	[Right 8][STAR]  Seafood Soup   [STAR][BR]
	[Right 8][STAR]  Seafood Salad  [STAR][BR]
	[DelayOn]
	[Wait][Scroll 4][DelayOn]
	[Wait][End]
}

#message:1D:(Menus_016D) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Right 15][Down 6]Looking for something?[BR]
	[Down 6]Drop by Merluvlee's Place! [RIGHT][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_016E) {
	[DelayOff]
	[Style sign]
	[CenterX 255][BR]
	[Down 3]Shooting Star Summit [RIGHT][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_016F) {
	[DelayOff]
	[Style lamppost height=72]
	[Down 10][Color 0x1A][LEFT][Color 0x18][Right 122]Peach's Castle[BR]
	[Down 3][Color 0x18]Goomba Village [Color 0x1A][Right 120][RIGHT][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0170) {
	[DelayOff]
	[Style lamppost height=80]
	[Up 2][Right 115][Color 0x19][UP] North[BR]
	[Up 1][Color 0x1A]West [Color 0x18][Right 33]Peach's Castle     [Color 0x1A]East[BR]
	[Color 0x1A][LEFT][Color 0x18] Main Gate      Pleasant Path [Color 0x1A][RIGHT][BR]
	[Right 70][Color 0x18] Port/Station[BR]
	[Up 1][Right 115][Color 0x19][DOWN] South[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0171) {
	[DelayOff]
	[Style lamppost height=80]
	[Up 2][Right 115][Color 0x19][UP] North[BR]
	[Down 1][Color 0x1A]West [Color 0x18][Right 33][Up 2]Peach's Castle     [Color 0x1A][Down 1]East[BR]
	[Color 0x1A][LEFT][Color 0x18] Port           Forever Forest [Color 0x1A][RIGHT][BR]
	[Right 50][Color 0x18] Toad Town Station[BR]
	[Up 1][Right 115][Color 0x19][DOWN] South[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0172) {
	[DelayOff]
	[Style lamppost height=72]
	[Color 0x19][Down 8][Right 115][UP][BR]
	[Color 0x18][Right 35]Princess Peach's Castle[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0173) {
	[DelayOff]
	[Style lamppost height=72]
	[CenterX 255][Down 3][BR]
	[Color 0x1A][LEFT] [Color 0x18]Port       Peach's Castle  [Color 0x1A][RIGHT][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0174) {
	[DelayOff]
	[Style lamppost height=72]
	[CenterX 255][Down 3][BR]
	Princess Peach's Castle [Color 0x1A][RIGHT][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0175) {
	[DelayOff]
	[Style sign]
	[Down 6]Welcome to Toad Town's Famous[BR]
	[Down 6]Li'l Oink Farm.[BR]
	[BR]
	[Up 12][BR]
	Hit the bar overhead, pay 10[BR]
	coins, and wait for the egg.[BR]
	Hit it with the Hammer to [BR]
	hatch the Li'l Oink.[BR]
	Try to find out what kind of[BR]
	Li'l Oink will be born![BR]
	Have fun watching those [BR]
	adorable Li'l Oinks![BR]
	Be careful, though--if someone[BR]
	gets inside the fence, all[BR]
	the Li'l Oinks will run away.[BR]
	[BR]
	You can have a maximum of[BR]
	10 Li'l Oinks on the farm.[BR]
	[BR]
	[BR]
	When the 11th Li'l Oink enters,[BR]
	the 1st will leave.[BR]
	Now, try to see all of the[BR]
	different types of Li'l Oinks![BR]
	[DelayOn]
	[Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][Wait][Scroll 4][DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0176) {
	[Style inspect]
	Jump here and hit the lever [BR]
	for 20 coins.[BR]
	[Wait][Next]
	Do you want to jump?[BR]
	[Yield][End]
}

#message:1D:(Menus_0177) {
	[Style inspect]
	[Down 6]The door is securely locked[BR]
	from the other side.[Wait][End]
}

#message:1D:(Menus_0178) {
	[DelayOff]
	[Style sign]
	[SetPosX 2][LEFT] Toad Town[SetPosX 70][SetPosY 15]Koopa Bros. Fortress [RIGHT][SetPosX 90][SetPosY 28]Koopa Village[SetPosX 120][SetPosY 38][DOWN][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0179) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 6]No entry allowed, Mario![BR]
	[Down 4]    Yours truly, The Koopa Bros.[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_017A) {
	[DelayOff]
	[Style sign]
	[CenterX 255][SetPosX 35][Down 6]Welcome [Down 10][SetPosX 220][RIGHT][BR]
	[Up 10][Down 6]Dry Dry Outpost[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_017B) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 3][BR]
	Temporarily Closed[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_017C) {
	[DelayOff]
	[Style sign]
	[Down 6]Stone Cactus in the desert...[BR]
	[Down 6]Twice south, once east you go.[BR]
	[BR]
	[Down 6]Give up to the twister,[BR]
	[Down 6]Where Blue Cacti grow...[BR]
	[BR]
	[Down 6]Upon the mesa, the power of[BR]
	[Down 6]the dervish you'll know...[BR]
	[BR]
	[DelayOn]
	[Wait][Scroll 4][Wait][Scroll 4][DelayOn]
	[Wait][End]
}

#message:1D:(Menus_017D) {
	[Style narrate]
	You got the Super Hammer![BR]
	The attack power of [BR]
	Mario's Hammer increases![BR]
	[Wait][Next]
	On top of that, you can now [BR]
	destroy Stone Blocks![Wait][End]
}

#message:1D:(Menus_017E) {
	[DelayOff]
	[Style sign]
	[CenterX 255][Down 3][LEFT] Forever Forest [RIGHT][BR]
	[SetPosX 40][Down 5]Toad Town[BR]
	[SetPosX 70][SetPosY 32][DOWN][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_017F) {
	[DelayOff]
	[Style sign]
	[SetPosX 15][Down 3]If you have business at Boo's[BR]
	[SetPosX 15]Mansion, come this way.[BR]
	[SetPosX 120][SetPosY 30][DOWN][BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0180) {
	[Style narrate]
	You got the Super Boots![BR]
	[Pause 5]The attack power of[BR]
	Mario's Jump increases![BR]
	[Wait][Next]
	And now you can do the[BR]
	Spin Jump by pressing [A][BR]
	again while in the air![Wait][End]
}

#message:1D:(Menus_0181) {
	[Style inspect]
	Tap [A] to play the record.[BR]
	You've gotta have rhythm![BR]
	[Pause 10]Don't press it too fast[BR]
	or too slow![BR]
	[Wait][Next]
	If you press [B] while it's [BR]
	playing, the record will stop.[Wait][End]
}

#message:1D:(Menus_0182) {
	[DelayOff]
	[Style sign]
	[CenterX 255][BR]
	[Down 3]No entry allowed.[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0183) {
	[DelayOff]
	[Style sign]
	[CenterX 255][BR]
	[Down 3]Really! No entry allowed![BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0184) {
	[DelayOff]
	[Style sign]
	[CenterX 255][BR]
	[Down 3]Absolutely! No entry allowed!![BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0185) {
	[DelayOff]
	[Style sign]
	(NOT USED ANY LONGER!)[BR]
	[DelayOn]
	[Wait][End]
}

#message:1D:(Menus_0186) {
	[Style narrate]
	You got the Ultra Hammer![BR]
	[Pause 5]The attack power of[BR]
	Mario's Hammer increases!![BR]
	[Wait][Next]
	On top of that, you can[BR]
	now destroy Metal Blocks![Wait][End]
}

#message:1D:(Menus_0187) {
	[Style narrate]
	You got the Ultra Boots![BR]
	[Pause 5]The attack power of[BR]
	Mario's Jump increases!![BR]
	[Wait][Next]
	On top of that, you can now do[BR]
	a Tornado Jump by pressing [A][BR]
	again while in the air![Wait][End]
}

#message:1D:(Menus_0188) {
	[Style inspect]
	Are you ready to take off?[BR]
	[Yield][End]
}

#message:1D:(Menus_0189) {
	[Style narrate]
	[InputOff]
	Goombario joined your party!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] to have him tell you[BR]
	about people, places or things[BR]
	nearby.[BR]
	[Wait][Next]
	When you're interested,[BR]
	just ask him![BR]
	[Wait][Next]
	Goombario is also helpful during[BR]
	battles![BR]
	[Wait][Next]
	He can attack with Headbonk or[BR]
	he can tell you about an enemy's[BR]
	features and HP using his[BR]
	Tattle ability![Wait][End]
}

#message:1D:(Menus_018A) {
	[Style narrate]
	[InputOff]
	Kooper joined your party!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] to make him throw [BR]
	himself and reach an item or a [BR]
	switch in the distance.[BR]
	[Wait][Next]
	While in battle, he can attack[BR]
	an enemy on the ground with[BR]
	Shell Toss[BR]
	[Wait][Next]
	or attack all enemies on the[BR]
	ground with Power Shell![BR]
	[Wait][Next]
	When you want to switch your[BR]
	partner, press [C-RIGHT] and select[BR]
	the member you want to use.[Wait][End]
}

#message:1D:(Menus_018B) {
	[Style narrate]
	[InputOff]
	Bombette joined your party!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] to make Bombette [BR]
	walk for a short time and then[BR]
	explode![BR]
	[Wait][Next]
	She can destroy cracked walls[BR]
	or rocks and activate switches.[BR]
	[Wait][Next]
	While in battle, she can attack[BR]
	an enemy on the ground with her[BR]
	Body Slam ability[BR]
	[Wait][Next]
	or damage enemies on the ground[BR]
	with her Bomb attack![Wait][End]
}

#message:1D:(Menus_018C) {
	[Style narrate]
	[InputOff]
	Parakarry joined your party!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] to have him carry Mario[BR]
	and fly for a short time![BR]
	[Wait][Next]
	He can carry Mario over short[BR]
	gaps that he couldn't jump[BR]
	across by himself.[BR]
	[Wait][Next]
	While in battle, he can attack[BR]
	with Sky Dive or smash into[BR]
	enemies using his Shell Shot[BR]
	ability![Wait][End]
}

#message:1D:(Menus_018D) {
	[Style narrate]
	[InputOff]
	Bow joined the party-- [BR]
	like it or not!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] to have her make you[BR]
	both become transparent so[BR]
	no one will notice you![BR]
	[Wait][Next]
	While you're transparent,[BR]
	objects go right through you.[BR]
	[Wait][Next]
	But if you move or press [C-DOWN], you[BR]
	won't be transparent anymore.[BR]
	You'll return to normal.[BR]
	[Wait][Next]
	While in battle, she can slap[BR]
	enemies silly with her[BR]
	Smack attack[BR]
	[Wait][Next]
	or use Outta Sight to make you[BR]
	both become transparent so you[BR]
	can elude enemy attacks.[Wait][End]
}

#message:1D:(Menus_018E) {
	[Style narrate]
	[InputOff]
	Watt joined your party!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] to have her illuminate[BR]
	the area around you![BR]
	[Pause 10]With her light, you can see[BR]
	invisible blocks, too![BR]
	[Wait][Next]
	While in battle, she can shock[BR]
	enemies with Electro Dash or[BR]
	paralyze them with Power Shock![Wait][End]
}

#message:1D:(Menus_018F) {
	[Style narrate]
	[InputOff]
	Sushie joined your party!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] on platforms at the[BR]
	water's edge to ride her across[BR]
	the water.[BR]
	[Wait][Next]
	If you press [C-DOWN] again while[BR]
	riding her, she'll dive deep[BR]
	for a short time.[BR]
	[Wait][Next]
	While in battle, she can jump[BR]
	attack with Belly Flop or douse[BR]
	enemies with her Squirt ability![Wait][End]
}

#message:1D:(Menus_0190) {
	[Style narrate]
	[InputOff]
	Lakilester joined your party!![BR]
	[InputOn]
	[Wait][Next]
	[Image index=0 pos=85,97 hasBorder=1 alpha=255 fadeAmount=52]
	Press [C-DOWN] to ride Lakilester over[BR]
	spikes and lava.[BR]
	[Wait][Next]
	While in battle, he can attack[BR]
	by throwing a Spiny Egg with[BR]
	his Spiny Flip ability[BR]
	[Wait][Next]
	or attack all enemies by[BR]
	throwing many Spiny Eggs at[BR]
	once with Spiny Surge![Wait][End]
}

#message:1D:(Menus_0191) {
	[Style narrate]
	[Pause 5]Mario can now use the Star[BR]
	Spirit's Power in battle![Wait][End]
}

#message:1D:(Menus_0192) {
	[Style narrate]
	[Pause 5]Mario's Star Energy goes up[BR]
	to 2![BR]
	[Wait][Next]
	Mario can now use Lullaby,[BR]
	a new Star Spirit Power![BR]
	[Wait][Next]
	With Lullaby, you can make[BR]
	all enemies fall asleep![Wait][End]
}

#message:1D:(Menus_0193) {
	[Style narrate]
	[Pause 5]Mario's Star Energy goes up[BR]
	to 3![BR]
	[Wait][Next]
	Mario can now use Star Storm,[BR]
	a new Star Spirit Power![BR]
	[Wait][Next]
	With Star Storm, you can[BR]
	attack all enemies![Wait][End]
}

#message:1D:(Menus_0194) {
	[Style narrate]
	[Pause 5]Mario's Star Energy goes up[BR]
	to 4![BR]
	[Wait][Next]
	Mario can now use Chill Out, a[BR]
	new Star Spirit Power![BR]
	[Wait][Next]
	With Chill Out, you can lower the[BR]
	attack power of all enemies![Wait][End]
}

#message:1D:(Menus_0195) {
	[Style narrate]
	[Pause 5]Mario's Star Energy goes up[BR]
	to 5![BR]
	[Wait][Next]
	Mario can now use Smooch,[BR]
	a new Star Spirit Power![BR]
	[Wait][Next]
	With Smooch, you can restore[BR]
	Mario's HP![Wait][End]
}

#message:1D:(Menus_0196) {
	[Style narrate]
	[Pause 5]Mario's Star Energy goes up[BR]
	to 6![BR]
	[Wait][Next]
	Mario can now use Time Out,[BR]
	a new Star Spirit Power![BR]
	[Wait][Next]
	With Time Out, you can stop[BR]
	time--and stop all enemies[BR]
	in their tracks![Wait][End]
}

#message:1D:(Menus_0197) {
	[Style narrate]
	[Pause 5]Mario's Star Energy goes up[BR]
	to 7![BR]
	[Wait][Next]
	Mario can now use Up & Away,[BR]
	a new Star Spirit Power![BR]
	[Wait][Next]
	With Up & Away, you can turn[BR]
	all enemies into stars![Wait][End]
}

#message:1D:(Menus_0198) {
	[Style narrate]
	[Pause 5]Mario can now use Star Beam![Wait][End]
}

#message:1D:(Menus_0199) {
	[Style narrate]
	[Pause 5]Star Beam has been upgraded![BR]
	[Pause 10]It's now Peach Beam![BR]
	[Wait][Next]
	Mario can now use Peach Beam![Wait][End]
}

#message:1D:(Menus_019A) {
	[Style right]
	Don't underestimate me, Mario![BR]
	[Wait][Next]
	I'll never be be scared away[BR]
	by such a cheap trick![BR]
	No way! Never![Wait][End]
}

#message:1D:(Menus_019B) {
	[Style right]
	Hey, Mario!![BR]
	[Wait][Next]
	Don't even think of trying to [BR]
	beat me with such a cheesy[BR]
	trick![Wait][End]
}

#message:1D:(Menus_019C) {
	A Plea from the Stars[End]
}

#message:1D:(Menus_019D) {
	Storming Koopa Bros. Fortress[End]
}

#message:1D:(Menus_019E) {
	The Mystery of Dry Dry Ruins[End]
}

#message:1D:(Menus_019F) {
	The "Invincible" Tubba Blubba[End]
}

#message:1D:(Menus_01A0) {
	Trials in the Toy Box[End]
}

#message:1D:(Menus_01A1) {
	Hot Hot Times on Lavalava Island[End]
}

#message:1D:(Menus_01A2) {
	Dark Days in Flower Fields[End]
}

#message:1D:(Menus_01A3) {
	A Star Spirit on Ice[End]
}

#message:1D:(Menus_01A4) {
	A Star-Powered Showdown! [End]
}

#message:1D:(Menus_01A5) {
	[Style epilogue]
	[Color 0xA]And so Mario and friends[BR]
	beat the Koopa Bros. at[BR]
	their fortress and rescued[BR]
	the first Star Spirit.[BR]
	[Wait][Next]
	Still, six Star Spirits[BR]
	remain imprisoned, and[BR]
	they must save them as[BR]
	quickly as they can.[BR]
	[Wait][Next]
	The future of the[BR]
	Mushroom Kingdom, Star[BR]
	Haven and, of course,[BR]
	Princess Peach...[BR]
	[Wait][Next]
	lies in the hands of[BR]
	Mario...[BR]
	and his new friends.[BR]
	[Wait][Next]
	Their adventure has just[BR]
	begun.[Wait][End]
}

#message:1D:(Menus_01A6) {
	[Style epilogue]
	[Color 0xA]Thus Mario and party[BR]
	unearthed the legendary[BR]
	Dry Dry Ruins deep within[BR]
	Dry Dry Desert.[BR]
	[Wait][Next]
	They smashed Tutankoopa[BR]
	the Wizard and freed[BR]
	Mamar, the second of the[BR]
	wish-granting Star Spirits.[BR]
	[Wait][Next]
	But the enemies awaiting[BR]
	Mario grow ever stronger...[BR]
	and the challenges [BR]
	more difficult.[BR]
	[Wait][Next]
	What's in store for[BR]
	Mario and friends...[BR]
	Where will their adventure[BR]
	take them next?[Wait][End]
}

#message:1D:(Menus_01A7) {
	[Style epilogue]
	[Color 0xA]After solving the secret of[BR]
	"Invincible" Tubba Blubba,[BR]
	Mario and party set free[BR]
	Star Spirit Skolar.[BR]
	[Wait][Next]
	Now, with Tubba Blubba[BR]
	just a bad dream, the Boos[BR]
	are free to haunt to their[BR]
	hearts' content. [BR]
	[Wait][Next]
	Even the lonely wind[BR]
	echoing through Gusty[BR]
	Gulch seems to be[BR]
	celebrating the victory...[BR]
	[Wait][Next]
	at least for now.[BR]
	[Wait][Next]
	With newest party member,[BR]
	Bow, in tow, Mario and[BR]
	friends are ready to take[BR]
	on their next challenge.[Wait][End]
}

#message:1D:(Menus_01A8) {
	[Style epilogue]
	[Color 0xA]To save the fourth Star[BR]
	Spirit, Muskular, Mario[BR]
	and team disbanded the[BR]
	gang of Shy Guys toughs.[BR]
	[Wait][Next]
	Slowly, it seems as if the[BR]
	life force is returning to[BR]
	the once bleak night sky...[BR]
	[Wait][Next]
	But the stars won't[BR]
	truly shine until the[BR]
	Star Rod is wrested from[BR]
	Bowser's evil grasp.[BR]
	[Wait][Next]
	Three Star Spirits[BR]
	still await rescue.[BR]
	Where in the world are[BR]
	they being held?[Wait][End]
}

#message:1D:(Menus_01A9) {
	[Style epilogue]
	[Color 0xA]Venturing deep into the[BR]
	steamimg Mt. Lavalava,[BR]
	Mario and friends plucked[BR]
	the Lava Piranha...[BR]
	[Wait][Next]
	and rescued the fifth[BR]
	Star Spirit, Misstar,[BR]
	from a fiery fate.[BR]
	[Wait][Next]
	But the "treasure"[BR]
	Kolorado is looking for[BR]
	is yet to be found.[BR]
	Wherever could it be?[BR]
	[Wait][Next]
	What's that...?[BR]
	Something...strange...is[BR]
	going on around here...[Wait][End]
}

#message:1D:(Menus_01AA) {
	[Style epilogue]
	[Color 0xA]So it is that Mario and[BR]
	party defeat cruel cloud[BR]
	Huff N. Puff and set free[BR]
	the sixth Star Spirit.[BR]
	[Wait][Next]
	The thick clouds that once[BR]
	cast dark shadows have[BR]
	gone, and Flower Fields is[BR]
	bathed in sunshine again.[BR]
	[Wait][Next]
	A single Star Spirit waits[BR]
	to be rescued, waits to[BR]
	take its place in the[BR]
	Star Sanctuary.[BR]
	[Wait][Next]
	Perhaps you will see[BR]
	Princess Peach soon...[BR]
	Perhaps...[BR]
	Just wait and see.[BR]
	[Wait][Next]
	Kammy Koopa, who watches[BR]
	impatiently from Bowser's[BR]
	Castle, is waiting, too...[BR]
	[Wait][Next]
	for you to try to save[BR]
	them...[Wait][End]
}

#message:1D:(Menus_01AB) {
	[Style epilogue]
	[Color 0xA]Mario has saved the last[BR]
	Star Spirit, Kalmar,[BR]
	from the Crystal Palace[BR]
	at the edge of the world.[BR]
	[Wait][Next]
	Now, with the seven Star[BR]
	Spirits together, he has[BR]
	the power to challenge [BR]
	Bowser...and the Star Rod.[BR]
	[Wait][Next]
	At last, it is time for[BR]
	Mario's showdown with[BR]
	Evil King Bowser.[BR]
	[Wait][Next]
	Can Mario rescue Princess[BR]
	Peach and recover the [BR]
	Star Rod? Or will wishes [BR]
	forever go ungranted?[Wait][End]
}

#message:1D:(Lodgenet) {
	If Reset button on Controller is[BR]
	pressed during game, all previously[BR]
	saved data will be lost.[BR][BR]
	        Press [A] to continue.
	[End]
}