.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_info_handle_input
/* 174C24 8024C204 3C028025 */  lui        $v0, %hi(D_80251744)
/* 174C28 8024C208 8C421744 */  lw         $v0, %lo(D_80251744)($v0)
/* 174C2C 8024C20C 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 174C30 8024C210 AFBF0018 */  sw         $ra, 0x18($sp)
/* 174C34 8024C214 AFB10014 */  sw         $s1, 0x14($sp)
/* 174C38 8024C218 3042C000 */  andi       $v0, $v0, 0xC000
/* 174C3C 8024C21C 10400039 */  beqz       $v0, .Lfilemenu_8024C304
/* 174C40 8024C220 AFB00010 */   sw        $s0, 0x10($sp)
/* 174C44 8024C224 3C118025 */  lui        $s1, %hi(D_filemenu_8024E984)
/* 174C48 8024C228 8E31E984 */  lw         $s1, %lo(D_filemenu_8024E984)($s1)
/* 174C4C 8024C22C 3C018025 */  lui        $at, %hi(D_80251758)
/* 174C50 8024C230 A0201758 */  sb         $zero, %lo(D_80251758)($at)
/* 174C54 8024C234 82230004 */  lb         $v1, 0x4($s1)
/* 174C58 8024C238 24020001 */  addiu      $v0, $zero, 0x1
/* 174C5C 8024C23C 10620005 */  beq        $v1, $v0, .Lfilemenu_8024C254
/* 174C60 8024C240 24020003 */   addiu     $v0, $zero, 0x3
/* 174C64 8024C244 10620017 */  beq        $v1, $v0, .Lfilemenu_8024C2A4
/* 174C68 8024C248 2404002F */   addiu     $a0, $zero, 0x2F
/* 174C6C 8024C24C 080930BF */  j          .Lfilemenu_8024C2FC
/* 174C70 8024C250 00000000 */   nop
.Lfilemenu_8024C254:
/* 174C74 8024C254 A2200004 */  sb         $zero, 0x4($s1)
/* 174C78 8024C258 3C058024 */  lui        $a1, %hi(func_filemenu_80247304)
/* 174C7C 8024C25C 24A57304 */  addiu      $a1, $a1, %lo(func_filemenu_80247304)
/* 174C80 8024C260 0C051A8B */  jal        func_PAL_80146A2C
/* 174C84 8024C264 24040033 */   addiu     $a0, $zero, 0x33
/* 174C88 8024C268 3C058024 */  lui        $a1, %hi(func_filemenu_80247378)
/* 174C8C 8024C26C 24A57378 */  addiu      $a1, $a1, %lo(func_filemenu_80247378)
/* 174C90 8024C270 0C051A8B */  jal        func_PAL_80146A2C
/* 174C94 8024C274 24040034 */   addiu     $a0, $zero, 0x34
/* 174C98 8024C278 24040035 */  addiu      $a0, $zero, 0x35
/* 174C9C 8024C27C 3C108024 */  lui        $s0, %hi(func_filemenu_802473EC)
/* 174CA0 8024C280 261073EC */  addiu      $s0, $s0, %lo(func_filemenu_802473EC)
/* 174CA4 8024C284 0C051A8B */  jal        func_PAL_80146A2C
/* 174CA8 8024C288 0200282D */   daddu     $a1, $s0, $zero
/* 174CAC 8024C28C 24040037 */  addiu      $a0, $zero, 0x37
/* 174CB0 8024C290 0C051A8B */  jal        func_PAL_80146A2C
/* 174CB4 8024C294 0200282D */   daddu     $a1, $s0, $zero
/* 174CB8 8024C298 0220202D */  daddu      $a0, $s1, $zero
/* 174CBC 8024C29C 080930BC */  j          .Lfilemenu_8024C2F0
/* 174CC0 8024C2A0 0000282D */   daddu     $a1, $zero, $zero
.Lfilemenu_8024C2A4:
/* 174CC4 8024C2A4 A2200004 */  sb         $zero, 0x4($s1)
/* 174CC8 8024C2A8 3C058024 */  lui        $a1, %hi(func_filemenu_80247304)
/* 174CCC 8024C2AC 24A57304 */  addiu      $a1, $a1, %lo(func_filemenu_80247304)
/* 174CD0 8024C2B0 0C051A8B */  jal        func_PAL_80146A2C
/* 174CD4 8024C2B4 24040033 */   addiu     $a0, $zero, 0x33
/* 174CD8 8024C2B8 3C058024 */  lui        $a1, %hi(func_filemenu_80247378)
/* 174CDC 8024C2BC 24A57378 */  addiu      $a1, $a1, %lo(func_filemenu_80247378)
/* 174CE0 8024C2C0 0C051A8B */  jal        func_PAL_80146A2C
/* 174CE4 8024C2C4 24040034 */   addiu     $a0, $zero, 0x34
/* 174CE8 8024C2C8 24040035 */  addiu      $a0, $zero, 0x35
/* 174CEC 8024C2CC 3C108024 */  lui        $s0, %hi(func_filemenu_802473EC)
/* 174CF0 8024C2D0 261073EC */  addiu      $s0, $s0, %lo(func_filemenu_802473EC)
/* 174CF4 8024C2D4 0C051A8B */  jal        func_PAL_80146A2C
/* 174CF8 8024C2D8 0200282D */   daddu     $a1, $s0, $zero
/* 174CFC 8024C2DC 24040037 */  addiu      $a0, $zero, 0x37
/* 174D00 8024C2E0 0C051A8B */  jal        func_PAL_80146A2C
/* 174D04 8024C2E4 0200282D */   daddu     $a1, $s0, $zero
/* 174D08 8024C2E8 0220202D */  daddu      $a0, $s1, $zero
/* 174D0C 8024C2EC 24050001 */  addiu      $a1, $zero, 0x1
.Lfilemenu_8024C2F0:
/* 174D10 8024C2F0 0C091B29 */  jal        func_filemenu_80246CA4
/* 174D14 8024C2F4 24060002 */   addiu     $a2, $zero, 0x2
/* 174D18 8024C2F8 2404002F */  addiu      $a0, $zero, 0x2F
.Lfilemenu_8024C2FC:
/* 174D1C 8024C2FC 0C051A8B */  jal        func_PAL_80146A2C
/* 174D20 8024C300 24050002 */   addiu     $a1, $zero, 0x2
.Lfilemenu_8024C304:
/* 174D24 8024C304 8FBF0018 */  lw         $ra, 0x18($sp)
/* 174D28 8024C308 8FB10014 */  lw         $s1, 0x14($sp)
/* 174D2C 8024C30C 8FB00010 */  lw         $s0, 0x10($sp)
/* 174D30 8024C310 03E00008 */  jr         $ra
/* 174D34 8024C314 27BD0020 */   addiu     $sp, $sp, 0x20
