.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
glabel jtbl_PAL_802BEBD8
/* 3459A8 802BEBD8 802BDAB8 */ .word .LPAL_802BDAB8
/* 3459AC 802BEBDC 802BDD5C */ .word .LPAL_802BDD5C
/* 3459B0 802BEBE0 802BE24C */ .word .LPAL_802BE24C
/* 3459B4 802BEBE4 802BE38C */ .word .LPAL_802BE38C
/* 3459B8 802BEBE8 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459BC 802BEBEC 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459C0 802BEBF0 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459C4 802BEBF4 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459C8 802BEBF8 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459CC 802BEBFC 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459D0 802BEC00 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459D4 802BEC04 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459D8 802BEC08 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459DC 802BEC0C 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459E0 802BEC10 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459E4 802BEC14 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459E8 802BEC18 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459EC 802BEC1C 802BE3B0 */ .word .LPAL_802BE3B0
/* 3459F0 802BEC20 802BD73C */ .word .LPAL_802BD73C
/* 3459F4 802BEC24 802BD7F0 */ .word .LPAL_802BD7F0

glabel D_PAL_802BEC28
/* 3459F8 802BEC28 3F847AE147AE147B */ .double 0.0100000000000000002

glabel D_PAL_802BEC30
/* 345A00 802BEC30 3F847AE147AE147B */ .double 0.0100000000000000002

glabel D_PAL_802BEC38
/* 345A08 802BEC38 3F847AE147AE147B */ .double 0.0100000000000000002

glabel D_PAL_802BEC40
/* 345A10 802BEC40 3FF5555555555555 */ .double 1.33333333333333326


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel func_802BD638_31B658
/* 344408 802BD638 3C02800B */  lui        $v0, %hi(D_800AF5E8)
/* 34440C 802BD63C 8042F5E8 */  lb         $v0, %lo(D_800AF5E8)($v0)
/* 344410 802BD640 27BDFFA8 */  addiu      $sp, $sp, -0x58
/* 344414 802BD644 AFB50044 */  sw         $s5, 0x44($sp)
/* 344418 802BD648 0080A82D */  daddu      $s5, $a0, $zero
/* 34441C 802BD64C AFB40040 */  sw         $s4, 0x40($sp)
/* 344420 802BD650 3C148011 */  lui        $s4, %hi(D_8010DAC8)
/* 344424 802BD654 2694DAC8 */  addiu      $s4, $s4, %lo(D_8010DAC8)
/* 344428 802BD658 AFB60048 */  sw         $s6, 0x48($sp)
/* 34442C 802BD65C 3C168011 */  lui        $s6, %hi(D_8010D6B0)
/* 344430 802BD660 26D6D6B0 */  addiu      $s6, $s6, %lo(D_8010D6B0)
/* 344434 802BD664 AFBF004C */  sw         $ra, 0x4C($sp)
/* 344438 802BD668 AFB3003C */  sw         $s3, 0x3C($sp)
/* 34443C 802BD66C AFB20038 */  sw         $s2, 0x38($sp)
/* 344440 802BD670 AFB10034 */  sw         $s1, 0x34($sp)
/* 344444 802BD674 AFB00030 */  sw         $s0, 0x30($sp)
/* 344448 802BD678 F7B40050 */  sdc1       $f20, 0x50($sp)
/* 34444C 802BD67C 8EB0014C */  lw         $s0, 0x14C($s5)
/* 344450 802BD680 14400450 */  bnez       $v0, .LPAL_802BE7C4
/* 344454 802BD684 0000102D */   daddu     $v0, $zero, $zero
/* 344458 802BD688 10A00022 */  beqz       $a1, .LPAL_802BD714
/* 34445C 802BD68C 00000000 */   nop
/* 344460 802BD690 0C0AF57D */  jal        func_PAL_802BD5F4
/* 344464 802BD694 0200202D */   daddu     $a0, $s0, $zero
/* 344468 802BD698 8E820004 */  lw         $v0, 0x4($s4)
/* 34446C 802BD69C 3C030010 */  lui        $v1, (0x100000 >> 16)
/* 344470 802BD6A0 00431024 */  and        $v0, $v0, $v1
/* 344474 802BD6A4 10400003 */  beqz       $v0, .LPAL_802BD6B4
/* 344478 802BD6A8 00000000 */   nop
.LPAL_802BD6AC:
/* 34447C 802BD6AC 080AF9F1 */  j          .LPAL_802BE7C4
/* 344480 802BD6B0 24020002 */   addiu     $v0, $zero, 0x2
.LPAL_802BD6B4:
/* 344484 802BD6B4 3C02802C */  lui        $v0, %hi(D_802BEC64)
/* 344488 802BD6B8 8C42EC64 */  lw         $v0, %lo(D_802BEC64)($v0)
/* 34448C 802BD6BC 14400007 */  bnez       $v0, .LPAL_802BD6DC
/* 344490 802BD6C0 00000000 */   nop
/* 344494 802BD6C4 828200B4 */  lb         $v0, 0xB4($s4)
/* 344498 802BD6C8 2C420003 */  sltiu      $v0, $v0, 0x3
/* 34449C 802BD6CC 1040FFF7 */  beqz       $v0, .LPAL_802BD6AC
/* 3444A0 802BD6D0 24020014 */   addiu     $v0, $zero, 0x14
/* 3444A4 802BD6D4 080AF5C5 */  j          .LPAL_802BD714
/* 3444A8 802BD6D8 AEA20070 */   sw        $v0, 0x70($s5)
.LPAL_802BD6DC:
/* 3444AC 802BD6DC 82C20000 */  lb         $v0, 0x0($s6)
/* 3444B0 802BD6E0 1440000C */  bnez       $v0, .LPAL_802BD714
/* 3444B4 802BD6E4 3C030002 */   lui       $v1, (0x20009 >> 16)
/* 3444B8 802BD6E8 34630009 */  ori        $v1, $v1, (0x20009 & 0xFFFF)
/* 3444BC 802BD6EC 24020001 */  addiu      $v0, $zero, 0x1
/* 3444C0 802BD6F0 A2C20000 */  sb         $v0, 0x0($s6)
/* 3444C4 802BD6F4 24020002 */  addiu      $v0, $zero, 0x2
/* 3444C8 802BD6F8 A2C20003 */  sb         $v0, 0x3($s6)
/* 3444CC 802BD6FC 24020005 */  addiu      $v0, $zero, 0x5
/* 3444D0 802BD700 AEA20070 */  sw         $v0, 0x70($s5)
/* 3444D4 802BD704 2402001E */  addiu      $v0, $zero, 0x1E
/* 3444D8 802BD708 AE030028 */  sw         $v1, 0x28($s0)
/* 3444DC 802BD70C 3C01802C */  lui        $at, %hi(D_802BEC60)
/* 3444E0 802BD710 AC22EC60 */  sw         $v0, %lo(D_802BEC60)($at)
.LPAL_802BD714:
/* 3444E4 802BD714 8EA20070 */  lw         $v0, 0x70($s5)
/* 3444E8 802BD718 2443FFFE */  addiu      $v1, $v0, -0x2
/* 3444EC 802BD71C 2C620014 */  sltiu      $v0, $v1, 0x14
/* 3444F0 802BD720 10400323 */  beqz       $v0, .LPAL_802BE3B0
/* 3444F4 802BD724 00031080 */   sll       $v0, $v1, 2
/* 3444F8 802BD728 3C01802C */  lui        $at, %hi(jtbl_PAL_802BEBD8)
/* 3444FC 802BD72C 00220821 */  addu       $at, $at, $v0
/* 344500 802BD730 8C22EBD8 */  lw         $v0, %lo(jtbl_PAL_802BEBD8)($at)
/* 344504 802BD734 00400008 */  jr         $v0
/* 344508 802BD738 00000000 */   nop
.LPAL_802BD73C:
/* 34450C 802BD73C 82820015 */  lb         $v0, 0x15($s4)
/* 344510 802BD740 14400420 */  bnez       $v0, .LPAL_802BE7C4
/* 344514 802BD744 24020002 */   addiu     $v0, $zero, 0x2
/* 344518 802BD748 868200C0 */  lh         $v0, 0xC0($s4)
/* 34451C 802BD74C 1440041D */  bnez       $v0, .LPAL_802BE7C4
/* 344520 802BD750 24020002 */   addiu     $v0, $zero, 0x2
/* 344524 802BD754 8E020000 */  lw         $v0, 0x0($s0)
/* 344528 802BD758 30421000 */  andi       $v0, $v0, 0x1000
/* 34452C 802BD75C 50400419 */  beql       $v0, $zero, .LPAL_802BE7C4
/* 344530 802BD760 24020002 */   addiu     $v0, $zero, 0x2
/* 344534 802BD764 0C03723A */  jal        func_PAL_800DC8E8
/* 344538 802BD768 00000000 */   nop
/* 34453C 802BD76C 82820015 */  lb         $v0, 0x15($s4)
/* 344540 802BD770 24040001 */  addiu      $a0, $zero, 0x1
/* 344544 802BD774 AEA20078 */  sw         $v0, 0x78($s5)
/* 344548 802BD778 8E020000 */  lw         $v0, 0x0($s0)
/* 34454C 802BD77C 2403F5F7 */  addiu      $v1, $zero, -0xA09
/* 344550 802BD780 3C01802C */  lui        $at, %hi(D_802BEC74)
/* 344554 802BD784 AC24EC74 */  sw         $a0, %lo(D_802BEC74)($at)
/* 344558 802BD788 3C01802C */  lui        $at, %hi(D_PAL_802BEB50)
/* 34455C 802BD78C AC20EB50 */  sw         $zero, %lo(D_PAL_802BEB50)($at)
/* 344560 802BD790 3C01802C */  lui        $at, %hi(D_802BEC7C)
/* 344564 802BD794 AC20EC7C */  sw         $zero, %lo(D_802BEC7C)($at)
/* 344568 802BD798 00431024 */  and        $v0, $v0, $v1
/* 34456C 802BD79C 34420140 */  ori        $v0, $v0, 0x140
/* 344570 802BD7A0 AE020000 */  sw         $v0, 0x0($s0)
/* 344574 802BD7A4 24020002 */  addiu      $v0, $zero, 0x2
/* 344578 802BD7A8 A2C20003 */  sb         $v0, 0x3($s6)
/* 34457C 802BD7AC 0C03AF4C */  jal        func_PAL_800EBD30
/* 344580 802BD7B0 A2C40000 */   sb        $a0, 0x0($s6)
/* 344584 802BD7B4 3C01802C */  lui        $at, %hi(D_802BEC68)
/* 344588 802BD7B8 AC22EC68 */  sw         $v0, %lo(D_802BEC68)($at)
/* 34458C 802BD7BC 0C00EC85 */  jal        func_PAL_8003B214
/* 344590 802BD7C0 0200202D */   daddu     $a0, $s0, $zero
/* 344594 802BD7C4 C60C0038 */  lwc1       $f12, 0x38($s0)
/* 344598 802BD7C8 C60E0040 */  lwc1       $f14, 0x40($s0)
/* 34459C 802BD7CC 24020004 */  addiu      $v0, $zero, 0x4
/* 3445A0 802BD7D0 A602008E */  sh         $v0, 0x8E($s0)
/* 3445A4 802BD7D4 8E860028 */  lw         $a2, 0x28($s4)
/* 3445A8 802BD7D8 0C00A700 */  jal        func_PAL_80029C00
/* 3445AC 802BD7DC 8E870030 */   lw        $a3, 0x30($s4)
/* 3445B0 802BD7E0 E600000C */  swc1       $f0, 0xC($s0)
/* 3445B4 802BD7E4 8EA20070 */  lw         $v0, 0x70($s5)
/* 3445B8 802BD7E8 080AF8EB */  j          .LPAL_802BE3AC
/* 3445BC 802BD7EC 24420001 */   addiu     $v0, $v0, 0x1
.LPAL_802BD7F0:
/* 3445C0 802BD7F0 928200B4 */  lbu        $v0, 0xB4($s4)
/* 3445C4 802BD7F4 2442FFEB */  addiu      $v0, $v0, -0x15
/* 3445C8 802BD7F8 2C420003 */  sltiu      $v0, $v0, 0x3
/* 3445CC 802BD7FC 14400004 */  bnez       $v0, .LPAL_802BD810
/* 3445D0 802BD800 3C040001 */   lui       $a0, (0x10006 >> 16)
/* 3445D4 802BD804 868200C0 */  lh         $v0, 0xC0($s4)
/* 3445D8 802BD808 10400003 */  beqz       $v0, .LPAL_802BD818
/* 3445DC 802BD80C 00000000 */   nop
.LPAL_802BD810:
/* 3445E0 802BD810 080AF673 */  j          .LPAL_802BD9CC
/* 3445E4 802BD814 34840002 */   ori       $a0, $a0, (0x10002 & 0xFFFF)
.LPAL_802BD818:
/* 3445E8 802BD818 0C03719B */  jal        func_PAL_800DC66C
/* 3445EC 802BD81C 34840006 */   ori       $a0, $a0, (0x10006 & 0xFFFF)
/* 3445F0 802BD820 C6840028 */  lwc1       $f4, 0x28($s4)
/* 3445F4 802BD824 3C020002 */  lui        $v0, (0x20005 >> 16)
/* 3445F8 802BD828 E6040060 */  swc1       $f4, 0x60($s0)
/* 3445FC 802BD82C C682002C */  lwc1       $f2, 0x2C($s4)
/* 344600 802BD830 34420005 */  ori        $v0, $v0, (0x20005 & 0xFFFF)
/* 344604 802BD834 E6020064 */  swc1       $f2, 0x64($s0)
/* 344608 802BD838 C6800030 */  lwc1       $f0, 0x30($s4)
/* 34460C 802BD83C 3C065555 */  lui        $a2, (0x55555556 >> 16)
/* 344610 802BD840 AE020028 */  sw         $v0, 0x28($s0)
/* 344614 802BD844 E6000068 */  swc1       $f0, 0x68($s0)
/* 344618 802BD848 968200B2 */  lhu        $v0, 0xB2($s4)
/* 34461C 802BD84C 34C65556 */  ori        $a2, $a2, (0x55555556 & 0xFFFF)
/* 344620 802BD850 00021400 */  sll        $v0, $v0, 16
/* 344624 802BD854 00021C03 */  sra        $v1, $v0, 16
/* 344628 802BD858 00660018 */  mult       $v1, $a2
/* 34462C 802BD85C 26040060 */  addiu      $a0, $s0, 0x60
/* 344630 802BD860 8E870080 */  lw         $a3, 0x80($s4)
/* 344634 802BD864 000217C3 */  sra        $v0, $v0, 31
/* 344638 802BD868 00004010 */  mfhi       $t0
/* 34463C 802BD86C 01021023 */  subu       $v0, $t0, $v0
/* 344640 802BD870 00021400 */  sll        $v0, $v0, 16
/* 344644 802BD874 00021403 */  sra        $v0, $v0, 16
/* 344648 802BD878 44828000 */  mtc1       $v0, $f16
/* 34464C 802BD87C 00000000 */  nop
/* 344650 802BD880 46808420 */  cvt.s.w    $f16, $f16
/* 344654 802BD884 44068000 */  mfc1       $a2, $f16
/* 344658 802BD888 3C01802C */  lui        $at, %hi(D_802BEC80)
/* 34465C 802BD88C E424EC80 */  swc1       $f4, %lo(D_802BEC80)($at)
/* 344660 802BD890 3C01802C */  lui        $at, %hi(D_802BEC84)
/* 344664 802BD894 E422EC84 */  swc1       $f2, %lo(D_802BEC84)($at)
/* 344668 802BD898 3C01802C */  lui        $at, %hi(D_802BEC88)
/* 34466C 802BD89C E420EC88 */  swc1       $f0, %lo(D_802BEC88)($at)
/* 344670 802BD8A0 0C00A7C7 */  jal        func_PAL_80029F1C
/* 344674 802BD8A4 26050068 */   addiu     $a1, $s0, 0x68
/* 344678 802BD8A8 3C02802C */  lui        $v0, %hi(D_802BEC68)
/* 34467C 802BD8AC 8C42EC68 */  lw         $v0, %lo(D_802BEC68)($v0)
/* 344680 802BD8B0 C68C0080 */  lwc1       $f12, 0x80($s4)
/* 344684 802BD8B4 3C01C2B4 */  lui        $at, (0xC2B40000 >> 16)
/* 344688 802BD8B8 44810000 */  mtc1       $at, $f0
/* 34468C 802BD8BC 10400003 */  beqz       $v0, .LPAL_802BD8CC
/* 344690 802BD8C0 00000000 */   nop
/* 344694 802BD8C4 3C0142B4 */  lui        $at, (0x42B40000 >> 16)
/* 344698 802BD8C8 44810000 */  mtc1       $at, $f0
.LPAL_802BD8CC:
/* 34469C 802BD8CC 0C00A6A9 */  jal        func_PAL_80029AA4
/* 3446A0 802BD8D0 46006300 */   add.s     $f12, $f12, $f0
/* 3446A4 802BD8D4 868200B2 */  lh         $v0, 0xB2($s4)
/* 3446A8 802BD8D8 26040060 */  addiu      $a0, $s0, 0x60
/* 3446AC 802BD8DC 04410002 */  bgez       $v0, .LPAL_802BD8E8
/* 3446B0 802BD8E0 26050068 */   addiu     $a1, $s0, 0x68
/* 3446B4 802BD8E4 24420003 */  addiu      $v0, $v0, 0x3
.LPAL_802BD8E8:
/* 3446B8 802BD8E8 00021083 */  sra        $v0, $v0, 2
/* 3446BC 802BD8EC 44828000 */  mtc1       $v0, $f16
/* 3446C0 802BD8F0 00000000 */  nop
/* 3446C4 802BD8F4 46808420 */  cvt.s.w    $f16, $f16
/* 3446C8 802BD8F8 44070000 */  mfc1       $a3, $f0
/* 3446CC 802BD8FC 44068000 */  mfc1       $a2, $f16
/* 3446D0 802BD900 0C00A7C7 */  jal        func_PAL_80029F1C
/* 3446D4 802BD904 00000000 */   nop
/* 3446D8 802BD908 C6000060 */  lwc1       $f0, 0x60($s0)
/* 3446DC 802BD90C C60A0038 */  lwc1       $f10, 0x38($s0)
/* 3446E0 802BD910 8602008E */  lh         $v0, 0x8E($s0)
/* 3446E4 802BD914 C6040064 */  lwc1       $f4, 0x64($s0)
/* 3446E8 802BD918 C608003C */  lwc1       $f8, 0x3C($s0)
/* 3446EC 802BD91C C6060040 */  lwc1       $f6, 0x40($s0)
/* 3446F0 802BD920 44821000 */  mtc1       $v0, $f2
/* 3446F4 802BD924 00000000 */  nop
/* 3446F8 802BD928 468010A0 */  cvt.s.w    $f2, $f2
/* 3446FC 802BD92C 0040202D */  daddu      $a0, $v0, $zero
/* 344700 802BD930 460A0001 */  sub.s      $f0, $f0, $f10
/* 344704 802BD934 0080182D */  daddu      $v1, $a0, $zero
/* 344708 802BD938 9602008E */  lhu        $v0, 0x8E($s0)
/* 34470C 802BD93C 46082101 */  sub.s      $f4, $f4, $f8
/* 344710 802BD940 2442FFFF */  addiu      $v0, $v0, -0x1
/* 344714 802BD944 A602008E */  sh         $v0, 0x8E($s0)
/* 344718 802BD948 46020003 */  div.s      $f0, $f0, $f2
/* 34471C 802BD94C 46005280 */  add.s      $f10, $f10, $f0
/* 344720 802BD950 C6020068 */  lwc1       $f2, 0x68($s0)
/* 344724 802BD954 00021400 */  sll        $v0, $v0, 16
/* 344728 802BD958 46061081 */  sub.s      $f2, $f2, $f6
/* 34472C 802BD95C 44840000 */  mtc1       $a0, $f0
/* 344730 802BD960 00000000 */  nop
/* 344734 802BD964 46800020 */  cvt.s.w    $f0, $f0
/* 344738 802BD968 46002103 */  div.s      $f4, $f4, $f0
/* 34473C 802BD96C 46044200 */  add.s      $f8, $f8, $f4
/* 344740 802BD970 44830000 */  mtc1       $v1, $f0
/* 344744 802BD974 00000000 */  nop
/* 344748 802BD978 46800020 */  cvt.s.w    $f0, $f0
/* 34474C 802BD97C 46001083 */  div.s      $f2, $f2, $f0
/* 344750 802BD980 46023180 */  add.s      $f6, $f6, $f2
/* 344754 802BD984 E60A0038 */  swc1       $f10, 0x38($s0)
/* 344758 802BD988 E608003C */  swc1       $f8, 0x3C($s0)
/* 34475C 802BD98C 14400288 */  bnez       $v0, .LPAL_802BE3B0
/* 344760 802BD990 E6060040 */   swc1      $f6, 0x40($s0)
/* 344764 802BD994 0C00ECA7 */  jal        func_PAL_8003B29C
/* 344768 802BD998 0200202D */   daddu     $a0, $s0, $zero
/* 34476C 802BD99C 82830015 */  lb         $v1, 0x15($s4)
/* 344770 802BD9A0 8EA20078 */  lw         $v0, 0x78($s5)
/* 344774 802BD9A4 0043102A */  slt        $v0, $v0, $v1
/* 344778 802BD9A8 1040000C */  beqz       $v0, .LPAL_802BD9DC
/* 34477C 802BD9AC 3C030010 */   lui       $v1, (0x100000 >> 16)
/* 344780 802BD9B0 8E820004 */  lw         $v0, 0x4($s4)
/* 344784 802BD9B4 00431024 */  and        $v0, $v0, $v1
/* 344788 802BD9B8 14400003 */  bnez       $v0, .LPAL_802BD9C8
/* 34478C 802BD9BC 3C040001 */   lui       $a0, (0x10005 >> 16)
/* 344790 802BD9C0 080AF673 */  j          .LPAL_802BD9CC
/* 344794 802BD9C4 34840002 */   ori       $a0, $a0, (0x10002 & 0xFFFF)
.LPAL_802BD9C8:
/* 344798 802BD9C8 34840005 */  ori        $a0, $a0, (0x10005 & 0xFFFF)
.LPAL_802BD9CC:
/* 34479C 802BD9CC 0C03719B */  jal        func_PAL_800DC66C
/* 3447A0 802BD9D0 00000000 */   nop
/* 3447A4 802BD9D4 080AF8EC */  j          .LPAL_802BE3B0
/* 3447A8 802BD9D8 AEA00070 */   sw        $zero, 0x70($s5)
.LPAL_802BD9DC:
/* 3447AC 802BD9DC 3C020002 */  lui        $v0, (0x2000A >> 16)
/* 3447B0 802BD9E0 C6840080 */  lwc1       $f4, 0x80($s4)
/* 3447B4 802BD9E4 3C014190 */  lui        $at, (0x41900000 >> 16)
/* 3447B8 802BD9E8 44810000 */  mtc1       $at, $f0
/* 3447BC 802BD9EC 3C014040 */  lui        $at, (0x40400000 >> 16)
/* 3447C0 802BD9F0 44811000 */  mtc1       $at, $f2
/* 3447C4 802BD9F4 3442000A */  ori        $v0, $v0, (0x2000A & 0xFFFF)
/* 3447C8 802BD9F8 AE020028 */  sw         $v0, 0x28($s0)
/* 3447CC 802BD9FC 2402000C */  addiu      $v0, $zero, 0xC
/* 3447D0 802BDA00 A60200A8 */  sh         $v0, 0xA8($s0)
/* 3447D4 802BDA04 E604000C */  swc1       $f4, 0xC($s0)
/* 3447D8 802BDA08 E600001C */  swc1       $f0, 0x1C($s0)
/* 3447DC 802BDA0C E6020014 */  swc1       $f2, 0x14($s0)
/* 3447E0 802BDA10 C680002C */  lwc1       $f0, 0x2C($s4)
/* 3447E4 802BDA14 3C045555 */  lui        $a0, (0x55555556 >> 16)
/* 3447E8 802BDA18 E6000064 */  swc1       $f0, 0x64($s0)
/* 3447EC 802BDA1C 968200B0 */  lhu        $v0, 0xB0($s4)
/* 3447F0 802BDA20 34845556 */  ori        $a0, $a0, (0x55555556 & 0xFFFF)
/* 3447F4 802BDA24 00021400 */  sll        $v0, $v0, 16
/* 3447F8 802BDA28 00021C03 */  sra        $v1, $v0, 16
/* 3447FC 802BDA2C 00640018 */  mult       $v1, $a0
/* 344800 802BDA30 C682002C */  lwc1       $f2, 0x2C($s4)
/* 344804 802BDA34 000217C3 */  sra        $v0, $v0, 31
/* 344808 802BDA38 00004010 */  mfhi       $t0
/* 34480C 802BDA3C 01021023 */  subu       $v0, $t0, $v0
/* 344810 802BDA40 00021400 */  sll        $v0, $v0, 16
/* 344814 802BDA44 00021403 */  sra        $v0, $v0, 16
/* 344818 802BDA48 44820000 */  mtc1       $v0, $f0
/* 34481C 802BDA4C 00000000 */  nop
/* 344820 802BDA50 46800020 */  cvt.s.w    $f0, $f0
/* 344824 802BDA54 46001080 */  add.s      $f2, $f2, $f0
/* 344828 802BDA58 3C05800B */  lui        $a1, %hi(D_800B0460)
/* 34482C 802BDA5C 24A50460 */  addiu      $a1, $a1, %lo(D_800B0460)
/* 344830 802BDA60 3C040001 */  lui        $a0, (0x10007 >> 16)
/* 344834 802BDA64 E6020068 */  swc1       $f2, 0x68($s0)
/* 344838 802BDA68 8E820000 */  lw         $v0, 0x0($s4)
/* 34483C 802BDA6C 34840007 */  ori        $a0, $a0, (0x10007 & 0xFFFF)
/* 344840 802BDA70 AE800070 */  sw         $zero, 0x70($s4)
/* 344844 802BDA74 AE800074 */  sw         $zero, 0x74($s4)
/* 344848 802BDA78 AE800078 */  sw         $zero, 0x78($s4)
/* 34484C 802BDA7C AE80007C */  sw         $zero, 0x7C($s4)
/* 344850 802BDA80 94A30002 */  lhu        $v1, 0x2($a1)
/* 344854 802BDA84 34420002 */  ori        $v0, $v0, 0x2
/* 344858 802BDA88 34630001 */  ori        $v1, $v1, 0x1
/* 34485C 802BDA8C AE820000 */  sw         $v0, 0x0($s4)
/* 344860 802BDA90 0C03719B */  jal        func_PAL_800DC66C
/* 344864 802BDA94 A4A30002 */   sh        $v1, 0x2($a1)
/* 344868 802BDA98 24042081 */  addiu      $a0, $zero, 0x2081
/* 34486C 802BDA9C 0000282D */  daddu      $a1, $zero, $zero
/* 344870 802BDAA0 3C01802C */  lui        $at, %hi(D_802BEC70)
/* 344874 802BDAA4 AC20EC70 */  sw         $zero, %lo(D_802BEC70)($at)
/* 344878 802BDAA8 0C05222E */  jal        func_PAL_801488B8
/* 34487C 802BDAAC 2406FFFC */   addiu     $a2, $zero, -0x4
/* 344880 802BDAB0 24020002 */  addiu      $v0, $zero, 0x2
/* 344884 802BDAB4 AEA20070 */  sw         $v0, 0x70($s5)
.LPAL_802BDAB8:
/* 344888 802BDAB8 928200B4 */  lbu        $v0, 0xB4($s4)
/* 34488C 802BDABC 2442FFEB */  addiu      $v0, $v0, -0x15
/* 344890 802BDAC0 2C420003 */  sltiu      $v0, $v0, 0x3
/* 344894 802BDAC4 5440023A */  bnel       $v0, $zero, .LPAL_802BE3B0
/* 344898 802BDAC8 AEA00070 */   sw        $zero, 0x70($s5)
/* 34489C 802BDACC C602001C */  lwc1       $f2, 0x1C($s0)
/* 3448A0 802BDAD0 C6000014 */  lwc1       $f0, 0x14($s0)
/* 3448A4 802BDAD4 46001081 */  sub.s      $f2, $f2, $f0
/* 3448A8 802BDAD8 E602001C */  swc1       $f2, 0x1C($s0)
/* 3448AC 802BDADC C680002C */  lwc1       $f0, 0x2C($s4)
/* 3448B0 802BDAE0 46020000 */  add.s      $f0, $f0, $f2
/* 3448B4 802BDAE4 E680002C */  swc1       $f0, 0x2C($s4)
/* 3448B8 802BDAE8 C602001C */  lwc1       $f2, 0x1C($s0)
/* 3448BC 802BDAEC 44800000 */  mtc1       $zero, $f0
/* 3448C0 802BDAF0 00000000 */  nop
/* 3448C4 802BDAF4 4600103C */  c.lt.s     $f2, $f0
/* 3448C8 802BDAF8 00000000 */  nop
/* 3448CC 802BDAFC 4500000C */  bc1f       .LPAL_802BDB30
/* 3448D0 802BDB00 3C040001 */   lui       $a0, (0x10000 >> 16)
/* 3448D4 802BDB04 3C03802C */  lui        $v1, %hi(D_802BEC70)
/* 3448D8 802BDB08 2463EC70 */  addiu      $v1, $v1, %lo(D_802BEC70)
/* 3448DC 802BDB0C 8C620000 */  lw         $v0, 0x0($v1)
/* 3448E0 802BDB10 14400008 */  bnez       $v0, .LPAL_802BDB34
/* 3448E4 802BDB14 27A50020 */   addiu     $a1, $sp, 0x20
/* 3448E8 802BDB18 24020001 */  addiu      $v0, $zero, 0x1
/* 3448EC 802BDB1C AC620000 */  sw         $v0, 0x0($v1)
/* 3448F0 802BDB20 3C040001 */  lui        $a0, (0x10008 >> 16)
/* 3448F4 802BDB24 0C03719B */  jal        func_PAL_800DC66C
/* 3448F8 802BDB28 34840008 */   ori       $a0, $a0, (0x10008 & 0xFFFF)
/* 3448FC 802BDB2C 3C040001 */  lui        $a0, (0x10000 >> 16)
.LPAL_802BDB30:
/* 344900 802BDB30 27A50020 */  addiu      $a1, $sp, 0x20
.LPAL_802BDB34:
/* 344904 802BDB34 27A60024 */  addiu      $a2, $sp, 0x24
/* 344908 802BDB38 27A70028 */  addiu      $a3, $sp, 0x28
/* 34490C 802BDB3C 968300B0 */  lhu        $v1, 0xB0($s4)
/* 344910 802BDB40 C6820028 */  lwc1       $f2, 0x28($s4)
/* 344914 802BDB44 00031C00 */  sll        $v1, $v1, 16
/* 344918 802BDB48 00031403 */  sra        $v0, $v1, 16
/* 34491C 802BDB4C 00031FC2 */  srl        $v1, $v1, 31
/* 344920 802BDB50 00431021 */  addu       $v0, $v0, $v1
/* 344924 802BDB54 00021043 */  sra        $v0, $v0, 1
/* 344928 802BDB58 44820000 */  mtc1       $v0, $f0
/* 34492C 802BDB5C 00000000 */  nop
/* 344930 802BDB60 46800020 */  cvt.s.w    $f0, $f0
/* 344934 802BDB64 968300B0 */  lhu        $v1, 0xB0($s4)
/* 344938 802BDB68 46000506 */  mov.s      $f20, $f0
/* 34493C 802BDB6C E7A20020 */  swc1       $f2, 0x20($sp)
/* 344940 802BDB70 C682002C */  lwc1       $f2, 0x2C($s4)
/* 344944 802BDB74 C6840030 */  lwc1       $f4, 0x30($s4)
/* 344948 802BDB78 00031C00 */  sll        $v1, $v1, 16
/* 34494C 802BDB7C 00031403 */  sra        $v0, $v1, 16
/* 344950 802BDB80 00031FC2 */  srl        $v1, $v1, 31
/* 344954 802BDB84 00431021 */  addu       $v0, $v0, $v1
/* 344958 802BDB88 00021043 */  sra        $v0, $v0, 1
/* 34495C 802BDB8C 44820000 */  mtc1       $v0, $f0
/* 344960 802BDB90 00000000 */  nop
/* 344964 802BDB94 46800020 */  cvt.s.w    $f0, $f0
/* 344968 802BDB98 46001080 */  add.s      $f2, $f2, $f0
/* 34496C 802BDB9C C600001C */  lwc1       $f0, 0x1C($s0)
/* 344970 802BDBA0 27A2002C */  addiu      $v0, $sp, 0x2C
/* 344974 802BDBA4 46001081 */  sub.s      $f2, $f2, $f0
/* 344978 802BDBA8 E7A40028 */  swc1       $f4, 0x28($sp)
/* 34497C 802BDBAC E7B4002C */  swc1       $f20, 0x2C($sp)
/* 344980 802BDBB0 E7A20024 */  swc1       $f2, 0x24($sp)
/* 344984 802BDBB4 0C036578 */  jal        func_PAL_800D95E0
/* 344988 802BDBB8 AFA20010 */   sw        $v0, 0x10($sp)
/* 34498C 802BDBBC 10400013 */  beqz       $v0, .LPAL_802BDC0C
/* 344990 802BDBC0 00000000 */   nop
/* 344994 802BDBC4 C7A0002C */  lwc1       $f0, 0x2C($sp)
/* 344998 802BDBC8 4614003C */  c.lt.s     $f0, $f20
/* 34499C 802BDBCC 00000000 */  nop
/* 3449A0 802BDBD0 4500000E */  bc1f       .LPAL_802BDC0C
/* 3449A4 802BDBD4 0200202D */   daddu     $a0, $s0, $zero
/* 3449A8 802BDBD8 868200B0 */  lh         $v0, 0xB0($s4)
/* 3449AC 802BDBDC C7A20024 */  lwc1       $f2, 0x24($sp)
/* 3449B0 802BDBE0 3C038011 */  lui        $v1, %hi(D_8010B46A)
/* 3449B4 802BDBE4 9463B46A */  lhu        $v1, %lo(D_8010B46A)($v1)
/* 3449B8 802BDBE8 44820000 */  mtc1       $v0, $f0
/* 3449BC 802BDBEC 00000000 */  nop
/* 3449C0 802BDBF0 46800020 */  cvt.s.w    $f0, $f0
/* 3449C4 802BDBF4 46001081 */  sub.s      $f2, $f2, $f0
/* 3449C8 802BDBF8 3C028016 */  lui        $v0, %hi(D_80159110)
/* 3449CC 802BDBFC 24429110 */  addiu      $v0, $v0, %lo(D_80159110)
/* 3449D0 802BDC00 A4430008 */  sh         $v1, 0x8($v0)
/* 3449D4 802BDC04 0C0AF451 */  jal        func_PAL_802BD144
/* 3449D8 802BDC08 E682002C */   swc1      $f2, 0x2C($s4)
.LPAL_802BDC0C:
/* 3449DC 802BDC0C C600001C */  lwc1       $f0, 0x1C($s0)
/* 3449E0 802BDC10 44802000 */  mtc1       $zero, $f4
/* 3449E4 802BDC14 00000000 */  nop
/* 3449E8 802BDC18 4600203C */  c.lt.s     $f4, $f0
/* 3449EC 802BDC1C 00000000 */  nop
/* 3449F0 802BDC20 450101E3 */  bc1t       .LPAL_802BE3B0
/* 3449F4 802BDC24 00000000 */   nop
/* 3449F8 802BDC28 C682002C */  lwc1       $f2, 0x2C($s4)
/* 3449FC 802BDC2C C6000068 */  lwc1       $f0, 0x68($s0)
/* 344A00 802BDC30 4600103C */  c.lt.s     $f2, $f0
/* 344A04 802BDC34 00000000 */  nop
/* 344A08 802BDC38 450001DD */  bc1f       .LPAL_802BE3B0
/* 344A0C 802BDC3C 3C040002 */   lui       $a0, (0x20009 >> 16)
/* 344A10 802BDC40 34840009 */  ori        $a0, $a0, (0x20009 & 0xFFFF)
/* 344A14 802BDC44 8E020000 */  lw         $v0, 0x0($s0)
/* 344A18 802BDC48 3C014100 */  lui        $at, (0x41000000 >> 16)
/* 344A1C 802BDC4C 44810000 */  mtc1       $at, $f0
/* 344A20 802BDC50 2403FEFF */  addiu      $v1, $zero, -0x101
/* 344A24 802BDC54 3C01802C */  lui        $at, %hi(D_802BEC6C)
/* 344A28 802BDC58 AC20EC6C */  sw         $zero, %lo(D_802BEC6C)($at)
/* 344A2C 802BDC5C 00431024 */  and        $v0, $v0, $v1
/* 344A30 802BDC60 AE020000 */  sw         $v0, 0x0($s0)
/* 344A34 802BDC64 24020002 */  addiu      $v0, $zero, 0x2
/* 344A38 802BDC68 A2C20003 */  sb         $v0, 0x3($s6)
/* 344A3C 802BDC6C A2C20000 */  sb         $v0, 0x0($s6)
/* 344A40 802BDC70 E604004C */  swc1       $f4, 0x4C($s0)
/* 344A44 802BDC74 E6040010 */  swc1       $f4, 0x10($s0)
/* 344A48 802BDC78 E6000018 */  swc1       $f0, 0x18($s0)
/* 344A4C 802BDC7C AE040028 */  sw         $a0, 0x28($s0)
/* 344A50 802BDC80 C68C0080 */  lwc1       $f12, 0x80($s4)
/* 344A54 802BDC84 24020001 */  addiu      $v0, $zero, 0x1
/* 344A58 802BDC88 3C01802C */  lui        $at, %hi(D_PAL_802BEB50)
/* 344A5C 802BDC8C AC22EB50 */  sw         $v0, %lo(D_PAL_802BEB50)($at)
/* 344A60 802BDC90 0C00A89B */  jal        func_PAL_8002A26C
/* 344A64 802BDC94 24120003 */   addiu     $s2, $zero, 0x3
/* 344A68 802BDC98 C68C0080 */  lwc1       $f12, 0x80($s4)
/* 344A6C 802BDC9C 0C00A8B4 */  jal        func_PAL_8002A2D0
/* 344A70 802BDCA0 46000506 */   mov.s     $f20, $f0
/* 344A74 802BDCA4 860200A8 */  lh         $v0, 0xA8($s0)
/* 344A78 802BDCA8 C604003C */  lwc1       $f4, 0x3C($s0)
/* 344A7C 802BDCAC 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
/* 344A80 802BDCB0 44811000 */  mtc1       $at, $f2
/* 344A84 802BDCB4 46000007 */  neg.s      $f0, $f0
/* 344A88 802BDCB8 E7B40010 */  swc1       $f20, 0x10($sp)
/* 344A8C 802BDCBC E7A00018 */  swc1       $f0, 0x18($sp)
/* 344A90 802BDCC0 AFB2001C */  sw         $s2, 0x1C($sp)
/* 344A94 802BDCC4 44820000 */  mtc1       $v0, $f0
/* 344A98 802BDCC8 00000000 */  nop
/* 344A9C 802BDCCC 46800020 */  cvt.s.w    $f0, $f0
/* 344AA0 802BDCD0 46002100 */  add.s      $f4, $f4, $f0
/* 344AA4 802BDCD4 E7A20014 */  swc1       $f2, 0x14($sp)
/* 344AA8 802BDCD8 8E050038 */  lw         $a1, 0x38($s0)
/* 344AAC 802BDCDC 8E070040 */  lw         $a3, 0x40($s0)
/* 344AB0 802BDCE0 44062000 */  mfc1       $a2, $f4
/* 344AB4 802BDCE4 0C0B7570 */  jal        func_PAL_802DD5C0
/* 344AB8 802BDCE8 0240202D */   daddu     $a0, $s2, $zero
/* 344ABC 802BDCEC 0C0389FF */  jal        func_PAL_800E27FC
/* 344AC0 802BDCF0 00000000 */   nop
/* 344AC4 802BDCF4 3C11802C */  lui        $s1, %hi(D_802BEC74)
/* 344AC8 802BDCF8 2631EC74 */  addiu      $s1, $s1, %lo(D_802BEC74)
/* 344ACC 802BDCFC 8E220000 */  lw         $v0, 0x0($s1)
/* 344AD0 802BDD00 10400005 */  beqz       $v0, .LPAL_802BDD18
/* 344AD4 802BDD04 24040283 */   addiu     $a0, $zero, 0x283
/* 344AD8 802BDD08 0C037245 */  jal        func_PAL_800DC914
/* 344ADC 802BDD0C 00000000 */   nop
/* 344AE0 802BDD10 AE200000 */  sw         $zero, 0x0($s1)
/* 344AE4 802BDD14 24040283 */  addiu      $a0, $zero, 0x283
.LPAL_802BDD18:
/* 344AE8 802BDD18 0000282D */  daddu      $a1, $zero, $zero
/* 344AEC 802BDD1C 3C03800B */  lui        $v1, %hi(D_800B0460)
/* 344AF0 802BDD20 24630460 */  addiu      $v1, $v1, %lo(D_800B0460)
/* 344AF4 802BDD24 AEB20070 */  sw         $s2, 0x70($s5)
/* 344AF8 802BDD28 94620002 */  lhu        $v0, 0x2($v1)
/* 344AFC 802BDD2C 2406FFFC */  addiu      $a2, $zero, -0x4
/* 344B00 802BDD30 3C01802C */  lui        $at, %hi(D_802BEC70)
/* 344B04 802BDD34 AC20EC70 */  sw         $zero, %lo(D_802BEC70)($at)
/* 344B08 802BDD38 34420001 */  ori        $v0, $v0, 0x1
/* 344B0C 802BDD3C 0C05222E */  jal        func_PAL_801488B8
/* 344B10 802BDD40 A4620002 */   sh        $v0, 0x2($v1)
/* 344B14 802BDD44 24040284 */  addiu      $a0, $zero, 0x284
/* 344B18 802BDD48 0000282D */  daddu      $a1, $zero, $zero
/* 344B1C 802BDD4C 0C05222E */  jal        func_PAL_801488B8
/* 344B20 802BDD50 2406FFFC */   addiu     $a2, $zero, -0x4
/* 344B24 802BDD54 080AF8EC */  j          .LPAL_802BE3B0
/* 344B28 802BDD58 00000000 */   nop
.LPAL_802BDD5C:
/* 344B2C 802BDD5C 928200B4 */  lbu        $v0, 0xB4($s4)
/* 344B30 802BDD60 2442FFEB */  addiu      $v0, $v0, -0x15
/* 344B34 802BDD64 2C420002 */  sltiu      $v0, $v0, 0x2
/* 344B38 802BDD68 54400191 */  bnel       $v0, $zero, .LPAL_802BE3B0
/* 344B3C 802BDD6C AEA00070 */   sw        $zero, 0x70($s5)
/* 344B40 802BDD70 34048000 */  ori        $a0, $zero, 0x8000
/* 344B44 802BDD74 C6000038 */  lwc1       $f0, 0x38($s0)
/* 344B48 802BDD78 C602003C */  lwc1       $f2, 0x3C($s0)
/* 344B4C 802BDD7C C6040040 */  lwc1       $f4, 0x40($s0)
/* 344B50 802BDD80 C6060018 */  lwc1       $f6, 0x18($s0)
/* 344B54 802BDD84 3C0141A0 */  lui        $at, (0x41A00000 >> 16)
/* 344B58 802BDD88 4481A000 */  mtc1       $at, $f20
/* 344B5C 802BDD8C 27B20020 */  addiu      $s2, $sp, 0x20
/* 344B60 802BDD90 E7A00020 */  swc1       $f0, 0x20($sp)
/* 344B64 802BDD94 E7A20024 */  swc1       $f2, 0x24($sp)
/* 344B68 802BDD98 E7A40028 */  swc1       $f4, 0x28($sp)
/* 344B6C 802BDD9C E7A60010 */  swc1       $f6, 0x10($sp)
/* 344B70 802BDDA0 C600000C */  lwc1       $f0, 0xC($s0)
/* 344B74 802BDDA4 0240282D */  daddu      $a1, $s2, $zero
/* 344B78 802BDDA8 46140001 */  sub.s      $f0, $f0, $f20
/* 344B7C 802BDDAC 27B30024 */  addiu      $s3, $sp, 0x24
/* 344B80 802BDDB0 0260302D */  daddu      $a2, $s3, $zero
/* 344B84 802BDDB4 E7A00014 */  swc1       $f0, 0x14($sp)
/* 344B88 802BDDB8 860200A8 */  lh         $v0, 0xA8($s0)
/* 344B8C 802BDDBC 27B10028 */  addiu      $s1, $sp, 0x28
/* 344B90 802BDDC0 44820000 */  mtc1       $v0, $f0
/* 344B94 802BDDC4 00000000 */  nop
/* 344B98 802BDDC8 46800020 */  cvt.s.w    $f0, $f0
/* 344B9C 802BDDCC E7A00018 */  swc1       $f0, 0x18($sp)
/* 344BA0 802BDDD0 960300A6 */  lhu        $v1, 0xA6($s0)
/* 344BA4 802BDDD4 0220382D */  daddu      $a3, $s1, $zero
/* 344BA8 802BDDD8 00031C00 */  sll        $v1, $v1, 16
/* 344BAC 802BDDDC 00031403 */  sra        $v0, $v1, 16
/* 344BB0 802BDDE0 00031FC2 */  srl        $v1, $v1, 31
/* 344BB4 802BDDE4 00431021 */  addu       $v0, $v0, $v1
/* 344BB8 802BDDE8 00021043 */  sra        $v0, $v0, 1
/* 344BBC 802BDDEC 44820000 */  mtc1       $v0, $f0
/* 344BC0 802BDDF0 00000000 */  nop
/* 344BC4 802BDDF4 46800020 */  cvt.s.w    $f0, $f0
/* 344BC8 802BDDF8 0C036895 */  jal        func_PAL_800DA254
/* 344BCC 802BDDFC E7A0001C */   swc1      $f0, 0x1C($sp)
/* 344BD0 802BDE00 10400027 */  beqz       $v0, .LPAL_802BDEA0
/* 344BD4 802BDE04 34048000 */   ori       $a0, $zero, 0x8000
.LPAL_802BDE08:
/* 344BD8 802BDE08 0C0AF440 */  jal        func_PAL_802BD100
/* 344BDC 802BDE0C 0200202D */   daddu     $a0, $s0, $zero
/* 344BE0 802BDE10 14400004 */  bnez       $v0, .LPAL_802BDE24
/* 344BE4 802BDE14 2404010C */   addiu     $a0, $zero, 0x10C
/* 344BE8 802BDE18 0000282D */  daddu      $a1, $zero, $zero
/* 344BEC 802BDE1C 0C05222E */  jal        func_PAL_801488B8
/* 344BF0 802BDE20 2406FFFC */   addiu     $a2, $zero, -0x4
.LPAL_802BDE24:
/* 344BF4 802BDE24 C60C000C */  lwc1       $f12, 0xC($s0)
/* 344BF8 802BDE28 0C00A89B */  jal        func_PAL_8002A26C
/* 344BFC 802BDE2C 00000000 */   nop
/* 344C00 802BDE30 C60C000C */  lwc1       $f12, 0xC($s0)
/* 344C04 802BDE34 0C00A8B4 */  jal        func_PAL_8002A2D0
/* 344C08 802BDE38 46000506 */   mov.s     $f20, $f0
/* 344C0C 802BDE3C 24020001 */  addiu      $v0, $zero, 0x1
/* 344C10 802BDE40 860300A8 */  lh         $v1, 0xA8($s0)
/* 344C14 802BDE44 C604003C */  lwc1       $f4, 0x3C($s0)
/* 344C18 802BDE48 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
/* 344C1C 802BDE4C 44811000 */  mtc1       $at, $f2
/* 344C20 802BDE50 46000007 */  neg.s      $f0, $f0
/* 344C24 802BDE54 E7B40010 */  swc1       $f20, 0x10($sp)
/* 344C28 802BDE58 E7A00018 */  swc1       $f0, 0x18($sp)
/* 344C2C 802BDE5C AFA2001C */  sw         $v0, 0x1C($sp)
/* 344C30 802BDE60 44830000 */  mtc1       $v1, $f0
/* 344C34 802BDE64 00000000 */  nop
/* 344C38 802BDE68 46800020 */  cvt.s.w    $f0, $f0
/* 344C3C 802BDE6C 46002100 */  add.s      $f4, $f4, $f0
/* 344C40 802BDE70 E7A20014 */  swc1       $f2, 0x14($sp)
/* 344C44 802BDE74 8E050038 */  lw         $a1, 0x38($s0)
/* 344C48 802BDE78 8E070040 */  lw         $a3, 0x40($s0)
/* 344C4C 802BDE7C 44062000 */  mfc1       $a2, $f4
/* 344C50 802BDE80 0C0B7570 */  jal        func_PAL_802DD5C0
/* 344C54 802BDE84 24040003 */   addiu     $a0, $zero, 0x3
/* 344C58 802BDE88 0000202D */  daddu      $a0, $zero, $zero
/* 344C5C 802BDE8C 0080282D */  daddu      $a1, $a0, $zero
/* 344C60 802BDE90 0C05222E */  jal        func_PAL_801488B8
/* 344C64 802BDE94 2406FFFC */   addiu     $a2, $zero, -0x4
/* 344C68 802BDE98 080AF8EB */  j          .LPAL_802BE3AC
/* 344C6C 802BDE9C 24020007 */   addiu     $v0, $zero, 0x7
.LPAL_802BDEA0:
/* 344C70 802BDEA0 C6000038 */  lwc1       $f0, 0x38($s0)
/* 344C74 802BDEA4 C602003C */  lwc1       $f2, 0x3C($s0)
/* 344C78 802BDEA8 C6040040 */  lwc1       $f4, 0x40($s0)
/* 344C7C 802BDEAC C6060018 */  lwc1       $f6, 0x18($s0)
/* 344C80 802BDEB0 E7A00020 */  swc1       $f0, 0x20($sp)
/* 344C84 802BDEB4 E7A20024 */  swc1       $f2, 0x24($sp)
/* 344C88 802BDEB8 E7A40028 */  swc1       $f4, 0x28($sp)
/* 344C8C 802BDEBC E7A60010 */  swc1       $f6, 0x10($sp)
/* 344C90 802BDEC0 C600000C */  lwc1       $f0, 0xC($s0)
/* 344C94 802BDEC4 46140000 */  add.s      $f0, $f0, $f20
/* 344C98 802BDEC8 0240282D */  daddu      $a1, $s2, $zero
/* 344C9C 802BDECC E7A00014 */  swc1       $f0, 0x14($sp)
/* 344CA0 802BDED0 860200A8 */  lh         $v0, 0xA8($s0)
/* 344CA4 802BDED4 0260302D */  daddu      $a2, $s3, $zero
/* 344CA8 802BDED8 44820000 */  mtc1       $v0, $f0
/* 344CAC 802BDEDC 00000000 */  nop
/* 344CB0 802BDEE0 46800020 */  cvt.s.w    $f0, $f0
/* 344CB4 802BDEE4 E7A00018 */  swc1       $f0, 0x18($sp)
/* 344CB8 802BDEE8 960300A6 */  lhu        $v1, 0xA6($s0)
/* 344CBC 802BDEEC 0220382D */  daddu      $a3, $s1, $zero
/* 344CC0 802BDEF0 00031C00 */  sll        $v1, $v1, 16
/* 344CC4 802BDEF4 00031403 */  sra        $v0, $v1, 16
/* 344CC8 802BDEF8 00031FC2 */  srl        $v1, $v1, 31
/* 344CCC 802BDEFC 00431021 */  addu       $v0, $v0, $v1
/* 344CD0 802BDF00 00021043 */  sra        $v0, $v0, 1
/* 344CD4 802BDF04 44820000 */  mtc1       $v0, $f0
/* 344CD8 802BDF08 00000000 */  nop
/* 344CDC 802BDF0C 46800020 */  cvt.s.w    $f0, $f0
/* 344CE0 802BDF10 0C036895 */  jal        func_PAL_800DA254
/* 344CE4 802BDF14 E7A0001C */   swc1      $f0, 0x1C($sp)
/* 344CE8 802BDF18 1440FFBB */  bnez       $v0, .LPAL_802BDE08
/* 344CEC 802BDF1C 34048000 */   ori       $a0, $zero, 0x8000
/* 344CF0 802BDF20 C6000038 */  lwc1       $f0, 0x38($s0)
/* 344CF4 802BDF24 C602003C */  lwc1       $f2, 0x3C($s0)
/* 344CF8 802BDF28 C6040040 */  lwc1       $f4, 0x40($s0)
/* 344CFC 802BDF2C C6060018 */  lwc1       $f6, 0x18($s0)
/* 344D00 802BDF30 E7A00020 */  swc1       $f0, 0x20($sp)
/* 344D04 802BDF34 E7A20024 */  swc1       $f2, 0x24($sp)
/* 344D08 802BDF38 E7A40028 */  swc1       $f4, 0x28($sp)
/* 344D0C 802BDF3C E7A60010 */  swc1       $f6, 0x10($sp)
/* 344D10 802BDF40 C600000C */  lwc1       $f0, 0xC($s0)
/* 344D14 802BDF44 0240282D */  daddu      $a1, $s2, $zero
/* 344D18 802BDF48 E7A00014 */  swc1       $f0, 0x14($sp)
/* 344D1C 802BDF4C 860200A8 */  lh         $v0, 0xA8($s0)
/* 344D20 802BDF50 0260302D */  daddu      $a2, $s3, $zero
/* 344D24 802BDF54 44820000 */  mtc1       $v0, $f0
/* 344D28 802BDF58 00000000 */  nop
/* 344D2C 802BDF5C 46800020 */  cvt.s.w    $f0, $f0
/* 344D30 802BDF60 E7A00018 */  swc1       $f0, 0x18($sp)
/* 344D34 802BDF64 960300A6 */  lhu        $v1, 0xA6($s0)
/* 344D38 802BDF68 0220382D */  daddu      $a3, $s1, $zero
/* 344D3C 802BDF6C 00031C00 */  sll        $v1, $v1, 16
/* 344D40 802BDF70 00031403 */  sra        $v0, $v1, 16
/* 344D44 802BDF74 00031FC2 */  srl        $v1, $v1, 31
/* 344D48 802BDF78 00431021 */  addu       $v0, $v0, $v1
/* 344D4C 802BDF7C 00021043 */  sra        $v0, $v0, 1
/* 344D50 802BDF80 44820000 */  mtc1       $v0, $f0
/* 344D54 802BDF84 00000000 */  nop
/* 344D58 802BDF88 46800020 */  cvt.s.w    $f0, $f0
/* 344D5C 802BDF8C 0C036895 */  jal        func_PAL_800DA254
/* 344D60 802BDF90 E7A0001C */   swc1      $f0, 0x1C($sp)
/* 344D64 802BDF94 1440FF9C */  bnez       $v0, .LPAL_802BDE08
/* 344D68 802BDF98 0200202D */   daddu     $a0, $s0, $zero
/* 344D6C 802BDF9C C7A00020 */  lwc1       $f0, 0x20($sp)
/* 344D70 802BDFA0 C6020018 */  lwc1       $f2, 0x18($s0)
/* 344D74 802BDFA4 24050001 */  addiu      $a1, $zero, 0x1
/* 344D78 802BDFA8 E6000038 */  swc1       $f0, 0x38($s0)
/* 344D7C 802BDFAC C7A60024 */  lwc1       $f6, 0x24($sp)
/* 344D80 802BDFB0 C6000010 */  lwc1       $f0, 0x10($s0)
/* 344D84 802BDFB4 C7A40028 */  lwc1       $f4, 0x28($sp)
/* 344D88 802BDFB8 46020000 */  add.s      $f0, $f0, $f2
/* 344D8C 802BDFBC E606003C */  swc1       $f6, 0x3C($s0)
/* 344D90 802BDFC0 E6040040 */  swc1       $f4, 0x40($s0)
/* 344D94 802BDFC4 0C00F6D4 */  jal        func_PAL_8003DB50
/* 344D98 802BDFC8 E6000010 */   swc1      $f0, 0x10($s0)
/* 344D9C 802BDFCC C6000018 */  lwc1       $f0, 0x18($s0)
/* 344DA0 802BDFD0 3C014000 */  lui        $at, (0x40000000 >> 16)
/* 344DA4 802BDFD4 44811800 */  mtc1       $at, $f3
/* 344DA8 802BDFD8 44801000 */  mtc1       $zero, $f2
/* 344DAC 802BDFDC 46000021 */  cvt.d.s    $f0, $f0
/* 344DB0 802BDFE0 46220000 */  add.d      $f0, $f0, $f2
/* 344DB4 802BDFE4 3C01402C */  lui        $at, (0x402C0000 >> 16)
/* 344DB8 802BDFE8 44812800 */  mtc1       $at, $f5
/* 344DBC 802BDFEC 44802000 */  mtc1       $zero, $f4
/* 344DC0 802BDFF0 46200020 */  cvt.s.d    $f0, $f0
/* 344DC4 802BDFF4 460000A1 */  cvt.d.s    $f2, $f0
/* 344DC8 802BDFF8 4622203C */  c.lt.d     $f4, $f2
/* 344DCC 802BDFFC 00000000 */  nop
/* 344DD0 802BE000 45000005 */  bc1f       .LPAL_802BE018
/* 344DD4 802BE004 E6000018 */   swc1      $f0, 0x18($s0)
/* 344DD8 802BE008 3C014160 */  lui        $at, (0x41600000 >> 16)
/* 344DDC 802BE00C 44810000 */  mtc1       $at, $f0
/* 344DE0 802BE010 00000000 */  nop
/* 344DE4 802BE014 E6000018 */  swc1       $f0, 0x18($s0)
.LPAL_802BE018:
/* 344DE8 802BE018 3C0540C0 */  lui        $a1, (0x40C00000 >> 16)
/* 344DEC 802BE01C 0C00E736 */  jal        func_PAL_80039CD8
/* 344DF0 802BE020 0200202D */   daddu     $a0, $s0, $zero
/* 344DF4 802BE024 1440000E */  bnez       $v0, .LPAL_802BE060
/* 344DF8 802BE028 00000000 */   nop
/* 344DFC 802BE02C 8E820000 */  lw         $v0, 0x0($s4)
/* 344E00 802BE030 30420006 */  andi       $v0, $v0, 0x6
/* 344E04 802BE034 1440000A */  bnez       $v0, .LPAL_802BE060
/* 344E08 802BE038 00000000 */   nop
/* 344E0C 802BE03C C680002C */  lwc1       $f0, 0x2C($s4)
/* 344E10 802BE040 C602003C */  lwc1       $f2, 0x3C($s0)
/* 344E14 802BE044 46020001 */  sub.s      $f0, $f0, $f2
/* 344E18 802BE048 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 344E1C 802BE04C 44812000 */  mtc1       $at, $f4
/* 344E20 802BE050 00000000 */  nop
/* 344E24 802BE054 46040003 */  div.s      $f0, $f0, $f4
/* 344E28 802BE058 46001080 */  add.s      $f2, $f2, $f0
/* 344E2C 802BE05C E602003C */  swc1       $f2, 0x3C($s0)
.LPAL_802BE060:
/* 344E30 802BE060 0C00E53F */  jal        func_PAL_800394FC
/* 344E34 802BE064 0200202D */   daddu     $a0, $s0, $zero
/* 344E38 802BE068 8E020000 */  lw         $v0, 0x0($s0)
/* 344E3C 802BE06C 3C030200 */  lui        $v1, (0x2000000 >> 16)
/* 344E40 802BE070 00431024 */  and        $v0, $v0, $v1
/* 344E44 802BE074 1440004A */  bnez       $v0, .LPAL_802BE1A0
/* 344E48 802BE078 0000202D */   daddu     $a0, $zero, $zero
/* 344E4C 802BE07C 0C0AF45F */  jal        func_PAL_802BD17C
/* 344E50 802BE080 0200202D */   daddu     $a0, $s0, $zero
/* 344E54 802BE084 1040002F */  beqz       $v0, .LPAL_802BE144
/* 344E58 802BE088 24040286 */   addiu     $a0, $zero, 0x286
/* 344E5C 802BE08C 0000282D */  daddu      $a1, $zero, $zero
/* 344E60 802BE090 0C05222E */  jal        func_PAL_801488B8
/* 344E64 802BE094 2406FFFC */   addiu     $a2, $zero, -0x4
/* 344E68 802BE098 C60C000C */  lwc1       $f12, 0xC($s0)
/* 344E6C 802BE09C 0C00A89B */  jal        func_PAL_8002A26C
/* 344E70 802BE0A0 00000000 */   nop
/* 344E74 802BE0A4 C60C000C */  lwc1       $f12, 0xC($s0)
/* 344E78 802BE0A8 0C00A8B4 */  jal        func_PAL_8002A2D0
/* 344E7C 802BE0AC 46000506 */   mov.s     $f20, $f0
/* 344E80 802BE0B0 24020001 */  addiu      $v0, $zero, 0x1
/* 344E84 802BE0B4 860300A8 */  lh         $v1, 0xA8($s0)
/* 344E88 802BE0B8 C604003C */  lwc1       $f4, 0x3C($s0)
/* 344E8C 802BE0BC 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
/* 344E90 802BE0C0 44811000 */  mtc1       $at, $f2
/* 344E94 802BE0C4 46000007 */  neg.s      $f0, $f0
/* 344E98 802BE0C8 E7B40010 */  swc1       $f20, 0x10($sp)
/* 344E9C 802BE0CC E7A00018 */  swc1       $f0, 0x18($sp)
/* 344EA0 802BE0D0 AFA2001C */  sw         $v0, 0x1C($sp)
/* 344EA4 802BE0D4 44830000 */  mtc1       $v1, $f0
/* 344EA8 802BE0D8 00000000 */  nop
/* 344EAC 802BE0DC 46800020 */  cvt.s.w    $f0, $f0
/* 344EB0 802BE0E0 46002100 */  add.s      $f4, $f4, $f0
/* 344EB4 802BE0E4 E7A20014 */  swc1       $f2, 0x14($sp)
/* 344EB8 802BE0E8 8E050038 */  lw         $a1, 0x38($s0)
/* 344EBC 802BE0EC 8E070040 */  lw         $a3, 0x40($s0)
/* 344EC0 802BE0F0 44062000 */  mfc1       $a2, $f4
/* 344EC4 802BE0F4 0C0B7570 */  jal        func_PAL_802DD5C0
/* 344EC8 802BE0F8 24040003 */   addiu     $a0, $zero, 0x3
/* 344ECC 802BE0FC 0000202D */  daddu      $a0, $zero, $zero
/* 344ED0 802BE100 0080282D */  daddu      $a1, $a0, $zero
/* 344ED4 802BE104 0C05222E */  jal        func_PAL_801488B8
/* 344ED8 802BE108 2406FFFC */   addiu     $a2, $zero, -0x4
/* 344EDC 802BE10C 24020004 */  addiu      $v0, $zero, 0x4
/* 344EE0 802BE110 AEA20070 */  sw         $v0, 0x70($s5)
/* 344EE4 802BE114 C6000018 */  lwc1       $f0, 0x18($s0)
/* 344EE8 802BE118 3C014010 */  lui        $at, (0x40100000 >> 16)
/* 344EEC 802BE11C 44811800 */  mtc1       $at, $f3
/* 344EF0 802BE120 44801000 */  mtc1       $zero, $f2
/* 344EF4 802BE124 3C01802C */  lui        $at, %hi(D_PAL_802BEC28)
/* 344EF8 802BE128 D424EC28 */  ldc1       $f4, %lo(D_PAL_802BEC28)($at)
/* 344EFC 802BE12C 46000021 */  cvt.d.s    $f0, $f0
/* 344F00 802BE130 24020008 */  addiu      $v0, $zero, 0x8
/* 344F04 802BE134 3C01802C */  lui        $at, %hi(D_802BEC60)
/* 344F08 802BE138 AC22EC60 */  sw         $v0, %lo(D_802BEC60)($at)
/* 344F0C 802BE13C 080AF87F */  j          .LPAL_802BE1FC
/* 344F10 802BE140 46220001 */   sub.d     $f0, $f0, $f2
.LPAL_802BE144:
/* 344F14 802BE144 3C03802C */  lui        $v1, %hi(D_PAL_802BEB50)
/* 344F18 802BE148 8C63EB50 */  lw         $v1, %lo(D_PAL_802BEB50)($v1)
/* 344F1C 802BE14C 24020002 */  addiu      $v0, $zero, 0x2
/* 344F20 802BE150 1462000B */  bne        $v1, $v0, .LPAL_802BE180
/* 344F24 802BE154 0000202D */   daddu     $a0, $zero, $zero
/* 344F28 802BE158 0080282D */  daddu      $a1, $a0, $zero
/* 344F2C 802BE15C 0C05222E */  jal        func_PAL_801488B8
/* 344F30 802BE160 2406FFFC */   addiu     $a2, $zero, -0x4
/* 344F34 802BE164 24020005 */  addiu      $v0, $zero, 0x5
/* 344F38 802BE168 AEA20070 */  sw         $v0, 0x70($s5)
/* 344F3C 802BE16C 2402001E */  addiu      $v0, $zero, 0x1E
/* 344F40 802BE170 3C01802C */  lui        $at, %hi(D_802BEC60)
/* 344F44 802BE174 AC22EC60 */  sw         $v0, %lo(D_802BEC60)($at)
/* 344F48 802BE178 080AF8EC */  j          .LPAL_802BE3B0
/* 344F4C 802BE17C AE000018 */   sw        $zero, 0x18($s0)
.LPAL_802BE180:
/* 344F50 802BE180 C6020010 */  lwc1       $f2, 0x10($s0)
/* 344F54 802BE184 3C01430C */  lui        $at, (0x430C0000 >> 16)
/* 344F58 802BE188 44810000 */  mtc1       $at, $f0
/* 344F5C 802BE18C 00000000 */  nop
/* 344F60 802BE190 4602003C */  c.lt.s     $f0, $f2
/* 344F64 802BE194 00000000 */  nop
/* 344F68 802BE198 45000009 */  bc1f       .LPAL_802BE1C0
/* 344F6C 802BE19C 00000000 */   nop
.LPAL_802BE1A0:
/* 344F70 802BE1A0 0080282D */  daddu      $a1, $a0, $zero
/* 344F74 802BE1A4 2406FFFC */  addiu      $a2, $zero, -0x4
/* 344F78 802BE1A8 24020007 */  addiu      $v0, $zero, 0x7
/* 344F7C 802BE1AC AEA20070 */  sw         $v0, 0x70($s5)
/* 344F80 802BE1B0 0C05222E */  jal        func_PAL_801488B8
/* 344F84 802BE1B4 AE000018 */   sw        $zero, 0x18($s0)
/* 344F88 802BE1B8 080AF8EC */  j          .LPAL_802BE3B0
/* 344F8C 802BE1BC 00000000 */   nop
.LPAL_802BE1C0:
/* 344F90 802BE1C0 3C0142D2 */  lui        $at, (0x42D20000 >> 16)
/* 344F94 802BE1C4 44810000 */  mtc1       $at, $f0
/* 344F98 802BE1C8 00000000 */  nop
/* 344F9C 802BE1CC 4602003C */  c.lt.s     $f0, $f2
/* 344FA0 802BE1D0 00000000 */  nop
/* 344FA4 802BE1D4 45000076 */  bc1f       .LPAL_802BE3B0
/* 344FA8 802BE1D8 00000000 */   nop
/* 344FAC 802BE1DC C6000018 */  lwc1       $f0, 0x18($s0)
/* 344FB0 802BE1E0 3C014010 */  lui        $at, (0x40100000 >> 16)
/* 344FB4 802BE1E4 44811800 */  mtc1       $at, $f3
/* 344FB8 802BE1E8 44801000 */  mtc1       $zero, $f2
/* 344FBC 802BE1EC 46000021 */  cvt.d.s    $f0, $f0
/* 344FC0 802BE1F0 46220001 */  sub.d      $f0, $f0, $f2
/* 344FC4 802BE1F4 3C01802C */  lui        $at, %hi(D_PAL_802BEC30)
/* 344FC8 802BE1F8 D424EC30 */  ldc1       $f4, %lo(D_PAL_802BEC30)($at)
.LPAL_802BE1FC:
/* 344FCC 802BE1FC 46200020 */  cvt.s.d    $f0, $f0
/* 344FD0 802BE200 460000A1 */  cvt.d.s    $f2, $f0
/* 344FD4 802BE204 4624103C */  c.lt.d     $f2, $f4
/* 344FD8 802BE208 00000000 */  nop
/* 344FDC 802BE20C 45000068 */  bc1f       .LPAL_802BE3B0
/* 344FE0 802BE210 E6000018 */   swc1      $f0, 0x18($s0)
/* 344FE4 802BE214 C6000010 */  lwc1       $f0, 0x10($s0)
/* 344FE8 802BE218 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
/* 344FEC 802BE21C 44811800 */  mtc1       $at, $f3
/* 344FF0 802BE220 44801000 */  mtc1       $zero, $f2
/* 344FF4 802BE224 46000021 */  cvt.d.s    $f0, $f0
/* 344FF8 802BE228 46220000 */  add.d      $f0, $f0, $f2
/* 344FFC 802BE22C 3C013C23 */  lui        $at, (0x3C23D70A >> 16)
/* 345000 802BE230 3421D70A */  ori        $at, $at, (0x3C23D70A & 0xFFFF)
/* 345004 802BE234 44811000 */  mtc1       $at, $f2
/* 345008 802BE238 00000000 */  nop
/* 34500C 802BE23C E6020018 */  swc1       $f2, 0x18($s0)
/* 345010 802BE240 46200020 */  cvt.s.d    $f0, $f0
/* 345014 802BE244 080AF8EC */  j          .LPAL_802BE3B0
/* 345018 802BE248 E6000010 */   swc1      $f0, 0x10($s0)
.LPAL_802BE24C:
/* 34501C 802BE24C C6000038 */  lwc1       $f0, 0x38($s0)
/* 345020 802BE250 C602003C */  lwc1       $f2, 0x3C($s0)
/* 345024 802BE254 C6040040 */  lwc1       $f4, 0x40($s0)
/* 345028 802BE258 C6060018 */  lwc1       $f6, 0x18($s0)
/* 34502C 802BE25C 34048000 */  ori        $a0, $zero, 0x8000
/* 345030 802BE260 E7A00020 */  swc1       $f0, 0x20($sp)
/* 345034 802BE264 E7A20024 */  swc1       $f2, 0x24($sp)
/* 345038 802BE268 E7A40028 */  swc1       $f4, 0x28($sp)
/* 34503C 802BE26C E7A60010 */  swc1       $f6, 0x10($sp)
/* 345040 802BE270 C600000C */  lwc1       $f0, 0xC($s0)
/* 345044 802BE274 27A50020 */  addiu      $a1, $sp, 0x20
/* 345048 802BE278 E7A00014 */  swc1       $f0, 0x14($sp)
/* 34504C 802BE27C 860200A8 */  lh         $v0, 0xA8($s0)
/* 345050 802BE280 27A60024 */  addiu      $a2, $sp, 0x24
/* 345054 802BE284 44820000 */  mtc1       $v0, $f0
/* 345058 802BE288 00000000 */  nop
/* 34505C 802BE28C 46800020 */  cvt.s.w    $f0, $f0
/* 345060 802BE290 E7A00018 */  swc1       $f0, 0x18($sp)
/* 345064 802BE294 960300A6 */  lhu        $v1, 0xA6($s0)
/* 345068 802BE298 27A70028 */  addiu      $a3, $sp, 0x28
/* 34506C 802BE29C 00031C00 */  sll        $v1, $v1, 16
/* 345070 802BE2A0 00031403 */  sra        $v0, $v1, 16
/* 345074 802BE2A4 00031FC2 */  srl        $v1, $v1, 31
/* 345078 802BE2A8 00431021 */  addu       $v0, $v0, $v1
/* 34507C 802BE2AC 00021043 */  sra        $v0, $v0, 1
/* 345080 802BE2B0 44820000 */  mtc1       $v0, $f0
/* 345084 802BE2B4 00000000 */  nop
/* 345088 802BE2B8 46800020 */  cvt.s.w    $f0, $f0
/* 34508C 802BE2BC 0C036895 */  jal        func_PAL_800DA254
/* 345090 802BE2C0 E7A0001C */   swc1      $f0, 0x1C($sp)
/* 345094 802BE2C4 0200202D */  daddu      $a0, $s0, $zero
/* 345098 802BE2C8 C7A00020 */  lwc1       $f0, 0x20($sp)
/* 34509C 802BE2CC C6020018 */  lwc1       $f2, 0x18($s0)
/* 3450A0 802BE2D0 24050001 */  addiu      $a1, $zero, 0x1
/* 3450A4 802BE2D4 E6000038 */  swc1       $f0, 0x38($s0)
/* 3450A8 802BE2D8 C7A60024 */  lwc1       $f6, 0x24($sp)
/* 3450AC 802BE2DC C6000010 */  lwc1       $f0, 0x10($s0)
/* 3450B0 802BE2E0 C7A40028 */  lwc1       $f4, 0x28($sp)
/* 3450B4 802BE2E4 46020000 */  add.s      $f0, $f0, $f2
/* 3450B8 802BE2E8 E606003C */  swc1       $f6, 0x3C($s0)
/* 3450BC 802BE2EC E6040040 */  swc1       $f4, 0x40($s0)
/* 3450C0 802BE2F0 0C00F6D4 */  jal        func_PAL_8003DB50
/* 3450C4 802BE2F4 E6000010 */   swc1      $f0, 0x10($s0)
/* 3450C8 802BE2F8 C6000018 */  lwc1       $f0, 0x18($s0)
/* 3450CC 802BE2FC 3C014018 */  lui        $at, (0x40180000 >> 16)
/* 3450D0 802BE300 44811800 */  mtc1       $at, $f3
/* 3450D4 802BE304 44801000 */  mtc1       $zero, $f2
/* 3450D8 802BE308 46000021 */  cvt.d.s    $f0, $f0
/* 3450DC 802BE30C 46220001 */  sub.d      $f0, $f0, $f2
/* 3450E0 802BE310 3C01802C */  lui        $at, %hi(D_PAL_802BEC38)
/* 3450E4 802BE314 D424EC38 */  ldc1       $f4, %lo(D_PAL_802BEC38)($at)
/* 3450E8 802BE318 46200020 */  cvt.s.d    $f0, $f0
/* 3450EC 802BE31C 460000A1 */  cvt.d.s    $f2, $f0
/* 3450F0 802BE320 4624103C */  c.lt.d     $f2, $f4
/* 3450F4 802BE324 00000000 */  nop
/* 3450F8 802BE328 4500000E */  bc1f       .LPAL_802BE364
/* 3450FC 802BE32C E6000018 */   swc1      $f0, 0x18($s0)
/* 345100 802BE330 C6000010 */  lwc1       $f0, 0x10($s0)
/* 345104 802BE334 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
/* 345108 802BE338 44811800 */  mtc1       $at, $f3
/* 34510C 802BE33C 44801000 */  mtc1       $zero, $f2
/* 345110 802BE340 46000021 */  cvt.d.s    $f0, $f0
/* 345114 802BE344 46220000 */  add.d      $f0, $f0, $f2
/* 345118 802BE348 3C013C23 */  lui        $at, (0x3C23D70A >> 16)
/* 34511C 802BE34C 3421D70A */  ori        $at, $at, (0x3C23D70A & 0xFFFF)
/* 345120 802BE350 44811000 */  mtc1       $at, $f2
/* 345124 802BE354 00000000 */  nop
/* 345128 802BE358 E6020018 */  swc1       $f2, 0x18($s0)
/* 34512C 802BE35C 46200020 */  cvt.s.d    $f0, $f0
/* 345130 802BE360 E6000010 */  swc1       $f0, 0x10($s0)
.LPAL_802BE364:
/* 345134 802BE364 3C03802C */  lui        $v1, %hi(D_802BEC60)
/* 345138 802BE368 2463EC60 */  addiu      $v1, $v1, %lo(D_802BEC60)
/* 34513C 802BE36C 8C620000 */  lw         $v0, 0x0($v1)
/* 345140 802BE370 1440000B */  bnez       $v0, .LPAL_802BE3A0
/* 345144 802BE374 2442FFFF */   addiu     $v0, $v0, -0x1
/* 345148 802BE378 24020007 */  addiu      $v0, $zero, 0x7
/* 34514C 802BE37C AEA20070 */  sw         $v0, 0x70($s5)
/* 345150 802BE380 8C620000 */  lw         $v0, 0x0($v1)
/* 345154 802BE384 080AF8E8 */  j          .LPAL_802BE3A0
/* 345158 802BE388 2442FFFF */   addiu     $v0, $v0, -0x1
.LPAL_802BE38C:
/* 34515C 802BE38C 3C03802C */  lui        $v1, %hi(D_802BEC60)
/* 345160 802BE390 2463EC60 */  addiu      $v1, $v1, %lo(D_802BEC60)
/* 345164 802BE394 8C620000 */  lw         $v0, 0x0($v1)
/* 345168 802BE398 10400003 */  beqz       $v0, .LPAL_802BE3A8
/* 34516C 802BE39C 2442FFFF */   addiu     $v0, $v0, -0x1
.LPAL_802BE3A0:
/* 345170 802BE3A0 080AF8EC */  j          .LPAL_802BE3B0
/* 345174 802BE3A4 AC620000 */   sw        $v0, 0x0($v1)
.LPAL_802BE3A8:
/* 345178 802BE3A8 24020007 */  addiu      $v0, $zero, 0x7
.LPAL_802BE3AC:
/* 34517C 802BE3AC AEA20070 */  sw         $v0, 0x70($s5)
.LPAL_802BE3B0:
/* 345180 802BE3B0 8EA30070 */  lw         $v1, 0x70($s5)
/* 345184 802BE3B4 24020007 */  addiu      $v0, $zero, 0x7
/* 345188 802BE3B8 146200D5 */  bne        $v1, $v0, .LPAL_802BE710
/* 34518C 802BE3BC 00000000 */   nop
/* 345190 802BE3C0 8E020000 */  lw         $v0, 0x0($s0)
/* 345194 802BE3C4 34420100 */  ori        $v0, $v0, 0x100
/* 345198 802BE3C8 AE020000 */  sw         $v0, 0x0($s0)
/* 34519C 802BE3CC 928200B4 */  lbu        $v0, 0xB4($s4)
/* 3451A0 802BE3D0 2442FFEB */  addiu      $v0, $v0, -0x15
/* 3451A4 802BE3D4 2C420002 */  sltiu      $v0, $v0, 0x2
/* 3451A8 802BE3D8 544000CD */  bnel       $v0, $zero, .LPAL_802BE710
/* 3451AC 802BE3DC AEA00070 */   sw        $zero, 0x70($s5)
/* 3451B0 802BE3E0 3C01802C */  lui        $at, %hi(D_802BEC80)
/* 3451B4 802BE3E4 C42CEC80 */  lwc1       $f12, %lo(D_802BEC80)($at)
/* 3451B8 802BE3E8 3C01802C */  lui        $at, %hi(D_802BEC88)
/* 3451BC 802BE3EC C42EEC88 */  lwc1       $f14, %lo(D_802BEC88)($at)
/* 3451C0 802BE3F0 8E060038 */  lw         $a2, 0x38($s0)
/* 3451C4 802BE3F4 0C00A700 */  jal        func_PAL_80029C00
/* 3451C8 802BE3F8 8E070040 */   lw        $a3, 0x40($s0)
/* 3451CC 802BE3FC 46000506 */  mov.s      $f20, $f0
/* 3451D0 802BE400 C60C000C */  lwc1       $f12, 0xC($s0)
/* 3451D4 802BE404 0C00A6EA */  jal        func_PAL_80029BA8
/* 3451D8 802BE408 4600A386 */   mov.s     $f14, $f20
/* 3451DC 802BE40C 3C013E00 */  lui        $at, (0x3E000000 >> 16)
/* 3451E0 802BE410 44811000 */  mtc1       $at, $f2
/* 3451E4 802BE414 00000000 */  nop
/* 3451E8 802BE418 46020002 */  mul.s      $f0, $f0, $f2
/* 3451EC 802BE41C 00000000 */  nop
/* 3451F0 802BE420 4600A500 */  add.s      $f20, $f20, $f0
/* 3451F4 802BE424 C6000018 */  lwc1       $f0, 0x18($s0)
/* 3451F8 802BE428 46000007 */  neg.s      $f0, $f0
/* 3451FC 802BE42C 44050000 */  mfc1       $a1, $f0
/* 345200 802BE430 4406A000 */  mfc1       $a2, $f20
/* 345204 802BE434 0200202D */  daddu      $a0, $s0, $zero
/* 345208 802BE438 0C00EBD1 */  jal        func_PAL_8003AF44
/* 34520C 802BE43C AE06000C */   sw        $a2, 0xC($s0)
/* 345210 802BE440 C6020010 */  lwc1       $f2, 0x10($s0)
/* 345214 802BE444 C6000018 */  lwc1       $f0, 0x18($s0)
/* 345218 802BE448 46001081 */  sub.s      $f2, $f2, $f0
/* 34521C 802BE44C 0200202D */  daddu      $a0, $s0, $zero
/* 345220 802BE450 24050001 */  addiu      $a1, $zero, 0x1
/* 345224 802BE454 0C00F6D4 */  jal        func_PAL_8003DB50
/* 345228 802BE458 E6020010 */   swc1      $f2, 0x10($s0)
/* 34522C 802BE45C C6000018 */  lwc1       $f0, 0x18($s0)
/* 345230 802BE460 3C01802C */  lui        $at, %hi(D_PAL_802BEC40)
/* 345234 802BE464 D422EC40 */  ldc1       $f2, %lo(D_PAL_802BEC40)($at)
/* 345238 802BE468 46000021 */  cvt.d.s    $f0, $f0
/* 34523C 802BE46C 46220000 */  add.d      $f0, $f0, $f2
/* 345240 802BE470 3C01402C */  lui        $at, (0x402C0000 >> 16)
/* 345244 802BE474 44812800 */  mtc1       $at, $f5
/* 345248 802BE478 44802000 */  mtc1       $zero, $f4
/* 34524C 802BE47C 46200020 */  cvt.s.d    $f0, $f0
/* 345250 802BE480 460000A1 */  cvt.d.s    $f2, $f0
/* 345254 802BE484 4622203C */  c.lt.d     $f4, $f2
/* 345258 802BE488 00000000 */  nop
/* 34525C 802BE48C 45000005 */  bc1f       .LPAL_802BE4A4
/* 345260 802BE490 E6000018 */   swc1      $f0, 0x18($s0)
/* 345264 802BE494 3C014160 */  lui        $at, (0x41600000 >> 16)
/* 345268 802BE498 44810000 */  mtc1       $at, $f0
/* 34526C 802BE49C 00000000 */  nop
/* 345270 802BE4A0 E6000018 */  swc1       $f0, 0x18($s0)
.LPAL_802BE4A4:
/* 345274 802BE4A4 3C0540C0 */  lui        $a1, (0x40C00000 >> 16)
/* 345278 802BE4A8 0C00E736 */  jal        func_PAL_80039CD8
/* 34527C 802BE4AC 0200202D */   daddu     $a0, $s0, $zero
/* 345280 802BE4B0 1440000A */  bnez       $v0, .LPAL_802BE4DC
/* 345284 802BE4B4 00000000 */   nop
/* 345288 802BE4B8 C680002C */  lwc1       $f0, 0x2C($s4)
/* 34528C 802BE4BC C602003C */  lwc1       $f2, 0x3C($s0)
/* 345290 802BE4C0 46020001 */  sub.s      $f0, $f0, $f2
/* 345294 802BE4C4 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 345298 802BE4C8 44812000 */  mtc1       $at, $f4
/* 34529C 802BE4CC 00000000 */  nop
/* 3452A0 802BE4D0 46040003 */  div.s      $f0, $f0, $f4
/* 3452A4 802BE4D4 46001080 */  add.s      $f2, $f2, $f0
/* 3452A8 802BE4D8 E602003C */  swc1       $f2, 0x3C($s0)
.LPAL_802BE4DC:
/* 3452AC 802BE4DC C6020038 */  lwc1       $f2, 0x38($s0)
/* 3452B0 802BE4E0 C604003C */  lwc1       $f4, 0x3C($s0)
/* 3452B4 802BE4E4 C60C000C */  lwc1       $f12, 0xC($s0)
/* 3452B8 802BE4E8 3C014334 */  lui        $at, (0x43340000 >> 16)
/* 3452BC 802BE4EC 4481A000 */  mtc1       $at, $f20
/* 3452C0 802BE4F0 C6000040 */  lwc1       $f0, 0x40($s0)
/* 3452C4 802BE4F4 46146300 */  add.s      $f12, $f12, $f20
/* 3452C8 802BE4F8 E7A20020 */  swc1       $f2, 0x20($sp)
/* 3452CC 802BE4FC E7A40024 */  swc1       $f4, 0x24($sp)
/* 3452D0 802BE500 0C00A6A9 */  jal        func_PAL_80029AA4
/* 3452D4 802BE504 E7A00028 */   swc1      $f0, 0x28($sp)
/* 3452D8 802BE508 34048000 */  ori        $a0, $zero, 0x8000
/* 3452DC 802BE50C C6020018 */  lwc1       $f2, 0x18($s0)
/* 3452E0 802BE510 27A50020 */  addiu      $a1, $sp, 0x20
/* 3452E4 802BE514 E7A00014 */  swc1       $f0, 0x14($sp)
/* 3452E8 802BE518 E7A20010 */  swc1       $f2, 0x10($sp)
/* 3452EC 802BE51C 860200A8 */  lh         $v0, 0xA8($s0)
/* 3452F0 802BE520 27A60024 */  addiu      $a2, $sp, 0x24
/* 3452F4 802BE524 44820000 */  mtc1       $v0, $f0
/* 3452F8 802BE528 00000000 */  nop
/* 3452FC 802BE52C 46800020 */  cvt.s.w    $f0, $f0
/* 345300 802BE530 E7A00018 */  swc1       $f0, 0x18($sp)
/* 345304 802BE534 860200A6 */  lh         $v0, 0xA6($s0)
/* 345308 802BE538 27A70028 */  addiu      $a3, $sp, 0x28
/* 34530C 802BE53C 44820000 */  mtc1       $v0, $f0
/* 345310 802BE540 00000000 */  nop
/* 345314 802BE544 46800020 */  cvt.s.w    $f0, $f0
/* 345318 802BE548 0C036895 */  jal        func_PAL_800DA254
/* 34531C 802BE54C E7A0001C */   swc1      $f0, 0x1C($sp)
/* 345320 802BE550 10400026 */  beqz       $v0, .LPAL_802BE5EC
/* 345324 802BE554 2404010C */   addiu     $a0, $zero, 0x10C
/* 345328 802BE558 0000282D */  daddu      $a1, $zero, $zero
/* 34532C 802BE55C C7A00020 */  lwc1       $f0, 0x20($sp)
/* 345330 802BE560 C7A20024 */  lwc1       $f2, 0x24($sp)
/* 345334 802BE564 C7A40028 */  lwc1       $f4, 0x28($sp)
/* 345338 802BE568 2406FFFC */  addiu      $a2, $zero, -0x4
/* 34533C 802BE56C E6000038 */  swc1       $f0, 0x38($s0)
/* 345340 802BE570 E602003C */  swc1       $f2, 0x3C($s0)
/* 345344 802BE574 0C05222E */  jal        func_PAL_801488B8
/* 345348 802BE578 E6040040 */   swc1      $f4, 0x40($s0)
/* 34534C 802BE57C C60C000C */  lwc1       $f12, 0xC($s0)
/* 345350 802BE580 0C00A89B */  jal        func_PAL_8002A26C
/* 345354 802BE584 46146300 */   add.s     $f12, $f12, $f20
/* 345358 802BE588 C60C000C */  lwc1       $f12, 0xC($s0)
/* 34535C 802BE58C 46146300 */  add.s      $f12, $f12, $f20
/* 345360 802BE590 0C00A8B4 */  jal        func_PAL_8002A2D0
/* 345364 802BE594 46000506 */   mov.s     $f20, $f0
/* 345368 802BE598 24020001 */  addiu      $v0, $zero, 0x1
/* 34536C 802BE59C 860300A8 */  lh         $v1, 0xA8($s0)
/* 345370 802BE5A0 C604003C */  lwc1       $f4, 0x3C($s0)
/* 345374 802BE5A4 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
/* 345378 802BE5A8 44811000 */  mtc1       $at, $f2
/* 34537C 802BE5AC 46000007 */  neg.s      $f0, $f0
/* 345380 802BE5B0 E7B40010 */  swc1       $f20, 0x10($sp)
/* 345384 802BE5B4 E7A00018 */  swc1       $f0, 0x18($sp)
/* 345388 802BE5B8 AFA2001C */  sw         $v0, 0x1C($sp)
/* 34538C 802BE5BC 44830000 */  mtc1       $v1, $f0
/* 345390 802BE5C0 00000000 */  nop
/* 345394 802BE5C4 46800020 */  cvt.s.w    $f0, $f0
/* 345398 802BE5C8 46002100 */  add.s      $f4, $f4, $f0
/* 34539C 802BE5CC E7A20014 */  swc1       $f2, 0x14($sp)
/* 3453A0 802BE5D0 8E050038 */  lw         $a1, 0x38($s0)
/* 3453A4 802BE5D4 8E070040 */  lw         $a3, 0x40($s0)
/* 3453A8 802BE5D8 44062000 */  mfc1       $a2, $f4
/* 3453AC 802BE5DC 0C0B7570 */  jal        func_PAL_802DD5C0
/* 3453B0 802BE5E0 24040003 */   addiu     $a0, $zero, 0x3
/* 3453B4 802BE5E4 080AF9C4 */  j          .LPAL_802BE710
/* 3453B8 802BE5E8 AEA00070 */   sw        $zero, 0x70($s5)
.LPAL_802BE5EC:
/* 3453BC 802BE5EC 3C02802C */  lui        $v0, %hi(D_802BEC7C)
/* 3453C0 802BE5F0 8C42EC7C */  lw         $v0, %lo(D_802BEC7C)($v0)
/* 3453C4 802BE5F4 10400025 */  beqz       $v0, .LPAL_802BE68C
/* 3453C8 802BE5F8 00000000 */   nop
/* 3453CC 802BE5FC 3C04802C */  lui        $a0, %hi(D_802BEC78)
/* 3453D0 802BE600 8C84EC78 */  lw         $a0, %lo(D_802BEC78)($a0)
/* 3453D4 802BE604 0C04BEBE */  jal        func_PAL_8012FAF8
/* 3453D8 802BE608 00000000 */   nop
/* 3453DC 802BE60C 0040882D */  daddu      $s1, $v0, $zero
/* 3453E0 802BE610 C6060038 */  lwc1       $f6, 0x38($s0)
/* 3453E4 802BE614 C600003C */  lwc1       $f0, 0x3C($s0)
/* 3453E8 802BE618 3C014100 */  lui        $at, (0x41000000 >> 16)
/* 3453EC 802BE61C 44811000 */  mtc1       $at, $f2
/* 3453F0 802BE620 C6040040 */  lwc1       $f4, 0x40($s0)
/* 3453F4 802BE624 3C02802C */  lui        $v0, %hi(D_802BEC68)
/* 3453F8 802BE628 8C42EC68 */  lw         $v0, %lo(D_802BEC68)($v0)
/* 3453FC 802BE62C 46020000 */  add.s      $f0, $f0, $f2
/* 345400 802BE630 E7A60020 */  swc1       $f6, 0x20($sp)
/* 345404 802BE634 E7A40028 */  swc1       $f4, 0x28($sp)
/* 345408 802BE638 E7A00024 */  swc1       $f0, 0x24($sp)
/* 34540C 802BE63C C68C0080 */  lwc1       $f12, 0x80($s4)
/* 345410 802BE640 3C01C2B4 */  lui        $at, (0xC2B40000 >> 16)
/* 345414 802BE644 44810000 */  mtc1       $at, $f0
/* 345418 802BE648 10400003 */  beqz       $v0, .LPAL_802BE658
/* 34541C 802BE64C 00000000 */   nop
/* 345420 802BE650 3C0142B4 */  lui        $at, (0x42B40000 >> 16)
/* 345424 802BE654 44810000 */  mtc1       $at, $f0
.LPAL_802BE658:
/* 345428 802BE658 0C00A6A9 */  jal        func_PAL_80029AA4
/* 34542C 802BE65C 46006301 */   sub.s     $f12, $f12, $f0
/* 345430 802BE660 27A40020 */  addiu      $a0, $sp, 0x20
/* 345434 802BE664 3C064080 */  lui        $a2, (0x40800000 >> 16)
/* 345438 802BE668 44070000 */  mfc1       $a3, $f0
/* 34543C 802BE66C 0C00A7C7 */  jal        func_PAL_80029F1C
/* 345440 802BE670 27A50028 */   addiu     $a1, $sp, 0x28
/* 345444 802BE674 C7A00020 */  lwc1       $f0, 0x20($sp)
/* 345448 802BE678 C7A20024 */  lwc1       $f2, 0x24($sp)
/* 34544C 802BE67C C7A40028 */  lwc1       $f4, 0x28($sp)
/* 345450 802BE680 E6200008 */  swc1       $f0, 0x8($s1)
/* 345454 802BE684 E622000C */  swc1       $f2, 0xC($s1)
/* 345458 802BE688 E6240010 */  swc1       $f4, 0x10($s1)
.LPAL_802BE68C:
/* 34545C 802BE68C C6020010 */  lwc1       $f2, 0x10($s0)
/* 345460 802BE690 3C014170 */  lui        $at, (0x41700000 >> 16)
/* 345464 802BE694 44810000 */  mtc1       $at, $f0
/* 345468 802BE698 00000000 */  nop
/* 34546C 802BE69C 46001080 */  add.s      $f2, $f2, $f0
/* 345470 802BE6A0 C6040018 */  lwc1       $f4, 0x18($s0)
/* 345474 802BE6A4 4604103C */  c.lt.s     $f2, $f4
/* 345478 802BE6A8 00000000 */  nop
/* 34547C 802BE6AC 45030018 */  bc1tl      .LPAL_802BE710
/* 345480 802BE6B0 AEA00070 */   sw        $zero, 0x70($s5)
/* 345484 802BE6B4 3C01420C */  lui        $at, (0x420C0000 >> 16)
/* 345488 802BE6B8 44810000 */  mtc1       $at, $f0
/* 34548C 802BE6BC 00000000 */  nop
/* 345490 802BE6C0 4600103C */  c.lt.s     $f2, $f0
/* 345494 802BE6C4 00000000 */  nop
/* 345498 802BE6C8 45000011 */  bc1f       .LPAL_802BE710
/* 34549C 802BE6CC 00000000 */   nop
/* 3454A0 802BE6D0 3C014010 */  lui        $at, (0x40100000 >> 16)
/* 3454A4 802BE6D4 44810800 */  mtc1       $at, $f1
/* 3454A8 802BE6D8 44800000 */  mtc1       $zero, $f0
/* 3454AC 802BE6DC 460020A1 */  cvt.d.s    $f2, $f4
/* 3454B0 802BE6E0 46201081 */  sub.d      $f2, $f2, $f0
/* 3454B4 802BE6E4 462010A0 */  cvt.s.d    $f2, $f2
/* 3454B8 802BE6E8 E6020018 */  swc1       $f2, 0x18($s0)
/* 3454BC 802BE6EC 460010A1 */  cvt.d.s    $f2, $f2
/* 3454C0 802BE6F0 4620103C */  c.lt.d     $f2, $f0
/* 3454C4 802BE6F4 00000000 */  nop
/* 3454C8 802BE6F8 45000005 */  bc1f       .LPAL_802BE710
/* 3454CC 802BE6FC 00000000 */   nop
/* 3454D0 802BE700 3C014080 */  lui        $at, (0x40800000 >> 16)
/* 3454D4 802BE704 44810000 */  mtc1       $at, $f0
/* 3454D8 802BE708 00000000 */  nop
/* 3454DC 802BE70C E6000018 */  swc1       $f0, 0x18($s0)
.LPAL_802BE710:
/* 3454E0 802BE710 8EA20070 */  lw         $v0, 0x70($s5)
/* 3454E4 802BE714 1440002B */  bnez       $v0, .LPAL_802BE7C4
/* 3454E8 802BE718 0000102D */   daddu     $v0, $zero, $zero
/* 3454EC 802BE71C 3C11802C */  lui        $s1, %hi(D_802BEC74)
/* 3454F0 802BE720 2631EC74 */  addiu      $s1, $s1, %lo(D_802BEC74)
/* 3454F4 802BE724 8E220000 */  lw         $v0, 0x0($s1)
/* 3454F8 802BE728 10400005 */  beqz       $v0, .LPAL_802BE740
/* 3454FC 802BE72C 3C050002 */   lui       $a1, (0x20004 >> 16)
/* 345500 802BE730 0C037245 */  jal        func_PAL_800DC914
/* 345504 802BE734 00000000 */   nop
/* 345508 802BE738 AE200000 */  sw         $zero, 0x0($s1)
/* 34550C 802BE73C 3C050002 */  lui        $a1, (0x20004 >> 16)
.LPAL_802BE740:
/* 345510 802BE740 34A50004 */  ori        $a1, $a1, (0x20004 & 0xFFFF)
/* 345514 802BE744 24040284 */  addiu      $a0, $zero, 0x284
/* 345518 802BE748 8E020000 */  lw         $v0, 0x0($s0)
/* 34551C 802BE74C 2403F7BF */  addiu      $v1, $zero, -0x841
/* 345520 802BE750 3C01802C */  lui        $at, %hi(D_PAL_802BEB50)
/* 345524 802BE754 AC20EB50 */  sw         $zero, %lo(D_PAL_802BEB50)($at)
/* 345528 802BE758 34420100 */  ori        $v0, $v0, 0x100
/* 34552C 802BE75C 00431024 */  and        $v0, $v0, $v1
/* 345530 802BE760 AE020000 */  sw         $v0, 0x0($s0)
/* 345534 802BE764 24020018 */  addiu      $v0, $zero, 0x18
/* 345538 802BE768 A2C00003 */  sb         $zero, 0x3($s6)
/* 34553C 802BE76C A2C00000 */  sb         $zero, 0x0($s6)
/* 345540 802BE770 AE00001C */  sw         $zero, 0x1C($s0)
/* 345544 802BE774 A60200A8 */  sh         $v0, 0xA8($s0)
/* 345548 802BE778 0C052207 */  jal        func_PAL_8014881C
/* 34554C 802BE77C AE050028 */   sw        $a1, 0x28($s0)
/* 345550 802BE780 0C00ECA7 */  jal        func_PAL_8003B29C
/* 345554 802BE784 0200202D */   daddu     $a0, $s0, $zero
/* 345558 802BE788 3C11802C */  lui        $s1, %hi(D_802BEC7C)
/* 34555C 802BE78C 2631EC7C */  addiu      $s1, $s1, %lo(D_802BEC7C)
/* 345560 802BE790 8E220000 */  lw         $v0, 0x0($s1)
/* 345564 802BE794 10400006 */  beqz       $v0, .LPAL_802BE7B0
/* 345568 802BE798 00000000 */   nop
/* 34556C 802BE79C 3C04802C */  lui        $a0, %hi(D_802BEC78)
/* 345570 802BE7A0 8C84EC78 */  lw         $a0, %lo(D_802BEC78)($a0)
/* 345574 802BE7A4 0C04CB54 */  jal        func_PAL_80132D50
/* 345578 802BE7A8 00000000 */   nop
/* 34557C 802BE7AC AE200000 */  sw         $zero, 0x0($s1)
.LPAL_802BE7B0:
/* 345580 802BE7B0 3C01802C */  lui        $at, %hi(D_802BEC64)
/* 345584 802BE7B4 AC20EC64 */  sw         $zero, %lo(D_802BEC64)($at)
/* 345588 802BE7B8 0C03AF2B */  jal        func_PAL_800EBCAC
/* 34558C 802BE7BC 0200202D */   daddu     $a0, $s0, $zero
/* 345590 802BE7C0 24020002 */  addiu      $v0, $zero, 0x2
.LPAL_802BE7C4:
/* 345594 802BE7C4 8FBF004C */  lw         $ra, 0x4C($sp)
/* 345598 802BE7C8 8FB60048 */  lw         $s6, 0x48($sp)
/* 34559C 802BE7CC 8FB50044 */  lw         $s5, 0x44($sp)
/* 3455A0 802BE7D0 8FB40040 */  lw         $s4, 0x40($sp)
/* 3455A4 802BE7D4 8FB3003C */  lw         $s3, 0x3C($sp)
/* 3455A8 802BE7D8 8FB20038 */  lw         $s2, 0x38($sp)
/* 3455AC 802BE7DC 8FB10034 */  lw         $s1, 0x34($sp)
/* 3455B0 802BE7E0 8FB00030 */  lw         $s0, 0x30($sp)
/* 3455B4 802BE7E4 D7B40050 */  ldc1       $f20, 0x50($sp)
/* 3455B8 802BE7E8 03E00008 */  jr         $ra
/* 3455BC 802BE7EC 27BD0058 */   addiu     $sp, $sp, 0x58
