.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.12.1 */

glabel func_8006F000
/* 4A400 8006F000 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 4A404 8006F004 3C0E800B */  lui        $t6, %hi(D_800B11C8)
/* 4A408 8006F008 8DCE11C8 */  lw         $t6, %lo(D_800B11C8)($t6)
/* 4A40C 8006F00C 00000000 */  nop
/* 4A410 8006F010 15C00004 */  bnez       $t6, .L8006F024
/* 4A414 8006F014 00000000 */   nop
/* 4A418 8006F018 00047980 */  sll        $t7, $a0, 6
/* 4A41C 8006F01C 10000003 */  b          .L8006F02C
/* 4A420 8006F020 AFAF0004 */   sw        $t7, 0x4($sp)
.L8006F024:
/* 4A424 8006F024 0004C1C0 */  sll        $t8, $a0, 7
/* 4A428 8006F028 AFB80004 */  sw         $t8, 0x4($sp)
.L8006F02C:
/* 4A42C 8006F02C 8FA20004 */  lw         $v0, 0x4($sp)
/* 4A430 8006F030 10000003 */  b          .L8006F040
/* 4A434 8006F034 00000000 */   nop
/* 4A438 8006F038 10000001 */  b          .L8006F040
/* 4A43C 8006F03C 00000000 */   nop
.L8006F040:
/* 4A440 8006F040 03E00008 */  jr         $ra
/* 4A444 8006F044 27BD0008 */   addiu     $sp, $sp, 0x8

glabel func_8006F048
/* 4A448 8006F048 308400FF */  andi       $a0, $a0, 0xFF
/* 4A44C 8006F04C 30A500FF */  andi       $a1, $a1, 0xFF
/* 4A450 8006F050 30C600FF */  andi       $a2, $a2, 0xFF
/* 4A454 8006F054 30E700FF */  andi       $a3, $a3, 0xFF
/* 4A458 8006F058 8FAE0010 */  lw         $t6, 0x10($sp)
/* 4A45C 8006F05C 3C01A000 */  lui        $at, (0xA0000000 >> 16)
/* 4A460 8006F060 01C17825 */  or         $t7, $t6, $at
/* 4A464 8006F064 3C01800B */  lui        $at, %hi(D_800B115C)
/* 4A468 8006F068 AC2F115C */  sw         $t7, %lo(D_800B115C)($at)
/* 4A46C 8006F06C 3C18800B */  lui        $t8, %hi(D_800B1154)
/* 4A470 8006F070 93181154 */  lbu        $t8, %lo(D_800B1154)($t8)
/* 4A474 8006F074 3C01800B */  lui        $at, %hi(D_800B1154)
/* 4A478 8006F078 27190001 */  addiu      $t9, $t8, 0x1
/* 4A47C 8006F07C A0391154 */  sb         $t9, %lo(D_800B1154)($at)
/* 4A480 8006F080 3C01800B */  lui        $at, %hi(D_800B1155)
/* 4A484 8006F084 A0241155 */  sb         $a0, %lo(D_800B1155)($at)
/* 4A488 8006F088 3C01800B */  lui        $at, %hi(D_800B1158)
/* 4A48C 8006F08C A0251158 */  sb         $a1, %lo(D_800B1158)($at)
/* 4A490 8006F090 3C01800B */  lui        $at, %hi(D_800B1156)
/* 4A494 8006F094 A0261156 */  sb         $a2, %lo(D_800B1156)($at)
/* 4A498 8006F098 3C01800B */  lui        $at, %hi(D_800B1157)
/* 4A49C 8006F09C A0271157 */  sb         $a3, %lo(D_800B1157)($at)
/* 4A4A0 8006F0A0 24080001 */  addiu      $t0, $zero, 0x1
/* 4A4A4 8006F0A4 3C01800B */  lui        $at, %hi(D_800B1159)
/* 4A4A8 8006F0A8 A0281159 */  sb         $t0, %lo(D_800B1159)($at)
/* 4A4AC 8006F0AC 3C02800B */  lui        $v0, %hi(D_800B1150)
/* 4A4B0 8006F0B0 03E00008 */  jr         $ra
/* 4A4B4 8006F0B4 24421150 */   addiu     $v0, $v0, %lo(D_800B1150)

glabel func_8006F0B8
/* 4A4B8 8006F0B8 03E00008 */  jr         $ra
/* 4A4BC 8006F0BC 00000000 */   nop

glabel func_8006F0C0
/* 4A4C0 8006F0C0 03E00008 */  jr         $ra
/* 4A4C4 8006F0C4 00000000 */   nop

glabel func_8006F0C8
/* 4A4C8 8006F0C8 00047440 */  sll        $t6, $a0, 17
/* 4A4CC 8006F0CC 3C010800 */  lui        $at, (0x8000000 >> 16)
/* 4A4D0 8006F0D0 01C17821 */  addu       $t7, $t6, $at
/* 4A4D4 8006F0D4 3C01A000 */  lui        $at, (0xA0000000 >> 16)
/* 4A4D8 8006F0D8 01E1C025 */  or         $t8, $t7, $at
/* 4A4DC 8006F0DC 3C01800B */  lui        $at, %hi(D_800B115C)
/* 4A4E0 8006F0E0 AC38115C */  sw         $t8, %lo(D_800B115C)($at)
/* 4A4E4 8006F0E4 24990008 */  addiu      $t9, $a0, 0x8
/* 4A4E8 8006F0E8 3C01800B */  lui        $at, %hi(D_800B1154)
/* 4A4EC 8006F0EC A0391154 */  sb         $t9, %lo(D_800B1154)($at)
/* 4A4F0 8006F0F0 03E00008 */  jr         $ra
/* 4A4F4 8006F0F4 00000000 */   nop

glabel func_8006F0F8
/* 4A4F8 8006F0F8 03E00008 */  jr         $ra
/* 4A4FC 8006F0FC 00000000 */   nop

glabel func_8006F100
/* 4A500 8006F100 03E00008 */  jr         $ra
/* 4A504 8006F104 00000000 */   nop

glabel func_8006F108
/* 4A508 8006F108 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 4A50C 8006F10C AFBF0014 */  sw         $ra, 0x14($sp)
/* 4A510 8006F110 3C04800B */  lui        $a0, %hi(D_800B1138)
/* 4A514 8006F114 3C05800B */  lui        $a1, %hi(D_800B11C4)
/* 4A518 8006F118 24A511C4 */  addiu      $a1, $a1, %lo(D_800B11C4)
/* 4A51C 8006F11C 24841138 */  addiu      $a0, $a0, %lo(D_800B1138)
/* 4A520 8006F120 0C0195B8 */  jal        osCreateMesgQueue
/* 4A524 8006F124 24060001 */   addiu     $a2, $zero, 0x1
/* 4A528 8006F128 3C0E800B */  lui        $t6, %hi(D_800B115C)
/* 4A52C 8006F12C 8DCE115C */  lw         $t6, %lo(D_800B115C)($t6)
/* 4A530 8006F130 3C01A800 */  lui        $at, (0xA8000000 >> 16)
/* 4A534 8006F134 15C10004 */  bne        $t6, $at, .L8006F148
/* 4A538 8006F138 00000000 */   nop
/* 4A53C 8006F13C 3C02800B */  lui        $v0, %hi(D_800B1150)
/* 4A540 8006F140 1000003A */  b          .L8006F22C
/* 4A544 8006F144 24421150 */   addiu     $v0, $v0, %lo(D_800B1150)
.L8006F148:
/* 4A548 8006F148 240F0008 */  addiu      $t7, $zero, 0x8
/* 4A54C 8006F14C 3C01800B */  lui        $at, %hi(D_800B1154)
/* 4A550 8006F150 A02F1154 */  sb         $t7, %lo(D_800B1154)($at)
/* 4A554 8006F154 3C18A800 */  lui        $t8, (0xA8000000 >> 16)
/* 4A558 8006F158 3C01800B */  lui        $at, %hi(D_800B115C)
/* 4A55C 8006F15C AC38115C */  sw         $t8, %lo(D_800B115C)($at)
/* 4A560 8006F160 24190005 */  addiu      $t9, $zero, 0x5
/* 4A564 8006F164 3C01800B */  lui        $at, %hi(D_800B1155)
/* 4A568 8006F168 A0391155 */  sb         $t9, %lo(D_800B1155)($at)
/* 4A56C 8006F16C 2408000C */  addiu      $t0, $zero, 0xC
/* 4A570 8006F170 3C01800B */  lui        $at, %hi(D_800B1158)
/* 4A574 8006F174 A0281158 */  sb         $t0, %lo(D_800B1158)($at)
/* 4A578 8006F178 2409000F */  addiu      $t1, $zero, 0xF
/* 4A57C 8006F17C 3C01800B */  lui        $at, %hi(D_800B1156)
/* 4A580 8006F180 A0291156 */  sb         $t1, %lo(D_800B1156)($at)
/* 4A584 8006F184 240A0002 */  addiu      $t2, $zero, 0x2
/* 4A588 8006F188 3C01800B */  lui        $at, %hi(D_800B1157)
/* 4A58C 8006F18C A02A1157 */  sb         $t2, %lo(D_800B1157)($at)
/* 4A590 8006F190 240B0001 */  addiu      $t3, $zero, 0x1
/* 4A594 8006F194 3C01800B */  lui        $at, %hi(D_800B1159)
/* 4A598 8006F198 A02B1159 */  sb         $t3, %lo(D_800B1159)($at)
/* 4A59C 8006F19C 3C01800B */  lui        $at, %hi(D_800B1160)
/* 4A5A0 8006F1A0 AC201160 */  sw         $zero, %lo(D_800B1160)($at)
/* 4A5A4 8006F1A4 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A5A8 8006F1A8 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A5AC 8006F1AC 24840014 */  addiu      $a0, $a0, 0x14
/* 4A5B0 8006F1B0 0C0192B4 */  jal        bzero
/* 4A5B4 8006F1B4 24050060 */   addiu     $a1, $zero, 0x60
/* 4A5B8 8006F1B8 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A5BC 8006F1BC 0C018408 */  jal        osEPiLinkHandle
/* 4A5C0 8006F1C0 24841150 */   addiu     $a0, $a0, %lo(D_800B1150)
/* 4A5C4 8006F1C4 27A4001C */  addiu      $a0, $sp, 0x1C
/* 4A5C8 8006F1C8 0C01BCBC */  jal        func_8006F2F0
/* 4A5CC 8006F1CC 27A50018 */   addiu     $a1, $sp, 0x18
/* 4A5D0 8006F1D0 8FAC0018 */  lw         $t4, 0x18($sp)
/* 4A5D4 8006F1D4 3C0100C2 */  lui        $at, (0xC2001E >> 16)
/* 4A5D8 8006F1D8 3421001E */  ori        $at, $at, (0xC2001E & 0xFFFF)
/* 4A5DC 8006F1DC 11810008 */  beq        $t4, $at, .L8006F200
/* 4A5E0 8006F1E0 00000000 */   nop
/* 4A5E4 8006F1E4 3C0100C2 */  lui        $at, (0xC20001 >> 16)
/* 4A5E8 8006F1E8 34210001 */  ori        $at, $at, (0xC20001 & 0xFFFF)
/* 4A5EC 8006F1EC 11810004 */  beq        $t4, $at, .L8006F200
/* 4A5F0 8006F1F0 00000000 */   nop
/* 4A5F4 8006F1F4 3C0100C2 */  lui        $at, (0xC20000 >> 16)
/* 4A5F8 8006F1F8 15810004 */  bne        $t4, $at, .L8006F20C
/* 4A5FC 8006F1FC 00000000 */   nop
.L8006F200:
/* 4A600 8006F200 3C01800B */  lui        $at, %hi(D_800B11C8)
/* 4A604 8006F204 10000004 */  b          .L8006F218
/* 4A608 8006F208 AC2011C8 */   sw        $zero, %lo(D_800B11C8)($at)
.L8006F20C:
/* 4A60C 8006F20C 240D0001 */  addiu      $t5, $zero, 0x1
/* 4A610 8006F210 3C01800B */  lui        $at, %hi(D_800B11C8)
/* 4A614 8006F214 AC2D11C8 */  sw         $t5, %lo(D_800B11C8)($at)
.L8006F218:
/* 4A618 8006F218 3C02800B */  lui        $v0, %hi(D_800B1150)
/* 4A61C 8006F21C 10000003 */  b          .L8006F22C
/* 4A620 8006F220 24421150 */   addiu     $v0, $v0, %lo(D_800B1150)
/* 4A624 8006F224 10000001 */  b          .L8006F22C
/* 4A628 8006F228 00000000 */   nop
.L8006F22C:
/* 4A62C 8006F22C 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4A630 8006F230 27BD0020 */  addiu      $sp, $sp, 0x20
/* 4A634 8006F234 03E00008 */  jr         $ra
/* 4A638 8006F238 00000000 */   nop

glabel func_8006F23C
/* 4A63C 8006F23C 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 4A640 8006F240 AFBF0014 */  sw         $ra, 0x14($sp)
/* 4A644 8006F244 AFA40020 */  sw         $a0, 0x20($sp)
/* 4A648 8006F248 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A64C 8006F24C 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A650 8006F250 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A654 8006F254 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A658 8006F258 00A17025 */  or         $t6, $a1, $at
/* 4A65C 8006F25C 01C02825 */  or         $a1, $t6, $zero
/* 4A660 8006F260 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A664 8006F264 0C0183B0 */  jal        osEPiWriteIo
/* 4A668 8006F268 3C06D200 */   lui       $a2, (0xD2000000 >> 16)
/* 4A66C 8006F26C 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A670 8006F270 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A674 8006F274 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A678 8006F278 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A67C 8006F27C 0C0183C8 */  jal        osEPiReadIo
/* 4A680 8006F280 27A6001C */   addiu     $a2, $sp, 0x1C
/* 4A684 8006F284 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A688 8006F288 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A68C 8006F28C 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A690 8006F290 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A694 8006F294 00A17825 */  or         $t7, $a1, $at
/* 4A698 8006F298 01E02825 */  or         $a1, $t7, $zero
/* 4A69C 8006F29C 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A6A0 8006F2A0 0C0183B0 */  jal        osEPiWriteIo
/* 4A6A4 8006F2A4 3C06D200 */   lui       $a2, (0xD2000000 >> 16)
/* 4A6A8 8006F2A8 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A6AC 8006F2AC 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A6B0 8006F2B0 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A6B4 8006F2B4 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A6B8 8006F2B8 0C0183C8 */  jal        osEPiReadIo
/* 4A6BC 8006F2BC 27A6001C */   addiu     $a2, $sp, 0x1C
/* 4A6C0 8006F2C0 8FB8001C */  lw         $t8, 0x1C($sp)
/* 4A6C4 8006F2C4 8FA80020 */  lw         $t0, 0x20($sp)
/* 4A6C8 8006F2C8 331900FF */  andi       $t9, $t8, 0xFF
/* 4A6CC 8006F2CC A1190000 */  sb         $t9, 0x0($t0)
/* 4A6D0 8006F2D0 10000003 */  b          .L8006F2E0
/* 4A6D4 8006F2D4 00000000 */   nop
/* 4A6D8 8006F2D8 10000001 */  b          .L8006F2E0
/* 4A6DC 8006F2DC 00000000 */   nop
.L8006F2E0:
/* 4A6E0 8006F2E0 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4A6E4 8006F2E4 27BD0020 */  addiu      $sp, $sp, 0x20
/* 4A6E8 8006F2E8 03E00008 */  jr         $ra
/* 4A6EC 8006F2EC 00000000 */   nop

glabel func_8006F2F0
/* 4A6F0 8006F2F0 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 4A6F4 8006F2F4 AFBF0014 */  sw         $ra, 0x14($sp)
/* 4A6F8 8006F2F8 AFA40020 */  sw         $a0, 0x20($sp)
/* 4A6FC 8006F2FC AFA50024 */  sw         $a1, 0x24($sp)
/* 4A700 8006F300 0C01BC8F */  jal        func_8006F23C
/* 4A704 8006F304 27A4001F */   addiu     $a0, $sp, 0x1F
/* 4A708 8006F308 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A70C 8006F30C 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A710 8006F310 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A714 8006F314 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A718 8006F318 00A17025 */  or         $t6, $a1, $at
/* 4A71C 8006F31C 01C02825 */  or         $a1, $t6, $zero
/* 4A720 8006F320 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A724 8006F324 0C0183B0 */  jal        osEPiWriteIo
/* 4A728 8006F328 3C06E100 */   lui       $a2, (0xE1000000 >> 16)
/* 4A72C 8006F32C 3C01800B */  lui        $at, %hi(D_800B1122)
/* 4A730 8006F330 A0201122 */  sb         $zero, %lo(D_800B1122)($at)
/* 4A734 8006F334 3C0F800B */  lui        $t7, %hi(D_800B1138)
/* 4A738 8006F338 25EF1138 */  addiu      $t7, $t7, %lo(D_800B1138)
/* 4A73C 8006F33C 3C01800B */  lui        $at, %hi(D_800B1124)
/* 4A740 8006F340 AC2F1124 */  sw         $t7, %lo(D_800B1124)($at)
/* 4A744 8006F344 3C18800B */  lui        $t8, %hi(D_800B1110)
/* 4A748 8006F348 27181110 */  addiu      $t8, $t8, %lo(D_800B1110)
/* 4A74C 8006F34C 3C01800B */  lui        $at, %hi(D_800B1128)
/* 4A750 8006F350 AC381128 */  sw         $t8, %lo(D_800B1128)($at)
/* 4A754 8006F354 3C01800B */  lui        $at, %hi(D_800B112C)
/* 4A758 8006F358 AC20112C */  sw         $zero, %lo(D_800B112C)($at)
/* 4A75C 8006F35C 24190008 */  addiu      $t9, $zero, 0x8
/* 4A760 8006F360 3C01800B */  lui        $at, %hi(D_800B1130)
/* 4A764 8006F364 AC391130 */  sw         $t9, %lo(D_800B1130)($at)
/* 4A768 8006F368 3C04800B */  lui        $a0, %hi(D_800B1110)
/* 4A76C 8006F36C 24841110 */  addiu      $a0, $a0, %lo(D_800B1110)
/* 4A770 8006F370 0C018620 */  jal        osInvalDCache
/* 4A774 8006F374 24050010 */   addiu     $a1, $zero, 0x10
/* 4A778 8006F378 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A77C 8006F37C 3C05800B */  lui        $a1, %hi(D_800B1120)
/* 4A780 8006F380 24A51120 */  addiu      $a1, $a1, %lo(D_800B1120)
/* 4A784 8006F384 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A788 8006F388 0C0183E0 */  jal        osEPiStartDma
/* 4A78C 8006F38C 00003025 */   or        $a2, $zero, $zero
/* 4A790 8006F390 3C04800B */  lui        $a0, %hi(D_800B1138)
/* 4A794 8006F394 24841138 */  addiu      $a0, $a0, %lo(D_800B1138)
/* 4A798 8006F398 00002825 */  or         $a1, $zero, $zero
/* 4A79C 8006F39C 0C019614 */  jal        osRecvMesg
/* 4A7A0 8006F3A0 24060001 */   addiu     $a2, $zero, 0x1
/* 4A7A4 8006F3A4 3C08800B */  lui        $t0, %hi(D_800B1110)
/* 4A7A8 8006F3A8 25081110 */  addiu      $t0, $t0, %lo(D_800B1110)
/* 4A7AC 8006F3AC 8D090000 */  lw         $t1, 0x0($t0)
/* 4A7B0 8006F3B0 8FAA0020 */  lw         $t2, 0x20($sp)
/* 4A7B4 8006F3B4 00000000 */  nop
/* 4A7B8 8006F3B8 AD490000 */  sw         $t1, 0x0($t2)
/* 4A7BC 8006F3BC 3C0B800B */  lui        $t3, %hi(D_800B1110)
/* 4A7C0 8006F3C0 256B1110 */  addiu      $t3, $t3, %lo(D_800B1110)
/* 4A7C4 8006F3C4 8D6C0004 */  lw         $t4, 0x4($t3)
/* 4A7C8 8006F3C8 8FAD0024 */  lw         $t5, 0x24($sp)
/* 4A7CC 8006F3CC 00000000 */  nop
/* 4A7D0 8006F3D0 ADAC0000 */  sw         $t4, 0x0($t5)
/* 4A7D4 8006F3D4 10000003 */  b          .L8006F3E4
/* 4A7D8 8006F3D8 00000000 */   nop
/* 4A7DC 8006F3DC 10000001 */  b          .L8006F3E4
/* 4A7E0 8006F3E0 00000000 */   nop
.L8006F3E4:
/* 4A7E4 8006F3E4 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4A7E8 8006F3E8 27BD0020 */  addiu      $sp, $sp, 0x20
/* 4A7EC 8006F3EC 03E00008 */  jr         $ra
/* 4A7F0 8006F3F0 00000000 */   nop

glabel func_8006F3F4
/* 4A7F4 8006F3F4 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 4A7F8 8006F3F8 AFBF0014 */  sw         $ra, 0x14($sp)
/* 4A7FC 8006F3FC 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A800 8006F400 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A804 8006F404 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A808 8006F408 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A80C 8006F40C 00A17025 */  or         $t6, $a1, $at
/* 4A810 8006F410 01C02825 */  or         $a1, $t6, $zero
/* 4A814 8006F414 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A818 8006F418 0C0183B0 */  jal        osEPiWriteIo
/* 4A81C 8006F41C 3C06D200 */   lui       $a2, (0xD2000000 >> 16)
/* 4A820 8006F420 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A824 8006F424 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A828 8006F428 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A82C 8006F42C 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A830 8006F430 0C0183B0 */  jal        osEPiWriteIo
/* 4A834 8006F434 00003025 */   or        $a2, $zero, $zero
/* 4A838 8006F438 10000003 */  b          .L8006F448
/* 4A83C 8006F43C 00000000 */   nop
/* 4A840 8006F440 10000001 */  b          .L8006F448
/* 4A844 8006F444 00000000 */   nop
.L8006F448:
/* 4A848 8006F448 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4A84C 8006F44C 27BD0018 */  addiu      $sp, $sp, 0x18
/* 4A850 8006F450 03E00008 */  jr         $ra
/* 4A854 8006F454 00000000 */   nop

glabel func_8006F458
/* 4A858 8006F458 27BDFF90 */  addiu      $sp, $sp, -0x70
/* 4A85C 8006F45C AFBF0024 */  sw         $ra, 0x24($sp)
/* 4A860 8006F460 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A864 8006F464 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A868 8006F468 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A86C 8006F46C 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A870 8006F470 00A17025 */  or         $t6, $a1, $at
/* 4A874 8006F474 01C02825 */  or         $a1, $t6, $zero
/* 4A878 8006F478 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A87C 8006F47C 0C0183B0 */  jal        osEPiWriteIo
/* 4A880 8006F480 3C063C00 */   lui       $a2, (0x3C000000 >> 16)
/* 4A884 8006F484 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A888 8006F488 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A88C 8006F48C 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A890 8006F490 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A894 8006F494 00A17825 */  or         $t7, $a1, $at
/* 4A898 8006F498 01E02825 */  or         $a1, $t7, $zero
/* 4A89C 8006F49C 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A8A0 8006F4A0 0C0183B0 */  jal        osEPiWriteIo
/* 4A8A4 8006F4A4 3C067800 */   lui       $a2, (0x78000000 >> 16)
/* 4A8A8 8006F4A8 27A40030 */  addiu      $a0, $sp, 0x30
/* 4A8AC 8006F4AC 27A5002C */  addiu      $a1, $sp, 0x2C
/* 4A8B0 8006F4B0 0C0195B8 */  jal        osCreateMesgQueue
/* 4A8B4 8006F4B4 24060001 */   addiu     $a2, $zero, 0x1
.L8006F4B8:
/* 4A8B8 8006F4B8 3C07000A */  lui        $a3, (0xABA95 >> 16)
/* 4A8BC 8006F4BC 24180000 */  addiu      $t8, $zero, 0x0
/* 4A8C0 8006F4C0 24190000 */  addiu      $t9, $zero, 0x0
/* 4A8C4 8006F4C4 27A80030 */  addiu      $t0, $sp, 0x30
/* 4A8C8 8006F4C8 27A9002C */  addiu      $t1, $sp, 0x2C
/* 4A8CC 8006F4CC AFA9001C */  sw         $t1, 0x1C($sp)
/* 4A8D0 8006F4D0 AFA80018 */  sw         $t0, 0x18($sp)
/* 4A8D4 8006F4D4 AFB90014 */  sw         $t9, 0x14($sp)
/* 4A8D8 8006F4D8 AFB80010 */  sw         $t8, 0x10($sp)
/* 4A8DC 8006F4DC 34E7BA95 */  ori        $a3, $a3, (0xABA95 & 0xFFFF)
/* 4A8E0 8006F4E0 27A40048 */  addiu      $a0, $sp, 0x48
/* 4A8E4 8006F4E4 0C01992C */  jal        osSetTimer
/* 4A8E8 8006F4E8 24060000 */   addiu     $a2, $zero, 0x0
/* 4A8EC 8006F4EC 27A40030 */  addiu      $a0, $sp, 0x30
/* 4A8F0 8006F4F0 27A5002C */  addiu      $a1, $sp, 0x2C
/* 4A8F4 8006F4F4 0C019614 */  jal        osRecvMesg
/* 4A8F8 8006F4F8 24060001 */   addiu     $a2, $zero, 0x1
/* 4A8FC 8006F4FC 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A900 8006F500 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A904 8006F504 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A908 8006F508 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A90C 8006F50C 0C0183C8 */  jal        osEPiReadIo
/* 4A910 8006F510 27A6006C */   addiu     $a2, $sp, 0x6C
/* 4A914 8006F514 8FAA006C */  lw         $t2, 0x6C($sp)
/* 4A918 8006F518 24010002 */  addiu      $at, $zero, 0x2
/* 4A91C 8006F51C 314B0002 */  andi       $t3, $t2, 0x2
/* 4A920 8006F520 1161FFE5 */  beq        $t3, $at, .L8006F4B8
/* 4A924 8006F524 00000000 */   nop
/* 4A928 8006F528 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A92C 8006F52C 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A930 8006F530 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A934 8006F534 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A938 8006F538 0C0183C8 */  jal        osEPiReadIo
/* 4A93C 8006F53C 27A6006C */   addiu     $a2, $sp, 0x6C
/* 4A940 8006F540 0C01BCFD */  jal        func_8006F3F4
/* 4A944 8006F544 00000000 */   nop
/* 4A948 8006F548 8FAC006C */  lw         $t4, 0x6C($sp)
/* 4A94C 8006F54C 24010008 */  addiu      $at, $zero, 0x8
/* 4A950 8006F550 318D00FF */  andi       $t5, $t4, 0xFF
/* 4A954 8006F554 11A10008 */  beq        $t5, $at, .L8006F578
/* 4A958 8006F558 00000000 */   nop
/* 4A95C 8006F55C 24010048 */  addiu      $at, $zero, 0x48
/* 4A960 8006F560 11A10005 */  beq        $t5, $at, .L8006F578
/* 4A964 8006F564 00000000 */   nop
/* 4A968 8006F568 318E0008 */  andi       $t6, $t4, 0x8
/* 4A96C 8006F56C 24010008 */  addiu      $at, $zero, 0x8
/* 4A970 8006F570 15C10005 */  bne        $t6, $at, .L8006F588
/* 4A974 8006F574 00000000 */   nop
.L8006F578:
/* 4A978 8006F578 10000007 */  b          .L8006F598
/* 4A97C 8006F57C 00001025 */   or        $v0, $zero, $zero
/* 4A980 8006F580 10000003 */  b          .L8006F590
/* 4A984 8006F584 00000000 */   nop
.L8006F588:
/* 4A988 8006F588 10000003 */  b          .L8006F598
/* 4A98C 8006F58C 2402FFFF */   addiu     $v0, $zero, -0x1
.L8006F590:
/* 4A990 8006F590 10000001 */  b          .L8006F598
/* 4A994 8006F594 00000000 */   nop
.L8006F598:
/* 4A998 8006F598 8FBF0024 */  lw         $ra, 0x24($sp)
/* 4A99C 8006F59C 27BD0070 */  addiu      $sp, $sp, 0x70
/* 4A9A0 8006F5A0 03E00008 */  jr         $ra
/* 4A9A4 8006F5A4 00000000 */   nop

glabel func_8006F5A8
/* 4A9A8 8006F5A8 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 4A9AC 8006F5AC AFBF0014 */  sw         $ra, 0x14($sp)
/* 4A9B0 8006F5B0 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A9B4 8006F5B4 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A9B8 8006F5B8 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A9BC 8006F5BC 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A9C0 8006F5C0 00A17025 */  or         $t6, $a1, $at
/* 4A9C4 8006F5C4 01C02825 */  or         $a1, $t6, $zero
/* 4A9C8 8006F5C8 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A9CC 8006F5CC 0C0183B0 */  jal        osEPiWriteIo
/* 4A9D0 8006F5D0 3C063C00 */   lui       $a2, (0x3C000000 >> 16)
/* 4A9D4 8006F5D4 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4A9D8 8006F5D8 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4A9DC 8006F5DC 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4A9E0 8006F5E0 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4A9E4 8006F5E4 00A17825 */  or         $t7, $a1, $at
/* 4A9E8 8006F5E8 01E02825 */  or         $a1, $t7, $zero
/* 4A9EC 8006F5EC 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4A9F0 8006F5F0 0C0183B0 */  jal        osEPiWriteIo
/* 4A9F4 8006F5F4 3C067800 */   lui       $a2, (0x78000000 >> 16)
/* 4A9F8 8006F5F8 10000001 */  b          .L8006F600
/* 4A9FC 8006F5FC 00000000 */   nop
.L8006F600:
/* 4AA00 8006F600 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4AA04 8006F604 27BD0018 */  addiu      $sp, $sp, 0x18
/* 4AA08 8006F608 03E00008 */  jr         $ra
/* 4AA0C 8006F60C 00000000 */   nop

glabel func_8006F610
/* 4AA10 8006F610 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 4AA14 8006F614 AFBF0014 */  sw         $ra, 0x14($sp)
/* 4AA18 8006F618 0C01BC8F */  jal        func_8006F23C
/* 4AA1C 8006F61C 27A4001F */   addiu     $a0, $sp, 0x1F
/* 4AA20 8006F620 93AE001F */  lbu        $t6, 0x1F($sp)
/* 4AA24 8006F624 24010002 */  addiu      $at, $zero, 0x2
/* 4AA28 8006F628 31CF0002 */  andi       $t7, $t6, 0x2
/* 4AA2C 8006F62C 15E10005 */  bne        $t7, $at, .L8006F644
/* 4AA30 8006F630 00000000 */   nop
/* 4AA34 8006F634 1000001B */  b          .L8006F6A4
/* 4AA38 8006F638 24020002 */   addiu     $v0, $zero, 0x2
/* 4AA3C 8006F63C 10000003 */  b          .L8006F64C
/* 4AA40 8006F640 00000000 */   nop
.L8006F644:
/* 4AA44 8006F644 0C01BC8F */  jal        func_8006F23C
/* 4AA48 8006F648 27A4001F */   addiu     $a0, $sp, 0x1F
.L8006F64C:
/* 4AA4C 8006F64C 0C01BCFD */  jal        func_8006F3F4
/* 4AA50 8006F650 00000000 */   nop
/* 4AA54 8006F654 93B8001F */  lbu        $t8, 0x1F($sp)
/* 4AA58 8006F658 24010008 */  addiu      $at, $zero, 0x8
/* 4AA5C 8006F65C 331900FF */  andi       $t9, $t8, 0xFF
/* 4AA60 8006F660 13210008 */  beq        $t9, $at, .L8006F684
/* 4AA64 8006F664 00000000 */   nop
/* 4AA68 8006F668 24010048 */  addiu      $at, $zero, 0x48
/* 4AA6C 8006F66C 13210005 */  beq        $t9, $at, .L8006F684
/* 4AA70 8006F670 00000000 */   nop
/* 4AA74 8006F674 33080008 */  andi       $t0, $t8, 0x8
/* 4AA78 8006F678 24010008 */  addiu      $at, $zero, 0x8
/* 4AA7C 8006F67C 15010005 */  bne        $t0, $at, .L8006F694
/* 4AA80 8006F680 00000000 */   nop
.L8006F684:
/* 4AA84 8006F684 10000007 */  b          .L8006F6A4
/* 4AA88 8006F688 00001025 */   or        $v0, $zero, $zero
/* 4AA8C 8006F68C 10000003 */  b          .L8006F69C
/* 4AA90 8006F690 00000000 */   nop
.L8006F694:
/* 4AA94 8006F694 10000003 */  b          .L8006F6A4
/* 4AA98 8006F698 2402FFFF */   addiu     $v0, $zero, -0x1
.L8006F69C:
/* 4AA9C 8006F69C 10000001 */  b          .L8006F6A4
/* 4AAA0 8006F6A0 00000000 */   nop
.L8006F6A4:
/* 4AAA4 8006F6A4 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4AAA8 8006F6A8 27BD0020 */  addiu      $sp, $sp, 0x20
/* 4AAAC 8006F6AC 03E00008 */  jr         $ra
/* 4AAB0 8006F6B0 00000000 */   nop

glabel func_8006F6B4
/* 4AAB4 8006F6B4 27BDFF90 */  addiu      $sp, $sp, -0x70
/* 4AAB8 8006F6B8 AFBF0024 */  sw         $ra, 0x24($sp)
/* 4AABC 8006F6BC AFA40070 */  sw         $a0, 0x70($sp)
/* 4AAC0 8006F6C0 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AAC4 8006F6C4 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AAC8 8006F6C8 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4AACC 8006F6CC 8FA60070 */  lw         $a2, 0x70($sp)
/* 4AAD0 8006F6D0 00A17025 */  or         $t6, $a1, $at
/* 4AAD4 8006F6D4 3C014B00 */  lui        $at, (0x4B000000 >> 16)
/* 4AAD8 8006F6D8 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AADC 8006F6DC 00C17825 */  or         $t7, $a2, $at
/* 4AAE0 8006F6E0 01E03025 */  or         $a2, $t7, $zero
/* 4AAE4 8006F6E4 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AAE8 8006F6E8 0C0183B0 */  jal        osEPiWriteIo
/* 4AAEC 8006F6EC 01C02825 */   or        $a1, $t6, $zero
/* 4AAF0 8006F6F0 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AAF4 8006F6F4 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AAF8 8006F6F8 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4AAFC 8006F6FC 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AB00 8006F700 00A1C025 */  or         $t8, $a1, $at
/* 4AB04 8006F704 03002825 */  or         $a1, $t8, $zero
/* 4AB08 8006F708 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AB0C 8006F70C 0C0183B0 */  jal        osEPiWriteIo
/* 4AB10 8006F710 3C067800 */   lui       $a2, (0x78000000 >> 16)
/* 4AB14 8006F714 27A40030 */  addiu      $a0, $sp, 0x30
/* 4AB18 8006F718 27A5002C */  addiu      $a1, $sp, 0x2C
/* 4AB1C 8006F71C 0C0195B8 */  jal        osCreateMesgQueue
/* 4AB20 8006F720 24060001 */   addiu     $a2, $zero, 0x1
.L8006F724:
/* 4AB24 8006F724 3C070008 */  lui        $a3, (0x8F0D1 >> 16)
/* 4AB28 8006F728 24080000 */  addiu      $t0, $zero, 0x0
/* 4AB2C 8006F72C 24090000 */  addiu      $t1, $zero, 0x0
/* 4AB30 8006F730 27B90030 */  addiu      $t9, $sp, 0x30
/* 4AB34 8006F734 27AA002C */  addiu      $t2, $sp, 0x2C
/* 4AB38 8006F738 AFAA001C */  sw         $t2, 0x1C($sp)
/* 4AB3C 8006F73C AFB90018 */  sw         $t9, 0x18($sp)
/* 4AB40 8006F740 AFA90014 */  sw         $t1, 0x14($sp)
/* 4AB44 8006F744 AFA80010 */  sw         $t0, 0x10($sp)
/* 4AB48 8006F748 34E7F0D1 */  ori        $a3, $a3, (0x8F0D1 & 0xFFFF)
/* 4AB4C 8006F74C 27A40048 */  addiu      $a0, $sp, 0x48
/* 4AB50 8006F750 0C01992C */  jal        osSetTimer
/* 4AB54 8006F754 24060000 */   addiu     $a2, $zero, 0x0
/* 4AB58 8006F758 27A40030 */  addiu      $a0, $sp, 0x30
/* 4AB5C 8006F75C 27A5002C */  addiu      $a1, $sp, 0x2C
/* 4AB60 8006F760 0C019614 */  jal        osRecvMesg
/* 4AB64 8006F764 24060001 */   addiu     $a2, $zero, 0x1
/* 4AB68 8006F768 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AB6C 8006F76C 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AB70 8006F770 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AB74 8006F774 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AB78 8006F778 0C0183C8 */  jal        osEPiReadIo
/* 4AB7C 8006F77C 27A6006C */   addiu     $a2, $sp, 0x6C
/* 4AB80 8006F780 8FAB006C */  lw         $t3, 0x6C($sp)
/* 4AB84 8006F784 24010002 */  addiu      $at, $zero, 0x2
/* 4AB88 8006F788 316C0002 */  andi       $t4, $t3, 0x2
/* 4AB8C 8006F78C 1181FFE5 */  beq        $t4, $at, .L8006F724
/* 4AB90 8006F790 00000000 */   nop
/* 4AB94 8006F794 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AB98 8006F798 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AB9C 8006F79C 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4ABA0 8006F7A0 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4ABA4 8006F7A4 0C0183C8 */  jal        osEPiReadIo
/* 4ABA8 8006F7A8 27A6006C */   addiu     $a2, $sp, 0x6C
/* 4ABAC 8006F7AC 0C01BCFD */  jal        func_8006F3F4
/* 4ABB0 8006F7B0 00000000 */   nop
/* 4ABB4 8006F7B4 8FAD006C */  lw         $t5, 0x6C($sp)
/* 4ABB8 8006F7B8 24010008 */  addiu      $at, $zero, 0x8
/* 4ABBC 8006F7BC 31AE00FF */  andi       $t6, $t5, 0xFF
/* 4ABC0 8006F7C0 11C10008 */  beq        $t6, $at, .L8006F7E4
/* 4ABC4 8006F7C4 00000000 */   nop
/* 4ABC8 8006F7C8 24010048 */  addiu      $at, $zero, 0x48
/* 4ABCC 8006F7CC 11C10005 */  beq        $t6, $at, .L8006F7E4
/* 4ABD0 8006F7D0 00000000 */   nop
/* 4ABD4 8006F7D4 31AF0008 */  andi       $t7, $t5, 0x8
/* 4ABD8 8006F7D8 24010008 */  addiu      $at, $zero, 0x8
/* 4ABDC 8006F7DC 15E10005 */  bne        $t7, $at, .L8006F7F4
/* 4ABE0 8006F7E0 00000000 */   nop
.L8006F7E4:
/* 4ABE4 8006F7E4 10000007 */  b          .L8006F804
/* 4ABE8 8006F7E8 00001025 */   or        $v0, $zero, $zero
/* 4ABEC 8006F7EC 10000003 */  b          .L8006F7FC
/* 4ABF0 8006F7F0 00000000 */   nop
.L8006F7F4:
/* 4ABF4 8006F7F4 10000003 */  b          .L8006F804
/* 4ABF8 8006F7F8 2402FFFF */   addiu     $v0, $zero, -0x1
.L8006F7FC:
/* 4ABFC 8006F7FC 10000001 */  b          .L8006F804
/* 4AC00 8006F800 00000000 */   nop
.L8006F804:
/* 4AC04 8006F804 8FBF0024 */  lw         $ra, 0x24($sp)
/* 4AC08 8006F808 27BD0070 */  addiu      $sp, $sp, 0x70
/* 4AC0C 8006F80C 03E00008 */  jr         $ra
/* 4AC10 8006F810 00000000 */   nop

glabel func_8006F814
/* 4AC14 8006F814 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 4AC18 8006F818 AFBF0014 */  sw         $ra, 0x14($sp)
/* 4AC1C 8006F81C AFA40018 */  sw         $a0, 0x18($sp)
/* 4AC20 8006F820 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AC24 8006F824 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AC28 8006F828 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4AC2C 8006F82C 8FA60018 */  lw         $a2, 0x18($sp)
/* 4AC30 8006F830 00A17025 */  or         $t6, $a1, $at
/* 4AC34 8006F834 3C014B00 */  lui        $at, (0x4B000000 >> 16)
/* 4AC38 8006F838 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AC3C 8006F83C 00C17825 */  or         $t7, $a2, $at
/* 4AC40 8006F840 01E03025 */  or         $a2, $t7, $zero
/* 4AC44 8006F844 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AC48 8006F848 0C0183B0 */  jal        osEPiWriteIo
/* 4AC4C 8006F84C 01C02825 */   or        $a1, $t6, $zero
/* 4AC50 8006F850 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AC54 8006F854 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AC58 8006F858 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4AC5C 8006F85C 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AC60 8006F860 00A1C025 */  or         $t8, $a1, $at
/* 4AC64 8006F864 03002825 */  or         $a1, $t8, $zero
/* 4AC68 8006F868 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AC6C 8006F86C 0C0183B0 */  jal        osEPiWriteIo
/* 4AC70 8006F870 3C067800 */   lui       $a2, (0x78000000 >> 16)
/* 4AC74 8006F874 10000001 */  b          .L8006F87C
/* 4AC78 8006F878 00000000 */   nop
.L8006F87C:
/* 4AC7C 8006F87C 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4AC80 8006F880 27BD0018 */  addiu      $sp, $sp, 0x18
/* 4AC84 8006F884 03E00008 */  jr         $ra
/* 4AC88 8006F888 00000000 */   nop

glabel func_8006F88C
/* 4AC8C 8006F88C 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 4AC90 8006F890 AFBF0014 */  sw         $ra, 0x14($sp)
/* 4AC94 8006F894 AFA40020 */  sw         $a0, 0x20($sp)
/* 4AC98 8006F898 AFA50024 */  sw         $a1, 0x24($sp)
/* 4AC9C 8006F89C AFA60028 */  sw         $a2, 0x28($sp)
/* 4ACA0 8006F8A0 AFA7002C */  sw         $a3, 0x2C($sp)
/* 4ACA4 8006F8A4 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4ACA8 8006F8A8 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4ACAC 8006F8AC 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4ACB0 8006F8B0 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4ACB4 8006F8B4 00A17025 */  or         $t6, $a1, $at
/* 4ACB8 8006F8B8 01C02825 */  or         $a1, $t6, $zero
/* 4ACBC 8006F8BC 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4ACC0 8006F8C0 0C0183B0 */  jal        osEPiWriteIo
/* 4ACC4 8006F8C4 3C06B400 */   lui       $a2, (0xB4000000 >> 16)
/* 4ACC8 8006F8C8 8FAF0024 */  lw         $t7, 0x24($sp)
/* 4ACCC 8006F8CC 8FB80020 */  lw         $t8, 0x20($sp)
/* 4ACD0 8006F8D0 00000000 */  nop
/* 4ACD4 8006F8D4 A30F0002 */  sb         $t7, 0x2($t8)
/* 4ACD8 8006F8D8 8FB9002C */  lw         $t9, 0x2C($sp)
/* 4ACDC 8006F8DC 8FA80020 */  lw         $t0, 0x20($sp)
/* 4ACE0 8006F8E0 00000000 */  nop
/* 4ACE4 8006F8E4 AD190004 */  sw         $t9, 0x4($t0)
/* 4ACE8 8006F8E8 8FA90028 */  lw         $t1, 0x28($sp)
/* 4ACEC 8006F8EC 8FAA0020 */  lw         $t2, 0x20($sp)
/* 4ACF0 8006F8F0 00000000 */  nop
/* 4ACF4 8006F8F4 AD490008 */  sw         $t1, 0x8($t2)
/* 4ACF8 8006F8F8 8FAB0020 */  lw         $t3, 0x20($sp)
/* 4ACFC 8006F8FC 00000000 */  nop
/* 4AD00 8006F900 AD60000C */  sw         $zero, 0xC($t3)
/* 4AD04 8006F904 8FAD0020 */  lw         $t5, 0x20($sp)
/* 4AD08 8006F908 240C0080 */  addiu      $t4, $zero, 0x80
/* 4AD0C 8006F90C ADAC0010 */  sw         $t4, 0x10($t5)
/* 4AD10 8006F910 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AD14 8006F914 8FA50020 */  lw         $a1, 0x20($sp)
/* 4AD18 8006F918 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AD1C 8006F91C 0C0183E0 */  jal        osEPiStartDma
/* 4AD20 8006F920 24060001 */   addiu     $a2, $zero, 0x1
/* 4AD24 8006F924 AFA2001C */  sw         $v0, 0x1C($sp)
/* 4AD28 8006F928 8FA2001C */  lw         $v0, 0x1C($sp)
/* 4AD2C 8006F92C 10000003 */  b          .L8006F93C
/* 4AD30 8006F930 00000000 */   nop
/* 4AD34 8006F934 10000001 */  b          .L8006F93C
/* 4AD38 8006F938 00000000 */   nop
.L8006F93C:
/* 4AD3C 8006F93C 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4AD40 8006F940 27BD0020 */  addiu      $sp, $sp, 0x20
/* 4AD44 8006F944 03E00008 */  jr         $ra
/* 4AD48 8006F948 00000000 */   nop

glabel func_8006F94C
/* 4AD4C 8006F94C 27BDFF90 */  addiu      $sp, $sp, -0x70
/* 4AD50 8006F950 AFBF0024 */  sw         $ra, 0x24($sp)
/* 4AD54 8006F954 AFA40070 */  sw         $a0, 0x70($sp)
/* 4AD58 8006F958 3C0E800B */  lui        $t6, %hi(D_800B11C8)
/* 4AD5C 8006F95C 8DCE11C8 */  lw         $t6, %lo(D_800B11C8)($t6)
/* 4AD60 8006F960 24010001 */  addiu      $at, $zero, 0x1
/* 4AD64 8006F964 15C1000A */  bne        $t6, $at, .L8006F990
/* 4AD68 8006F968 00000000 */   nop
/* 4AD6C 8006F96C 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AD70 8006F970 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AD74 8006F974 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4AD78 8006F978 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AD7C 8006F97C 00A17825 */  or         $t7, $a1, $at
/* 4AD80 8006F980 01E02825 */  or         $a1, $t7, $zero
/* 4AD84 8006F984 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AD88 8006F988 0C0183B0 */  jal        osEPiWriteIo
/* 4AD8C 8006F98C 3C06B400 */   lui       $a2, (0xB4000000 >> 16)
.L8006F990:
/* 4AD90 8006F990 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AD94 8006F994 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AD98 8006F998 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4AD9C 8006F99C 8FA60070 */  lw         $a2, 0x70($sp)
/* 4ADA0 8006F9A0 00A1C025 */  or         $t8, $a1, $at
/* 4ADA4 8006F9A4 3C01A500 */  lui        $at, (0xA5000000 >> 16)
/* 4ADA8 8006F9A8 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4ADAC 8006F9AC 00C1C825 */  or         $t9, $a2, $at
/* 4ADB0 8006F9B0 03203025 */  or         $a2, $t9, $zero
/* 4ADB4 8006F9B4 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4ADB8 8006F9B8 0C0183B0 */  jal        osEPiWriteIo
/* 4ADBC 8006F9BC 03002825 */   or        $a1, $t8, $zero
/* 4ADC0 8006F9C0 27A40030 */  addiu      $a0, $sp, 0x30
/* 4ADC4 8006F9C4 27A5002C */  addiu      $a1, $sp, 0x2C
/* 4ADC8 8006F9C8 0C0195B8 */  jal        osCreateMesgQueue
/* 4ADCC 8006F9CC 24060001 */   addiu     $a2, $zero, 0x1
.L8006F9D0:
/* 4ADD0 8006F9D0 24080000 */  addiu      $t0, $zero, 0x0
/* 4ADD4 8006F9D4 24090000 */  addiu      $t1, $zero, 0x0
/* 4ADD8 8006F9D8 27AA0030 */  addiu      $t2, $sp, 0x30
/* 4ADDC 8006F9DC 27AB002C */  addiu      $t3, $sp, 0x2C
/* 4ADE0 8006F9E0 AFAB001C */  sw         $t3, 0x1C($sp)
/* 4ADE4 8006F9E4 AFAA0018 */  sw         $t2, 0x18($sp)
/* 4ADE8 8006F9E8 AFA90014 */  sw         $t1, 0x14($sp)
/* 4ADEC 8006F9EC AFA80010 */  sw         $t0, 0x10($sp)
/* 4ADF0 8006F9F0 27A40048 */  addiu      $a0, $sp, 0x48
/* 4ADF4 8006F9F4 24060000 */  addiu      $a2, $zero, 0x0
/* 4ADF8 8006F9F8 0C01992C */  jal        osSetTimer
/* 4ADFC 8006F9FC 2407249F */   addiu     $a3, $zero, 0x249F
/* 4AE00 8006FA00 27A40030 */  addiu      $a0, $sp, 0x30
/* 4AE04 8006FA04 27A5002C */  addiu      $a1, $sp, 0x2C
/* 4AE08 8006FA08 0C019614 */  jal        osRecvMesg
/* 4AE0C 8006FA0C 24060001 */   addiu     $a2, $zero, 0x1
/* 4AE10 8006FA10 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AE14 8006FA14 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AE18 8006FA18 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AE1C 8006FA1C 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AE20 8006FA20 0C0183C8 */  jal        osEPiReadIo
/* 4AE24 8006FA24 27A6006C */   addiu     $a2, $sp, 0x6C
/* 4AE28 8006FA28 8FAC006C */  lw         $t4, 0x6C($sp)
/* 4AE2C 8006FA2C 24010001 */  addiu      $at, $zero, 0x1
/* 4AE30 8006FA30 318D0001 */  andi       $t5, $t4, 0x1
/* 4AE34 8006FA34 11A1FFE6 */  beq        $t5, $at, .L8006F9D0
/* 4AE38 8006FA38 00000000 */   nop
/* 4AE3C 8006FA3C 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AE40 8006FA40 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AE44 8006FA44 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AE48 8006FA48 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AE4C 8006FA4C 0C0183C8 */  jal        osEPiReadIo
/* 4AE50 8006FA50 27A6006C */   addiu     $a2, $sp, 0x6C
/* 4AE54 8006FA54 0C01BCFD */  jal        func_8006F3F4
/* 4AE58 8006FA58 00000000 */   nop
/* 4AE5C 8006FA5C 8FAE006C */  lw         $t6, 0x6C($sp)
/* 4AE60 8006FA60 24010004 */  addiu      $at, $zero, 0x4
/* 4AE64 8006FA64 31CF00FF */  andi       $t7, $t6, 0xFF
/* 4AE68 8006FA68 11E10008 */  beq        $t7, $at, .L8006FA8C
/* 4AE6C 8006FA6C 00000000 */   nop
/* 4AE70 8006FA70 24010044 */  addiu      $at, $zero, 0x44
/* 4AE74 8006FA74 11E10005 */  beq        $t7, $at, .L8006FA8C
/* 4AE78 8006FA78 00000000 */   nop
/* 4AE7C 8006FA7C 31D80004 */  andi       $t8, $t6, 0x4
/* 4AE80 8006FA80 24010004 */  addiu      $at, $zero, 0x4
/* 4AE84 8006FA84 17010005 */  bne        $t8, $at, .L8006FA9C
/* 4AE88 8006FA88 00000000 */   nop
.L8006FA8C:
/* 4AE8C 8006FA8C 10000007 */  b          .L8006FAAC
/* 4AE90 8006FA90 00001025 */   or        $v0, $zero, $zero
/* 4AE94 8006FA94 10000003 */  b          .L8006FAA4
/* 4AE98 8006FA98 00000000 */   nop
.L8006FA9C:
/* 4AE9C 8006FA9C 10000003 */  b          .L8006FAAC
/* 4AEA0 8006FAA0 2402FFFF */   addiu     $v0, $zero, -0x1
.L8006FAA4:
/* 4AEA4 8006FAA4 10000001 */  b          .L8006FAAC
/* 4AEA8 8006FAA8 00000000 */   nop
.L8006FAAC:
/* 4AEAC 8006FAAC 8FBF0024 */  lw         $ra, 0x24($sp)
/* 4AEB0 8006FAB0 27BD0070 */  addiu      $sp, $sp, 0x70
/* 4AEB4 8006FAB4 03E00008 */  jr         $ra
/* 4AEB8 8006FAB8 00000000 */   nop

glabel func_8006FABC
/* 4AEBC 8006FABC 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 4AEC0 8006FAC0 AFBF0014 */  sw         $ra, 0x14($sp)
/* 4AEC4 8006FAC4 AFA40028 */  sw         $a0, 0x28($sp)
/* 4AEC8 8006FAC8 AFA5002C */  sw         $a1, 0x2C($sp)
/* 4AECC 8006FACC AFA60030 */  sw         $a2, 0x30($sp)
/* 4AED0 8006FAD0 AFA70034 */  sw         $a3, 0x34($sp)
/* 4AED4 8006FAD4 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AED8 8006FAD8 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AEDC 8006FADC 3C010001 */  lui        $at, (0x10000 >> 16)
/* 4AEE0 8006FAE0 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AEE4 8006FAE4 00A17025 */  or         $t6, $a1, $at
/* 4AEE8 8006FAE8 01C02825 */  or         $a1, $t6, $zero
/* 4AEEC 8006FAEC 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AEF0 8006FAF0 0C0183B0 */  jal        osEPiWriteIo
/* 4AEF4 8006FAF4 3C06F000 */   lui       $a2, (0xF0000000 >> 16)
/* 4AEF8 8006FAF8 3C05800B */  lui        $a1, %hi(D_800B115C)
/* 4AEFC 8006FAFC 8CA5115C */  lw         $a1, %lo(D_800B115C)($a1)
/* 4AF00 8006FB00 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AF04 8006FB04 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AF08 8006FB08 0C0183C8 */  jal        osEPiReadIo
/* 4AF0C 8006FB0C 27A60020 */   addiu     $a2, $sp, 0x20
/* 4AF10 8006FB10 8FAF002C */  lw         $t7, 0x2C($sp)
/* 4AF14 8006FB14 8FB80028 */  lw         $t8, 0x28($sp)
/* 4AF18 8006FB18 00000000 */  nop
/* 4AF1C 8006FB1C A30F0002 */  sb         $t7, 0x2($t8)
/* 4AF20 8006FB20 8FB9003C */  lw         $t9, 0x3C($sp)
/* 4AF24 8006FB24 8FA80028 */  lw         $t0, 0x28($sp)
/* 4AF28 8006FB28 00000000 */  nop
/* 4AF2C 8006FB2C AD190004 */  sw         $t9, 0x4($t0)
/* 4AF30 8006FB30 8FA90034 */  lw         $t1, 0x34($sp)
/* 4AF34 8006FB34 8FAA0028 */  lw         $t2, 0x28($sp)
/* 4AF38 8006FB38 00000000 */  nop
/* 4AF3C 8006FB3C AD490008 */  sw         $t1, 0x8($t2)
/* 4AF40 8006FB40 8FAB0030 */  lw         $t3, 0x30($sp)
/* 4AF44 8006FB44 8FAC0038 */  lw         $t4, 0x38($sp)
/* 4AF48 8006FB48 00000000 */  nop
/* 4AF4C 8006FB4C 016C6821 */  addu       $t5, $t3, $t4
/* 4AF50 8006FB50 25AEFFFF */  addiu      $t6, $t5, -0x1
/* 4AF54 8006FB54 AFAE001C */  sw         $t6, 0x1C($sp)
/* 4AF58 8006FB58 8FAF001C */  lw         $t7, 0x1C($sp)
/* 4AF5C 8006FB5C 8FB90030 */  lw         $t9, 0x30($sp)
/* 4AF60 8006FB60 31F80F00 */  andi       $t8, $t7, 0xF00
/* 4AF64 8006FB64 33280F00 */  andi       $t0, $t9, 0xF00
/* 4AF68 8006FB68 1308002A */  beq        $t8, $t0, .L8006FC14
/* 4AF6C 8006FB6C 00000000 */   nop
/* 4AF70 8006FB70 8FA90030 */  lw         $t1, 0x30($sp)
/* 4AF74 8006FB74 240B0100 */  addiu      $t3, $zero, 0x100
/* 4AF78 8006FB78 312A00FF */  andi       $t2, $t1, 0xFF
/* 4AF7C 8006FB7C 016A6023 */  subu       $t4, $t3, $t2
/* 4AF80 8006FB80 AFAC0018 */  sw         $t4, 0x18($sp)
/* 4AF84 8006FB84 8FAD0038 */  lw         $t5, 0x38($sp)
/* 4AF88 8006FB88 8FAE0018 */  lw         $t6, 0x18($sp)
/* 4AF8C 8006FB8C 00000000 */  nop
/* 4AF90 8006FB90 01AE7823 */  subu       $t7, $t5, $t6
/* 4AF94 8006FB94 AFAF0038 */  sw         $t7, 0x38($sp)
/* 4AF98 8006FB98 8FB90018 */  lw         $t9, 0x18($sp)
/* 4AF9C 8006FB9C 8FA80028 */  lw         $t0, 0x28($sp)
/* 4AFA0 8006FBA0 0019C1C0 */  sll        $t8, $t9, 7
/* 4AFA4 8006FBA4 AD180010 */  sw         $t8, 0x10($t0)
/* 4AFA8 8006FBA8 8FA40030 */  lw         $a0, 0x30($sp)
/* 4AFAC 8006FBAC 0C01BC00 */  jal        func_8006F000
/* 4AFB0 8006FBB0 00000000 */   nop
/* 4AFB4 8006FBB4 8FA90028 */  lw         $t1, 0x28($sp)
/* 4AFB8 8006FBB8 00000000 */  nop
/* 4AFBC 8006FBBC AD22000C */  sw         $v0, 0xC($t1)
/* 4AFC0 8006FBC0 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4AFC4 8006FBC4 8FA50028 */  lw         $a1, 0x28($sp)
/* 4AFC8 8006FBC8 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4AFCC 8006FBCC 0C0183E0 */  jal        osEPiStartDma
/* 4AFD0 8006FBD0 00003025 */   or        $a2, $zero, $zero
/* 4AFD4 8006FBD4 8FA4003C */  lw         $a0, 0x3C($sp)
/* 4AFD8 8006FBD8 00002825 */  or         $a1, $zero, $zero
/* 4AFDC 8006FBDC 0C019614 */  jal        osRecvMesg
/* 4AFE0 8006FBE0 24060001 */   addiu     $a2, $zero, 0x1
/* 4AFE4 8006FBE4 8FAB0030 */  lw         $t3, 0x30($sp)
/* 4AFE8 8006FBE8 00000000 */  nop
/* 4AFEC 8006FBEC 256A0100 */  addiu      $t2, $t3, 0x100
/* 4AFF0 8006FBF0 314C0F00 */  andi       $t4, $t2, 0xF00
/* 4AFF4 8006FBF4 AFAC0030 */  sw         $t4, 0x30($sp)
/* 4AFF8 8006FBF8 8FAD0028 */  lw         $t5, 0x28($sp)
/* 4AFFC 8006FBFC 00000000 */  nop
/* 4B000 8006FC00 8DAE0008 */  lw         $t6, 0x8($t5)
/* 4B004 8006FC04 8DAF0010 */  lw         $t7, 0x10($t5)
/* 4B008 8006FC08 00000000 */  nop
/* 4B00C 8006FC0C 01CFC821 */  addu       $t9, $t6, $t7
/* 4B010 8006FC10 ADB90008 */  sw         $t9, 0x8($t5)
.L8006FC14:
/* 4B014 8006FC14 8FB80038 */  lw         $t8, 0x38($sp)
/* 4B018 8006FC18 00000000 */  nop
/* 4B01C 8006FC1C 2F010101 */  sltiu      $at, $t8, 0x101
/* 4B020 8006FC20 1420002A */  bnez       $at, .L8006FCCC
/* 4B024 8006FC24 00000000 */   nop
.L8006FC28:
/* 4B028 8006FC28 24080100 */  addiu      $t0, $zero, 0x100
/* 4B02C 8006FC2C AFA80018 */  sw         $t0, 0x18($sp)
/* 4B030 8006FC30 8FA90038 */  lw         $t1, 0x38($sp)
/* 4B034 8006FC34 00000000 */  nop
/* 4B038 8006FC38 252BFF00 */  addiu      $t3, $t1, -0x100
/* 4B03C 8006FC3C AFAB0038 */  sw         $t3, 0x38($sp)
/* 4B040 8006FC40 8FAA0018 */  lw         $t2, 0x18($sp)
/* 4B044 8006FC44 8FAE0028 */  lw         $t6, 0x28($sp)
/* 4B048 8006FC48 000A61C0 */  sll        $t4, $t2, 7
/* 4B04C 8006FC4C ADCC0010 */  sw         $t4, 0x10($t6)
/* 4B050 8006FC50 8FA40030 */  lw         $a0, 0x30($sp)
/* 4B054 8006FC54 0C01BC00 */  jal        func_8006F000
/* 4B058 8006FC58 00000000 */   nop
/* 4B05C 8006FC5C 8FAF0028 */  lw         $t7, 0x28($sp)
/* 4B060 8006FC60 00000000 */  nop
/* 4B064 8006FC64 ADE2000C */  sw         $v0, 0xC($t7)
/* 4B068 8006FC68 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4B06C 8006FC6C 8FA50028 */  lw         $a1, 0x28($sp)
/* 4B070 8006FC70 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4B074 8006FC74 0C0183E0 */  jal        osEPiStartDma
/* 4B078 8006FC78 00003025 */   or        $a2, $zero, $zero
/* 4B07C 8006FC7C 8FA4003C */  lw         $a0, 0x3C($sp)
/* 4B080 8006FC80 00002825 */  or         $a1, $zero, $zero
/* 4B084 8006FC84 0C019614 */  jal        osRecvMesg
/* 4B088 8006FC88 24060001 */   addiu     $a2, $zero, 0x1
/* 4B08C 8006FC8C 8FB90030 */  lw         $t9, 0x30($sp)
/* 4B090 8006FC90 00000000 */  nop
/* 4B094 8006FC94 272D0100 */  addiu      $t5, $t9, 0x100
/* 4B098 8006FC98 AFAD0030 */  sw         $t5, 0x30($sp)
/* 4B09C 8006FC9C 8FB80028 */  lw         $t8, 0x28($sp)
/* 4B0A0 8006FCA0 00000000 */  nop
/* 4B0A4 8006FCA4 8F080008 */  lw         $t0, 0x8($t8)
/* 4B0A8 8006FCA8 8F090010 */  lw         $t1, 0x10($t8)
/* 4B0AC 8006FCAC 00000000 */  nop
/* 4B0B0 8006FCB0 01095821 */  addu       $t3, $t0, $t1
/* 4B0B4 8006FCB4 AF0B0008 */  sw         $t3, 0x8($t8)
/* 4B0B8 8006FCB8 8FAA0038 */  lw         $t2, 0x38($sp)
/* 4B0BC 8006FCBC 00000000 */  nop
/* 4B0C0 8006FCC0 2D410101 */  sltiu      $at, $t2, 0x101
/* 4B0C4 8006FCC4 1020FFD8 */  beqz       $at, .L8006FC28
/* 4B0C8 8006FCC8 00000000 */   nop
.L8006FCCC:
/* 4B0CC 8006FCCC 8FAC0038 */  lw         $t4, 0x38($sp)
/* 4B0D0 8006FCD0 8FAF0028 */  lw         $t7, 0x28($sp)
/* 4B0D4 8006FCD4 000C71C0 */  sll        $t6, $t4, 7
/* 4B0D8 8006FCD8 ADEE0010 */  sw         $t6, 0x10($t7)
/* 4B0DC 8006FCDC 8FA40030 */  lw         $a0, 0x30($sp)
/* 4B0E0 8006FCE0 0C01BC00 */  jal        func_8006F000
/* 4B0E4 8006FCE4 00000000 */   nop
/* 4B0E8 8006FCE8 8FB90028 */  lw         $t9, 0x28($sp)
/* 4B0EC 8006FCEC 00000000 */  nop
/* 4B0F0 8006FCF0 AF22000C */  sw         $v0, 0xC($t9)
/* 4B0F4 8006FCF4 3C04800B */  lui        $a0, %hi(D_800B1150)
/* 4B0F8 8006FCF8 8FA50028 */  lw         $a1, 0x28($sp)
/* 4B0FC 8006FCFC 24841150 */  addiu      $a0, $a0, %lo(D_800B1150)
/* 4B100 8006FD00 0C0183E0 */  jal        osEPiStartDma
/* 4B104 8006FD04 00003025 */   or        $a2, $zero, $zero
/* 4B108 8006FD08 AFA20024 */  sw         $v0, 0x24($sp)
/* 4B10C 8006FD0C 8FA20024 */  lw         $v0, 0x24($sp)
/* 4B110 8006FD10 10000003 */  b          .L8006FD20
/* 4B114 8006FD14 00000000 */   nop
/* 4B118 8006FD18 10000001 */  b          .L8006FD20
/* 4B11C 8006FD1C 00000000 */   nop
.L8006FD20:
/* 4B120 8006FD20 8FBF0014 */  lw         $ra, 0x14($sp)
/* 4B124 8006FD24 27BD0028 */  addiu      $sp, $sp, 0x28
/* 4B128 8006FD28 03E00008 */  jr         $ra
/* 4B12C 8006FD2C 00000000 */   nop
