.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel state_step_exit_language_select
/* 10D40 80035940 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 10D44 80035944 AFBF0014 */  sw         $ra, 0x14($sp)
/* 10D48 80035948 0C092315 */  jal        func_80244BC4
/* 10D4C 8003594C AFB00010 */   sw        $s0, 0x10($sp)
/* 10D50 80035950 3C10800A */  lui        $s0, %hi(D_800A0931)
/* 10D54 80035954 2610F091 */  addiu      $s0, $s0, %lo(D_800A0931)
/* 10D58 80035958 82030000 */  lb         $v1, 0x0($s0)
/* 10D5C 8003595C 24020002 */  addiu      $v0, $zero, 0x2
/* 10D60 80035960 10620022 */  beq        $v1, $v0, .L800359EC
/* 10D64 80035964 28620003 */   slti      $v0, $v1, 0x3
/* 10D68 80035968 50400005 */  beql       $v0, $zero, .L80035980
/* 10D6C 8003596C 24020003 */   addiu     $v0, $zero, 0x3
/* 10D70 80035970 10600007 */  beqz       $v1, .L80035990
/* 10D74 80035974 0000282D */   daddu     $a1, $zero, $zero
/* 10D78 80035978 0800D68C */  j          .L80035A30
/* 10D7C 8003597C 00000000 */   nop
.L80035980:
/* 10D80 80035980 10620020 */  beq        $v1, $v0, .L80035A04
/* 10D84 80035984 00000000 */   nop
/* 10D88 80035988 0800D68C */  j          .L80035A30
/* 10D8C 8003598C 00000000 */   nop
.L80035990:
/* 10D90 80035990 2404002C */  addiu      $a0, $zero, 0x2C
/* 10D94 80035994 0080382D */  daddu      $a3, $a0, $zero
/* 10D98 80035998 2406FFFF */  addiu      $a2, $zero, -0x1
/* 10D9C 8003599C 3C038016 */  lui        $v1, %hi(D_80158E90)
/* 10DA0 800359A0 24638E90 */  addiu      $v1, $v1, %lo(D_80158E90)
.L800359A4:
/* 10DA4 800359A4 80620003 */  lb         $v0, 0x3($v1)
/* 10DA8 800359A8 10470003 */  beq        $v0, $a3, .L800359B8
/* 10DAC 800359AC 00000000 */   nop
/* 10DB0 800359B0 54460005 */  bnel       $v0, $a2, .L800359C8
/* 10DB4 800359B4 24840001 */   addiu     $a0, $a0, 0x1
.L800359B8:
/* 10DB8 800359B8 90620000 */  lbu        $v0, 0x0($v1)
/* 10DBC 800359BC 30420008 */  andi       $v0, $v0, 0x8
/* 10DC0 800359C0 00A22821 */  addu       $a1, $a1, $v0
/* 10DC4 800359C4 24840001 */  addiu      $a0, $a0, 0x1
.L800359C8:
/* 10DC8 800359C8 28820040 */  slti       $v0, $a0, 0x40
/* 10DCC 800359CC 1440FFF5 */  bnez       $v0, .L800359A4
/* 10DD0 800359D0 24630020 */   addiu     $v1, $v1, 0x20
/* 10DD4 800359D4 14A00016 */  bnez       $a1, .L80035A30
/* 10DD8 800359D8 24020002 */   addiu     $v0, $zero, 0x2
/* 10DDC 800359DC 3C01800A */  lui        $at, %hi(D_800A0931)
/* 10DE0 800359E0 A022F091 */  sb         $v0, %lo(D_800A0931)($at)
/* 10DE4 800359E4 0800D68C */  j          .L80035A30
/* 10DE8 800359E8 00000000 */   nop
.L800359EC:
/* 10DEC 800359EC 0C0922E4 */  jal        filemenu_cleanup
/* 10DF0 800359F0 00000000 */   nop
/* 10DF4 800359F4 0C051A9D */  jal        set_windows_visible
/* 10DF8 800359F8 0000202D */   daddu     $a0, $zero, $zero
/* 10DFC 800359FC 24020003 */  addiu      $v0, $zero, 0x3
/* 10E00 80035A00 A2020000 */  sb         $v0, 0x0($s0)
.L80035A04:
/* 10E04 80035A04 0C009C02 */  jal        set_time_freeze_mode
/* 10E08 80035A08 0000202D */   daddu     $a0, $zero, $zero
/* 10E0C 80035A0C 0C00CE04 */  jal        set_game_mode
/* 10E10 80035A10 24040002 */   addiu     $a0, $zero, 0x2
/* 10E14 80035A14 3C04FFFE */  lui        $a0, (0xFFFEFFFF >> 16)
/* 10E18 80035A18 3C038009 */  lui        $v1, %hi(gOverrideFlags)
/* 10E1C 80035A1C 24636A28 */  addiu      $v1, $v1, %lo(gOverrideFlags)
/* 10E20 80035A20 8C620000 */  lw         $v0, 0x0($v1)
/* 10E24 80035A24 3484FFFF */  ori        $a0, $a0, (0xFFFEFFFF & 0xFFFF)
/* 10E28 80035A28 00441024 */  and        $v0, $v0, $a0
/* 10E2C 80035A2C AC620000 */  sw         $v0, 0x0($v1)
.L80035A30:
/* 10E30 80035A30 8FBF0014 */  lw         $ra, 0x14($sp)
/* 10E34 80035A34 8FB00010 */  lw         $s0, 0x10($sp)
/* 10E38 80035A38 03E00008 */  jr         $ra
/* 10E3C 80035A3C 27BD0018 */   addiu     $sp, $sp, 0x18
