#include "../common/Credits.h"

#define MSG_Credits_008F MESSAGE_ID(0x2E, 0x08F)
#define MSG_Credits_0090 MESSAGE_ID(0x2E, 0x090)
#define MSG_Credits_0091 MESSAGE_ID(0x2E, 0x091)
#define MSG_Credits_0092 MESSAGE_ID(0x2E, 0x092)
#define MSG_Credits_0093 MESSAGE_ID(0x2E, 0x093)
#define MSG_Credits_0094 MESSAGE_ID(0x2E, 0x094)
#define MSG_Credits_0095 MESSAGE_ID(0x2E, 0x095)
#define MSG_Credits_0096 MESSAGE_ID(0x2E, 0x096)
#define MSG_Credits_0097 MESSAGE_ID(0x2E, 0x097)
#define MSG_Credits_0098 MESSAGE_ID(0x2E, 0x098)
#define MSG_Credits_0099 MESSAGE_ID(0x2E, 0x099)
#define MSG_Credits_009A MESSAGE_ID(0x2E, 0x09A)
#define MSG_Credits_009B MESSAGE_ID(0x2E, 0x09B)
#define MSG_Credits_009C MESSAGE_ID(0x2E, 0x09C)
#define MSG_Credits_009D MESSAGE_ID(0x2E, 0x09D)

CreditsEntry N(Credits_Names)[] = {
    {
        .next = 195,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0034,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0035,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0036,
        .posX = 159,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0037,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0038,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0039,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 50,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_003A,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_003B,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_003C,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_003D,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_003E,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_003F,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0040,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0041,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0042,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0043,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0045,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0044,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0046,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0047,
        .posX = STANDARD_POS_X,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0048,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0049,
        .posX = STANDARD_POS_X,
        .posY = 208,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 50,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_004A,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_004B,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_004C,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_004D,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_004E,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_004F,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0050,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0051,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0052,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0053,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0054,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 50,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0055,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0057,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0056,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0076,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = 50,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0070,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_008F,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0090,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0091,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0092,
        .posX = STANDARD_POS_X,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0093,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0094,
        .posX = STANDARD_POS_X,
        .posY = 208,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0095,
        .posX = STANDARD_POS_X,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0096,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0097,
        .posX = STANDARD_POS_X,
        .posY = 208,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0098,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0099,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_009A,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_009B,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_009C,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_009D,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_0081,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_0080,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_007E,
        .posX = STANDARD_POS_X,
        .posY = 191,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .next = 33,
    },
    {
        .msgID = MSG_Credits_006E,
        .posX = STANDARD_POS_X,
        .posY = 186,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_007B,
        .posX = STANDARD_POS_X,
        .posY = 203,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 0,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 116,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 1,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005D,
        .posX = STANDARD_POS_X,
        .posY = 182,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005E,
        .posX = STANDARD_POS_X,
        .posY = 195,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 0,
        .flags = CREDITS_FLAG_1,
    },
    {
        .msgID = MSG_Credits_005F,
        .posX = STANDARD_POS_X,
        .posY = 208,
        .palette = 1,
        .appearMode = CREDITS_APPEAR_MODE_00,
        .appearTime = STANDARD_APPEAR_TIME,
        .perCharDelayIn = 1,
        .holdMode = CREDITS_HOLD_MODE_00,
        .holdTime = 102,
        .vanishMode = CREDITS_VANISH_MODE_00,
        .vanishTime = 25,
        .perCharDelayOut = 0,
        .next = 160,
        .flags = CREDITS_FLAG_1,
    },
    {
        .appearMode = CREDITS_APPEAR_MODE_04,
        .appearTime = 0,
        .perCharDelayIn = 0,
        .next = -1,
    },
};
