.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_PAL_802D8B04
/* F8CD4 802D8B04 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* F8CD8 802D8B08 AFBF0010 */  sw         $ra, 0x10($sp)
/* F8CDC 802D8B0C 8C82000C */  lw         $v0, 0xC($a0)
/* F8CE0 802D8B10 3C068015 */  lui        $a2, %hi(D_PAL_8014AE4C)
/* F8CE4 802D8B14 8CC6AE4C */  lw         $a2, %lo(D_PAL_8014AE4C)($a2)
/* F8CE8 802D8B18 0C0B2C26 */  jal        evt_set_variable
/* F8CEC 802D8B1C 8C450000 */   lw        $a1, 0x0($v0)
/* F8CF0 802D8B20 8FBF0010 */  lw         $ra, 0x10($sp)
/* F8CF4 802D8B24 24020002 */  addiu      $v0, $zero, 0x2
/* F8CF8 802D8B28 03E00008 */  jr         $ra
/* F8CFC 802D8B2C 27BD0018 */   addiu     $sp, $sp, 0x18
