.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_draw_contents_option_left
/* 1718B8 80248E98 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1718BC 80248E9C AFB1001C */  sw         $s1, 0x1C($sp)
/* 1718C0 80248EA0 00A0882D */  daddu      $s1, $a1, $zero
/* 1718C4 80248EA4 AFB20020 */  sw         $s2, 0x20($sp)
/* 1718C8 80248EA8 3C0300FF */  lui        $v1, (0xFFFF00 >> 16)
/* 1718CC 80248EAC AFBF0024 */  sw         $ra, 0x24($sp)
/* 1718D0 80248EB0 AFB00018 */  sw         $s0, 0x18($sp)
/* 1718D4 80248EB4 8C820000 */  lw         $v0, 0x0($a0)
/* 1718D8 80248EB8 3463FF00 */  ori        $v1, $v1, (0xFFFF00 & 0xFFFF)
/* 1718DC 80248EBC 00431024 */  and        $v0, $v0, $v1
/* 1718E0 80248EC0 3C038015 */  lui        $v1, %hi(D_PAL_8014AE4C)
/* 1718E4 80248EC4 8C63AE4C */  lw         $v1, %lo(D_PAL_8014AE4C)($v1)
/* 1718E8 80248EC8 24040200 */  addiu      $a0, $zero, 0x200
/* 1718EC 80248ECC 3C108025 */  lui        $s0, %hi(D_filemenu_802508E8)
/* 1718F0 80248ED0 02038021 */  addu       $s0, $s0, $v1
/* 1718F4 80248ED4 921008E8 */  lbu        $s0, %lo(D_filemenu_802508E8)($s0)
/* 1718F8 80248ED8 14440006 */  bne        $v0, $a0, .Lfilemenu_80248EF4
/* 1718FC 80248EDC 00C0902D */   daddu     $s2, $a2, $zero
/* 171900 80248EE0 24040035 */  addiu      $a0, $zero, 0x35
/* 171904 80248EE4 02302821 */  addu       $a1, $s1, $s0
/* 171908 80248EE8 24A5FFF6 */  addiu      $a1, $a1, -0xA
/* 17190C 80248EEC 0C091B44 */  jal        func_filemenu_80246D10
/* 171910 80248EF0 26460008 */   addiu     $a2, $s2, 0x8
.Lfilemenu_80248EF4:
/* 171914 80248EF4 0C093A16 */  jal        func_filemenu_8024E858
/* 171918 80248EF8 24040008 */   addiu     $a0, $zero, 0x8
/* 17191C 80248EFC 0040202D */  daddu      $a0, $v0, $zero
/* 171920 80248F00 02302821 */  addu       $a1, $s1, $s0
/* 171924 80248F04 26460002 */  addiu      $a2, $s2, 0x2
/* 171928 80248F08 24020001 */  addiu      $v0, $zero, 0x1
/* 17192C 80248F0C 240700FF */  addiu      $a3, $zero, 0xFF
/* 171930 80248F10 AFA00010 */  sw         $zero, 0x10($sp)
/* 171934 80248F14 0C0939C7 */  jal        func_filemenu_8024E71C
/* 171938 80248F18 AFA20014 */   sw        $v0, 0x14($sp)
/* 17193C 80248F1C 8FBF0024 */  lw         $ra, 0x24($sp)
/* 171940 80248F20 8FB20020 */  lw         $s2, 0x20($sp)
/* 171944 80248F24 8FB1001C */  lw         $s1, 0x1C($sp)
/* 171948 80248F28 8FB00018 */  lw         $s0, 0x18($sp)
/* 17194C 80248F2C 03E00008 */  jr         $ra
/* 171950 80248F30 27BD0028 */   addiu     $sp, $sp, 0x28
