.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_draw_contents_title
/* 1716E0 80248CC0 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 1716E4 80248CC4 AFB20020 */  sw         $s2, 0x20($sp)
/* 1716E8 80248CC8 00A0902D */  daddu      $s2, $a1, $zero
/* 1716EC 80248CCC AFB30024 */  sw         $s3, 0x24($sp)
/* 1716F0 80248CD0 AFBF0028 */  sw         $ra, 0x28($sp)
/* 1716F4 80248CD4 AFB1001C */  sw         $s1, 0x1C($sp)
/* 1716F8 80248CD8 AFB00018 */  sw         $s0, 0x18($sp)
/* 1716FC 80248CDC 80830004 */  lb         $v1, 0x4($a0)
/* 171700 80248CE0 24020001 */  addiu      $v0, $zero, 0x1
/* 171704 80248CE4 10620011 */  beq        $v1, $v0, .Lfilemenu_80248D2C
/* 171708 80248CE8 00C0982D */   daddu     $s3, $a2, $zero
/* 17170C 80248CEC 28620002 */  slti       $v0, $v1, 0x2
/* 171710 80248CF0 10400005 */  beqz       $v0, .Lfilemenu_80248D08
/* 171714 80248CF4 24020002 */   addiu     $v0, $zero, 0x2
/* 171718 80248CF8 50600009 */  beql       $v1, $zero, .Lfilemenu_80248D20
/* 17171C 80248CFC 24070001 */   addiu     $a3, $zero, 0x1
/* 171720 80248D00 0809235D */  j          .Lfilemenu_80248D74
/* 171724 80248D04 00000000 */   nop
.Lfilemenu_80248D08:
/* 171728 80248D08 1062000C */  beq        $v1, $v0, .Lfilemenu_80248D3C
/* 17172C 80248D0C 24020003 */   addiu     $v0, $zero, 0x3
/* 171730 80248D10 50620012 */  beql       $v1, $v0, .Lfilemenu_80248D5C
/* 171734 80248D14 24070004 */   addiu     $a3, $zero, 0x4
/* 171738 80248D18 0809235D */  j          .Lfilemenu_80248D74
/* 17173C 80248D1C 00000000 */   nop
.Lfilemenu_80248D20:
/* 171740 80248D20 24100009 */  addiu      $s0, $zero, 0x9
/* 171744 80248D24 0809235D */  j          .Lfilemenu_80248D74
/* 171748 80248D28 24110004 */   addiu     $s1, $zero, 0x4
.Lfilemenu_80248D2C:
/* 17174C 80248D2C 24070002 */  addiu      $a3, $zero, 0x2
/* 171750 80248D30 24100008 */  addiu      $s0, $zero, 0x8
/* 171754 80248D34 0809235D */  j          .Lfilemenu_80248D74
/* 171758 80248D38 24110004 */   addiu     $s1, $zero, 0x4
.Lfilemenu_80248D3C:
/* 17175C 80248D3C 24070003 */  addiu      $a3, $zero, 0x3
/* 171760 80248D40 3C028015 */  lui        $v0, %hi(D_PAL_8014AE4C)
/* 171764 80248D44 8C42AE4C */  lw         $v0, %lo(D_PAL_8014AE4C)($v0)
/* 171768 80248D48 3C108025 */  lui        $s0, %hi(D_filemenu_80250938)
/* 17176C 80248D4C 02028021 */  addu       $s0, $s0, $v0
/* 171770 80248D50 92100938 */  lbu        $s0, %lo(D_filemenu_80250938)($s0)
/* 171774 80248D54 0809235D */  j          .Lfilemenu_80248D74
/* 171778 80248D58 24110004 */   addiu     $s1, $zero, 0x4
.Lfilemenu_80248D5C:
/* 17177C 80248D5C 3C028015 */  lui        $v0, %hi(D_PAL_8014AE4C)
/* 171780 80248D60 8C42AE4C */  lw         $v0, %lo(D_PAL_8014AE4C)($v0)
/* 171784 80248D64 00E0882D */  daddu      $s1, $a3, $zero
/* 171788 80248D68 3C108025 */  lui        $s0, %hi(D_filemenu_8025093C)
/* 17178C 80248D6C 02028021 */  addu       $s0, $s0, $v0
/* 171790 80248D70 9210093C */  lbu        $s0, %lo(D_filemenu_8025093C)($s0)
.Lfilemenu_80248D74:
/* 171794 80248D74 0C093A16 */  jal        func_filemenu_8024E858
/* 171798 80248D78 00E0202D */   daddu     $a0, $a3, $zero
/* 17179C 80248D7C 0040202D */  daddu      $a0, $v0, $zero
/* 1717A0 80248D80 02502821 */  addu       $a1, $s2, $s0
/* 1717A4 80248D84 02713021 */  addu       $a2, $s3, $s1
/* 1717A8 80248D88 240700FF */  addiu      $a3, $zero, 0xFF
/* 1717AC 80248D8C AFA00010 */  sw         $zero, 0x10($sp)
/* 1717B0 80248D90 0C0939C7 */  jal        func_filemenu_8024E71C
/* 1717B4 80248D94 AFA00014 */   sw        $zero, 0x14($sp)
/* 1717B8 80248D98 8FBF0028 */  lw         $ra, 0x28($sp)
/* 1717BC 80248D9C 8FB30024 */  lw         $s3, 0x24($sp)
/* 1717C0 80248DA0 8FB20020 */  lw         $s2, 0x20($sp)
/* 1717C4 80248DA4 8FB1001C */  lw         $s1, 0x1C($sp)
/* 1717C8 80248DA8 8FB00018 */  lw         $s0, 0x18($sp)
/* 1717CC 80248DAC 03E00008 */  jr         $ra
/* 1717D0 80248DB0 27BD0030 */   addiu     $sp, $sp, 0x30
