.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_800F4C1C
/* 8A114 800F1004 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 8A118 800F1008 AFB40028 */  sw         $s4, 0x28($sp)
/* 8A11C 800F100C 00C0A02D */  daddu      $s4, $a2, $zero
/* 8A120 800F1010 AFB20020 */  sw         $s2, 0x20($sp)
/* 8A124 800F1014 26920008 */  addiu      $s2, $s4, 0x8
/* 8A128 800F1018 AFB00018 */  sw         $s0, 0x18($sp)
/* 8A12C 800F101C 3C10001D */  lui        $s0, (0x1D0069 >> 16)
/* 8A130 800F1020 3C028011 */  lui        $v0, %hi(D_8010C199)
/* 8A134 800F1024 8042C199 */  lb         $v0, %lo(D_8010C199)($v0)
/* 8A138 800F1028 36100069 */  ori        $s0, $s0, (0x1D0069 & 0xFFFF)
/* 8A13C 800F102C AFB30024 */  sw         $s3, 0x24($sp)
/* 8A140 800F1030 24B30010 */  addiu      $s3, $a1, 0x10
/* 8A144 800F1034 AFB1001C */  sw         $s1, 0x1C($sp)
/* 8A148 800F1038 24110001 */  addiu      $s1, $zero, 0x1
/* 8A14C 800F103C 14510003 */  bne        $v0, $s1, .LPAL_800F104C
/* 8A150 800F1040 AFBF002C */   sw        $ra, 0x2C($sp)
/* 8A154 800F1044 3C10001D */  lui        $s0, (0x1D0068 >> 16)
/* 8A158 800F1048 36100068 */  ori        $s0, $s0, (0x1D0068 & 0xFFFF)
.LPAL_800F104C:
/* 8A15C 800F104C 0C0493F4 */  jal        func_80124FD0
/* 8A160 800F1050 0200202D */   daddu     $a0, $s0, $zero
/* 8A164 800F1054 54510001 */  bnel       $v0, $s1, .LPAL_800F105C
/* 8A168 800F1058 26920004 */   addiu     $s2, $s4, 0x4
.LPAL_800F105C:
/* 8A16C 800F105C 0200202D */  daddu      $a0, $s0, $zero
/* 8A170 800F1060 2402000F */  addiu      $v0, $zero, 0xF
/* 8A174 800F1064 0260282D */  daddu      $a1, $s3, $zero
/* 8A178 800F1068 0240302D */  daddu      $a2, $s2, $zero
/* 8A17C 800F106C 240700FF */  addiu      $a3, $zero, 0xFF
/* 8A180 800F1070 AFA20010 */  sw         $v0, 0x10($sp)
/* 8A184 800F1074 0C049403 */  jal        func_8012500C
/* 8A188 800F1078 AFA00014 */   sw        $zero, 0x14($sp)
/* 8A18C 800F107C 8FBF002C */  lw         $ra, 0x2C($sp)
/* 8A190 800F1080 8FB40028 */  lw         $s4, 0x28($sp)
/* 8A194 800F1084 8FB30024 */  lw         $s3, 0x24($sp)
/* 8A198 800F1088 8FB20020 */  lw         $s2, 0x20($sp)
/* 8A19C 800F108C 8FB1001C */  lw         $s1, 0x1C($sp)
/* 8A1A0 800F1090 8FB00018 */  lw         $s0, 0x18($sp)
/* 8A1A4 800F1094 03E00008 */  jr         $ra
/* 8A1A8 800F1098 27BD0030 */   addiu     $sp, $sp, 0x30
