.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_mgm_02_80240000
/* E827F0 80240000 3C030019 */  lui        $v1, (0x190008 >> 16)
/* E827F4 80240004 3C028024 */  lui        $v0, %hi(D_80242A50)
/* E827F8 80240008 8C422A50 */  lw         $v0, %lo(D_80242A50)($v0)
/* E827FC 8024000C 10400002 */  beqz       $v0, .Lmgm_02_80240018
/* E82800 80240010 34630008 */   ori       $v1, $v1, (0x190008 & 0xFFFF)
/* E82804 80240014 0000182D */  daddu      $v1, $zero, $zero
.Lmgm_02_80240018:
/* E82808 80240018 03E00008 */  jr         $ra
/* E8280C 8024001C 0060102D */   daddu     $v0, $v1, $zero
