.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel load_effect
/* 35F44 8005AB44 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 35F48 8005AB48 AFB20020 */  sw         $s2, 0x20($sp)
/* 35F4C 8005AB4C 0080902D */  daddu      $s2, $a0, $zero
/* 35F50 8005AB50 3C038008 */  lui        $v1, %hi(gEffectTable)
/* 35F54 8005AB54 2463B5B0 */  addiu      $v1, $v1, %lo(gEffectTable)
/* 35F58 8005AB58 00121040 */  sll        $v0, $s2, 1
/* 35F5C 8005AB5C 00521021 */  addu       $v0, $v0, $s2
/* 35F60 8005AB60 000210C0 */  sll        $v0, $v0, 3
/* 35F64 8005AB64 AFB1001C */  sw         $s1, 0x1C($sp)
/* 35F68 8005AB68 00438821 */  addu       $s1, $v0, $v1
/* 35F6C 8005AB6C 0000202D */  daddu      $a0, $zero, $zero
/* 35F70 8005AB70 AFB00018 */  sw         $s0, 0x18($sp)
/* 35F74 8005AB74 3C10800A */  lui        $s0, %hi(gEffectGraphicsData)
/* 35F78 8005AB78 26102770 */  addiu      $s0, $s0, %lo(gEffectGraphicsData)
/* 35F7C 8005AB7C AFBF0024 */  sw         $ra, 0x24($sp)
.LPAL_8005AB80:
/* 35F80 8005AB80 8E020000 */  lw         $v0, 0x0($s0)
/* 35F84 8005AB84 30420001 */  andi       $v0, $v0, 0x1
/* 35F88 8005AB88 50400005 */  beql       $v0, $zero, .LPAL_8005ABA0
/* 35F8C 8005AB8C 24840001 */   addiu     $a0, $a0, 0x1
/* 35F90 8005AB90 8E020004 */  lw         $v0, 0x4($s0)
/* 35F94 8005AB94 10520006 */  beq        $v0, $s2, .LPAL_8005ABB0
/* 35F98 8005AB98 2882000F */   slti      $v0, $a0, 0xF
/* 35F9C 8005AB9C 24840001 */  addiu      $a0, $a0, 0x1
.LPAL_8005ABA0:
/* 35FA0 8005ABA0 2882000F */  slti       $v0, $a0, 0xF
/* 35FA4 8005ABA4 1440FFF6 */  bnez       $v0, .LPAL_8005AB80
/* 35FA8 8005ABA8 26100020 */   addiu     $s0, $s0, 0x20
/* 35FAC 8005ABAC 2882000F */  slti       $v0, $a0, 0xF
.LPAL_8005ABB0:
/* 35FB0 8005ABB0 1440007F */  bnez       $v0, .LPAL_8005ADB0
/* 35FB4 8005ABB4 24020001 */   addiu     $v0, $zero, 0x1
/* 35FB8 8005ABB8 0000202D */  daddu      $a0, $zero, $zero
/* 35FBC 8005ABBC 3C10800A */  lui        $s0, %hi(gEffectGraphicsData)
/* 35FC0 8005ABC0 26102770 */  addiu      $s0, $s0, %lo(gEffectGraphicsData)
.LPAL_8005ABC4:
/* 35FC4 8005ABC4 8E020000 */  lw         $v0, 0x0($s0)
/* 35FC8 8005ABC8 30420001 */  andi       $v0, $v0, 0x1
/* 35FCC 8005ABCC 10400006 */  beqz       $v0, .LPAL_8005ABE8
/* 35FD0 8005ABD0 2882000F */   slti      $v0, $a0, 0xF
/* 35FD4 8005ABD4 24840001 */  addiu      $a0, $a0, 0x1
/* 35FD8 8005ABD8 2882000F */  slti       $v0, $a0, 0xF
/* 35FDC 8005ABDC 1440FFF9 */  bnez       $v0, .LPAL_8005ABC4
/* 35FE0 8005ABE0 26100020 */   addiu     $s0, $s0, 0x20
/* 35FE4 8005ABE4 2882000F */  slti       $v0, $a0, 0xF
.LPAL_8005ABE8:
/* 35FE8 8005ABE8 14400003 */  bnez       $v0, .LPAL_8005ABF8
/* 35FEC 8005ABEC 3C0700FF */   lui       $a3, (0xFFFFFF >> 16)
.LPAL_8005ABF0:
/* 35FF0 8005ABF0 08016AFC */  j          .LPAL_8005ABF0
/* 35FF4 8005ABF4 00000000 */   nop
.LPAL_8005ABF8:
/* 35FF8 8005ABF8 34E7FFFF */  ori        $a3, $a3, (0xFFFFFF & 0xFFFF)
/* 35FFC 8005ABFC 0000282D */  daddu      $a1, $zero, $zero
/* 36000 8005AC00 2402FFFF */  addiu      $v0, $zero, -0x1
/* 36004 8005AC04 3C038019 */  lui        $v1, %hi(D_80195000)
/* 36008 8005AC08 24635000 */  addiu      $v1, $v1, %lo(D_80195000)
/* 3600C 8005AC0C AFA20010 */  sw         $v0, 0x10($sp)
/* 36010 8005AC10 AFA20014 */  sw         $v0, 0x14($sp)
/* 36014 8005AC14 00041300 */  sll        $v0, $a0, 12
/* 36018 8005AC18 00431021 */  addu       $v0, $v0, $v1
/* 3601C 8005AC1C 8E26000C */  lw         $a2, 0xC($s1)
/* 36020 8005AC20 0C019D84 */  jal        osMapTLB
/* 36024 8005AC24 00473824 */   and       $a3, $v0, $a3
/* 36028 8005AC28 8E240004 */  lw         $a0, 0x4($s1)
/* 3602C 8005AC2C 8E250008 */  lw         $a1, 0x8($s1)
/* 36030 8005AC30 0C00A5AF */  jal        dma_copy
/* 36034 8005AC34 8E26000C */   lw        $a2, 0xC($s1)
/* 36038 8005AC38 8E220010 */  lw         $v0, 0x10($s1)
/* 3603C 8005AC3C 5040005C */  beql       $v0, $zero, .LPAL_8005ADB0
/* 36040 8005AC40 24020001 */   addiu     $v0, $zero, 0x1
/* 36044 8005AC44 8E240014 */  lw         $a0, 0x14($s1)
/* 36048 8005AC48 0C00AAEA */  jal        general_heap_malloc
/* 3604C 8005AC4C 00822023 */   subu      $a0, $a0, $v0
/* 36050 8005AC50 14400003 */  bnez       $v0, .LPAL_8005AC60
/* 36054 8005AC54 AE02001C */   sw        $v0, 0x1C($s0)
.LPAL_8005AC58:
/* 36058 8005AC58 08016B16 */  j          .LPAL_8005AC58
/* 3605C 8005AC5C 00000000 */   nop
.LPAL_8005AC60:
/* 36060 8005AC60 8E240010 */  lw         $a0, 0x10($s1)
/* 36064 8005AC64 3C02003C */  lui        $v0, %hi(D_3B9190)
/* 36068 8005AC68 24429190 */  addiu      $v0, $v0, %lo(D_3B9190)
/* 3606C 8005AC6C 14820024 */  bne        $a0, $v0, .LPAL_8005AD00
/* 36070 8005AC70 24020001 */   addiu     $v0, $zero, 0x1
/* 36074 8005AC74 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 36078 8005AC78 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 3607C 8005AC7C 1062000B */  beq        $v1, $v0, .LPAL_8005ACAC
/* 36080 8005AC80 28620002 */   slti      $v0, $v1, 0x2
/* 36084 8005AC84 10400005 */  beqz       $v0, .LPAL_8005AC9C
/* 36088 8005AC88 24020002 */   addiu     $v0, $zero, 0x2
/* 3608C 8005AC8C 10600043 */  beqz       $v1, .LPAL_8005AD9C
/* 36090 8005AC90 00000000 */   nop
/* 36094 8005AC94 08016B39 */  j          .LPAL_8005ACE4
/* 36098 8005AC98 00000000 */   nop
.LPAL_8005AC9C:
/* 3609C 8005AC9C 1062000A */  beq        $v1, $v0, .LPAL_8005ACC8
/* 360A0 8005ACA0 00000000 */   nop
/* 360A4 8005ACA4 08016B39 */  j          .LPAL_8005ACE4
/* 360A8 8005ACA8 00000000 */   nop
.LPAL_8005ACAC:
/* 360AC 8005ACAC 3C04003C */  lui        $a0, %hi(D_3BAAF0)
/* 360B0 8005ACB0 2484AAF0 */  addiu      $a0, $a0, %lo(D_3BAAF0)
/* 360B4 8005ACB4 8E06001C */  lw         $a2, 0x1C($s0)
/* 360B8 8005ACB8 3C05003C */  lui        $a1, %hi(D_3BC450)
/* 360BC 8005ACBC 24A5C450 */  addiu      $a1, $a1, %lo(D_3BC450)
/* 360C0 8005ACC0 08016B69 */  j          .LPAL_8005ADA4
/* 360C4 8005ACC4 00000000 */   nop
.LPAL_8005ACC8:
/* 360C8 8005ACC8 3C04003C */  lui        $a0, %hi(D_3BC450)
/* 360CC 8005ACCC 2484C450 */  addiu      $a0, $a0, %lo(D_3BC450)
/* 360D0 8005ACD0 8E06001C */  lw         $a2, 0x1C($s0)
/* 360D4 8005ACD4 3C05003C */  lui        $a1, %hi(D_3BDDB0)
/* 360D8 8005ACD8 24A5DDB0 */  addiu      $a1, $a1, %lo(D_3BDDB0)
/* 360DC 8005ACDC 08016B69 */  j          .LPAL_8005ADA4
/* 360E0 8005ACE0 00000000 */   nop
.LPAL_8005ACE4:
/* 360E4 8005ACE4 3C04003C */  lui        $a0, %hi(D_3BDDB0)
/* 360E8 8005ACE8 2484DDB0 */  addiu      $a0, $a0, %lo(D_3BDDB0)
/* 360EC 8005ACEC 8E06001C */  lw         $a2, 0x1C($s0)
/* 360F0 8005ACF0 3C05003C */  lui        $a1, %hi(D_3BF710)
/* 360F4 8005ACF4 24A5F710 */  addiu      $a1, $a1, %lo(D_3BF710)
/* 360F8 8005ACF8 08016B69 */  j          .LPAL_8005ADA4
/* 360FC 8005ACFC 00000000 */   nop
.LPAL_8005AD00:
/* 36100 8005AD00 3C020042 */  lui        $v0, %hi(D_4198D0)
/* 36104 8005AD04 244298D0 */  addiu      $v0, $v0, %lo(D_4198D0)
/* 36108 8005AD08 14820024 */  bne        $a0, $v0, .LPAL_8005AD9C
/* 3610C 8005AD0C 24020001 */   addiu     $v0, $zero, 0x1
/* 36110 8005AD10 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 36114 8005AD14 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 36118 8005AD18 1062000B */  beq        $v1, $v0, .LPAL_8005AD48
/* 3611C 8005AD1C 28620002 */   slti      $v0, $v1, 0x2
/* 36120 8005AD20 10400005 */  beqz       $v0, .LPAL_8005AD38
/* 36124 8005AD24 24020002 */   addiu     $v0, $zero, 0x2
/* 36128 8005AD28 1060001C */  beqz       $v1, .LPAL_8005AD9C
/* 3612C 8005AD2C 00000000 */   nop
/* 36130 8005AD30 08016B60 */  j          .LPAL_8005AD80
/* 36134 8005AD34 00000000 */   nop
.LPAL_8005AD38:
/* 36138 8005AD38 1062000A */  beq        $v1, $v0, .LPAL_8005AD64
/* 3613C 8005AD3C 00000000 */   nop
/* 36140 8005AD40 08016B60 */  j          .LPAL_8005AD80
/* 36144 8005AD44 00000000 */   nop
.LPAL_8005AD48:
/* 36148 8005AD48 3C040042 */  lui        $a0, %hi(D_425E60)
/* 3614C 8005AD4C 24845E60 */  addiu      $a0, $a0, %lo(D_425E60)
/* 36150 8005AD50 8E06001C */  lw         $a2, 0x1C($s0)
/* 36154 8005AD54 3C050043 */  lui        $a1, %hi(D_4323F0)
/* 36158 8005AD58 24A523F0 */  addiu      $a1, $a1, %lo(D_4323F0)
/* 3615C 8005AD5C 08016B69 */  j          .LPAL_8005ADA4
/* 36160 8005AD60 00000000 */   nop
.LPAL_8005AD64:
/* 36164 8005AD64 3C040043 */  lui        $a0, %hi(D_4323F0)
/* 36168 8005AD68 248423F0 */  addiu      $a0, $a0, %lo(D_4323F0)
/* 3616C 8005AD6C 8E06001C */  lw         $a2, 0x1C($s0)
/* 36170 8005AD70 3C050044 */  lui        $a1, %hi(D_43E980)
/* 36174 8005AD74 24A5E980 */  addiu      $a1, $a1, %lo(D_43E980)
/* 36178 8005AD78 08016B69 */  j          .LPAL_8005ADA4
/* 3617C 8005AD7C 00000000 */   nop
.LPAL_8005AD80:
/* 36180 8005AD80 3C040044 */  lui        $a0, %hi(D_43E980)
/* 36184 8005AD84 2484E980 */  addiu      $a0, $a0, %lo(D_43E980)
/* 36188 8005AD88 8E06001C */  lw         $a2, 0x1C($s0)
/* 3618C 8005AD8C 3C050045 */  lui        $a1, %hi(D_44AF10)
/* 36190 8005AD90 24A5AF10 */  addiu      $a1, $a1, %lo(D_44AF10)
/* 36194 8005AD94 08016B69 */  j          .LPAL_8005ADA4
/* 36198 8005AD98 00000000 */   nop
.LPAL_8005AD9C:
/* 3619C 8005AD9C 8E250014 */  lw         $a1, 0x14($s1)
/* 361A0 8005ADA0 8E06001C */  lw         $a2, 0x1C($s0)
.LPAL_8005ADA4:
/* 361A4 8005ADA4 0C00A5AF */  jal        dma_copy
/* 361A8 8005ADA8 00000000 */   nop
/* 361AC 8005ADAC 24020001 */  addiu      $v0, $zero, 0x1
.LPAL_8005ADB0:
/* 361B0 8005ADB0 0040182D */  daddu      $v1, $v0, $zero
/* 361B4 8005ADB4 AE120004 */  sw         $s2, 0x4($s0)
/* 361B8 8005ADB8 AE000008 */  sw         $zero, 0x8($s0)
/* 361BC 8005ADBC AE030000 */  sw         $v1, 0x0($s0)
/* 361C0 8005ADC0 8FBF0024 */  lw         $ra, 0x24($sp)
/* 361C4 8005ADC4 8FB20020 */  lw         $s2, 0x20($sp)
/* 361C8 8005ADC8 8FB1001C */  lw         $s1, 0x1C($sp)
/* 361CC 8005ADCC 8FB00018 */  lw         $s0, 0x18($sp)
/* 361D0 8005ADD0 03E00008 */  jr         $ra
/* 361D4 8005ADD4 27BD0028 */   addiu     $sp, $sp, 0x28
/* 361D8 8005ADD8 00000000 */  nop
/* 361DC 8005ADDC 00000000 */  nop
