.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_draw_contents_file_create_header
/* 174D98 8024C378 27BDFFC0 */  addiu      $sp, $sp, -0x40
/* 174D9C 8024C37C AFB40030 */  sw         $s4, 0x30($sp)
/* 174DA0 8024C380 00A0A02D */  daddu      $s4, $a1, $zero
/* 174DA4 8024C384 AFB50034 */  sw         $s5, 0x34($sp)
/* 174DA8 8024C388 00C0A82D */  daddu      $s5, $a2, $zero
/* 174DAC 8024C38C 3C028015 */  lui        $v0, %hi(D_PAL_8014AE4C)
/* 174DB0 8024C390 8C42AE4C */  lw         $v0, %lo(D_PAL_8014AE4C)($v0)
/* 174DB4 8024C394 24040021 */  addiu      $a0, $zero, 0x21
/* 174DB8 8024C398 AFB60038 */  sw         $s6, 0x38($sp)
/* 174DBC 8024C39C 24160029 */  addiu      $s6, $zero, 0x29
/* 174DC0 8024C3A0 AFB00020 */  sw         $s0, 0x20($sp)
/* 174DC4 8024C3A4 0000802D */  daddu      $s0, $zero, $zero
/* 174DC8 8024C3A8 AFB3002C */  sw         $s3, 0x2C($sp)
/* 174DCC 8024C3AC 3C138025 */  lui        $s3, %hi(D_802517C0)
/* 174DD0 8024C3B0 267317C0 */  addiu      $s3, $s3, %lo(D_802517C0)
/* 174DD4 8024C3B4 AFB10024 */  sw         $s1, 0x24($sp)
/* 174DD8 8024C3B8 AFBF003C */  sw         $ra, 0x3C($sp)
/* 174DDC 8024C3BC AFB20028 */  sw         $s2, 0x28($sp)
/* 174DE0 8024C3C0 3C128025 */  lui        $s2, %hi(D_filemenu_8025095C)
/* 174DE4 8024C3C4 02429021 */  addu       $s2, $s2, $v0
/* 174DE8 8024C3C8 9252095C */  lbu        $s2, %lo(D_filemenu_8025095C)($s2)
/* 174DEC 8024C3CC 0C093A16 */  jal        func_filemenu_8024E858
/* 174DF0 8024C3D0 24110006 */   addiu     $s1, $zero, 0x6
/* 174DF4 8024C3D4 0040202D */  daddu      $a0, $v0, $zero
/* 174DF8 8024C3D8 2685000A */  addiu      $a1, $s4, 0xA
/* 174DFC 8024C3DC 02B13021 */  addu       $a2, $s5, $s1
/* 174E00 8024C3E0 240700FF */  addiu      $a3, $zero, 0xFF
/* 174E04 8024C3E4 AFA00010 */  sw         $zero, 0x10($sp)
/* 174E08 8024C3E8 0C0939C7 */  jal        func_filemenu_8024E71C
/* 174E0C 8024C3EC AFA00014 */   sw        $zero, 0x14($sp)
/* 174E10 8024C3F0 3C048025 */  lui        $a0, %hi(D_802527E0)
/* 174E14 8024C3F4 248427E0 */  addiu      $a0, $a0, %lo(D_802527E0)
/* 174E18 8024C3F8 24050008 */  addiu      $a1, $zero, 0x8
/* 174E1C 8024C3FC 26A70016 */  addiu      $a3, $s5, 0x16
/* 174E20 8024C400 240200FF */  addiu      $v0, $zero, 0xFF
/* 174E24 8024C404 AFA20010 */  sw         $v0, 0x10($sp)
/* 174E28 8024C408 2402000B */  addiu      $v0, $zero, 0xB
/* 174E2C 8024C40C AFA00014 */  sw         $zero, 0x14($sp)
/* 174E30 8024C410 AFA00018 */  sw         $zero, 0x18($sp)
/* 174E34 8024C414 AFA2001C */  sw         $v0, 0x1C($sp)
/* 174E38 8024C418 02923021 */  addu       $a2, $s4, $s2
/* 174E3C 8024C41C 0C093A20 */  jal        func_filemenu_8024E880
/* 174E40 8024C420 24C60002 */   addiu     $a2, $a2, 0x2
/* 174E44 8024C424 02511021 */  addu       $v0, $s2, $s1
.Lfilemenu_8024C428:
/* 174E48 8024C428 8E640004 */  lw         $a0, 0x4($s3)
/* 174E4C 8024C42C 02822821 */  addu       $a1, $s4, $v0
/* 174E50 8024C430 0C050D4D */  jal        func_PAL_80143534
/* 174E54 8024C434 02B63021 */   addu      $a2, $s5, $s6
/* 174E58 8024C438 16000006 */  bnez       $s0, .Lfilemenu_8024C454
/* 174E5C 8024C43C 00000000 */   nop
/* 174E60 8024C440 8E640004 */  lw         $a0, 0x4($s3)
/* 174E64 8024C444 0C050CE4 */  jal        func_PAL_80143390
/* 174E68 8024C448 2631000B */   addiu     $s1, $s1, 0xB
/* 174E6C 8024C44C 08093119 */  j          .Lfilemenu_8024C464
/* 174E70 8024C450 26100001 */   addiu     $s0, $s0, 0x1
.Lfilemenu_8024C454:
/* 174E74 8024C454 8E640004 */  lw         $a0, 0x4($s3)
/* 174E78 8024C458 0C050CDD */  jal        func_PAL_80143374
/* 174E7C 8024C45C 2631000B */   addiu     $s1, $s1, 0xB
/* 174E80 8024C460 26100001 */  addiu      $s0, $s0, 0x1
.Lfilemenu_8024C464:
/* 174E84 8024C464 2A020008 */  slti       $v0, $s0, 0x8
/* 174E88 8024C468 1440FFEF */  bnez       $v0, .Lfilemenu_8024C428
/* 174E8C 8024C46C 02511021 */   addu      $v0, $s2, $s1
/* 174E90 8024C470 3C038025 */  lui        $v1, %hi(D_80251758)
/* 174E94 8024C474 80631758 */  lb         $v1, %lo(D_80251758)($v1)
/* 174E98 8024C478 24020003 */  addiu      $v0, $zero, 0x3
/* 174E9C 8024C47C 14620015 */  bne        $v1, $v0, .Lfilemenu_8024C4D4
/* 174EA0 8024C480 24020008 */   addiu     $v0, $zero, 0x8
/* 174EA4 8024C484 3C038025 */  lui        $v1, %hi(D_80251750)
/* 174EA8 8024C488 80631750 */  lb         $v1, %lo(D_80251750)($v1)
/* 174EAC 8024C48C 14620003 */  bne        $v1, $v0, .Lfilemenu_8024C49C
/* 174EB0 8024C490 00031040 */   sll       $v0, $v1, 1
/* 174EB4 8024C494 0809312C */  j          .Lfilemenu_8024C4B0
/* 174EB8 8024C498 26420056 */   addiu     $v0, $s2, 0x56
.Lfilemenu_8024C49C:
/* 174EBC 8024C49C 00431021 */  addu       $v0, $v0, $v1
/* 174EC0 8024C4A0 00021080 */  sll        $v0, $v0, 2
/* 174EC4 8024C4A4 00431023 */  subu       $v0, $v0, $v1
/* 174EC8 8024C4A8 24420009 */  addiu      $v0, $v0, 0x9
/* 174ECC 8024C4AC 02421021 */  addu       $v0, $s2, $v0
.Lfilemenu_8024C4B0:
/* 174ED0 8024C4B0 02822821 */  addu       $a1, $s4, $v0
/* 174ED4 8024C4B4 3C108025 */  lui        $s0, %hi(D_802517C0)
/* 174ED8 8024C4B8 261017C0 */  addiu      $s0, $s0, %lo(D_802517C0)
/* 174EDC 8024C4BC 8E040000 */  lw         $a0, 0x0($s0)
/* 174EE0 8024C4C0 0C050D4D */  jal        func_PAL_80143534
/* 174EE4 8024C4C4 26A6002D */   addiu     $a2, $s5, 0x2D
/* 174EE8 8024C4C8 8E040000 */  lw         $a0, 0x0($s0)
/* 174EEC 8024C4CC 0C050CDD */  jal        func_PAL_80143374
/* 174EF0 8024C4D0 00000000 */   nop
.Lfilemenu_8024C4D4:
/* 174EF4 8024C4D4 8FBF003C */  lw         $ra, 0x3C($sp)
/* 174EF8 8024C4D8 8FB60038 */  lw         $s6, 0x38($sp)
/* 174EFC 8024C4DC 8FB50034 */  lw         $s5, 0x34($sp)
/* 174F00 8024C4E0 8FB40030 */  lw         $s4, 0x30($sp)
/* 174F04 8024C4E4 8FB3002C */  lw         $s3, 0x2C($sp)
/* 174F08 8024C4E8 8FB20028 */  lw         $s2, 0x28($sp)
/* 174F0C 8024C4EC 8FB10024 */  lw         $s1, 0x24($sp)
/* 174F10 8024C4F0 8FB00020 */  lw         $s0, 0x20($sp)
/* 174F14 8024C4F4 03E00008 */  jr         $ra
/* 174F18 8024C4F8 27BD0040 */   addiu     $sp, $sp, 0x40
