.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
glabel jtbl_PAL_802ABA38
/* 4732E8 802ABA38 802A38AC */ .word .LPAL_802A38AC
/* 4732EC 802ABA3C 802A3718 */ .word .LPAL_802A3718
/* 4732F0 802ABA40 802A2C84 */ .word .LPAL_802A2C84
/* 4732F4 802ABA44 802A3490 */ .word .LPAL_802A3490
/* 4732F8 802ABA48 802A3C6C */ .word .LPAL_802A3C6C
/* 4732FC 802ABA4C 802A3C6C */ .word .LPAL_802A3C6C
/* 473300 802ABA50 802A3C6C */ .word .LPAL_802A3C6C
/* 473304 802ABA54 802A3C6C */ .word .LPAL_802A3C6C
/* 473308 802ABA58 802A3C6C */ .word .LPAL_802A3C6C
/* 47330C 802ABA5C 802A3C6C */ .word .LPAL_802A3C6C
/* 473310 802ABA60 802A3C6C */ .word .LPAL_802A3C6C
/* 473314 802ABA64 802A3C6C */ .word .LPAL_802A3C6C
/* 473318 802ABA68 802A38DC */ .word .LPAL_802A38DC
/* 47331C 802ABA6C 802A3974 */ .word .LPAL_802A3974
/* 473320 802ABA70 802A3C6C */ .word .LPAL_802A3C6C
/* 473324 802ABA74 802A3C6C */ .word .LPAL_802A3C6C
/* 473328 802ABA78 802A3C6C */ .word .LPAL_802A3C6C
/* 47332C 802ABA7C 802A3C6C */ .word .LPAL_802A3C6C
/* 473330 802ABA80 802A3C6C */ .word .LPAL_802A3C6C
/* 473334 802ABA84 802A3C6C */ .word .LPAL_802A3C6C
/* 473338 802ABA88 802A3C6C */ .word .LPAL_802A3C6C
/* 47333C 802ABA8C 802A3C6C */ .word .LPAL_802A3C6C
/* 473340 802ABA90 802A399C */ .word .LPAL_802A399C
/* 473344 802ABA94 802A3C6C */ .word .LPAL_802A3C6C
/* 473348 802ABA98 802A3C6C */ .word .LPAL_802A3C6C
/* 47334C 802ABA9C 802A3C6C */ .word .LPAL_802A3C6C
/* 473350 802ABAA0 802A3C6C */ .word .LPAL_802A3C6C
/* 473354 802ABAA4 802A3C6C */ .word .LPAL_802A3C6C
/* 473358 802ABAA8 802A3C6C */ .word .LPAL_802A3C6C
/* 47335C 802ABAAC 802A3C6C */ .word .LPAL_802A3C6C
/* 473360 802ABAB0 802A3C6C */ .word .LPAL_802A3C6C
/* 473364 802ABAB4 802A3C6C */ .word .LPAL_802A3C6C
/* 473368 802ABAB8 802A3A20 */ .word .LPAL_802A3A20
/* 47336C 802ABABC 802A3C6C */ .word .LPAL_802A3C6C
/* 473370 802ABAC0 802A3C6C */ .word .LPAL_802A3C6C
/* 473374 802ABAC4 802A3C6C */ .word .LPAL_802A3C6C
/* 473378 802ABAC8 802A3C6C */ .word .LPAL_802A3C6C
/* 47337C 802ABACC 802A3C6C */ .word .LPAL_802A3C6C
/* 473380 802ABAD0 802A3C6C */ .word .LPAL_802A3C6C
/* 473384 802ABAD4 802A3C6C */ .word .LPAL_802A3C6C
/* 473388 802ABAD8 802A3C6C */ .word .LPAL_802A3C6C
/* 47338C 802ABADC 802A3C6C */ .word .LPAL_802A3C6C
/* 473390 802ABAE0 802A3A78 */ .word .LPAL_802A3A78
/* 473394 802ABAE4 802A3A9C */ .word .LPAL_802A3A9C
/* 473398 802ABAE8 802A3BC0 */ .word .LPAL_802A3BC0
/* 47339C 802ABAEC 00000000 */ .word 0x00000000


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel btl_submenu_moves_update
/* 46A4D4 802A2C24 3C02802B */  lui        $v0, %hi(D_802AD348)
/* 46A4D8 802A2C28 9042D348 */  lbu        $v0, %lo(D_802AD348)($v0)
/* 46A4DC 802A2C2C 27BDFFB8 */  addiu      $sp, $sp, -0x48
/* 46A4E0 802A2C30 AFB1002C */  sw         $s1, 0x2C($sp)
/* 46A4E4 802A2C34 3C11800E */  lui        $s1, %hi(D_800D87E0)
/* 46A4E8 802A2C38 263187E0 */  addiu      $s1, $s1, %lo(D_800D87E0)
/* 46A4EC 802A2C3C AFBF0044 */  sw         $ra, 0x44($sp)
/* 46A4F0 802A2C40 AFB60040 */  sw         $s6, 0x40($sp)
/* 46A4F4 802A2C44 AFB5003C */  sw         $s5, 0x3C($sp)
/* 46A4F8 802A2C48 AFB40038 */  sw         $s4, 0x38($sp)
/* 46A4FC 802A2C4C AFB30034 */  sw         $s3, 0x34($sp)
/* 46A500 802A2C50 AFB20030 */  sw         $s2, 0x30($sp)
/* 46A504 802A2C54 24420002 */  addiu      $v0, $v0, 0x2
/* 46A508 802A2C58 00021600 */  sll        $v0, $v0, 24
/* 46A50C 802A2C5C 00021E03 */  sra        $v1, $v0, 24
/* 46A510 802A2C60 2C62002D */  sltiu      $v0, $v1, 0x2D
/* 46A514 802A2C64 10400401 */  beqz       $v0, .LPAL_802A3C6C
/* 46A518 802A2C68 AFB00028 */   sw        $s0, 0x28($sp)
/* 46A51C 802A2C6C 00031080 */  sll        $v0, $v1, 2
/* 46A520 802A2C70 3C01802B */  lui        $at, %hi(jtbl_PAL_802ABA38)
/* 46A524 802A2C74 00220821 */  addu       $at, $at, $v0
/* 46A528 802A2C78 8C22BA38 */  lw         $v0, %lo(jtbl_PAL_802ABA38)($at)
/* 46A52C 802A2C7C 00400008 */  jr         $v0
/* 46A530 802A2C80 00000000 */   nop
.LPAL_802A2C84:
/* 46A534 802A2C84 3C05802B */  lui        $a1, %hi(D_802AD34C)
/* 46A538 802A2C88 80A5D34C */  lb         $a1, %lo(D_802AD34C)($a1)
/* 46A53C 802A2C8C 3C04802B */  lui        $a0, %hi(D_802AD349)
/* 46A540 802A2C90 8084D349 */  lb         $a0, %lo(D_802AD349)($a0)
/* 46A544 802A2C94 24020014 */  addiu      $v0, $zero, 0x14
/* 46A548 802A2C98 3C01802B */  lui        $at, %hi(D_802AD430)
/* 46A54C 802A2C9C A422D430 */  sh         $v0, %lo(D_802AD430)($at)
/* 46A550 802A2CA0 24020044 */  addiu      $v0, $zero, 0x44
/* 46A554 802A2CA4 3C01802B */  lui        $at, %hi(D_802AD432)
/* 46A558 802A2CA8 A422D432 */  sh         $v0, %lo(D_802AD432)($at)
/* 46A55C 802A2CAC 00051823 */  negu       $v1, $a1
/* 46A560 802A2CB0 00031040 */  sll        $v0, $v1, 1
/* 46A564 802A2CB4 00431021 */  addu       $v0, $v0, $v1
/* 46A568 802A2CB8 00021080 */  sll        $v0, $v0, 2
/* 46A56C 802A2CBC 00431021 */  addu       $v0, $v0, $v1
/* 46A570 802A2CC0 00852023 */  subu       $a0, $a0, $a1
/* 46A574 802A2CC4 3C01802B */  lui        $at, %hi(D_802AD350)
/* 46A578 802A2CC8 A422D350 */  sh         $v0, %lo(D_802AD350)($at)
/* 46A57C 802A2CCC 00041040 */  sll        $v0, $a0, 1
/* 46A580 802A2CD0 00441021 */  addu       $v0, $v0, $a0
/* 46A584 802A2CD4 00021080 */  sll        $v0, $v0, 2
/* 46A588 802A2CD8 3C05802B */  lui        $a1, %hi(D_802AD6E4)
/* 46A58C 802A2CDC 24A5D6E4 */  addiu      $a1, $a1, %lo(D_802AD6E4)
/* 46A590 802A2CE0 8CA30000 */  lw         $v1, 0x0($a1)
/* 46A594 802A2CE4 00441021 */  addu       $v0, $v0, $a0
/* 46A598 802A2CE8 3C01802B */  lui        $at, %hi(D_802AD352)
/* 46A59C 802A2CEC A422D352 */  sh         $v0, %lo(D_802AD352)($at)
/* 46A5A0 802A2CF0 18600009 */  blez       $v1, .LPAL_802A2D18
/* 46A5A4 802A2CF4 0000802D */   daddu     $s0, $zero, $zero
/* 46A5A8 802A2CF8 3C03802B */  lui        $v1, %hi(D_802AD438)
/* 46A5AC 802A2CFC 2463D438 */  addiu      $v1, $v1, %lo(D_802AD438)
.LPAL_802A2D00:
/* 46A5B0 802A2D00 AC700000 */  sw         $s0, 0x0($v1)
/* 46A5B4 802A2D04 8CA20000 */  lw         $v0, 0x0($a1)
/* 46A5B8 802A2D08 26100001 */  addiu      $s0, $s0, 0x1
/* 46A5BC 802A2D0C 0202102A */  slt        $v0, $s0, $v0
/* 46A5C0 802A2D10 1440FFFB */  bnez       $v0, .LPAL_802A2D00
/* 46A5C4 802A2D14 24630004 */   addiu     $v1, $v1, 0x4
.LPAL_802A2D18:
/* 46A5C8 802A2D18 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46A5CC 802A2D1C 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46A5D0 802A2D20 14400042 */  bnez       $v0, .LPAL_802A2E2C
/* 46A5D4 802A2D24 00000000 */   nop
/* 46A5D8 802A2D28 3C03802B */  lui        $v1, %hi(D_802AD6E4)
/* 46A5DC 802A2D2C 8C63D6E4 */  lw         $v1, %lo(D_802AD6E4)($v1)
/* 46A5E0 802A2D30 2462FFFF */  addiu      $v0, $v1, -0x1
/* 46A5E4 802A2D34 1840003D */  blez       $v0, .LPAL_802A2E2C
/* 46A5E8 802A2D38 0000802D */   daddu     $s0, $zero, $zero
/* 46A5EC 802A2D3C 0060882D */  daddu      $s1, $v1, $zero
/* 46A5F0 802A2D40 3C0E802B */  lui        $t6, %hi(D_802AD810)
/* 46A5F4 802A2D44 25CED810 */  addiu      $t6, $t6, %lo(D_802AD810)
/* 46A5F8 802A2D48 3C0D802B */  lui        $t5, %hi(D_802AD560)
/* 46A5FC 802A2D4C 25ADD560 */  addiu      $t5, $t5, %lo(D_802AD560)
/* 46A600 802A2D50 3C0C802B */  lui        $t4, %hi(D_802AD680)
/* 46A604 802A2D54 258CD680 */  addiu      $t4, $t4, %lo(D_802AD680)
/* 46A608 802A2D58 3C0F802B */  lui        $t7, %hi(D_802AD438)
/* 46A60C 802A2D5C 25EFD438 */  addiu      $t7, $t7, %lo(D_802AD438)
/* 46A610 802A2D60 01E0502D */  daddu      $t2, $t7, $zero
.LPAL_802A2D64:
/* 46A614 802A2D64 26090001 */  addiu      $t1, $s0, 0x1
/* 46A618 802A2D68 0131102A */  slt        $v0, $t1, $s1
/* 46A61C 802A2D6C 10400028 */  beqz       $v0, .LPAL_802A2E10
/* 46A620 802A2D70 00091080 */   sll       $v0, $t1, 2
/* 46A624 802A2D74 0140402D */  daddu      $t0, $t2, $zero
/* 46A628 802A2D78 3C0B802B */  lui        $t3, %hi(D_802AD6E4)
/* 46A62C 802A2D7C 8D6BD6E4 */  lw         $t3, %lo(D_802AD6E4)($t3)
/* 46A630 802A2D80 004F3821 */  addu       $a3, $v0, $t7
.LPAL_802A2D84:
/* 46A634 802A2D84 8D060000 */  lw         $a2, 0x0($t0)
/* 46A638 802A2D88 8CE40000 */  lw         $a0, 0x0($a3)
/* 46A63C 802A2D8C 00CE1021 */  addu       $v0, $a2, $t6
/* 46A640 802A2D90 008E1821 */  addu       $v1, $a0, $t6
/* 46A644 802A2D94 80450000 */  lb         $a1, 0x0($v0)
/* 46A648 802A2D98 80630000 */  lb         $v1, 0x0($v1)
/* 46A64C 802A2D9C 00A3102A */  slt        $v0, $a1, $v1
/* 46A650 802A2DA0 54400018 */  bnel       $v0, $zero, .LPAL_802A2E04
/* 46A654 802A2DA4 25290001 */   addiu     $t1, $t1, 0x1
/* 46A658 802A2DA8 14A30011 */  bne        $a1, $v1, .LPAL_802A2DF0
/* 46A65C 802A2DAC 00063080 */   sll       $a2, $a2, 2
/* 46A660 802A2DB0 00CD1821 */  addu       $v1, $a2, $t5
/* 46A664 802A2DB4 00042080 */  sll        $a0, $a0, 2
/* 46A668 802A2DB8 008D1021 */  addu       $v0, $a0, $t5
/* 46A66C 802A2DBC 8C630000 */  lw         $v1, 0x0($v1)
/* 46A670 802A2DC0 8C450000 */  lw         $a1, 0x0($v0)
/* 46A674 802A2DC4 0065102A */  slt        $v0, $v1, $a1
/* 46A678 802A2DC8 5440000E */  bnel       $v0, $zero, .LPAL_802A2E04
/* 46A67C 802A2DCC 25290001 */   addiu     $t1, $t1, 0x1
/* 46A680 802A2DD0 14650007 */  bne        $v1, $a1, .LPAL_802A2DF0
/* 46A684 802A2DD4 00CC1021 */   addu      $v0, $a2, $t4
/* 46A688 802A2DD8 008C2021 */  addu       $a0, $a0, $t4
/* 46A68C 802A2DDC 8C430000 */  lw         $v1, 0x0($v0)
/* 46A690 802A2DE0 8C820000 */  lw         $v0, 0x0($a0)
/* 46A694 802A2DE4 0062182A */  slt        $v1, $v1, $v0
/* 46A698 802A2DE8 54600006 */  bnel       $v1, $zero, .LPAL_802A2E04
/* 46A69C 802A2DEC 25290001 */   addiu     $t1, $t1, 0x1
.LPAL_802A2DF0:
/* 46A6A0 802A2DF0 8CE20000 */  lw         $v0, 0x0($a3)
/* 46A6A4 802A2DF4 8D030000 */  lw         $v1, 0x0($t0)
/* 46A6A8 802A2DF8 AD020000 */  sw         $v0, 0x0($t0)
/* 46A6AC 802A2DFC ACE30000 */  sw         $v1, 0x0($a3)
/* 46A6B0 802A2E00 25290001 */  addiu      $t1, $t1, 0x1
.LPAL_802A2E04:
/* 46A6B4 802A2E04 012B102A */  slt        $v0, $t1, $t3
/* 46A6B8 802A2E08 1440FFDE */  bnez       $v0, .LPAL_802A2D84
/* 46A6BC 802A2E0C 24E70004 */   addiu     $a3, $a3, 0x4
.LPAL_802A2E10:
/* 46A6C0 802A2E10 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46A6C4 802A2E14 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46A6C8 802A2E18 26100001 */  addiu      $s0, $s0, 0x1
/* 46A6CC 802A2E1C 2442FFFF */  addiu      $v0, $v0, -0x1
/* 46A6D0 802A2E20 0202102A */  slt        $v0, $s0, $v0
/* 46A6D4 802A2E24 1440FFCF */  bnez       $v0, .LPAL_802A2D64
/* 46A6D8 802A2E28 254A0004 */   addiu     $t2, $t2, 0x4
.LPAL_802A2E2C:
/* 46A6DC 802A2E2C 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46A6E0 802A2E30 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46A6E4 802A2E34 1840001C */  blez       $v0, .LPAL_802A2EA8
/* 46A6E8 802A2E38 0000802D */   daddu     $s0, $zero, $zero
/* 46A6EC 802A2E3C 3C14802B */  lui        $s4, %hi(D_802AD4A0)
/* 46A6F0 802A2E40 2694D4A0 */  addiu      $s4, $s4, %lo(D_802AD4A0)
/* 46A6F4 802A2E44 3C13802B */  lui        $s3, %hi(D_802AD368)
/* 46A6F8 802A2E48 2673D368 */  addiu      $s3, $s3, %lo(D_802AD368)
/* 46A6FC 802A2E4C 3C11802B */  lui        $s1, %hi(D_802AD438)
/* 46A700 802A2E50 2631D438 */  addiu      $s1, $s1, %lo(D_802AD438)
.LPAL_802A2E54:
/* 46A704 802A2E54 8E220000 */  lw         $v0, 0x0($s1)
/* 46A708 802A2E58 26310004 */  addiu      $s1, $s1, 0x4
/* 46A70C 802A2E5C 00021080 */  sll        $v0, $v0, 2
/* 46A710 802A2E60 00541021 */  addu       $v0, $v0, $s4
/* 46A714 802A2E64 8C440000 */  lw         $a0, 0x0($v0)
/* 46A718 802A2E68 0C050015 */  jal        func_PAL_80140054
/* 46A71C 802A2E6C 26100001 */   addiu     $s0, $s0, 0x1
/* 46A720 802A2E70 0040902D */  daddu      $s2, $v0, $zero
/* 46A724 802A2E74 3C053EE6 */  lui        $a1, (0x3EE66666 >> 16)
/* 46A728 802A2E78 34A56666 */  ori        $a1, $a1, (0x3EE66666 & 0xFFFF)
/* 46A72C 802A2E7C 0240202D */  daddu      $a0, $s2, $zero
/* 46A730 802A2E80 0C050DF4 */  jal        func_PAL_801437D0
/* 46A734 802A2E84 AE720000 */   sw        $s2, 0x0($s3)
/* 46A738 802A2E88 0240202D */  daddu      $a0, $s2, $zero
/* 46A73C 802A2E8C 0C050D6C */  jal        func_PAL_801435B0
/* 46A740 802A2E90 34058080 */   ori       $a1, $zero, 0x8080
/* 46A744 802A2E94 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46A748 802A2E98 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46A74C 802A2E9C 0202102A */  slt        $v0, $s0, $v0
/* 46A750 802A2EA0 1440FFEC */  bnez       $v0, .LPAL_802A2E54
/* 46A754 802A2EA4 26730004 */   addiu     $s3, $s3, 0x4
.LPAL_802A2EA8:
/* 46A758 802A2EA8 3C048010 */  lui        $a0, %hi(D_PAL_80102D18)
/* 46A75C 802A2EAC 24842D18 */  addiu      $a0, $a0, %lo(D_PAL_80102D18)
/* 46A760 802A2EB0 0C050015 */  jal        func_PAL_80140054
/* 46A764 802A2EB4 00000000 */   nop
/* 46A768 802A2EB8 0040902D */  daddu      $s2, $v0, $zero
/* 46A76C 802A2EBC 0240202D */  daddu      $a0, $s2, $zero
/* 46A770 802A2EC0 3C052000 */  lui        $a1, (0x20000080 >> 16)
/* 46A774 802A2EC4 3C01802B */  lui        $at, %hi(D_802AD358)
/* 46A778 802A2EC8 AC32D358 */  sw         $s2, %lo(D_802AD358)($at)
/* 46A77C 802A2ECC 0C050D6C */  jal        func_PAL_801435B0
/* 46A780 802A2ED0 34A50080 */   ori       $a1, $a1, (0x20000080 & 0xFFFF)
/* 46A784 802A2ED4 3C11802B */  lui        $s1, %hi(D_802AD430)
/* 46A788 802A2ED8 2631D430 */  addiu      $s1, $s1, %lo(D_802AD430)
/* 46A78C 802A2EDC 3C10802B */  lui        $s0, %hi(D_802AD432)
/* 46A790 802A2EE0 2610D432 */  addiu      $s0, $s0, %lo(D_802AD432)
/* 46A794 802A2EE4 86250000 */  lh         $a1, 0x0($s1)
/* 46A798 802A2EE8 86060000 */  lh         $a2, 0x0($s0)
/* 46A79C 802A2EEC 0C050D4D */  jal        func_PAL_80143534
/* 46A7A0 802A2EF0 0240202D */   daddu     $a0, $s2, $zero
/* 46A7A4 802A2EF4 3C048010 */  lui        $a0, %hi(D_PAL_80105EF4)
/* 46A7A8 802A2EF8 24845EF4 */  addiu      $a0, $a0, %lo(D_PAL_80105EF4)
/* 46A7AC 802A2EFC 0C050015 */  jal        func_PAL_80140054
/* 46A7B0 802A2F00 00000000 */   nop
/* 46A7B4 802A2F04 0040902D */  daddu      $s2, $v0, $zero
/* 46A7B8 802A2F08 0240202D */  daddu      $a0, $s2, $zero
/* 46A7BC 802A2F0C 3C052000 */  lui        $a1, (0x20000080 >> 16)
/* 46A7C0 802A2F10 3C01802B */  lui        $at, %hi(D_802AD35C)
/* 46A7C4 802A2F14 AC32D35C */  sw         $s2, %lo(D_802AD35C)($at)
/* 46A7C8 802A2F18 0C050D6C */  jal        func_PAL_801435B0
/* 46A7CC 802A2F1C 34A50080 */   ori       $a1, $a1, (0x20000080 & 0xFFFF)
/* 46A7D0 802A2F20 0240202D */  daddu      $a0, $s2, $zero
/* 46A7D4 802A2F24 86250000 */  lh         $a1, 0x0($s1)
/* 46A7D8 802A2F28 86060000 */  lh         $a2, 0x0($s0)
/* 46A7DC 802A2F2C 24A50027 */  addiu      $a1, $a1, 0x27
/* 46A7E0 802A2F30 0C050D4D */  jal        func_PAL_80143534
/* 46A7E4 802A2F34 24C6FFF9 */   addiu     $a2, $a2, -0x7
/* 46A7E8 802A2F38 3C048010 */  lui        $a0, %hi(D_PAL_80105EA8)
/* 46A7EC 802A2F3C 24845EA8 */  addiu      $a0, $a0, %lo(D_PAL_80105EA8)
/* 46A7F0 802A2F40 0C050015 */  jal        func_PAL_80140054
/* 46A7F4 802A2F44 00000000 */   nop
/* 46A7F8 802A2F48 0040902D */  daddu      $s2, $v0, $zero
/* 46A7FC 802A2F4C 0240202D */  daddu      $a0, $s2, $zero
/* 46A800 802A2F50 3C052000 */  lui        $a1, (0x20000080 >> 16)
/* 46A804 802A2F54 3C01802B */  lui        $at, %hi(D_802AD360)
/* 46A808 802A2F58 AC32D360 */  sw         $s2, %lo(D_802AD360)($at)
/* 46A80C 802A2F5C 0C050D6C */  jal        func_PAL_801435B0
/* 46A810 802A2F60 34A50080 */   ori       $a1, $a1, (0x20000080 & 0xFFFF)
/* 46A814 802A2F64 0240202D */  daddu      $a0, $s2, $zero
/* 46A818 802A2F68 86250000 */  lh         $a1, 0x0($s1)
/* 46A81C 802A2F6C 86060000 */  lh         $a2, 0x0($s0)
/* 46A820 802A2F70 24A50027 */  addiu      $a1, $a1, 0x27
/* 46A824 802A2F74 0C050D4D */  jal        func_PAL_80143534
/* 46A828 802A2F78 24C6004E */   addiu     $a2, $a2, 0x4E
/* 46A82C 802A2F7C 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46A830 802A2F80 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46A834 802A2F84 1440000A */  bnez       $v0, .LPAL_802A2FB0
/* 46A838 802A2F88 00000000 */   nop
/* 46A83C 802A2F8C 3C048010 */  lui        $a0, %hi(D_PAL_80106D38)
/* 46A840 802A2F90 24846D38 */  addiu      $a0, $a0, %lo(D_PAL_80106D38)
/* 46A844 802A2F94 0C050015 */  jal        func_PAL_80140054
/* 46A848 802A2F98 00000000 */   nop
/* 46A84C 802A2F9C 0040902D */  daddu      $s2, $v0, $zero
/* 46A850 802A2FA0 3C01802B */  lui        $at, %hi(D_802AD3C8)
/* 46A854 802A2FA4 AC22D3C8 */  sw         $v0, %lo(D_802AD3C8)($at)
/* 46A858 802A2FA8 080A8BF7 */  j          .LPAL_802A2FDC
/* 46A85C 802A2FAC 0240202D */   daddu     $a0, $s2, $zero
.LPAL_802A2FB0:
/* 46A860 802A2FB0 3C048010 */  lui        $a0, %hi(D_80107174)
/* 46A864 802A2FB4 24847174 */  addiu      $a0, $a0, %lo(D_80107174)
/* 46A868 802A2FB8 0C050015 */  jal        func_PAL_80140054
/* 46A86C 802A2FBC 00000000 */   nop
/* 46A870 802A2FC0 0040902D */  daddu      $s2, $v0, $zero
/* 46A874 802A2FC4 3C053F40 */  lui        $a1, (0x3F400000 >> 16)
/* 46A878 802A2FC8 3C01802B */  lui        $at, %hi(D_802AD3C8)
/* 46A87C 802A2FCC AC32D3C8 */  sw         $s2, %lo(D_802AD3C8)($at)
/* 46A880 802A2FD0 0C050DF4 */  jal        func_PAL_801437D0
/* 46A884 802A2FD4 0240202D */   daddu     $a0, $s2, $zero
/* 46A888 802A2FD8 0240202D */  daddu      $a0, $s2, $zero
.LPAL_802A2FDC:
/* 46A88C 802A2FDC 0C050D6C */  jal        func_PAL_801435B0
/* 46A890 802A2FE0 24050080 */   addiu     $a1, $zero, 0x80
/* 46A894 802A2FE4 0240202D */  daddu      $a0, $s2, $zero
/* 46A898 802A2FE8 3C05802B */  lui        $a1, %hi(D_802AD430)
/* 46A89C 802A2FEC 84A5D430 */  lh         $a1, %lo(D_802AD430)($a1)
/* 46A8A0 802A2FF0 3C06802B */  lui        $a2, %hi(D_802AD432)
/* 46A8A4 802A2FF4 84C6D432 */  lh         $a2, %lo(D_802AD432)($a2)
/* 46A8A8 802A2FF8 0C050D4D */  jal        func_PAL_80143534
/* 46A8AC 802A2FFC 24A50038 */   addiu     $a1, $a1, 0x38
/* 46A8B0 802A3000 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46A8B4 802A3004 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46A8B8 802A3008 1840003D */  blez       $v0, .LPAL_802A3100
/* 46A8BC 802A300C 0000802D */   daddu     $s0, $zero, $zero
/* 46A8C0 802A3010 24140001 */  addiu      $s4, $zero, 0x1
/* 46A8C4 802A3014 3C16802B */  lui        $s6, %hi(D_PAL_802AB4FC)
/* 46A8C8 802A3018 26D6B4FC */  addiu      $s6, $s6, %lo(D_PAL_802AB4FC)
/* 46A8CC 802A301C 3C15802B */  lui        $s5, %hi(D_PAL_802AB53C)
/* 46A8D0 802A3020 26B5B53C */  addiu      $s5, $s5, %lo(D_PAL_802AB53C)
/* 46A8D4 802A3024 3C13802B */  lui        $s3, %hi(D_802AD3D0)
/* 46A8D8 802A3028 2673D3D0 */  addiu      $s3, $s3, %lo(D_802AD3D0)
/* 46A8DC 802A302C 3C11802B */  lui        $s1, %hi(D_802AD620)
/* 46A8E0 802A3030 2631D620 */  addiu      $s1, $s1, %lo(D_802AD620)
.LPAL_802A3034:
/* 46A8E4 802A3034 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46A8E8 802A3038 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46A8EC 802A303C 1440000E */  bnez       $v0, .LPAL_802A3078
/* 46A8F0 802A3040 00000000 */   nop
/* 46A8F4 802A3044 8E220000 */  lw         $v0, 0x0($s1)
/* 46A8F8 802A3048 10400004 */  beqz       $v0, .LPAL_802A305C
/* 46A8FC 802A304C 0000902D */   daddu     $s2, $zero, $zero
/* 46A900 802A3050 14540002 */  bne        $v0, $s4, .LPAL_802A305C
/* 46A904 802A3054 24120002 */   addiu     $s2, $zero, 0x2
/* 46A908 802A3058 24120001 */  addiu      $s2, $zero, 0x1
.LPAL_802A305C:
/* 46A90C 802A305C 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 46A910 802A3060 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 46A914 802A3064 00121900 */  sll        $v1, $s2, 4
/* 46A918 802A3068 00021080 */  sll        $v0, $v0, 2
/* 46A91C 802A306C 00431021 */  addu       $v0, $v0, $v1
/* 46A920 802A3070 080A8C2A */  j          .LPAL_802A30A8
/* 46A924 802A3074 00561021 */   addu      $v0, $v0, $s6
.LPAL_802A3078:
/* 46A928 802A3078 8E220000 */  lw         $v0, 0x0($s1)
/* 46A92C 802A307C 10400004 */  beqz       $v0, .LPAL_802A3090
/* 46A930 802A3080 0000902D */   daddu     $s2, $zero, $zero
/* 46A934 802A3084 14540002 */  bne        $v0, $s4, .LPAL_802A3090
/* 46A938 802A3088 24120002 */   addiu     $s2, $zero, 0x2
/* 46A93C 802A308C 24120001 */  addiu      $s2, $zero, 0x1
.LPAL_802A3090:
/* 46A940 802A3090 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 46A944 802A3094 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 46A948 802A3098 00121900 */  sll        $v1, $s2, 4
/* 46A94C 802A309C 00021080 */  sll        $v0, $v0, 2
/* 46A950 802A30A0 00431021 */  addu       $v0, $v0, $v1
/* 46A954 802A30A4 00551021 */  addu       $v0, $v0, $s5
.LPAL_802A30A8:
/* 46A958 802A30A8 8C440000 */  lw         $a0, 0x0($v0)
/* 46A95C 802A30AC 0C050015 */  jal        func_PAL_80140054
/* 46A960 802A30B0 26310004 */   addiu     $s1, $s1, 0x4
/* 46A964 802A30B4 0040902D */  daddu      $s2, $v0, $zero
/* 46A968 802A30B8 AE720000 */  sw         $s2, 0x0($s3)
/* 46A96C 802A30BC 0240202D */  daddu      $a0, $s2, $zero
/* 46A970 802A30C0 0C050D6C */  jal        func_PAL_801435B0
/* 46A974 802A30C4 24050080 */   addiu     $a1, $zero, 0x80
/* 46A978 802A30C8 0240202D */  daddu      $a0, $s2, $zero
/* 46A97C 802A30CC 26730004 */  addiu      $s3, $s3, 0x4
/* 46A980 802A30D0 3C05802B */  lui        $a1, %hi(D_802AD430)
/* 46A984 802A30D4 84A5D430 */  lh         $a1, %lo(D_802AD430)($a1)
/* 46A988 802A30D8 3C06802B */  lui        $a2, %hi(D_802AD432)
/* 46A98C 802A30DC 84C6D432 */  lh         $a2, %lo(D_802AD432)($a2)
/* 46A990 802A30E0 0C050D4D */  jal        func_PAL_80143534
/* 46A994 802A30E4 24A50038 */   addiu     $a1, $a1, 0x38
/* 46A998 802A30E8 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46A99C 802A30EC 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46A9A0 802A30F0 26100001 */  addiu      $s0, $s0, 0x1
/* 46A9A4 802A30F4 0202102A */  slt        $v0, $s0, $v0
/* 46A9A8 802A30F8 1440FFCE */  bnez       $v0, .LPAL_802A3034
/* 46A9AC 802A30FC 00000000 */   nop
.LPAL_802A3100:
/* 46A9B0 802A3100 3C14802B */  lui        $s4, %hi(D_802AD430)
/* 46A9B4 802A3104 8694D430 */  lh         $s4, %lo(D_802AD430)($s4)
/* 46A9B8 802A3108 2402000A */  addiu      $v0, $zero, 0xA
/* 46A9BC 802A310C 3C01802B */  lui        $at, %hi(D_802AD354)
/* 46A9C0 802A3110 A422D354 */  sh         $v0, %lo(D_802AD354)($at)
/* 46A9C4 802A3114 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46A9C8 802A3118 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46A9CC 802A311C 3C13802B */  lui        $s3, %hi(D_802AD432)
/* 46A9D0 802A3120 8673D432 */  lh         $s3, %lo(D_802AD432)($s3)
/* 46A9D4 802A3124 1440003E */  bnez       $v0, .LPAL_802A3220
/* 46A9D8 802A3128 24040001 */   addiu     $a0, $zero, 0x1
/* 46A9DC 802A312C 0280282D */  daddu      $a1, $s4, $zero
/* 46A9E0 802A3130 0260302D */  daddu      $a2, $s3, $zero
/* 46A9E4 802A3134 3C118015 */  lui        $s1, %hi(gCurrentLanguage)
/* 46A9E8 802A3138 2631AE4C */  addiu      $s1, $s1, %lo(gCurrentLanguage)
/* 46A9EC 802A313C 2410FFFF */  addiu      $s0, $zero, -0x1
/* 46A9F0 802A3140 3C03802B */  lui        $v1, %hi(D_802AD34E)
/* 46A9F4 802A3144 8063D34E */  lb         $v1, %lo(D_802AD34E)($v1)
/* 46A9F8 802A3148 8E270000 */  lw         $a3, 0x0($s1)
/* 46A9FC 802A314C 00831004 */  sllv       $v0, $v1, $a0
/* 46AA00 802A3150 00431021 */  addu       $v0, $v0, $v1
/* 46AA04 802A3154 00021080 */  sll        $v0, $v0, 2
/* 46AA08 802A3158 00431021 */  addu       $v0, $v0, $v1
/* 46AA0C 802A315C 3C01802B */  lui        $at, %hi(D_PAL_802AB4E4)
/* 46AA10 802A3160 00270821 */  addu       $at, $at, $a3
/* 46AA14 802A3164 9027B4E4 */  lbu        $a3, %lo(D_PAL_802AB4E4)($at)
/* 46AA18 802A3168 2442001C */  addiu      $v0, $v0, 0x1C
/* 46AA1C 802A316C AFA20010 */  sw         $v0, 0x10($sp)
/* 46AA20 802A3170 3C02802A */  lui        $v0, %hi(func_PAL_802A3C98)
/* 46AA24 802A3174 24423C98 */  addiu      $v0, $v0, %lo(func_PAL_802A3C98)
/* 46AA28 802A3178 AFA00014 */  sw         $zero, 0x14($sp)
/* 46AA2C 802A317C AFA20018 */  sw         $v0, 0x18($sp)
/* 46AA30 802A3180 AFA0001C */  sw         $zero, 0x1C($sp)
/* 46AA34 802A3184 0C051A1E */  jal        func_PAL_80146878
/* 46AA38 802A3188 AFB00020 */   sw        $s0, 0x20($sp)
/* 46AA3C 802A318C 24040002 */  addiu      $a0, $zero, 0x2
/* 46AA40 802A3190 2666FFFA */  addiu      $a2, $s3, -0x6
/* 46AA44 802A3194 8E220000 */  lw         $v0, 0x0($s1)
/* 46AA48 802A3198 24120001 */  addiu      $s2, $zero, 0x1
/* 46AA4C 802A319C 3C05802B */  lui        $a1, %hi(D_PAL_802AB4EC)
/* 46AA50 802A31A0 00A22821 */  addu       $a1, $a1, $v0
/* 46AA54 802A31A4 90A5B4EC */  lbu        $a1, %lo(D_PAL_802AB4EC)($a1)
/* 46AA58 802A31A8 3C07802B */  lui        $a3, %hi(D_PAL_802AB4F0)
/* 46AA5C 802A31AC 00E23821 */  addu       $a3, $a3, $v0
/* 46AA60 802A31B0 90E7B4F0 */  lbu        $a3, %lo(D_PAL_802AB4F0)($a3)
/* 46AA64 802A31B4 24020010 */  addiu      $v0, $zero, 0x10
/* 46AA68 802A31B8 AFA20010 */  sw         $v0, 0x10($sp)
/* 46AA6C 802A31BC 3C02802A */  lui        $v0, %hi(func_PAL_802A446C)
/* 46AA70 802A31C0 2442446C */  addiu      $v0, $v0, %lo(func_PAL_802A446C)
/* 46AA74 802A31C4 AFB20014 */  sw         $s2, 0x14($sp)
/* 46AA78 802A31C8 AFA20018 */  sw         $v0, 0x18($sp)
/* 46AA7C 802A31CC AFA0001C */  sw         $zero, 0x1C($sp)
/* 46AA80 802A31D0 AFB00020 */  sw         $s0, 0x20($sp)
/* 46AA84 802A31D4 0C051A1E */  jal        func_PAL_80146878
/* 46AA88 802A31D8 02852821 */   addu      $a1, $s4, $a1
/* 46AA8C 802A31DC 24040003 */  addiu      $a0, $zero, 0x3
/* 46AA90 802A31E0 2666FFF4 */  addiu      $a2, $s3, -0xC
/* 46AA94 802A31E4 8E220000 */  lw         $v0, 0x0($s1)
/* 46AA98 802A31E8 24070020 */  addiu      $a3, $zero, 0x20
/* 46AA9C 802A31EC 3C05802B */  lui        $a1, %hi(D_PAL_802AB4F8)
/* 46AAA0 802A31F0 00A22821 */  addu       $a1, $a1, $v0
/* 46AAA4 802A31F4 90A5B4F8 */  lbu        $a1, %lo(D_PAL_802AB4F8)($a1)
/* 46AAA8 802A31F8 00E0102D */  daddu      $v0, $a3, $zero
/* 46AAAC 802A31FC AFA20010 */  sw         $v0, 0x10($sp)
/* 46AAB0 802A3200 3C02802A */  lui        $v0, %hi(func_PAL_802A4500)
/* 46AAB4 802A3204 24424500 */  addiu      $v0, $v0, %lo(func_PAL_802A4500)
/* 46AAB8 802A3208 AFB20014 */  sw         $s2, 0x14($sp)
/* 46AABC 802A320C AFA20018 */  sw         $v0, 0x18($sp)
/* 46AAC0 802A3210 AFA0001C */  sw         $zero, 0x1C($sp)
/* 46AAC4 802A3214 AFB00020 */  sw         $s0, 0x20($sp)
/* 46AAC8 802A3218 080A8CC4 */  j          .LPAL_802A3310
/* 46AACC 802A321C 24A50078 */   addiu     $a1, $a1, 0x78
.LPAL_802A3220:
/* 46AAD0 802A3220 0280282D */  daddu      $a1, $s4, $zero
/* 46AAD4 802A3224 0260302D */  daddu      $a2, $s3, $zero
/* 46AAD8 802A3228 3C118015 */  lui        $s1, %hi(gCurrentLanguage)
/* 46AADC 802A322C 2631AE4C */  addiu      $s1, $s1, %lo(gCurrentLanguage)
/* 46AAE0 802A3230 2410FFFF */  addiu      $s0, $zero, -0x1
/* 46AAE4 802A3234 3C03802B */  lui        $v1, %hi(D_802AD34E)
/* 46AAE8 802A3238 8063D34E */  lb         $v1, %lo(D_802AD34E)($v1)
/* 46AAEC 802A323C 8E270000 */  lw         $a3, 0x0($s1)
/* 46AAF0 802A3240 00831004 */  sllv       $v0, $v1, $a0
/* 46AAF4 802A3244 00431021 */  addu       $v0, $v0, $v1
/* 46AAF8 802A3248 00021080 */  sll        $v0, $v0, 2
/* 46AAFC 802A324C 00431021 */  addu       $v0, $v0, $v1
/* 46AB00 802A3250 3C01802B */  lui        $at, %hi(D_PAL_802AB4CC)
/* 46AB04 802A3254 00270821 */  addu       $at, $at, $a3
/* 46AB08 802A3258 9027B4CC */  lbu        $a3, %lo(D_PAL_802AB4CC)($at)
/* 46AB0C 802A325C 2442001C */  addiu      $v0, $v0, 0x1C
/* 46AB10 802A3260 AFA20010 */  sw         $v0, 0x10($sp)
/* 46AB14 802A3264 3C02802A */  lui        $v0, %hi(func_PAL_802A3C98)
/* 46AB18 802A3268 24423C98 */  addiu      $v0, $v0, %lo(func_PAL_802A3C98)
/* 46AB1C 802A326C AFA00014 */  sw         $zero, 0x14($sp)
/* 46AB20 802A3270 AFA20018 */  sw         $v0, 0x18($sp)
/* 46AB24 802A3274 AFA0001C */  sw         $zero, 0x1C($sp)
/* 46AB28 802A3278 0C051A1E */  jal        func_PAL_80146878
/* 46AB2C 802A327C AFB00020 */   sw        $s0, 0x20($sp)
/* 46AB30 802A3280 24040004 */  addiu      $a0, $zero, 0x4
/* 46AB34 802A3284 2666FFFA */  addiu      $a2, $s3, -0x6
/* 46AB38 802A3288 8E220000 */  lw         $v0, 0x0($s1)
/* 46AB3C 802A328C 24120001 */  addiu      $s2, $zero, 0x1
/* 46AB40 802A3290 3C05802B */  lui        $a1, %hi(D_PAL_802AB4D8)
/* 46AB44 802A3294 00A22821 */  addu       $a1, $a1, $v0
/* 46AB48 802A3298 90A5B4D8 */  lbu        $a1, %lo(D_PAL_802AB4D8)($a1)
/* 46AB4C 802A329C 3C07802B */  lui        $a3, %hi(D_PAL_802AB4DC)
/* 46AB50 802A32A0 00E23821 */  addu       $a3, $a3, $v0
/* 46AB54 802A32A4 90E7B4DC */  lbu        $a3, %lo(D_PAL_802AB4DC)($a3)
/* 46AB58 802A32A8 24020010 */  addiu      $v0, $zero, 0x10
/* 46AB5C 802A32AC AFA20010 */  sw         $v0, 0x10($sp)
/* 46AB60 802A32B0 3C02802A */  lui        $v0, %hi(func_PAL_802A446C)
/* 46AB64 802A32B4 2442446C */  addiu      $v0, $v0, %lo(func_PAL_802A446C)
/* 46AB68 802A32B8 AFB20014 */  sw         $s2, 0x14($sp)
/* 46AB6C 802A32BC AFA20018 */  sw         $v0, 0x18($sp)
/* 46AB70 802A32C0 AFA0001C */  sw         $zero, 0x1C($sp)
/* 46AB74 802A32C4 AFB00020 */  sw         $s0, 0x20($sp)
/* 46AB78 802A32C8 0C051A1E */  jal        func_PAL_80146878
/* 46AB7C 802A32CC 02852821 */   addu      $a1, $s4, $a1
/* 46AB80 802A32D0 24040005 */  addiu      $a0, $zero, 0x5
/* 46AB84 802A32D4 2666FFF4 */  addiu      $a2, $s3, -0xC
/* 46AB88 802A32D8 8E220000 */  lw         $v0, 0x0($s1)
/* 46AB8C 802A32DC 24070020 */  addiu      $a3, $zero, 0x20
/* 46AB90 802A32E0 3C05802B */  lui        $a1, %hi(D_PAL_802AB4D4)
/* 46AB94 802A32E4 00A22821 */  addu       $a1, $a1, $v0
/* 46AB98 802A32E8 90A5B4D4 */  lbu        $a1, %lo(D_PAL_802AB4D4)($a1)
/* 46AB9C 802A32EC 24020023 */  addiu      $v0, $zero, 0x23
/* 46ABA0 802A32F0 AFA20010 */  sw         $v0, 0x10($sp)
/* 46ABA4 802A32F4 3C02802A */  lui        $v0, %hi(func_PAL_802A4500)
/* 46ABA8 802A32F8 24424500 */  addiu      $v0, $v0, %lo(func_PAL_802A4500)
/* 46ABAC 802A32FC AFB20014 */  sw         $s2, 0x14($sp)
/* 46ABB0 802A3300 AFA20018 */  sw         $v0, 0x18($sp)
/* 46ABB4 802A3304 AFA0001C */  sw         $zero, 0x1C($sp)
/* 46ABB8 802A3308 AFB00020 */  sw         $s0, 0x20($sp)
/* 46ABBC 802A330C 24A5006E */  addiu      $a1, $a1, 0x6E
.LPAL_802A3310:
/* 46ABC0 802A3310 0C051A1E */  jal        func_PAL_80146878
/* 46ABC4 802A3314 02852821 */   addu      $a1, $s4, $a1
/* 46ABC8 802A3318 24140014 */  addiu      $s4, $zero, 0x14
/* 46ABCC 802A331C 24040008 */  addiu      $a0, $zero, 0x8
/* 46ABD0 802A3320 0280282D */  daddu      $a1, $s4, $zero
/* 46ABD4 802A3324 240600BA */  addiu      $a2, $zero, 0xBA
/* 46ABD8 802A3328 24070118 */  addiu      $a3, $zero, 0x118
/* 46ABDC 802A332C 24020020 */  addiu      $v0, $zero, 0x20
/* 46ABE0 802A3330 AFA20010 */  sw         $v0, 0x10($sp)
/* 46ABE4 802A3334 3C02802A */  lui        $v0, %hi(func_PAL_802A454C)
/* 46ABE8 802A3338 2442454C */  addiu      $v0, $v0, %lo(func_PAL_802A454C)
/* 46ABEC 802A333C AFA20018 */  sw         $v0, 0x18($sp)
/* 46ABF0 802A3340 2402FFFF */  addiu      $v0, $zero, -0x1
/* 46ABF4 802A3344 AFB40014 */  sw         $s4, 0x14($sp)
/* 46ABF8 802A3348 AFA0001C */  sw         $zero, 0x1C($sp)
/* 46ABFC 802A334C 0C051A1E */  jal        func_PAL_80146878
/* 46AC00 802A3350 AFA20020 */   sw        $v0, 0x20($sp)
/* 46AC04 802A3354 24040001 */  addiu      $a0, $zero, 0x1
/* 46AC08 802A3358 0C051A8B */  jal        func_PAL_80146A2C
/* 46AC0C 802A335C 0080282D */   daddu     $a1, $a0, $zero
/* 46AC10 802A3360 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46AC14 802A3364 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46AC18 802A3368 54400006 */  bnel       $v0, $zero, .LPAL_802A3384
/* 46AC1C 802A336C 24040004 */   addiu     $a0, $zero, 0x4
/* 46AC20 802A3370 24040002 */  addiu      $a0, $zero, 0x2
/* 46AC24 802A3374 0C051A8B */  jal        func_PAL_80146A2C
/* 46AC28 802A3378 24050001 */   addiu     $a1, $zero, 0x1
/* 46AC2C 802A337C 080A8CE4 */  j          .LPAL_802A3390
/* 46AC30 802A3380 24040003 */   addiu     $a0, $zero, 0x3
.LPAL_802A3384:
/* 46AC34 802A3384 0C051A8B */  jal        func_PAL_80146A2C
/* 46AC38 802A3388 24050001 */   addiu     $a1, $zero, 0x1
/* 46AC3C 802A338C 24040005 */  addiu      $a0, $zero, 0x5
.LPAL_802A3390:
/* 46AC40 802A3390 0C051A8B */  jal        func_PAL_80146A2C
/* 46AC44 802A3394 24050001 */   addiu     $a1, $zero, 0x1
/* 46AC48 802A3398 24040008 */  addiu      $a0, $zero, 0x8
/* 46AC4C 802A339C 0C051A8B */  jal        func_PAL_80146A2C
/* 46AC50 802A33A0 24050001 */   addiu     $a1, $zero, 0x1
/* 46AC54 802A33A4 3C05802B */  lui        $a1, %hi(D_802AD34C)
/* 46AC58 802A33A8 24A5D34C */  addiu      $a1, $a1, %lo(D_802AD34C)
/* 46AC5C 802A33AC 3C06802B */  lui        $a2, %hi(D_802AD6E4)
/* 46AC60 802A33B0 24C6D6E4 */  addiu      $a2, $a2, %lo(D_802AD6E4)
/* 46AC64 802A33B4 3C08802B */  lui        $t0, %hi(D_802AD349)
/* 46AC68 802A33B8 8108D349 */  lb         $t0, %lo(D_802AD349)($t0)
/* 46AC6C 802A33BC 3C07802B */  lui        $a3, %hi(D_802AD34D)
/* 46AC70 802A33C0 80E7D34D */  lb         $a3, %lo(D_802AD34D)($a3)
.LPAL_802A33C4:
/* 46AC74 802A33C4 80A20000 */  lb         $v0, 0x0($a1)
/* 46AC78 802A33C8 90A30000 */  lbu        $v1, 0x0($a1)
/* 46AC7C 802A33CC 00471021 */  addu       $v0, $v0, $a3
/* 46AC80 802A33D0 2442FFFF */  addiu      $v0, $v0, -0x1
/* 46AC84 802A33D4 0102102A */  slt        $v0, $t0, $v0
/* 46AC88 802A33D8 14400010 */  bnez       $v0, .LPAL_802A341C
/* 46AC8C 802A33DC 0000202D */   daddu     $a0, $zero, $zero
/* 46AC90 802A33E0 24630001 */  addiu      $v1, $v1, 0x1
/* 46AC94 802A33E4 A0A30000 */  sb         $v1, 0x0($a1)
/* 46AC98 802A33E8 00031E00 */  sll        $v1, $v1, 24
/* 46AC9C 802A33EC 8CC20000 */  lw         $v0, 0x0($a2)
/* 46ACA0 802A33F0 00031E03 */  sra        $v1, $v1, 24
/* 46ACA4 802A33F4 2442FFFA */  addiu      $v0, $v0, -0x6
/* 46ACA8 802A33F8 0043102A */  slt        $v0, $v0, $v1
/* 46ACAC 802A33FC 50400007 */  beql       $v0, $zero, .LPAL_802A341C
/* 46ACB0 802A3400 24040001 */   addiu     $a0, $zero, 0x1
/* 46ACB4 802A3404 90C20003 */  lbu        $v0, 0x3($a2)
/* 46ACB8 802A3408 2442FFFA */  addiu      $v0, $v0, -0x6
/* 46ACBC 802A340C A0A20000 */  sb         $v0, 0x0($a1)
/* 46ACC0 802A3410 00021600 */  sll        $v0, $v0, 24
/* 46ACC4 802A3414 04420001 */  bltzl      $v0, .LPAL_802A341C
/* 46ACC8 802A3418 A0A00000 */   sb        $zero, 0x0($a1)
.LPAL_802A341C:
/* 46ACCC 802A341C 1480FFE9 */  bnez       $a0, .LPAL_802A33C4
/* 46ACD0 802A3420 24020001 */   addiu     $v0, $zero, 0x1
/* 46ACD4 802A3424 3C03802B */  lui        $v1, %hi(D_802AD34C)
/* 46ACD8 802A3428 9063D34C */  lbu        $v1, %lo(D_802AD34C)($v1)
/* 46ACDC 802A342C 3C04802B */  lui        $a0, %hi(D_802AD349)
/* 46ACE0 802A3430 8084D349 */  lb         $a0, %lo(D_802AD349)($a0)
/* 46ACE4 802A3434 3C01802B */  lui        $at, %hi(D_802AD348)
/* 46ACE8 802A3438 A022D348 */  sb         $v0, %lo(D_802AD348)($at)
/* 46ACEC 802A343C 24620006 */  addiu      $v0, $v1, 0x6
/* 46ACF0 802A3440 00031E00 */  sll        $v1, $v1, 24
/* 46ACF4 802A3444 00031E03 */  sra        $v1, $v1, 24
/* 46ACF8 802A3448 00032823 */  negu       $a1, $v1
/* 46ACFC 802A344C 3C01802B */  lui        $at, %hi(D_802AD34D)
/* 46AD00 802A3450 A022D34D */  sb         $v0, %lo(D_802AD34D)($at)
/* 46AD04 802A3454 00051040 */  sll        $v0, $a1, 1
/* 46AD08 802A3458 00451021 */  addu       $v0, $v0, $a1
/* 46AD0C 802A345C 00021080 */  sll        $v0, $v0, 2
/* 46AD10 802A3460 00451021 */  addu       $v0, $v0, $a1
/* 46AD14 802A3464 00832023 */  subu       $a0, $a0, $v1
/* 46AD18 802A3468 3C01802B */  lui        $at, %hi(D_802AD350)
/* 46AD1C 802A346C A422D350 */  sh         $v0, %lo(D_802AD350)($at)
/* 46AD20 802A3470 00041040 */  sll        $v0, $a0, 1
/* 46AD24 802A3474 00441021 */  addu       $v0, $v0, $a0
/* 46AD28 802A3478 00021080 */  sll        $v0, $v0, 2
/* 46AD2C 802A347C 00441021 */  addu       $v0, $v0, $a0
/* 46AD30 802A3480 3C01802B */  lui        $at, %hi(D_802AD352)
/* 46AD34 802A3484 A422D352 */  sh         $v0, %lo(D_802AD352)($at)
/* 46AD38 802A3488 080A8F1C */  j          .LPAL_802A3C70
/* 46AD3C 802A348C 0000102D */   daddu     $v0, $zero, $zero
.LPAL_802A3490:
/* 46AD40 802A3490 3C050001 */  lui        $a1, (0x12000 >> 16)
/* 46AD44 802A3494 3C04802B */  lui        $a0, %hi(D_802AD349)
/* 46AD48 802A3498 2484D349 */  addiu      $a0, $a0, %lo(D_802AD349)
/* 46AD4C 802A349C 34A52000 */  ori        $a1, $a1, (0x12000 & 0xFFFF)
/* 46AD50 802A34A0 8E220218 */  lw         $v0, 0x218($s1)
/* 46AD54 802A34A4 90830000 */  lbu        $v1, 0x0($a0)
/* 46AD58 802A34A8 00451024 */  and        $v0, $v0, $a1
/* 46AD5C 802A34AC 3C01802B */  lui        $at, %hi(D_802AD34A)
/* 46AD60 802A34B0 A023D34A */  sb         $v1, %lo(D_802AD34A)($at)
/* 46AD64 802A34B4 10400008 */  beqz       $v0, .LPAL_802A34D8
/* 46AD68 802A34B8 00031600 */   sll       $v0, $v1, 24
/* 46AD6C 802A34BC 1C400005 */  bgtz       $v0, .LPAL_802A34D4
/* 46AD70 802A34C0 2462FFFF */   addiu     $v0, $v1, -0x1
/* 46AD74 802A34C4 8E220214 */  lw         $v0, 0x214($s1)
/* 46AD78 802A34C8 00451024 */  and        $v0, $v0, $a1
/* 46AD7C 802A34CC 10400002 */  beqz       $v0, .LPAL_802A34D8
/* 46AD80 802A34D0 2462FFFF */   addiu     $v0, $v1, -0x1
.LPAL_802A34D4:
/* 46AD84 802A34D4 A0820000 */  sb         $v0, 0x0($a0)
.LPAL_802A34D8:
/* 46AD88 802A34D8 3C060002 */  lui        $a2, (0x20010 >> 16)
/* 46AD8C 802A34DC 8E220218 */  lw         $v0, 0x218($s1)
/* 46AD90 802A34E0 34C60010 */  ori        $a2, $a2, (0x20010 & 0xFFFF)
/* 46AD94 802A34E4 00461024 */  and        $v0, $v0, $a2
/* 46AD98 802A34E8 10400010 */  beqz       $v0, .LPAL_802A352C
/* 46AD9C 802A34EC 00000000 */   nop
/* 46ADA0 802A34F0 3C05802B */  lui        $a1, %hi(D_802AD349)
/* 46ADA4 802A34F4 24A5D349 */  addiu      $a1, $a1, %lo(D_802AD349)
/* 46ADA8 802A34F8 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46ADAC 802A34FC 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46ADB0 802A3500 80A30000 */  lb         $v1, 0x0($a1)
/* 46ADB4 802A3504 90A40000 */  lbu        $a0, 0x0($a1)
/* 46ADB8 802A3508 2442FFFF */  addiu      $v0, $v0, -0x1
/* 46ADBC 802A350C 0062182A */  slt        $v1, $v1, $v0
/* 46ADC0 802A3510 14600005 */  bnez       $v1, .LPAL_802A3528
/* 46ADC4 802A3514 24820001 */   addiu     $v0, $a0, 0x1
/* 46ADC8 802A3518 8E220214 */  lw         $v0, 0x214($s1)
/* 46ADCC 802A351C 00461024 */  and        $v0, $v0, $a2
/* 46ADD0 802A3520 10400002 */  beqz       $v0, .LPAL_802A352C
/* 46ADD4 802A3524 24820001 */   addiu     $v0, $a0, 0x1
.LPAL_802A3528:
/* 46ADD8 802A3528 A0A20000 */  sb         $v0, 0x0($a1)
.LPAL_802A352C:
/* 46ADDC 802A352C 3C10802B */  lui        $s0, %hi(D_802AD349)
/* 46ADE0 802A3530 2610D349 */  addiu      $s0, $s0, %lo(D_802AD349)
/* 46ADE4 802A3534 82020000 */  lb         $v0, 0x0($s0)
/* 46ADE8 802A3538 04410005 */  bgez       $v0, .LPAL_802A3550
/* 46ADEC 802A353C 00000000 */   nop
/* 46ADF0 802A3540 3C02802B */  lui        $v0, %hi(D_802AD6E7)
/* 46ADF4 802A3544 9042D6E7 */  lbu        $v0, %lo(D_802AD6E7)($v0)
/* 46ADF8 802A3548 2442FFFF */  addiu      $v0, $v0, -0x1
/* 46ADFC 802A354C A2020000 */  sb         $v0, 0x0($s0)
.LPAL_802A3550:
/* 46AE00 802A3550 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46AE04 802A3554 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46AE08 802A3558 82030000 */  lb         $v1, 0x0($s0)
/* 46AE0C 802A355C 2442FFFF */  addiu      $v0, $v0, -0x1
/* 46AE10 802A3560 0043102A */  slt        $v0, $v0, $v1
/* 46AE14 802A3564 54400001 */  bnel       $v0, $zero, .LPAL_802A356C
/* 46AE18 802A3568 A2000000 */   sb        $zero, 0x0($s0)
.LPAL_802A356C:
/* 46AE1C 802A356C 3C03802B */  lui        $v1, %hi(D_802AD34A)
/* 46AE20 802A3570 8063D34A */  lb         $v1, %lo(D_802AD34A)($v1)
/* 46AE24 802A3574 82020000 */  lb         $v0, 0x0($s0)
/* 46AE28 802A3578 10620009 */  beq        $v1, $v0, .LPAL_802A35A0
/* 46AE2C 802A357C 00031080 */   sll       $v0, $v1, 2
/* 46AE30 802A3580 3C04802B */  lui        $a0, %hi(D_802AD368)
/* 46AE34 802A3584 00822021 */  addu       $a0, $a0, $v0
/* 46AE38 802A3588 8C84D368 */  lw         $a0, %lo(D_802AD368)($a0)
/* 46AE3C 802A358C 3C053EE6 */  lui        $a1, (0x3EE66666 >> 16)
/* 46AE40 802A3590 0C050DF4 */  jal        func_PAL_801437D0
/* 46AE44 802A3594 34A56666 */   ori       $a1, $a1, (0x3EE66666 & 0xFFFF)
/* 46AE48 802A3598 0C052219 */  jal        func_PAL_80148864
/* 46AE4C 802A359C 240400C7 */   addiu     $a0, $zero, 0xC7
.LPAL_802A35A0:
/* 46AE50 802A35A0 3C04802B */  lui        $a0, %hi(D_802AD34C)
/* 46AE54 802A35A4 2484D34C */  addiu      $a0, $a0, %lo(D_802AD34C)
/* 46AE58 802A35A8 80820000 */  lb         $v0, 0x0($a0)
/* 46AE5C 802A35AC 82030000 */  lb         $v1, 0x0($s0)
/* 46AE60 802A35B0 24420001 */  addiu      $v0, $v0, 0x1
/* 46AE64 802A35B4 0062182A */  slt        $v1, $v1, $v0
/* 46AE68 802A35B8 90820000 */  lbu        $v0, 0x0($a0)
/* 46AE6C 802A35BC 10600005 */  beqz       $v1, .LPAL_802A35D4
/* 46AE70 802A35C0 2442FFFF */   addiu     $v0, $v0, -0x1
/* 46AE74 802A35C4 A0820000 */  sb         $v0, 0x0($a0)
/* 46AE78 802A35C8 00021600 */  sll        $v0, $v0, 24
/* 46AE7C 802A35CC 04420001 */  bltzl      $v0, .LPAL_802A35D4
/* 46AE80 802A35D0 A0800000 */   sb        $zero, 0x0($a0)
.LPAL_802A35D4:
/* 46AE84 802A35D4 3C02802B */  lui        $v0, %hi(D_802AD34D)
/* 46AE88 802A35D8 8042D34D */  lb         $v0, %lo(D_802AD34D)($v0)
/* 46AE8C 802A35DC 3C03802B */  lui        $v1, %hi(D_802AD349)
/* 46AE90 802A35E0 8063D349 */  lb         $v1, %lo(D_802AD349)($v1)
/* 46AE94 802A35E4 2442FFFF */  addiu      $v0, $v0, -0x1
/* 46AE98 802A35E8 0062182A */  slt        $v1, $v1, $v0
/* 46AE9C 802A35EC 14600015 */  bnez       $v1, .LPAL_802A3644
/* 46AEA0 802A35F0 00000000 */   nop
/* 46AEA4 802A35F4 3C04802B */  lui        $a0, %hi(D_802AD34C)
/* 46AEA8 802A35F8 2484D34C */  addiu      $a0, $a0, %lo(D_802AD34C)
/* 46AEAC 802A35FC 90820000 */  lbu        $v0, 0x0($a0)
/* 46AEB0 802A3600 3C05802B */  lui        $a1, %hi(D_802AD6E4)
/* 46AEB4 802A3604 24A5D6E4 */  addiu      $a1, $a1, %lo(D_802AD6E4)
/* 46AEB8 802A3608 24420001 */  addiu      $v0, $v0, 0x1
/* 46AEBC 802A360C A0820000 */  sb         $v0, 0x0($a0)
/* 46AEC0 802A3610 00021600 */  sll        $v0, $v0, 24
/* 46AEC4 802A3614 8CA30000 */  lw         $v1, 0x0($a1)
/* 46AEC8 802A3618 00021603 */  sra        $v0, $v0, 24
/* 46AECC 802A361C 2463FFFA */  addiu      $v1, $v1, -0x6
/* 46AED0 802A3620 0062182A */  slt        $v1, $v1, $v0
/* 46AED4 802A3624 10600007 */  beqz       $v1, .LPAL_802A3644
/* 46AED8 802A3628 00000000 */   nop
/* 46AEDC 802A362C 90A20003 */  lbu        $v0, 0x3($a1)
/* 46AEE0 802A3630 2442FFFA */  addiu      $v0, $v0, -0x6
/* 46AEE4 802A3634 A0820000 */  sb         $v0, 0x0($a0)
/* 46AEE8 802A3638 00021600 */  sll        $v0, $v0, 24
/* 46AEEC 802A363C 04420001 */  bltzl      $v0, .LPAL_802A3644
/* 46AEF0 802A3640 A0800000 */   sb        $zero, 0x0($a0)
.LPAL_802A3644:
/* 46AEF4 802A3644 3C02802B */  lui        $v0, %hi(D_802AD34C)
/* 46AEF8 802A3648 9042D34C */  lbu        $v0, %lo(D_802AD34C)($v0)
/* 46AEFC 802A364C 8E230214 */  lw         $v1, 0x214($s1)
/* 46AF00 802A3650 24420006 */  addiu      $v0, $v0, 0x6
/* 46AF04 802A3654 3C01802B */  lui        $at, %hi(D_802AD34D)
/* 46AF08 802A3658 A022D34D */  sb         $v0, %lo(D_802AD34D)($at)
/* 46AF0C 802A365C 30628000 */  andi       $v0, $v1, 0x8000
/* 46AF10 802A3660 10400025 */  beqz       $v0, .LPAL_802A36F8
/* 46AF14 802A3664 30624000 */   andi      $v0, $v1, 0x4000
/* 46AF18 802A3668 3C11802B */  lui        $s1, %hi(D_802AD349)
/* 46AF1C 802A366C 2631D349 */  addiu      $s1, $s1, %lo(D_802AD349)
/* 46AF20 802A3670 82220000 */  lb         $v0, 0x0($s1)
/* 46AF24 802A3674 00021080 */  sll        $v0, $v0, 2
/* 46AF28 802A3678 3C01802B */  lui        $at, %hi(D_802AD438)
/* 46AF2C 802A367C 00220821 */  addu       $at, $at, $v0
/* 46AF30 802A3680 8C22D438 */  lw         $v0, %lo(D_802AD438)($at)
/* 46AF34 802A3684 3C10802B */  lui        $s0, %hi(D_802AD438)
/* 46AF38 802A3688 2610D438 */  addiu      $s0, $s0, %lo(D_802AD438)
/* 46AF3C 802A368C 00021080 */  sll        $v0, $v0, 2
/* 46AF40 802A3690 3C03802B */  lui        $v1, %hi(D_802AD750)
/* 46AF44 802A3694 00621821 */  addu       $v1, $v1, $v0
/* 46AF48 802A3698 8C63D750 */  lw         $v1, %lo(D_802AD750)($v1)
/* 46AF4C 802A369C 24020001 */  addiu      $v0, $zero, 0x1
/* 46AF50 802A36A0 14620005 */  bne        $v1, $v0, .LPAL_802A36B8
/* 46AF54 802A36A4 00000000 */   nop
/* 46AF58 802A36A8 0C052219 */  jal        func_PAL_80148864
/* 46AF5C 802A36AC 240400C9 */   addiu     $a0, $zero, 0xC9
/* 46AF60 802A36B0 080A8F19 */  j          .LPAL_802A3C64
/* 46AF64 802A36B4 2402FFFF */   addiu     $v0, $zero, -0x1
.LPAL_802A36B8:
/* 46AF68 802A36B8 0C052219 */  jal        func_PAL_80148864
/* 46AF6C 802A36BC 2404021D */   addiu     $a0, $zero, 0x21D
/* 46AF70 802A36C0 82220000 */  lb         $v0, 0x0($s1)
/* 46AF74 802A36C4 00021080 */  sll        $v0, $v0, 2
/* 46AF78 802A36C8 00501021 */  addu       $v0, $v0, $s0
/* 46AF7C 802A36CC 8C420000 */  lw         $v0, 0x0($v0)
/* 46AF80 802A36D0 3C03802B */  lui        $v1, %hi(D_802AD498)
/* 46AF84 802A36D4 2463D498 */  addiu      $v1, $v1, %lo(D_802AD498)
/* 46AF88 802A36D8 AC600000 */  sw         $zero, 0x0($v1)
/* 46AF8C 802A36DC 3C01802B */  lui        $at, %hi(D_802AD828)
/* 46AF90 802A36E0 00220821 */  addu       $at, $at, $v0
/* 46AF94 802A36E4 8022D828 */  lb         $v0, %lo(D_802AD828)($at)
/* 46AF98 802A36E8 54400001 */  bnel       $v0, $zero, .LPAL_802A36F0
/* 46AF9C 802A36EC AC620000 */   sw        $v0, 0x0($v1)
.LPAL_802A36F0:
/* 46AFA0 802A36F0 080A8F19 */  j          .LPAL_802A3C64
/* 46AFA4 802A36F4 24020028 */   addiu     $v0, $zero, 0x28
.LPAL_802A36F8:
/* 46AFA8 802A36F8 1040015D */  beqz       $v0, .LPAL_802A3C70
/* 46AFAC 802A36FC 0000102D */   daddu     $v0, $zero, $zero
/* 46AFB0 802A3700 0C052219 */  jal        func_PAL_80148864
/* 46AFB4 802A3704 240400CA */   addiu     $a0, $zero, 0xCA
/* 46AFB8 802A3708 0C0A89E1 */  jal        func_PAL_802A2784
/* 46AFBC 802A370C 00000000 */   nop
/* 46AFC0 802A3710 080A8F19 */  j          .LPAL_802A3C64
/* 46AFC4 802A3714 2402FFFE */   addiu     $v0, $zero, -0x2
.LPAL_802A3718:
/* 46AFC8 802A3718 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46AFCC 802A371C 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46AFD0 802A3720 1840000F */  blez       $v0, .LPAL_802A3760
/* 46AFD4 802A3724 0000802D */   daddu     $s0, $zero, $zero
/* 46AFD8 802A3728 3C11802B */  lui        $s1, %hi(D_802AD368)
/* 46AFDC 802A372C 2631D368 */  addiu      $s1, $s1, %lo(D_802AD368)
/* 46AFE0 802A3730 240500A0 */  addiu      $a1, $zero, 0xA0
.LPAL_802A3734:
/* 46AFE4 802A3734 00A0302D */  daddu      $a2, $a1, $zero
/* 46AFE8 802A3738 00A0382D */  daddu      $a3, $a1, $zero
/* 46AFEC 802A373C 8E240000 */  lw         $a0, 0x0($s1)
/* 46AFF0 802A3740 0C050EAB */  jal        func_PAL_80143AAC
/* 46AFF4 802A3744 26310004 */   addiu     $s1, $s1, 0x4
/* 46AFF8 802A3748 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46AFFC 802A374C 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46B000 802A3750 26100001 */  addiu      $s0, $s0, 0x1
/* 46B004 802A3754 0202102A */  slt        $v0, $s0, $v0
/* 46B008 802A3758 1440FFF6 */  bnez       $v0, .LPAL_802A3734
/* 46B00C 802A375C 240500A0 */   addiu     $a1, $zero, 0xA0
.LPAL_802A3760:
/* 46B010 802A3760 240500A0 */  addiu      $a1, $zero, 0xA0
/* 46B014 802A3764 00A0302D */  daddu      $a2, $a1, $zero
/* 46B018 802A3768 3C04802B */  lui        $a0, %hi(D_802AD358)
/* 46B01C 802A376C 8C84D358 */  lw         $a0, %lo(D_802AD358)($a0)
/* 46B020 802A3770 0C050EAB */  jal        func_PAL_80143AAC
/* 46B024 802A3774 00A0382D */   daddu     $a3, $a1, $zero
/* 46B028 802A3778 240500A0 */  addiu      $a1, $zero, 0xA0
/* 46B02C 802A377C 00A0302D */  daddu      $a2, $a1, $zero
/* 46B030 802A3780 3C04802B */  lui        $a0, %hi(D_802AD35C)
/* 46B034 802A3784 8C84D35C */  lw         $a0, %lo(D_802AD35C)($a0)
/* 46B038 802A3788 0C050EAB */  jal        func_PAL_80143AAC
/* 46B03C 802A378C 00A0382D */   daddu     $a3, $a1, $zero
/* 46B040 802A3790 240500A0 */  addiu      $a1, $zero, 0xA0
/* 46B044 802A3794 00A0302D */  daddu      $a2, $a1, $zero
/* 46B048 802A3798 3C04802B */  lui        $a0, %hi(D_802AD360)
/* 46B04C 802A379C 8C84D360 */  lw         $a0, %lo(D_802AD360)($a0)
/* 46B050 802A37A0 0C050EAB */  jal        func_PAL_80143AAC
/* 46B054 802A37A4 00A0382D */   daddu     $a3, $a1, $zero
/* 46B058 802A37A8 240500A0 */  addiu      $a1, $zero, 0xA0
/* 46B05C 802A37AC 00A0302D */  daddu      $a2, $a1, $zero
/* 46B060 802A37B0 3C04802B */  lui        $a0, %hi(D_802AD3C8)
/* 46B064 802A37B4 8C84D3C8 */  lw         $a0, %lo(D_802AD3C8)($a0)
/* 46B068 802A37B8 0C050EAB */  jal        func_PAL_80143AAC
/* 46B06C 802A37BC 00A0382D */   daddu     $a3, $a1, $zero
/* 46B070 802A37C0 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46B074 802A37C4 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46B078 802A37C8 1840000F */  blez       $v0, .LPAL_802A3808
/* 46B07C 802A37CC 0000802D */   daddu     $s0, $zero, $zero
/* 46B080 802A37D0 3C11802B */  lui        $s1, %hi(D_802AD3D0)
/* 46B084 802A37D4 2631D3D0 */  addiu      $s1, $s1, %lo(D_802AD3D0)
/* 46B088 802A37D8 240500A0 */  addiu      $a1, $zero, 0xA0
.LPAL_802A37DC:
/* 46B08C 802A37DC 00A0302D */  daddu      $a2, $a1, $zero
/* 46B090 802A37E0 00A0382D */  daddu      $a3, $a1, $zero
/* 46B094 802A37E4 8E240000 */  lw         $a0, 0x0($s1)
/* 46B098 802A37E8 0C050EAB */  jal        func_PAL_80143AAC
/* 46B09C 802A37EC 26310004 */   addiu     $s1, $s1, 0x4
/* 46B0A0 802A37F0 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46B0A4 802A37F4 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46B0A8 802A37F8 26100001 */  addiu      $s0, $s0, 0x1
/* 46B0AC 802A37FC 0202102A */  slt        $v0, $s0, $v0
/* 46B0B0 802A3800 5440FFF6 */  bnel       $v0, $zero, .LPAL_802A37DC
/* 46B0B4 802A3804 240500A0 */   addiu     $a1, $zero, 0xA0
.LPAL_802A3808:
/* 46B0B8 802A3808 3C04802B */  lui        $a0, %hi(D_802AD358)
/* 46B0BC 802A380C 8C84D358 */  lw         $a0, %lo(D_802AD358)($a0)
/* 46B0C0 802A3810 3C058010 */  lui        $a1, %hi(D_PAL_80102CF0)
/* 46B0C4 802A3814 24A52CF0 */  addiu      $a1, $a1, %lo(D_PAL_80102CF0)
/* 46B0C8 802A3818 0C050CEB */  jal        func_PAL_801433AC
/* 46B0CC 802A381C 00000000 */   nop
/* 46B0D0 802A3820 24040001 */  addiu      $a0, $zero, 0x1
/* 46B0D4 802A3824 2402000D */  addiu      $v0, $zero, 0xD
/* 46B0D8 802A3828 3C01802B */  lui        $at, %hi(D_802AD354)
/* 46B0DC 802A382C A422D354 */  sh         $v0, %lo(D_802AD354)($at)
/* 46B0E0 802A3830 0C051A8B */  jal        func_PAL_80146A2C
/* 46B0E4 802A3834 24050004 */   addiu     $a1, $zero, 0x4
/* 46B0E8 802A3838 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B0EC 802A383C 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B0F0 802A3840 54400006 */  bnel       $v0, $zero, .LPAL_802A385C
/* 46B0F4 802A3844 24040004 */   addiu     $a0, $zero, 0x4
/* 46B0F8 802A3848 24040002 */  addiu      $a0, $zero, 0x2
/* 46B0FC 802A384C 0C051A8B */  jal        func_PAL_80146A2C
/* 46B100 802A3850 24050004 */   addiu     $a1, $zero, 0x4
/* 46B104 802A3854 080A8E1A */  j          .LPAL_802A3868
/* 46B108 802A3858 24040003 */   addiu     $a0, $zero, 0x3
.LPAL_802A385C:
/* 46B10C 802A385C 0C051A8B */  jal        func_PAL_80146A2C
/* 46B110 802A3860 0080282D */   daddu     $a1, $a0, $zero
/* 46B114 802A3864 24040005 */  addiu      $a0, $zero, 0x5
.LPAL_802A3868:
/* 46B118 802A3868 0C051A8B */  jal        func_PAL_80146A2C
/* 46B11C 802A386C 24050004 */   addiu     $a1, $zero, 0x4
/* 46B120 802A3870 24040008 */  addiu      $a0, $zero, 0x8
/* 46B124 802A3874 0C051A8B */  jal        func_PAL_80146A2C
/* 46B128 802A3878 24050002 */   addiu     $a1, $zero, 0x2
/* 46B12C 802A387C 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B130 802A3880 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B134 802A3884 14400005 */  bnez       $v0, .LPAL_802A389C
/* 46B138 802A3888 00000000 */   nop
/* 46B13C 802A388C 0C03988A */  jal        func_PAL_800E6228
/* 46B140 802A3890 00000000 */   nop
/* 46B144 802A3894 080A8E5D */  j          .LPAL_802A3974
/* 46B148 802A3898 00000000 */   nop
.LPAL_802A389C:
/* 46B14C 802A389C 0C0398BB */  jal        func_PAL_800E62EC
/* 46B150 802A38A0 00000000 */   nop
/* 46B154 802A38A4 080A8E5D */  j          .LPAL_802A3974
/* 46B158 802A38A8 00000000 */   nop
.LPAL_802A38AC:
/* 46B15C 802A38AC 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B160 802A38B0 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B164 802A38B4 14400005 */  bnez       $v0, .LPAL_802A38CC
/* 46B168 802A38B8 00000000 */   nop
/* 46B16C 802A38BC 0C03988A */  jal        func_PAL_800E6228
/* 46B170 802A38C0 00000000 */   nop
/* 46B174 802A38C4 080A8F1C */  j          .LPAL_802A3C70
/* 46B178 802A38C8 240200FF */   addiu     $v0, $zero, 0xFF
.LPAL_802A38CC:
/* 46B17C 802A38CC 0C0398BB */  jal        func_PAL_800E62EC
/* 46B180 802A38D0 00000000 */   nop
/* 46B184 802A38D4 080A8F1C */  j          .LPAL_802A3C70
/* 46B188 802A38D8 240200FF */   addiu     $v0, $zero, 0xFF
.LPAL_802A38DC:
/* 46B18C 802A38DC 24040001 */  addiu      $a0, $zero, 0x1
/* 46B190 802A38E0 0C051A8B */  jal        func_PAL_80146A2C
/* 46B194 802A38E4 24050002 */   addiu     $a1, $zero, 0x2
/* 46B198 802A38E8 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B19C 802A38EC 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B1A0 802A38F0 54400006 */  bnel       $v0, $zero, .LPAL_802A390C
/* 46B1A4 802A38F4 24040004 */   addiu     $a0, $zero, 0x4
/* 46B1A8 802A38F8 24040002 */  addiu      $a0, $zero, 0x2
/* 46B1AC 802A38FC 0C051A8B */  jal        func_PAL_80146A2C
/* 46B1B0 802A3900 0080282D */   daddu     $a1, $a0, $zero
/* 46B1B4 802A3904 080A8E46 */  j          .LPAL_802A3918
/* 46B1B8 802A3908 24040003 */   addiu     $a0, $zero, 0x3
.LPAL_802A390C:
/* 46B1BC 802A390C 0C051A8B */  jal        func_PAL_80146A2C
/* 46B1C0 802A3910 24050002 */   addiu     $a1, $zero, 0x2
/* 46B1C4 802A3914 24040005 */  addiu      $a0, $zero, 0x5
.LPAL_802A3918:
/* 46B1C8 802A3918 0C051A8B */  jal        func_PAL_80146A2C
/* 46B1CC 802A391C 24050002 */   addiu     $a1, $zero, 0x2
/* 46B1D0 802A3920 24040008 */  addiu      $a0, $zero, 0x8
/* 46B1D4 802A3924 0C051A8B */  jal        func_PAL_80146A2C
/* 46B1D8 802A3928 24050002 */   addiu     $a1, $zero, 0x2
/* 46B1DC 802A392C 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B1E0 802A3930 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B1E4 802A3934 14400005 */  bnez       $v0, .LPAL_802A394C
/* 46B1E8 802A3938 00000000 */   nop
/* 46B1EC 802A393C 0C03988A */  jal        func_PAL_800E6228
/* 46B1F0 802A3940 00000000 */   nop
/* 46B1F4 802A3944 080A8E55 */  j          .LPAL_802A3954
/* 46B1F8 802A3948 00000000 */   nop
.LPAL_802A394C:
/* 46B1FC 802A394C 0C0398BB */  jal        func_PAL_800E62EC
/* 46B200 802A3950 00000000 */   nop
.LPAL_802A3954:
/* 46B204 802A3954 3C04802B */  lui        $a0, %hi(D_802AD349)
/* 46B208 802A3958 8084D349 */  lb         $a0, %lo(D_802AD349)($a0)
/* 46B20C 802A395C 00041080 */  sll        $v0, $a0, 2
/* 46B210 802A3960 3C01802B */  lui        $at, %hi(D_802AD438)
/* 46B214 802A3964 00220821 */  addu       $at, $at, $v0
/* 46B218 802A3968 8C22D438 */  lw         $v0, %lo(D_802AD438)($at)
/* 46B21C 802A396C 080A8E82 */  j          .LPAL_802A3A08
/* 46B220 802A3970 2403000B */   addiu     $v1, $zero, 0xB
.LPAL_802A3974:
/* 46B224 802A3974 3C03802B */  lui        $v1, %hi(D_802AD349)
/* 46B228 802A3978 8063D349 */  lb         $v1, %lo(D_802AD349)($v1)
/* 46B22C 802A397C 00031080 */  sll        $v0, $v1, 2
/* 46B230 802A3980 3C01802B */  lui        $at, %hi(D_802AD438)
/* 46B234 802A3984 00220821 */  addu       $at, $at, $v0
/* 46B238 802A3988 8C22D438 */  lw         $v0, %lo(D_802AD438)($at)
/* 46B23C 802A398C 3C01802B */  lui        $at, %hi(D_802AD840)
/* 46B240 802A3990 AC23D840 */  sw         $v1, %lo(D_802AD840)($at)
/* 46B244 802A3994 080A8F1C */  j          .LPAL_802A3C70
/* 46B248 802A3998 24420001 */   addiu     $v0, $v0, 0x1
.LPAL_802A399C:
/* 46B24C 802A399C 24040001 */  addiu      $a0, $zero, 0x1
/* 46B250 802A39A0 0C051A8B */  jal        func_PAL_80146A2C
/* 46B254 802A39A4 0080282D */   daddu     $a1, $a0, $zero
/* 46B258 802A39A8 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B25C 802A39AC 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B260 802A39B0 54400006 */  bnel       $v0, $zero, .LPAL_802A39CC
/* 46B264 802A39B4 24040004 */   addiu     $a0, $zero, 0x4
/* 46B268 802A39B8 24040002 */  addiu      $a0, $zero, 0x2
/* 46B26C 802A39BC 0C051A8B */  jal        func_PAL_80146A2C
/* 46B270 802A39C0 24050001 */   addiu     $a1, $zero, 0x1
/* 46B274 802A39C4 080A8E76 */  j          .LPAL_802A39D8
/* 46B278 802A39C8 24040003 */   addiu     $a0, $zero, 0x3
.LPAL_802A39CC:
/* 46B27C 802A39CC 0C051A8B */  jal        func_PAL_80146A2C
/* 46B280 802A39D0 24050001 */   addiu     $a1, $zero, 0x1
/* 46B284 802A39D4 24040005 */  addiu      $a0, $zero, 0x5
.LPAL_802A39D8:
/* 46B288 802A39D8 0C051A8B */  jal        func_PAL_80146A2C
/* 46B28C 802A39DC 24050001 */   addiu     $a1, $zero, 0x1
/* 46B290 802A39E0 24040008 */  addiu      $a0, $zero, 0x8
/* 46B294 802A39E4 0C051A8B */  jal        func_PAL_80146A2C
/* 46B298 802A39E8 24050001 */   addiu     $a1, $zero, 0x1
/* 46B29C 802A39EC 3C04802B */  lui        $a0, %hi(D_802AD349)
/* 46B2A0 802A39F0 8084D349 */  lb         $a0, %lo(D_802AD349)($a0)
/* 46B2A4 802A39F4 00041080 */  sll        $v0, $a0, 2
/* 46B2A8 802A39F8 3C01802B */  lui        $at, %hi(D_802AD438)
/* 46B2AC 802A39FC 00220821 */  addu       $at, $at, $v0
/* 46B2B0 802A3A00 8C22D438 */  lw         $v0, %lo(D_802AD438)($at)
/* 46B2B4 802A3A04 24030001 */  addiu      $v1, $zero, 0x1
.LPAL_802A3A08:
/* 46B2B8 802A3A08 3C01802B */  lui        $at, %hi(D_802AD348)
/* 46B2BC 802A3A0C A023D348 */  sb         $v1, %lo(D_802AD348)($at)
/* 46B2C0 802A3A10 3C01802B */  lui        $at, %hi(D_802AD840)
/* 46B2C4 802A3A14 AC24D840 */  sw         $a0, %lo(D_802AD840)($at)
/* 46B2C8 802A3A18 080A8F1C */  j          .LPAL_802A3C70
/* 46B2CC 802A3A1C 24420001 */   addiu     $v0, $v0, 0x1
.LPAL_802A3A20:
/* 46B2D0 802A3A20 24040001 */  addiu      $a0, $zero, 0x1
/* 46B2D4 802A3A24 0C051A8B */  jal        func_PAL_80146A2C
/* 46B2D8 802A3A28 24050009 */   addiu     $a1, $zero, 0x9
/* 46B2DC 802A3A2C 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B2E0 802A3A30 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B2E4 802A3A34 54400006 */  bnel       $v0, $zero, .LPAL_802A3A50
/* 46B2E8 802A3A38 24040004 */   addiu     $a0, $zero, 0x4
/* 46B2EC 802A3A3C 24040002 */  addiu      $a0, $zero, 0x2
/* 46B2F0 802A3A40 0C051A8B */  jal        func_PAL_80146A2C
/* 46B2F4 802A3A44 24050009 */   addiu     $a1, $zero, 0x9
/* 46B2F8 802A3A48 080A8E97 */  j          .LPAL_802A3A5C
/* 46B2FC 802A3A4C 24040003 */   addiu     $a0, $zero, 0x3
.LPAL_802A3A50:
/* 46B300 802A3A50 0C051A8B */  jal        func_PAL_80146A2C
/* 46B304 802A3A54 24050009 */   addiu     $a1, $zero, 0x9
/* 46B308 802A3A58 24040005 */  addiu      $a0, $zero, 0x5
.LPAL_802A3A5C:
/* 46B30C 802A3A5C 0C051A8B */  jal        func_PAL_80146A2C
/* 46B310 802A3A60 24050009 */   addiu     $a1, $zero, 0x9
/* 46B314 802A3A64 24040008 */  addiu      $a0, $zero, 0x8
/* 46B318 802A3A68 0C051A8B */  jal        func_PAL_80146A2C
/* 46B31C 802A3A6C 24050002 */   addiu     $a1, $zero, 0x2
/* 46B320 802A3A70 080A8F19 */  j          .LPAL_802A3C64
/* 46B324 802A3A74 2402FFFF */   addiu     $v0, $zero, -0x1
.LPAL_802A3A78:
/* 46B328 802A3A78 2402FFFF */  addiu      $v0, $zero, -0x1
/* 46B32C 802A3A7C 0040182D */  daddu      $v1, $v0, $zero
/* 46B330 802A3A80 3C01802B */  lui        $at, %hi(D_802AD840)
/* 46B334 802A3A84 AC23D840 */  sw         $v1, %lo(D_802AD840)($at)
/* 46B338 802A3A88 24030029 */  addiu      $v1, $zero, 0x29
/* 46B33C 802A3A8C 3C01802B */  lui        $at, %hi(D_802AD348)
/* 46B340 802A3A90 A023D348 */  sb         $v1, %lo(D_802AD348)($at)
/* 46B344 802A3A94 080A8F1C */  j          .LPAL_802A3C70
/* 46B348 802A3A98 00000000 */   nop
.LPAL_802A3A9C:
/* 46B34C 802A3A9C 24040001 */  addiu      $a0, $zero, 0x1
/* 46B350 802A3AA0 0C051A8B */  jal        func_PAL_80146A2C
/* 46B354 802A3AA4 24050002 */   addiu     $a1, $zero, 0x2
/* 46B358 802A3AA8 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B35C 802A3AAC 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B360 802A3AB0 54400006 */  bnel       $v0, $zero, .LPAL_802A3ACC
/* 46B364 802A3AB4 24040004 */   addiu     $a0, $zero, 0x4
/* 46B368 802A3AB8 24040002 */  addiu      $a0, $zero, 0x2
/* 46B36C 802A3ABC 0C051A8B */  jal        func_PAL_80146A2C
/* 46B370 802A3AC0 0080282D */   daddu     $a1, $a0, $zero
/* 46B374 802A3AC4 080A8EB6 */  j          .LPAL_802A3AD8
/* 46B378 802A3AC8 24040003 */   addiu     $a0, $zero, 0x3
.LPAL_802A3ACC:
/* 46B37C 802A3ACC 0C051A8B */  jal        func_PAL_80146A2C
/* 46B380 802A3AD0 24050002 */   addiu     $a1, $zero, 0x2
/* 46B384 802A3AD4 24040005 */  addiu      $a0, $zero, 0x5
.LPAL_802A3AD8:
/* 46B388 802A3AD8 0C051A8B */  jal        func_PAL_80146A2C
/* 46B38C 802A3ADC 24050002 */   addiu     $a1, $zero, 0x2
/* 46B390 802A3AE0 24040008 */  addiu      $a0, $zero, 0x8
/* 46B394 802A3AE4 0C051A8B */  jal        func_PAL_80146A2C
/* 46B398 802A3AE8 24050002 */   addiu     $a1, $zero, 0x2
/* 46B39C 802A3AEC 3C11001D */  lui        $s1, (0x1D00C3 >> 16)
/* 46B3A0 802A3AF0 3C02802B */  lui        $v0, %hi(D_802AD498)
/* 46B3A4 802A3AF4 8C42D498 */  lw         $v0, %lo(D_802AD498)($v0)
/* 46B3A8 802A3AF8 14400008 */  bnez       $v0, .LPAL_802A3B1C
/* 46B3AC 802A3AFC 363100C3 */   ori       $s1, $s1, (0x1D00C3 & 0xFFFF)
/* 46B3B0 802A3B00 3C11001D */  lui        $s1, (0x1D00A0 >> 16)
/* 46B3B4 802A3B04 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B3B8 802A3B08 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B3BC 802A3B0C 14400003 */  bnez       $v0, .LPAL_802A3B1C
/* 46B3C0 802A3B10 363100A0 */   ori       $s1, $s1, (0x1D00A0 & 0xFFFF)
/* 46B3C4 802A3B14 3C11001D */  lui        $s1, (0x1D009F >> 16)
/* 46B3C8 802A3B18 3631009F */  ori        $s1, $s1, (0x1D009F & 0xFFFF)
.LPAL_802A3B1C:
/* 46B3CC 802A3B1C 0220202D */  daddu      $a0, $s1, $zero
/* 46B3D0 802A3B20 0C0493E5 */  jal        func_PAL_80124F94
/* 46B3D4 802A3B24 0000282D */   daddu     $a1, $zero, $zero
/* 46B3D8 802A3B28 24500017 */  addiu      $s0, $v0, 0x17
/* 46B3DC 802A3B2C 001017C2 */  srl        $v0, $s0, 31
/* 46B3E0 802A3B30 02021021 */  addu       $v0, $s0, $v0
/* 46B3E4 802A3B34 00021043 */  sra        $v0, $v0, 1
/* 46B3E8 802A3B38 240300A0 */  addiu      $v1, $zero, 0xA0
/* 46B3EC 802A3B3C 0062A023 */  subu       $s4, $v1, $v0
/* 46B3F0 802A3B40 0C0493F4 */  jal        func_PAL_80124FD0
/* 46B3F4 802A3B44 0220202D */   daddu     $a0, $s1, $zero
/* 46B3F8 802A3B48 24040009 */  addiu      $a0, $zero, 0x9
/* 46B3FC 802A3B4C 0280282D */  daddu      $a1, $s4, $zero
/* 46B400 802A3B50 24060050 */  addiu      $a2, $zero, 0x50
/* 46B404 802A3B54 0200382D */  daddu      $a3, $s0, $zero
/* 46B408 802A3B58 2442FFFF */  addiu      $v0, $v0, -0x1
/* 46B40C 802A3B5C 00021040 */  sll        $v0, $v0, 1
/* 46B410 802A3B60 3C03802B */  lui        $v1, %hi(D_PAL_802AB4C0)
/* 46B414 802A3B64 00621821 */  addu       $v1, $v1, $v0
/* 46B418 802A3B68 8463B4C0 */  lh         $v1, %lo(D_PAL_802AB4C0)($v1)
/* 46B41C 802A3B6C 24020014 */  addiu      $v0, $zero, 0x14
/* 46B420 802A3B70 AFA20014 */  sw         $v0, 0x14($sp)
/* 46B424 802A3B74 3C02802A */  lui        $v0, %hi(func_PAL_802A45EC)
/* 46B428 802A3B78 244245EC */  addiu      $v0, $v0, %lo(func_PAL_802A45EC)
/* 46B42C 802A3B7C AFA20018 */  sw         $v0, 0x18($sp)
/* 46B430 802A3B80 2402FFFF */  addiu      $v0, $zero, -0x1
/* 46B434 802A3B84 AFA0001C */  sw         $zero, 0x1C($sp)
/* 46B438 802A3B88 AFA20020 */  sw         $v0, 0x20($sp)
/* 46B43C 802A3B8C 0C051A1E */  jal        func_PAL_80146878
/* 46B440 802A3B90 AFA30010 */   sw        $v1, 0x10($sp)
/* 46B444 802A3B94 24040009 */  addiu      $a0, $zero, 0x9
/* 46B448 802A3B98 0C051A8B */  jal        func_PAL_80146A2C
/* 46B44C 802A3B9C 24050001 */   addiu     $a1, $zero, 0x1
/* 46B450 802A3BA0 2403003C */  addiu      $v1, $zero, 0x3C
/* 46B454 802A3BA4 3C01802B */  lui        $at, %hi(D_802AD34B)
/* 46B458 802A3BA8 A023D34B */  sb         $v1, %lo(D_802AD34B)($at)
/* 46B45C 802A3BAC 2403002A */  addiu      $v1, $zero, 0x2A
/* 46B460 802A3BB0 3C01802B */  lui        $at, %hi(D_802AD348)
/* 46B464 802A3BB4 A023D348 */  sb         $v1, %lo(D_802AD348)($at)
/* 46B468 802A3BB8 080A8F1C */  j          .LPAL_802A3C70
/* 46B46C 802A3BBC 2402FFFF */   addiu     $v0, $zero, -0x1
.LPAL_802A3BC0:
/* 46B470 802A3BC0 3C028007 */  lui        $v0, %hi(D_PAL_800714AC)
/* 46B474 802A3BC4 8C4214AC */  lw         $v0, %lo(D_PAL_800714AC)($v0)
/* 46B478 802A3BC8 8C420010 */  lw         $v0, 0x10($v0)
/* 46B47C 802A3BCC 3042C000 */  andi       $v0, $v0, 0xC000
/* 46B480 802A3BD0 10400003 */  beqz       $v0, .LPAL_802A3BE0
/* 46B484 802A3BD4 00000000 */   nop
/* 46B488 802A3BD8 3C01802B */  lui        $at, %hi(D_802AD34B)
/* 46B48C 802A3BDC A020D34B */  sb         $zero, %lo(D_802AD34B)($at)
.LPAL_802A3BE0:
/* 46B490 802A3BE0 3C04802B */  lui        $a0, %hi(D_802AD34B)
/* 46B494 802A3BE4 2484D34B */  addiu      $a0, $a0, %lo(D_802AD34B)
/* 46B498 802A3BE8 80820000 */  lb         $v0, 0x0($a0)
/* 46B49C 802A3BEC 90830000 */  lbu        $v1, 0x0($a0)
/* 46B4A0 802A3BF0 10400004 */  beqz       $v0, .LPAL_802A3C04
/* 46B4A4 802A3BF4 2462FFFF */   addiu     $v0, $v1, -0x1
/* 46B4A8 802A3BF8 A0820000 */  sb         $v0, 0x0($a0)
/* 46B4AC 802A3BFC 080A8F1C */  j          .LPAL_802A3C70
/* 46B4B0 802A3C00 2402FFFF */   addiu     $v0, $zero, -0x1
.LPAL_802A3C04:
/* 46B4B4 802A3C04 24040009 */  addiu      $a0, $zero, 0x9
/* 46B4B8 802A3C08 0C051A8B */  jal        func_PAL_80146A2C
/* 46B4BC 802A3C0C 24050002 */   addiu     $a1, $zero, 0x2
/* 46B4C0 802A3C10 24040001 */  addiu      $a0, $zero, 0x1
/* 46B4C4 802A3C14 0C051A8B */  jal        func_PAL_80146A2C
/* 46B4C8 802A3C18 0080282D */   daddu     $a1, $a0, $zero
/* 46B4CC 802A3C1C 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B4D0 802A3C20 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B4D4 802A3C24 54400006 */  bnel       $v0, $zero, .LPAL_802A3C40
/* 46B4D8 802A3C28 24040004 */   addiu     $a0, $zero, 0x4
/* 46B4DC 802A3C2C 24040002 */  addiu      $a0, $zero, 0x2
/* 46B4E0 802A3C30 0C051A8B */  jal        func_PAL_80146A2C
/* 46B4E4 802A3C34 24050001 */   addiu     $a1, $zero, 0x1
/* 46B4E8 802A3C38 080A8F13 */  j          .LPAL_802A3C4C
/* 46B4EC 802A3C3C 24040003 */   addiu     $a0, $zero, 0x3
.LPAL_802A3C40:
/* 46B4F0 802A3C40 0C051A8B */  jal        func_PAL_80146A2C
/* 46B4F4 802A3C44 24050001 */   addiu     $a1, $zero, 0x1
/* 46B4F8 802A3C48 24040005 */  addiu      $a0, $zero, 0x5
.LPAL_802A3C4C:
/* 46B4FC 802A3C4C 0C051A8B */  jal        func_PAL_80146A2C
/* 46B500 802A3C50 24050001 */   addiu     $a1, $zero, 0x1
/* 46B504 802A3C54 24040008 */  addiu      $a0, $zero, 0x8
/* 46B508 802A3C58 0C051A8B */  jal        func_PAL_80146A2C
/* 46B50C 802A3C5C 24050001 */   addiu     $a1, $zero, 0x1
/* 46B510 802A3C60 24020001 */  addiu      $v0, $zero, 0x1
.LPAL_802A3C64:
/* 46B514 802A3C64 3C01802B */  lui        $at, %hi(D_802AD348)
/* 46B518 802A3C68 A022D348 */  sb         $v0, %lo(D_802AD348)($at)
.LPAL_802A3C6C:
/* 46B51C 802A3C6C 0000102D */  daddu      $v0, $zero, $zero
.LPAL_802A3C70:
/* 46B520 802A3C70 8FBF0044 */  lw         $ra, 0x44($sp)
/* 46B524 802A3C74 8FB60040 */  lw         $s6, 0x40($sp)
/* 46B528 802A3C78 8FB5003C */  lw         $s5, 0x3C($sp)
/* 46B52C 802A3C7C 8FB40038 */  lw         $s4, 0x38($sp)
/* 46B530 802A3C80 8FB30034 */  lw         $s3, 0x34($sp)
/* 46B534 802A3C84 8FB20030 */  lw         $s2, 0x30($sp)
/* 46B538 802A3C88 8FB1002C */  lw         $s1, 0x2C($sp)
/* 46B53C 802A3C8C 8FB00028 */  lw         $s0, 0x28($sp)
/* 46B540 802A3C90 03E00008 */  jr         $ra
/* 46B544 802A3C94 27BD0048 */   addiu     $sp, $sp, 0x48
