.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel btl_main_menu_update
/* 468A60 802A11B0 27BDFFB8 */  addiu      $sp, $sp, -0x48
/* 468A64 802A11B4 3C06800E */  lui        $a2, %hi(D_800D87E0)
/* 468A68 802A11B8 24C687E0 */  addiu      $a2, $a2, %lo(D_800D87E0)
/* 468A6C 802A11BC AFB00018 */  sw         $s0, 0x18($sp)
/* 468A70 802A11C0 3C10802B */  lui        $s0, %hi(D_802AD244)
/* 468A74 802A11C4 2610D244 */  addiu      $s0, $s0, %lo(D_802AD244)
/* 468A78 802A11C8 AFBF0030 */  sw         $ra, 0x30($sp)
/* 468A7C 802A11CC AFB5002C */  sw         $s5, 0x2C($sp)
/* 468A80 802A11D0 AFB40028 */  sw         $s4, 0x28($sp)
/* 468A84 802A11D4 AFB30024 */  sw         $s3, 0x24($sp)
/* 468A88 802A11D8 AFB20020 */  sw         $s2, 0x20($sp)
/* 468A8C 802A11DC AFB1001C */  sw         $s1, 0x1C($sp)
/* 468A90 802A11E0 F7B60040 */  sdc1       $f22, 0x40($sp)
/* 468A94 802A11E4 F7B40038 */  sdc1       $f20, 0x38($sp)
/* 468A98 802A11E8 82030000 */  lb         $v1, 0x0($s0)
/* 468A9C 802A11EC 2402000A */  addiu      $v0, $zero, 0xA
/* 468AA0 802A11F0 1062023F */  beq        $v1, $v0, .LPAL_802A1AF0
/* 468AA4 802A11F4 00000000 */   nop
/* 468AA8 802A11F8 2862000B */  slti       $v0, $v1, 0xB
/* 468AAC 802A11FC 50400010 */  beql       $v0, $zero, .LPAL_802A1240
/* 468AB0 802A1200 2402001E */   addiu     $v0, $zero, 0x1E
/* 468AB4 802A1204 10600021 */  beqz       $v1, .LPAL_802A128C
/* 468AB8 802A1208 24020036 */   addiu     $v0, $zero, 0x36
/* 468ABC 802A120C 1C600006 */  bgtz       $v1, .LPAL_802A1228
/* 468AC0 802A1210 24050001 */   addiu     $a1, $zero, 0x1
/* 468AC4 802A1214 2402FFFF */  addiu      $v0, $zero, -0x1
/* 468AC8 802A1218 1062022D */  beq        $v1, $v0, .LPAL_802A1AD0
/* 468ACC 802A121C 24030064 */   addiu     $v1, $zero, 0x64
/* 468AD0 802A1220 080A86F2 */  j          .LPAL_802A1BC8
/* 468AD4 802A1224 0000102D */   daddu     $v0, $zero, $zero
.LPAL_802A1228:
/* 468AD8 802A1228 10650141 */  beq        $v1, $a1, .LPAL_802A1730
/* 468ADC 802A122C 24020002 */   addiu     $v0, $zero, 0x2
/* 468AE0 802A1230 106201D4 */  beq        $v1, $v0, .LPAL_802A1984
/* 468AE4 802A1234 0000102D */   daddu     $v0, $zero, $zero
/* 468AE8 802A1238 080A86F2 */  j          .LPAL_802A1BC8
/* 468AEC 802A123C 00000000 */   nop
.LPAL_802A1240:
/* 468AF0 802A1240 1062024A */  beq        $v1, $v0, .LPAL_802A1B6C
/* 468AF4 802A1244 24020003 */   addiu     $v0, $zero, 0x3
/* 468AF8 802A1248 2862001F */  slti       $v0, $v1, 0x1F
/* 468AFC 802A124C 10400008 */  beqz       $v0, .LPAL_802A1270
/* 468B00 802A1250 2402000B */   addiu     $v0, $zero, 0xB
/* 468B04 802A1254 10620230 */  beq        $v1, $v0, .LPAL_802A1B18
/* 468B08 802A1258 00000000 */   nop
/* 468B0C 802A125C 24020014 */  addiu      $v0, $zero, 0x14
/* 468B10 802A1260 10620234 */  beq        $v1, $v0, .LPAL_802A1B34
/* 468B14 802A1264 24020003 */   addiu     $v0, $zero, 0x3
/* 468B18 802A1268 080A86F2 */  j          .LPAL_802A1BC8
/* 468B1C 802A126C 0000102D */   daddu     $v0, $zero, $zero
.LPAL_802A1270:
/* 468B20 802A1270 24020064 */  addiu      $v0, $zero, 0x64
/* 468B24 802A1274 10620244 */  beq        $v1, $v0, .LPAL_802A1B88
/* 468B28 802A1278 24020065 */   addiu     $v0, $zero, 0x65
/* 468B2C 802A127C 10620248 */  beq        $v1, $v0, .LPAL_802A1BA0
/* 468B30 802A1280 0000102D */   daddu     $v0, $zero, $zero
/* 468B34 802A1284 080A86F2 */  j          .LPAL_802A1BC8
/* 468B38 802A1288 00000000 */   nop
.LPAL_802A128C:
/* 468B3C 802A128C 3C01802B */  lui        $at, %hi(D_802AD2A0)
/* 468B40 802A1290 AC22D2A0 */  sw         $v0, %lo(D_802AD2A0)($at)
/* 468B44 802A1294 240200AD */  addiu      $v0, $zero, 0xAD
/* 468B48 802A1298 3C013E99 */  lui        $at, (0x3E99999A >> 16)
/* 468B4C 802A129C 3421999A */  ori        $at, $at, (0x3E99999A & 0xFFFF)
/* 468B50 802A12A0 44810000 */  mtc1       $at, $f0
/* 468B54 802A12A4 3C04802B */  lui        $a0, %hi(D_802AD2F3)
/* 468B58 802A12A8 9084D2F3 */  lbu        $a0, %lo(D_802AD2F3)($a0)
/* 468B5C 802A12AC 3C05802B */  lui        $a1, %hi(D_802AD2EC)
/* 468B60 802A12B0 24A5D2EC */  addiu      $a1, $a1, %lo(D_802AD2EC)
/* 468B64 802A12B4 3C01802B */  lui        $at, %hi(D_802AD2A4)
/* 468B68 802A12B8 AC22D2A4 */  sw         $v0, %lo(D_802AD2A4)($at)
/* 468B6C 802A12BC 3C01802B */  lui        $at, %hi(D_802AD248)
/* 468B70 802A12C0 A020D248 */  sb         $zero, %lo(D_802AD248)($at)
/* 468B74 802A12C4 3C01802B */  lui        $at, %hi(D_802AD2B0)
/* 468B78 802A12C8 E420D2B0 */  swc1       $f0, %lo(D_802AD2B0)($at)
/* 468B7C 802A12CC 3C01802B */  lui        $at, %hi(D_802AD2AB)
/* 468B80 802A12D0 A024D2AB */  sb         $a0, %lo(D_802AD2AB)($at)
/* 468B84 802A12D4 90A20003 */  lbu        $v0, 0x3($a1)
/* 468B88 802A12D8 00041823 */  negu       $v1, $a0
/* 468B8C 802A12DC 3C01802B */  lui        $at, %hi(D_802AD2A9)
/* 468B90 802A12E0 A023D2A9 */  sb         $v1, %lo(D_802AD2A9)($at)
/* 468B94 802A12E4 8CA30000 */  lw         $v1, 0x0($a1)
/* 468B98 802A12E8 2442FFFF */  addiu      $v0, $v0, -0x1
/* 468B9C 802A12EC 00441023 */  subu       $v0, $v0, $a0
/* 468BA0 802A12F0 3C01802B */  lui        $at, %hi(D_802AD2AA)
/* 468BA4 802A12F4 A022D2AA */  sb         $v0, %lo(D_802AD2AA)($at)
/* 468BA8 802A12F8 1860002A */  blez       $v1, .LPAL_802A13A4
/* 468BAC 802A12FC 0000982D */   daddu     $s3, $zero, $zero
/* 468BB0 802A1300 3C14802B */  lui        $s4, %hi(D_802AD268)
/* 468BB4 802A1304 2694D268 */  addiu      $s4, $s4, %lo(D_802AD268)
/* 468BB8 802A1308 3C12802B */  lui        $s2, %hi(D_802AD250)
/* 468BBC 802A130C 2652D250 */  addiu      $s2, $s2, %lo(D_802AD250)
/* 468BC0 802A1310 3C10802B */  lui        $s0, %hi(D_802AD2B8)
/* 468BC4 802A1314 2610D2B8 */  addiu      $s0, $s0, %lo(D_802AD2B8)
.LPAL_802A1318:
/* 468BC8 802A1318 8E040000 */  lw         $a0, 0x0($s0)
/* 468BCC 802A131C 26100004 */  addiu      $s0, $s0, 0x4
/* 468BD0 802A1320 0C050015 */  jal        func_PAL_80140054
/* 468BD4 802A1324 26730001 */   addiu     $s3, $s3, 0x1
/* 468BD8 802A1328 0040882D */  daddu      $s1, $v0, $zero
/* 468BDC 802A132C 0220202D */  daddu      $a0, $s1, $zero
/* 468BE0 802A1330 24050005 */  addiu      $a1, $zero, 0x5
/* 468BE4 802A1334 0C050D63 */  jal        func_PAL_8014358C
/* 468BE8 802A1338 AE510000 */   sw        $s1, 0x0($s2)
/* 468BEC 802A133C 0220202D */  daddu      $a0, $s1, $zero
/* 468BF0 802A1340 0C050D6C */  jal        func_PAL_801435B0
/* 468BF4 802A1344 34058082 */   ori       $a1, $zero, 0x8082
/* 468BF8 802A1348 0220202D */  daddu      $a0, $s1, $zero
/* 468BFC 802A134C 3C053F40 */  lui        $a1, (0x3F400000 >> 16)
/* 468C00 802A1350 0C050DF4 */  jal        func_PAL_801437D0
/* 468C04 802A1354 26520004 */   addiu     $s2, $s2, 0x4
/* 468C08 802A1358 3C048029 */  lui        $a0, %hi(D_802932E0)
/* 468C0C 802A135C 248432E0 */  addiu      $a0, $a0, %lo(D_802932E0)
/* 468C10 802A1360 0C050015 */  jal        func_PAL_80140054
/* 468C14 802A1364 00000000 */   nop
/* 468C18 802A1368 0040882D */  daddu      $s1, $v0, $zero
/* 468C1C 802A136C 0220202D */  daddu      $a0, $s1, $zero
/* 468C20 802A1370 0C050EE2 */  jal        func_PAL_80143B88
/* 468C24 802A1374 AE910000 */   sw        $s1, 0x0($s4)
/* 468C28 802A1378 0220202D */  daddu      $a0, $s1, $zero
/* 468C2C 802A137C 0C050D63 */  jal        func_PAL_8014358C
/* 468C30 802A1380 2405000A */   addiu     $a1, $zero, 0xA
/* 468C34 802A1384 0220202D */  daddu      $a0, $s1, $zero
/* 468C38 802A1388 0C050D6C */  jal        func_PAL_801435B0
/* 468C3C 802A138C 34058082 */   ori       $a1, $zero, 0x8082
/* 468C40 802A1390 3C02802B */  lui        $v0, %hi(D_802AD2EC)
/* 468C44 802A1394 8C42D2EC */  lw         $v0, %lo(D_802AD2EC)($v0)
/* 468C48 802A1398 0262102A */  slt        $v0, $s3, $v0
/* 468C4C 802A139C 1440FFDE */  bnez       $v0, .LPAL_802A1318
/* 468C50 802A13A0 26940004 */   addiu     $s4, $s4, 0x4
.LPAL_802A13A4:
/* 468C54 802A13A4 3C048029 */  lui        $a0, %hi(D_802932E0)
/* 468C58 802A13A8 248432E0 */  addiu      $a0, $a0, %lo(D_802932E0)
/* 468C5C 802A13AC 0C050015 */  jal        func_PAL_80140054
/* 468C60 802A13B0 00000000 */   nop
/* 468C64 802A13B4 0040882D */  daddu      $s1, $v0, $zero
/* 468C68 802A13B8 3C01802B */  lui        $at, %hi(D_802AD280)
/* 468C6C 802A13BC AC31D280 */  sw         $s1, %lo(D_802AD280)($at)
/* 468C70 802A13C0 0C050EE2 */  jal        func_PAL_80143B88
/* 468C74 802A13C4 0220202D */   daddu     $a0, $s1, $zero
/* 468C78 802A13C8 0220202D */  daddu      $a0, $s1, $zero
/* 468C7C 802A13CC 0C050D63 */  jal        func_PAL_8014358C
/* 468C80 802A13D0 24050007 */   addiu     $a1, $zero, 0x7
/* 468C84 802A13D4 0220202D */  daddu      $a0, $s1, $zero
/* 468C88 802A13D8 0C050D6C */  jal        func_PAL_801435B0
/* 468C8C 802A13DC 34058082 */   ori       $a1, $zero, 0x8082
/* 468C90 802A13E0 3C108029 */  lui        $s0, %hi(D_802932B8)
/* 468C94 802A13E4 261032B8 */  addiu      $s0, $s0, %lo(D_802932B8)
/* 468C98 802A13E8 0C050015 */  jal        func_PAL_80140054
/* 468C9C 802A13EC 0200202D */   daddu     $a0, $s0, $zero
/* 468CA0 802A13F0 0040882D */  daddu      $s1, $v0, $zero
/* 468CA4 802A13F4 3C01802B */  lui        $at, %hi(D_802AD284)
/* 468CA8 802A13F8 AC31D284 */  sw         $s1, %lo(D_802AD284)($at)
/* 468CAC 802A13FC 0C050EE2 */  jal        func_PAL_80143B88
/* 468CB0 802A1400 0220202D */   daddu     $a0, $s1, $zero
/* 468CB4 802A1404 0220202D */  daddu      $a0, $s1, $zero
/* 468CB8 802A1408 0C050D63 */  jal        func_PAL_8014358C
/* 468CBC 802A140C 0000282D */   daddu     $a1, $zero, $zero
/* 468CC0 802A1410 0220202D */  daddu      $a0, $s1, $zero
/* 468CC4 802A1414 24050028 */  addiu      $a1, $zero, 0x28
/* 468CC8 802A1418 0C050D4D */  jal        func_PAL_80143534
/* 468CCC 802A141C 240600D4 */   addiu     $a2, $zero, 0xD4
/* 468CD0 802A1420 0220202D */  daddu      $a0, $s1, $zero
/* 468CD4 802A1424 0000282D */  daddu      $a1, $zero, $zero
/* 468CD8 802A1428 2406005B */  addiu      $a2, $zero, 0x5B
/* 468CDC 802A142C 0C050EAB */  jal        func_PAL_80143AAC
/* 468CE0 802A1430 2407007F */   addiu     $a3, $zero, 0x7F
/* 468CE4 802A1434 0220202D */  daddu      $a0, $s1, $zero
/* 468CE8 802A1438 24050010 */  addiu      $a1, $zero, 0x10
/* 468CEC 802A143C 0C050F89 */  jal        func_PAL_80143E24
/* 468CF0 802A1440 2406FFF0 */   addiu     $a2, $zero, -0x10
/* 468CF4 802A1444 0220202D */  daddu      $a0, $s1, $zero
/* 468CF8 802A1448 0C050D6C */  jal        func_PAL_801435B0
/* 468CFC 802A144C 24050080 */   addiu     $a1, $zero, 0x80
/* 468D00 802A1450 0220202D */  daddu      $a0, $s1, $zero
/* 468D04 802A1454 0C050D77 */  jal        func_PAL_801435DC
/* 468D08 802A1458 34058000 */   ori       $a1, $zero, 0x8000
/* 468D0C 802A145C 0220202D */  daddu      $a0, $s1, $zero
/* 468D10 802A1460 0C050E98 */  jal        func_PAL_80143A60
/* 468D14 802A1464 240500F0 */   addiu     $a1, $zero, 0xF0
/* 468D18 802A1468 0C050015 */  jal        func_PAL_80140054
/* 468D1C 802A146C 0200202D */   daddu     $a0, $s0, $zero
/* 468D20 802A1470 0040882D */  daddu      $s1, $v0, $zero
/* 468D24 802A1474 3C01802B */  lui        $at, %hi(D_802AD288)
/* 468D28 802A1478 AC31D288 */  sw         $s1, %lo(D_802AD288)($at)
/* 468D2C 802A147C 0C050EE2 */  jal        func_PAL_80143B88
/* 468D30 802A1480 0220202D */   daddu     $a0, $s1, $zero
/* 468D34 802A1484 0220202D */  daddu      $a0, $s1, $zero
/* 468D38 802A1488 0C050D63 */  jal        func_PAL_8014358C
/* 468D3C 802A148C 24050002 */   addiu     $a1, $zero, 0x2
/* 468D40 802A1490 0220202D */  daddu      $a0, $s1, $zero
/* 468D44 802A1494 24050027 */  addiu      $a1, $zero, 0x27
/* 468D48 802A1498 0C050D4D */  jal        func_PAL_80143534
/* 468D4C 802A149C 240600D4 */   addiu     $a2, $zero, 0xD4
/* 468D50 802A14A0 0220202D */  daddu      $a0, $s1, $zero
/* 468D54 802A14A4 0000282D */  daddu      $a1, $zero, $zero
/* 468D58 802A14A8 2406005B */  addiu      $a2, $zero, 0x5B
/* 468D5C 802A14AC 0C050EAB */  jal        func_PAL_80143AAC
/* 468D60 802A14B0 2407007F */   addiu     $a3, $zero, 0x7F
/* 468D64 802A14B4 0220202D */  daddu      $a0, $s1, $zero
/* 468D68 802A14B8 24050010 */  addiu      $a1, $zero, 0x10
/* 468D6C 802A14BC 0C050F89 */  jal        func_PAL_80143E24
/* 468D70 802A14C0 2406FFF0 */   addiu     $a2, $zero, -0x10
/* 468D74 802A14C4 0220202D */  daddu      $a0, $s1, $zero
/* 468D78 802A14C8 0C050D6C */  jal        func_PAL_801435B0
/* 468D7C 802A14CC 24050080 */   addiu     $a1, $zero, 0x80
/* 468D80 802A14D0 0220202D */  daddu      $a0, $s1, $zero
/* 468D84 802A14D4 0C050D77 */  jal        func_PAL_801435DC
/* 468D88 802A14D8 34058000 */   ori       $a1, $zero, 0x8000
/* 468D8C 802A14DC 0220202D */  daddu      $a0, $s1, $zero
/* 468D90 802A14E0 0C050E98 */  jal        func_PAL_80143A60
/* 468D94 802A14E4 240500F0 */   addiu     $a1, $zero, 0xF0
/* 468D98 802A14E8 3C048029 */  lui        $a0, %hi(D_PAL_80293308)
/* 468D9C 802A14EC 24843308 */  addiu      $a0, $a0, %lo(D_PAL_80293308)
/* 468DA0 802A14F0 0C050015 */  jal        func_PAL_80140054
/* 468DA4 802A14F4 00000000 */   nop
/* 468DA8 802A14F8 0040882D */  daddu      $s1, $v0, $zero
/* 468DAC 802A14FC 3C01802B */  lui        $at, %hi(D_802AD28C)
/* 468DB0 802A1500 AC31D28C */  sw         $s1, %lo(D_802AD28C)($at)
/* 468DB4 802A1504 0C050EE2 */  jal        func_PAL_80143B88
/* 468DB8 802A1508 0220202D */   daddu     $a0, $s1, $zero
/* 468DBC 802A150C 0220202D */  daddu      $a0, $s1, $zero
/* 468DC0 802A1510 0C050D63 */  jal        func_PAL_8014358C
/* 468DC4 802A1514 24050014 */   addiu     $a1, $zero, 0x14
/* 468DC8 802A1518 0220202D */  daddu      $a0, $s1, $zero
/* 468DCC 802A151C 2405004E */  addiu      $a1, $zero, 0x4E
/* 468DD0 802A1520 0C050D4D */  jal        func_PAL_80143534
/* 468DD4 802A1524 240600B2 */   addiu     $a2, $zero, 0xB2
/* 468DD8 802A1528 0220202D */  daddu      $a0, $s1, $zero
/* 468DDC 802A152C 240500FF */  addiu      $a1, $zero, 0xFF
/* 468DE0 802A1530 00A0302D */  daddu      $a2, $a1, $zero
/* 468DE4 802A1534 0C050EAB */  jal        func_PAL_80143AAC
/* 468DE8 802A1538 00A0382D */   daddu     $a3, $a1, $zero
/* 468DEC 802A153C 0220202D */  daddu      $a0, $s1, $zero
/* 468DF0 802A1540 0000282D */  daddu      $a1, $zero, $zero
/* 468DF4 802A1544 0C050F89 */  jal        func_PAL_80143E24
/* 468DF8 802A1548 00A0302D */   daddu     $a2, $a1, $zero
/* 468DFC 802A154C 44800000 */  mtc1       $zero, $f0
/* 468E00 802A1550 0220202D */  daddu      $a0, $s1, $zero
/* 468E04 802A1554 44050000 */  mfc1       $a1, $f0
/* 468E08 802A1558 3C07C234 */  lui        $a3, (0xC2340000 >> 16)
/* 468E0C 802A155C 0C050F75 */  jal        func_PAL_80143DD4
/* 468E10 802A1560 00A0302D */   daddu     $a2, $a1, $zero
/* 468E14 802A1564 0220202D */  daddu      $a0, $s1, $zero
/* 468E18 802A1568 0C050E98 */  jal        func_PAL_80143A60
/* 468E1C 802A156C 240500C8 */   addiu     $a1, $zero, 0xC8
/* 468E20 802A1570 0220202D */  daddu      $a0, $s1, $zero
/* 468E24 802A1574 0C050D6C */  jal        func_PAL_801435B0
/* 468E28 802A1578 34058082 */   ori       $a1, $zero, 0x8082
/* 468E2C 802A157C 3C048029 */  lui        $a0, %hi(D_802933D4)
/* 468E30 802A1580 248433D4 */  addiu      $a0, $a0, %lo(D_802933D4)
/* 468E34 802A1584 0C050015 */  jal        func_PAL_80140054
/* 468E38 802A1588 00000000 */   nop
/* 468E3C 802A158C 0040882D */  daddu      $s1, $v0, $zero
/* 468E40 802A1590 0220202D */  daddu      $a0, $s1, $zero
/* 468E44 802A1594 3C01802B */  lui        $at, %hi(D_802AD29C)
/* 468E48 802A1598 AC31D29C */  sw         $s1, %lo(D_802AD29C)($at)
/* 468E4C 802A159C 0C050D63 */  jal        func_PAL_8014358C
/* 468E50 802A15A0 0000282D */   daddu     $a1, $zero, $zero
/* 468E54 802A15A4 0220202D */  daddu      $a0, $s1, $zero
/* 468E58 802A15A8 24050061 */  addiu      $a1, $zero, 0x61
/* 468E5C 802A15AC 0C050D4D */  jal        func_PAL_80143534
/* 468E60 802A15B0 240600D0 */   addiu     $a2, $zero, 0xD0
/* 468E64 802A15B4 0220202D */  daddu      $a0, $s1, $zero
/* 468E68 802A15B8 240500FF */  addiu      $a1, $zero, 0xFF
/* 468E6C 802A15BC 00A0302D */  daddu      $a2, $a1, $zero
/* 468E70 802A15C0 0C050EAB */  jal        func_PAL_80143AAC
/* 468E74 802A15C4 00A0382D */   daddu     $a3, $a1, $zero
/* 468E78 802A15C8 0220202D */  daddu      $a0, $s1, $zero
/* 468E7C 802A15CC 0C050D6C */  jal        func_PAL_801435B0
/* 468E80 802A15D0 24050080 */   addiu     $a1, $zero, 0x80
/* 468E84 802A15D4 0220202D */  daddu      $a0, $s1, $zero
/* 468E88 802A15D8 0C050D77 */  jal        func_PAL_801435DC
/* 468E8C 802A15DC 34058000 */   ori       $a1, $zero, 0x8000
/* 468E90 802A15E0 0220202D */  daddu      $a0, $s1, $zero
/* 468E94 802A15E4 0C050E98 */  jal        func_PAL_80143A60
/* 468E98 802A15E8 240500E6 */   addiu     $a1, $zero, 0xE6
/* 468E9C 802A15EC 3C048029 */  lui        $a0, %hi(D_80293330)
/* 468EA0 802A15F0 24843330 */  addiu      $a0, $a0, %lo(D_80293330)
/* 468EA4 802A15F4 0C050015 */  jal        func_PAL_80140054
/* 468EA8 802A15F8 00000000 */   nop
/* 468EAC 802A15FC 0040882D */  daddu      $s1, $v0, $zero
/* 468EB0 802A1600 0220202D */  daddu      $a0, $s1, $zero
/* 468EB4 802A1604 3C01802B */  lui        $at, %hi(D_802AD290)
/* 468EB8 802A1608 AC31D290 */  sw         $s1, %lo(D_802AD290)($at)
/* 468EBC 802A160C 0C050D63 */  jal        func_PAL_8014358C
/* 468EC0 802A1610 24050005 */   addiu     $a1, $zero, 0x5
/* 468EC4 802A1614 0220202D */  daddu      $a0, $s1, $zero
/* 468EC8 802A1618 0C050D77 */  jal        func_PAL_801435DC
/* 468ECC 802A161C 34058000 */   ori       $a1, $zero, 0x8000
/* 468ED0 802A1620 0220202D */  daddu      $a0, $s1, $zero
/* 468ED4 802A1624 0C050D6C */  jal        func_PAL_801435B0
/* 468ED8 802A1628 24050080 */   addiu     $a1, $zero, 0x80
/* 468EDC 802A162C 0220202D */  daddu      $a0, $s1, $zero
/* 468EE0 802A1630 2405005E */  addiu      $a1, $zero, 0x5E
/* 468EE4 802A1634 0C050D4D */  jal        func_PAL_80143534
/* 468EE8 802A1638 240600D1 */   addiu     $a2, $zero, 0xD1
/* 468EEC 802A163C 3C048029 */  lui        $a0, %hi(D_8029335C)
/* 468EF0 802A1640 2484335C */  addiu      $a0, $a0, %lo(D_8029335C)
/* 468EF4 802A1644 0C050015 */  jal        func_PAL_80140054
/* 468EF8 802A1648 00000000 */   nop
/* 468EFC 802A164C 0040882D */  daddu      $s1, $v0, $zero
/* 468F00 802A1650 0220202D */  daddu      $a0, $s1, $zero
/* 468F04 802A1654 3C01802B */  lui        $at, %hi(D_802AD294)
/* 468F08 802A1658 AC31D294 */  sw         $s1, %lo(D_802AD294)($at)
/* 468F0C 802A165C 0C050D63 */  jal        func_PAL_8014358C
/* 468F10 802A1660 24050005 */   addiu     $a1, $zero, 0x5
/* 468F14 802A1664 0220202D */  daddu      $a0, $s1, $zero
/* 468F18 802A1668 0C050D77 */  jal        func_PAL_801435DC
/* 468F1C 802A166C 34058000 */   ori       $a1, $zero, 0x8000
/* 468F20 802A1670 0220202D */  daddu      $a0, $s1, $zero
/* 468F24 802A1674 0C050D6C */  jal        func_PAL_801435B0
/* 468F28 802A1678 24050080 */   addiu     $a1, $zero, 0x80
/* 468F2C 802A167C 0220202D */  daddu      $a0, $s1, $zero
/* 468F30 802A1680 24050051 */  addiu      $a1, $zero, 0x51
/* 468F34 802A1684 0C050D4D */  jal        func_PAL_80143534
/* 468F38 802A1688 240600D2 */   addiu     $a2, $zero, 0xD2
/* 468F3C 802A168C 3C048029 */  lui        $a0, %hi(D_80293398)
/* 468F40 802A1690 24843398 */  addiu      $a0, $a0, %lo(D_80293398)
/* 468F44 802A1694 0C050015 */  jal        func_PAL_80140054
/* 468F48 802A1698 00000000 */   nop
/* 468F4C 802A169C 0040882D */  daddu      $s1, $v0, $zero
/* 468F50 802A16A0 0220202D */  daddu      $a0, $s1, $zero
/* 468F54 802A16A4 3C01802B */  lui        $at, %hi(D_802AD298)
/* 468F58 802A16A8 AC31D298 */  sw         $s1, %lo(D_802AD298)($at)
/* 468F5C 802A16AC 0C050D63 */  jal        func_PAL_8014358C
/* 468F60 802A16B0 24050005 */   addiu     $a1, $zero, 0x5
/* 468F64 802A16B4 0220202D */  daddu      $a0, $s1, $zero
/* 468F68 802A16B8 0C050D77 */  jal        func_PAL_801435DC
/* 468F6C 802A16BC 34058000 */   ori       $a1, $zero, 0x8000
/* 468F70 802A16C0 0220202D */  daddu      $a0, $s1, $zero
/* 468F74 802A16C4 0C050D6C */  jal        func_PAL_801435B0
/* 468F78 802A16C8 24050080 */   addiu     $a1, $zero, 0x80
/* 468F7C 802A16CC 0220202D */  daddu      $a0, $s1, $zero
/* 468F80 802A16D0 24050066 */  addiu      $a1, $zero, 0x66
/* 468F84 802A16D4 0C050D4D */  jal        func_PAL_80143534
/* 468F88 802A16D8 240600D2 */   addiu     $a2, $zero, 0xD2
/* 468F8C 802A16DC 3C03802B */  lui        $v1, %hi(D_802AD340)
/* 468F90 802A16E0 8C63D340 */  lw         $v1, %lo(D_802AD340)($v1)
/* 468F94 802A16E4 24020064 */  addiu      $v0, $zero, 0x64
/* 468F98 802A16E8 3C01802B */  lui        $at, %hi(D_802AD24E)
/* 468F9C 802A16EC A422D24E */  sh         $v0, %lo(D_802AD24E)($at)
/* 468FA0 802A16F0 24020003 */  addiu      $v0, $zero, 0x3
/* 468FA4 802A16F4 3C01802B */  lui        $at, %hi(D_802AD245)
/* 468FA8 802A16F8 A022D245 */  sb         $v0, %lo(D_802AD245)($at)
/* 468FAC 802A16FC 24020001 */  addiu      $v0, $zero, 0x1
/* 468FB0 802A1700 3C01802B */  lui        $at, %hi(D_802AD244)
/* 468FB4 802A1704 A022D244 */  sb         $v0, %lo(D_802AD244)($at)
/* 468FB8 802A1708 000310C0 */  sll        $v0, $v1, 3
/* 468FBC 802A170C 00431023 */  subu       $v0, $v0, $v1
/* 468FC0 802A1710 00021080 */  sll        $v0, $v0, 2
/* 468FC4 802A1714 4482A000 */  mtc1       $v0, $f20
/* 468FC8 802A1718 00000000 */  nop
/* 468FCC 802A171C 4680A520 */  cvt.s.w    $f20, $f20
/* 468FD0 802A1720 3C01802B */  lui        $at, %hi(D_802AD2AC)
/* 468FD4 802A1724 E434D2AC */  swc1       $f20, %lo(D_802AD2AC)($at)
/* 468FD8 802A1728 080A86F2 */  j          .LPAL_802A1BC8
/* 468FDC 802A172C 0000102D */   daddu     $v0, $zero, $zero
.LPAL_802A1730:
/* 468FE0 802A1730 3C035555 */  lui        $v1, (0x55555556 >> 16)
/* 468FE4 802A1734 3C10802B */  lui        $s0, %hi(D_802AD245)
/* 468FE8 802A1738 2610D245 */  addiu      $s0, $s0, %lo(D_802AD245)
/* 468FEC 802A173C 82040000 */  lb         $a0, 0x0($s0)
/* 468FF0 802A1740 34635556 */  ori        $v1, $v1, (0x55555556 & 0xFFFF)
/* 468FF4 802A1744 00041040 */  sll        $v0, $a0, 1
/* 468FF8 802A1748 00441021 */  addu       $v0, $v0, $a0
/* 468FFC 802A174C 000210C0 */  sll        $v0, $v0, 3
/* 469000 802A1750 00441021 */  addu       $v0, $v0, $a0
/* 469004 802A1754 00021080 */  sll        $v0, $v0, 2
/* 469008 802A1758 00430018 */  mult       $v0, $v1
/* 46900C 802A175C 000217C3 */  sra        $v0, $v0, 31
/* 469010 802A1760 00004010 */  mfhi       $t0
/* 469014 802A1764 01021023 */  subu       $v0, $t0, $v0
/* 469018 802A1768 3C01802B */  lui        $at, %hi(D_802AD24E)
/* 46901C 802A176C A422D24E */  sh         $v0, %lo(D_802AD24E)($at)
/* 469020 802A1770 1080000A */  beqz       $a0, .LPAL_802A179C
/* 469024 802A1774 00000000 */   nop
/* 469028 802A1778 14850005 */  bne        $a0, $a1, .LPAL_802A1790
/* 46902C 802A177C 00000000 */   nop
/* 469030 802A1780 3C04802B */  lui        $a0, %hi(D_802AD28C)
/* 469034 802A1784 8C84D28C */  lw         $a0, %lo(D_802AD28C)($a0)
/* 469038 802A1788 0C050D77 */  jal        func_PAL_801435DC
/* 46903C 802A178C 24050002 */   addiu     $a1, $zero, 0x2
.LPAL_802A1790:
/* 469040 802A1790 92020000 */  lbu        $v0, 0x0($s0)
/* 469044 802A1794 080A86F0 */  j          .LPAL_802A1BC0
/* 469048 802A1798 2442FFFF */   addiu     $v0, $v0, -0x1
.LPAL_802A179C:
/* 46904C 802A179C 3C02802B */  lui        $v0, %hi(D_802AD340)
/* 469050 802A17A0 8C42D340 */  lw         $v0, %lo(D_802AD340)($v0)
/* 469054 802A17A4 3C01802B */  lui        $at, %hi(D_802AD246)
/* 469058 802A17A8 A020D246 */  sb         $zero, %lo(D_802AD246)($at)
/* 46905C 802A17AC 3C01802B */  lui        $at, %hi(D_802AD247)
/* 469060 802A17B0 A020D247 */  sb         $zero, %lo(D_802AD247)($at)
/* 469064 802A17B4 000218C0 */  sll        $v1, $v0, 3
/* 469068 802A17B8 00621823 */  subu       $v1, $v1, $v0
/* 46906C 802A17BC 00031880 */  sll        $v1, $v1, 2
/* 469070 802A17C0 3C02802B */  lui        $v0, %hi(D_802AD2EC)
/* 469074 802A17C4 8C42D2EC */  lw         $v0, %lo(D_802AD2EC)($v0)
/* 469078 802A17C8 4483A000 */  mtc1       $v1, $f20
/* 46907C 802A17CC 00000000 */  nop
/* 469080 802A17D0 4680A520 */  cvt.s.w    $f20, $f20
/* 469084 802A17D4 3C01802B */  lui        $at, %hi(D_802AD2AC)
/* 469088 802A17D8 E434D2AC */  swc1       $f20, %lo(D_802AD2AC)($at)
/* 46908C 802A17DC 18400039 */  blez       $v0, .LPAL_802A18C4
/* 469090 802A17E0 0000982D */   daddu     $s3, $zero, $zero
/* 469094 802A17E4 4480B000 */  mtc1       $zero, $f22
/* 469098 802A17E8 3C15802B */  lui        $s5, %hi(D_802AD268)
/* 46909C 802A17EC 26B5D268 */  addiu      $s5, $s5, %lo(D_802AD268)
/* 4690A0 802A17F0 3C14802B */  lui        $s4, %hi(D_802AD250)
/* 4690A4 802A17F4 2694D250 */  addiu      $s4, $s4, %lo(D_802AD250)
.LPAL_802A17F8:
/* 4690A8 802A17F8 27A40010 */  addiu      $a0, $sp, 0x10
/* 4690AC 802A17FC 27A50014 */  addiu      $a1, $sp, 0x14
/* 4690B0 802A1800 3C0642AE */  lui        $a2, (0x42AE0000 >> 16)
/* 4690B4 802A1804 4407A000 */  mfc1       $a3, $f20
/* 4690B8 802A1808 26730001 */  addiu      $s3, $s3, 0x1
/* 4690BC 802A180C E7B60010 */  swc1       $f22, 0x10($sp)
/* 4690C0 802A1810 0C00A7C7 */  jal        func_PAL_80029F1C
/* 4690C4 802A1814 E7B60014 */   swc1      $f22, 0x14($sp)
/* 4690C8 802A1818 8E910000 */  lw         $s1, 0x0($s4)
/* 4690CC 802A181C 26940004 */  addiu      $s4, $s4, 0x4
/* 4690D0 802A1820 3C01802B */  lui        $at, %hi(D_802AD2A0)
/* 4690D4 802A1824 C422D2A0 */  lwc1       $f2, %lo(D_802AD2A0)($at)
/* 4690D8 802A1828 468010A0 */  cvt.s.w    $f2, $f2
/* 4690DC 802A182C C7A00010 */  lwc1       $f0, 0x10($sp)
/* 4690E0 802A1830 C7A40014 */  lwc1       $f4, 0x14($sp)
/* 4690E4 802A1834 46001080 */  add.s      $f2, $f2, $f0
/* 4690E8 802A1838 0220202D */  daddu      $a0, $s1, $zero
/* 4690EC 802A183C 3C01802B */  lui        $at, %hi(D_802AD2A4)
/* 4690F0 802A1840 C420D2A4 */  lwc1       $f0, %lo(D_802AD2A4)($at)
/* 4690F4 802A1844 46800020 */  cvt.s.w    $f0, $f0
/* 4690F8 802A1848 46040000 */  add.s      $f0, $f0, $f4
/* 4690FC 802A184C 4600118D */  trunc.w.s  $f6, $f2
/* 469100 802A1850 44123000 */  mfc1       $s2, $f6
/* 469104 802A1854 00000000 */  nop
/* 469108 802A1858 0240282D */  daddu      $a1, $s2, $zero
/* 46910C 802A185C 4600018D */  trunc.w.s  $f6, $f0
/* 469110 802A1860 44103000 */  mfc1       $s0, $f6
/* 469114 802A1864 0C050D4D */  jal        func_PAL_80143534
/* 469118 802A1868 0200302D */   daddu     $a2, $s0, $zero
/* 46911C 802A186C 0220202D */  daddu      $a0, $s1, $zero
/* 469120 802A1870 0C050D77 */  jal        func_PAL_801435DC
/* 469124 802A1874 24050002 */   addiu     $a1, $zero, 0x2
/* 469128 802A1878 0240282D */  daddu      $a1, $s2, $zero
/* 46912C 802A187C 0200302D */  daddu      $a2, $s0, $zero
/* 469130 802A1880 8EB10000 */  lw         $s1, 0x0($s5)
/* 469134 802A1884 26B50004 */  addiu      $s5, $s5, 0x4
/* 469138 802A1888 0C050D4D */  jal        func_PAL_80143534
/* 46913C 802A188C 0220202D */   daddu     $a0, $s1, $zero
/* 469140 802A1890 0220202D */  daddu      $a0, $s1, $zero
/* 469144 802A1894 0C050E98 */  jal        func_PAL_80143A60
/* 469148 802A1898 24050064 */   addiu     $a1, $zero, 0x64
/* 46914C 802A189C 0220202D */  daddu      $a0, $s1, $zero
/* 469150 802A18A0 0C050D77 */  jal        func_PAL_801435DC
/* 469154 802A18A4 24050002 */   addiu     $a1, $zero, 0x2
/* 469158 802A18A8 3C02802B */  lui        $v0, %hi(D_802AD2EC)
/* 46915C 802A18AC 8C42D2EC */  lw         $v0, %lo(D_802AD2EC)($v0)
/* 469160 802A18B0 3C0141E0 */  lui        $at, (0x41E00000 >> 16)
/* 469164 802A18B4 44810000 */  mtc1       $at, $f0
/* 469168 802A18B8 0262102A */  slt        $v0, $s3, $v0
/* 46916C 802A18BC 1440FFCE */  bnez       $v0, .LPAL_802A17F8
/* 469170 802A18C0 4600A500 */   add.s     $f20, $f20, $f0
.LPAL_802A18C4:
/* 469174 802A18C4 27A40010 */  addiu      $a0, $sp, 0x10
/* 469178 802A18C8 3C03802B */  lui        $v1, %hi(D_802AD340)
/* 46917C 802A18CC 8C63D340 */  lw         $v1, %lo(D_802AD340)($v1)
/* 469180 802A18D0 3C0642AE */  lui        $a2, (0x42AE0000 >> 16)
/* 469184 802A18D4 000310C0 */  sll        $v0, $v1, 3
/* 469188 802A18D8 00431023 */  subu       $v0, $v0, $v1
/* 46918C 802A18DC 00021080 */  sll        $v0, $v0, 2
/* 469190 802A18E0 44823000 */  mtc1       $v0, $f6
/* 469194 802A18E4 00000000 */  nop
/* 469198 802A18E8 468031A0 */  cvt.s.w    $f6, $f6
/* 46919C 802A18EC 44073000 */  mfc1       $a3, $f6
/* 4691A0 802A18F0 27A50014 */  addiu      $a1, $sp, 0x14
/* 4691A4 802A18F4 AFA00010 */  sw         $zero, 0x10($sp)
/* 4691A8 802A18F8 0C00A7C7 */  jal        func_PAL_80029F1C
/* 4691AC 802A18FC AFA00014 */   sw        $zero, 0x14($sp)
/* 4691B0 802A1900 3C01802B */  lui        $at, %hi(D_802AD2A0)
/* 4691B4 802A1904 C422D2A0 */  lwc1       $f2, %lo(D_802AD2A0)($at)
/* 4691B8 802A1908 468010A0 */  cvt.s.w    $f2, $f2
/* 4691BC 802A190C C7A00010 */  lwc1       $f0, 0x10($sp)
/* 4691C0 802A1910 3C11802B */  lui        $s1, %hi(D_802AD280)
/* 4691C4 802A1914 8E31D280 */  lw         $s1, %lo(D_802AD280)($s1)
/* 4691C8 802A1918 46001080 */  add.s      $f2, $f2, $f0
/* 4691CC 802A191C C7A40014 */  lwc1       $f4, 0x14($sp)
/* 4691D0 802A1920 3C01802B */  lui        $at, %hi(D_802AD2A4)
/* 4691D4 802A1924 C420D2A4 */  lwc1       $f0, %lo(D_802AD2A4)($at)
/* 4691D8 802A1928 46800020 */  cvt.s.w    $f0, $f0
/* 4691DC 802A192C 46040000 */  add.s      $f0, $f0, $f4
/* 4691E0 802A1930 4600118D */  trunc.w.s  $f6, $f2
/* 4691E4 802A1934 44053000 */  mfc1       $a1, $f6
/* 4691E8 802A1938 4600018D */  trunc.w.s  $f6, $f0
/* 4691EC 802A193C 44063000 */  mfc1       $a2, $f6
/* 4691F0 802A1940 0C050D4D */  jal        func_PAL_80143534
/* 4691F4 802A1944 0220202D */   daddu     $a0, $s1, $zero
/* 4691F8 802A1948 0220202D */  daddu      $a0, $s1, $zero
/* 4691FC 802A194C 0C050E98 */  jal        func_PAL_80143A60
/* 469200 802A1950 240500B4 */   addiu     $a1, $zero, 0xB4
/* 469204 802A1954 3C053F59 */  lui        $a1, (0x3F59999A >> 16)
/* 469208 802A1958 34A5999A */  ori        $a1, $a1, (0x3F59999A & 0xFFFF)
/* 46920C 802A195C 0C050DF4 */  jal        func_PAL_801437D0
/* 469210 802A1960 0220202D */   daddu     $a0, $s1, $zero
/* 469214 802A1964 0220202D */  daddu      $a0, $s1, $zero
/* 469218 802A1968 0C050D77 */  jal        func_PAL_801435DC
/* 46921C 802A196C 24050002 */   addiu     $a1, $zero, 0x2
/* 469220 802A1970 24020002 */  addiu      $v0, $zero, 0x2
/* 469224 802A1974 3C01802B */  lui        $at, %hi(D_802AD244)
/* 469228 802A1978 A022D244 */  sb         $v0, %lo(D_802AD244)($at)
/* 46922C 802A197C 080A86F2 */  j          .LPAL_802A1BC8
/* 469230 802A1980 0000102D */   daddu     $v0, $zero, $zero
.LPAL_802A1984:
/* 469234 802A1984 8CC20214 */  lw         $v0, 0x214($a2)
/* 469238 802A1988 30428000 */  andi       $v0, $v0, 0x8000
/* 46923C 802A198C 10400021 */  beqz       $v0, .LPAL_802A1A14
/* 469240 802A1990 00000000 */   nop
/* 469244 802A1994 3C11802B */  lui        $s1, %hi(D_802AD246)
/* 469248 802A1998 2631D246 */  addiu      $s1, $s1, %lo(D_802AD246)
/* 46924C 802A199C 3C12802B */  lui        $s2, %hi(D_802AD2AB)
/* 469250 802A19A0 2652D2AB */  addiu      $s2, $s2, %lo(D_802AD2AB)
/* 469254 802A19A4 82220000 */  lb         $v0, 0x0($s1)
/* 469258 802A19A8 82430000 */  lb         $v1, 0x0($s2)
/* 46925C 802A19AC 00431021 */  addu       $v0, $v0, $v1
/* 469260 802A19B0 00021080 */  sll        $v0, $v0, 2
/* 469264 802A19B4 3C01802B */  lui        $at, %hi(D_802AD310)
/* 469268 802A19B8 00220821 */  addu       $at, $at, $v0
/* 46926C 802A19BC 8C22D310 */  lw         $v0, %lo(D_802AD310)($at)
/* 469270 802A19C0 14450005 */  bne        $v0, $a1, .LPAL_802A19D8
/* 469274 802A19C4 00000000 */   nop
/* 469278 802A19C8 0C052219 */  jal        func_PAL_80148864
/* 46927C 802A19CC 240400C9 */   addiu     $a0, $zero, 0xC9
/* 469280 802A19D0 080A86F0 */  j          .LPAL_802A1BC0
/* 469284 802A19D4 2402FFFF */   addiu     $v0, $zero, -0x1
.LPAL_802A19D8:
/* 469288 802A19D8 0C052219 */  jal        func_PAL_80148864
/* 46928C 802A19DC 2404021D */   addiu     $a0, $zero, 0x21D
/* 469290 802A19E0 82220000 */  lb         $v0, 0x0($s1)
/* 469294 802A19E4 82430000 */  lb         $v1, 0x0($s2)
/* 469298 802A19E8 00431021 */  addu       $v0, $v0, $v1
/* 46929C 802A19EC 00021080 */  sll        $v0, $v0, 2
/* 4692A0 802A19F0 3C03802B */  lui        $v1, %hi(D_802AD32B)
/* 4692A4 802A19F4 00621821 */  addu       $v1, $v1, $v0
/* 4692A8 802A19F8 9063D32B */  lbu        $v1, %lo(D_802AD32B)($v1)
/* 4692AC 802A19FC 24020064 */  addiu      $v0, $zero, 0x64
/* 4692B0 802A1A00 A2020000 */  sb         $v0, 0x0($s0)
/* 4692B4 802A1A04 3C01802B */  lui        $at, %hi(D_802AD2A8)
/* 4692B8 802A1A08 A023D2A8 */  sb         $v1, %lo(D_802AD2A8)($at)
/* 4692BC 802A1A0C 080A86F2 */  j          .LPAL_802A1BC8
/* 4692C0 802A1A10 0000102D */   daddu     $v0, $zero, $zero
.LPAL_802A1A14:
/* 4692C4 802A1A14 3C05802B */  lui        $a1, %hi(D_802AD246)
/* 4692C8 802A1A18 24A5D246 */  addiu      $a1, $a1, %lo(D_802AD246)
/* 4692CC 802A1A1C 90A40000 */  lbu        $a0, 0x0($a1)
/* 4692D0 802A1A20 3C02802B */  lui        $v0, %hi(D_802AD248)
/* 4692D4 802A1A24 8042D248 */  lb         $v0, %lo(D_802AD248)($v0)
/* 4692D8 802A1A28 3C01802B */  lui        $at, %hi(D_802AD247)
/* 4692DC 802A1A2C A024D247 */  sb         $a0, %lo(D_802AD247)($at)
/* 4692E0 802A1A30 1440001B */  bnez       $v0, .LPAL_802A1AA0
/* 4692E4 802A1A34 3C030005 */   lui       $v1, (0x50000 >> 16)
/* 4692E8 802A1A38 8CC20218 */  lw         $v0, 0x218($a2)
/* 4692EC 802A1A3C 00431024 */  and        $v0, $v0, $v1
/* 4692F0 802A1A40 10400008 */  beqz       $v0, .LPAL_802A1A64
/* 4692F4 802A1A44 00041600 */   sll       $v0, $a0, 24
/* 4692F8 802A1A48 3C03802B */  lui        $v1, %hi(D_802AD2A9)
/* 4692FC 802A1A4C 8063D2A9 */  lb         $v1, %lo(D_802AD2A9)($v1)
/* 469300 802A1A50 00021603 */  sra        $v0, $v0, 24
/* 469304 802A1A54 0062182A */  slt        $v1, $v1, $v0
/* 469308 802A1A58 10600002 */  beqz       $v1, .LPAL_802A1A64
/* 46930C 802A1A5C 2482FFFF */   addiu     $v0, $a0, -0x1
/* 469310 802A1A60 A0A20000 */  sb         $v0, 0x0($a1)
.LPAL_802A1A64:
/* 469314 802A1A64 8CC20218 */  lw         $v0, 0x218($a2)
/* 469318 802A1A68 3C03000A */  lui        $v1, (0xA0000 >> 16)
/* 46931C 802A1A6C 00431024 */  and        $v0, $v0, $v1
/* 469320 802A1A70 1040000B */  beqz       $v0, .LPAL_802A1AA0
/* 469324 802A1A74 00000000 */   nop
/* 469328 802A1A78 3C04802B */  lui        $a0, %hi(D_802AD246)
/* 46932C 802A1A7C 2484D246 */  addiu      $a0, $a0, %lo(D_802AD246)
/* 469330 802A1A80 80820000 */  lb         $v0, 0x0($a0)
/* 469334 802A1A84 3C03802B */  lui        $v1, %hi(D_802AD2AA)
/* 469338 802A1A88 8063D2AA */  lb         $v1, %lo(D_802AD2AA)($v1)
/* 46933C 802A1A8C 0043102A */  slt        $v0, $v0, $v1
/* 469340 802A1A90 90830000 */  lbu        $v1, 0x0($a0)
/* 469344 802A1A94 10400002 */  beqz       $v0, .LPAL_802A1AA0
/* 469348 802A1A98 24620001 */   addiu     $v0, $v1, 0x1
/* 46934C 802A1A9C A0820000 */  sb         $v0, 0x0($a0)
.LPAL_802A1AA0:
/* 469350 802A1AA0 3C03802B */  lui        $v1, %hi(D_802AD247)
/* 469354 802A1AA4 8063D247 */  lb         $v1, %lo(D_802AD247)($v1)
/* 469358 802A1AA8 3C02802B */  lui        $v0, %hi(D_802AD246)
/* 46935C 802A1AAC 8042D246 */  lb         $v0, %lo(D_802AD246)($v0)
/* 469360 802A1AB0 10620044 */  beq        $v1, $v0, .LPAL_802A1BC4
/* 469364 802A1AB4 24020001 */   addiu     $v0, $zero, 0x1
/* 469368 802A1AB8 3C01802B */  lui        $at, %hi(D_802AD248)
/* 46936C 802A1ABC A022D248 */  sb         $v0, %lo(D_802AD248)($at)
/* 469370 802A1AC0 0C052219 */  jal        func_PAL_80148864
/* 469374 802A1AC4 240400C8 */   addiu     $a0, $zero, 0xC8
/* 469378 802A1AC8 080A86F2 */  j          .LPAL_802A1BC8
/* 46937C 802A1ACC 0000102D */   daddu     $v0, $zero, $zero
.LPAL_802A1AD0:
/* 469380 802A1AD0 3C02802B */  lui        $v0, %hi(D_802AD246)
/* 469384 802A1AD4 8042D246 */  lb         $v0, %lo(D_802AD246)($v0)
/* 469388 802A1AD8 3C04802B */  lui        $a0, %hi(D_802AD2AB)
/* 46938C 802A1ADC 8084D2AB */  lb         $a0, %lo(D_802AD2AB)($a0)
/* 469390 802A1AE0 3C01802B */  lui        $at, %hi(D_802AD24C)
/* 469394 802A1AE4 A423D24C */  sh         $v1, %lo(D_802AD24C)($at)
/* 469398 802A1AE8 080A86D9 */  j          .LPAL_802A1B64
/* 46939C 802A1AEC 00441021 */   addu      $v0, $v0, $a0
.LPAL_802A1AF0:
/* 4693A0 802A1AF0 3C02802B */  lui        $v0, %hi(D_802AD246)
/* 4693A4 802A1AF4 8042D246 */  lb         $v0, %lo(D_802AD246)($v0)
/* 4693A8 802A1AF8 3C04802B */  lui        $a0, %hi(D_802AD2AB)
/* 4693AC 802A1AFC 8084D2AB */  lb         $a0, %lo(D_802AD2AB)($a0)
/* 4693B0 802A1B00 3C01802B */  lui        $at, %hi(D_802AD245)
/* 4693B4 802A1B04 A020D245 */  sb         $zero, %lo(D_802AD245)($at)
/* 4693B8 802A1B08 3C01802B */  lui        $at, %hi(D_802AD24A)
/* 4693BC 802A1B0C A420D24A */  sh         $zero, %lo(D_802AD24A)($at)
/* 4693C0 802A1B10 080A86D7 */  j          .LPAL_802A1B5C
/* 4693C4 802A1B14 2403000B */   addiu     $v1, $zero, 0xB
.LPAL_802A1B18:
/* 4693C8 802A1B18 3C02802B */  lui        $v0, %hi(D_802AD246)
/* 4693CC 802A1B1C 8042D246 */  lb         $v0, %lo(D_802AD246)($v0)
/* 4693D0 802A1B20 3C03802B */  lui        $v1, %hi(D_802AD2AB)
/* 4693D4 802A1B24 8063D2AB */  lb         $v1, %lo(D_802AD2AB)($v1)
/* 4693D8 802A1B28 00431021 */  addu       $v0, $v0, $v1
/* 4693DC 802A1B2C 080A86F2 */  j          .LPAL_802A1BC8
/* 4693E0 802A1B30 24420001 */   addiu     $v0, $v0, 0x1
.LPAL_802A1B34:
/* 4693E4 802A1B34 3C01802B */  lui        $at, %hi(D_802AD245)
/* 4693E8 802A1B38 A022D245 */  sb         $v0, %lo(D_802AD245)($at)
/* 4693EC 802A1B3C 240200FF */  addiu      $v0, $zero, 0xFF
/* 4693F0 802A1B40 3C01802B */  lui        $at, %hi(D_802AD24A)
/* 4693F4 802A1B44 A422D24A */  sh         $v0, %lo(D_802AD24A)($at)
/* 4693F8 802A1B48 3C02802B */  lui        $v0, %hi(D_802AD246)
/* 4693FC 802A1B4C 8042D246 */  lb         $v0, %lo(D_802AD246)($v0)
/* 469400 802A1B50 3C04802B */  lui        $a0, %hi(D_802AD2AB)
/* 469404 802A1B54 8084D2AB */  lb         $a0, %lo(D_802AD2AB)($a0)
/* 469408 802A1B58 24030002 */  addiu      $v1, $zero, 0x2
.LPAL_802A1B5C:
/* 46940C 802A1B5C A2030000 */  sb         $v1, 0x0($s0)
/* 469410 802A1B60 00441021 */  addu       $v0, $v0, $a0
.LPAL_802A1B64:
/* 469414 802A1B64 080A86F2 */  j          .LPAL_802A1BC8
/* 469418 802A1B68 24420001 */   addiu     $v0, $v0, 0x1
.LPAL_802A1B6C:
/* 46941C 802A1B6C 3C01802B */  lui        $at, %hi(D_802AD245)
/* 469420 802A1B70 A022D245 */  sb         $v0, %lo(D_802AD245)($at)
/* 469424 802A1B74 240200FF */  addiu      $v0, $zero, 0xFF
/* 469428 802A1B78 3C01802B */  lui        $at, %hi(D_802AD24A)
/* 46942C 802A1B7C A422D24A */  sh         $v0, %lo(D_802AD24A)($at)
/* 469430 802A1B80 080A86F0 */  j          .LPAL_802A1BC0
/* 469434 802A1B84 2402FFFF */   addiu     $v0, $zero, -0x1
.LPAL_802A1B88:
/* 469438 802A1B88 3C04802B */  lui        $a0, %hi(D_802AD2A8)
/* 46943C 802A1B8C 8084D2A8 */  lb         $a0, %lo(D_802AD2A8)($a0)
/* 469440 802A1B90 0C093E40 */  jal        func_PAL_8024F900
/* 469444 802A1B94 2405005A */   addiu     $a1, $zero, 0x5A
/* 469448 802A1B98 080A86F0 */  j          .LPAL_802A1BC0
/* 46944C 802A1B9C 24020065 */   addiu     $v0, $zero, 0x65
.LPAL_802A1BA0:
/* 469450 802A1BA0 0C093E95 */  jal        func_PAL_8024FA54
/* 469454 802A1BA4 00000000 */   nop
/* 469458 802A1BA8 14400007 */  bnez       $v0, .LPAL_802A1BC8
/* 46945C 802A1BAC 0000102D */   daddu     $v0, $zero, $zero
/* 469460 802A1BB0 2402FFFF */  addiu      $v0, $zero, -0x1
/* 469464 802A1BB4 3C01802B */  lui        $at, %hi(D_802AD2A8)
/* 469468 802A1BB8 A022D2A8 */  sb         $v0, %lo(D_802AD2A8)($at)
/* 46946C 802A1BBC 24020002 */  addiu      $v0, $zero, 0x2
.LPAL_802A1BC0:
/* 469470 802A1BC0 A2020000 */  sb         $v0, 0x0($s0)
.LPAL_802A1BC4:
/* 469474 802A1BC4 0000102D */  daddu      $v0, $zero, $zero
.LPAL_802A1BC8:
/* 469478 802A1BC8 8FBF0030 */  lw         $ra, 0x30($sp)
/* 46947C 802A1BCC 8FB5002C */  lw         $s5, 0x2C($sp)
/* 469480 802A1BD0 8FB40028 */  lw         $s4, 0x28($sp)
/* 469484 802A1BD4 8FB30024 */  lw         $s3, 0x24($sp)
/* 469488 802A1BD8 8FB20020 */  lw         $s2, 0x20($sp)
/* 46948C 802A1BDC 8FB1001C */  lw         $s1, 0x1C($sp)
/* 469490 802A1BE0 8FB00018 */  lw         $s0, 0x18($sp)
/* 469494 802A1BE4 D7B60040 */  ldc1       $f22, 0x40($sp)
/* 469498 802A1BE8 D7B40038 */  ldc1       $f20, 0x38($sp)
/* 46949C 802A1BEC 03E00008 */  jr         $ra
/* 4694A0 802A1BF0 27BD0048 */   addiu     $sp, $sp, 0x48
