.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
glabel jtbl_PAL_802ABAF0
/* 4733A0 802ABAF0 802A3D00 */ .word .LPAL_802A3D00
/* 4733A4 802ABAF4 802A443C */ .word .LPAL_802A443C
/* 4733A8 802ABAF8 802A3D00 */ .word .LPAL_802A3D00
/* 4733AC 802ABAFC 802A443C */ .word .LPAL_802A443C
/* 4733B0 802ABB00 802A443C */ .word .LPAL_802A443C
/* 4733B4 802ABB04 802A443C */ .word .LPAL_802A443C
/* 4733B8 802ABB08 802A443C */ .word .LPAL_802A443C
/* 4733BC 802ABB0C 802A443C */ .word .LPAL_802A443C
/* 4733C0 802ABB10 802A443C */ .word .LPAL_802A443C
/* 4733C4 802ABB14 802A443C */ .word .LPAL_802A443C
/* 4733C8 802ABB18 802A443C */ .word .LPAL_802A443C
/* 4733CC 802ABB1C 802A3D00 */ .word .LPAL_802A3D00
/* 4733D0 802ABB20 802A443C */ .word .LPAL_802A443C
/* 4733D4 802ABB24 802A443C */ .word .LPAL_802A443C
/* 4733D8 802ABB28 802A443C */ .word .LPAL_802A443C
/* 4733DC 802ABB2C 802A443C */ .word .LPAL_802A443C
/* 4733E0 802ABB30 802A443C */ .word .LPAL_802A443C
/* 4733E4 802ABB34 802A443C */ .word .LPAL_802A443C
/* 4733E8 802ABB38 802A443C */ .word .LPAL_802A443C
/* 4733EC 802ABB3C 802A443C */ .word .LPAL_802A443C
/* 4733F0 802ABB40 802A443C */ .word .LPAL_802A443C
/* 4733F4 802ABB44 802A3D00 */ .word .LPAL_802A3D00
/* 4733F8 802ABB48 802A443C */ .word .LPAL_802A443C
/* 4733FC 802ABB4C 802A443C */ .word .LPAL_802A443C
/* 473400 802ABB50 802A443C */ .word .LPAL_802A443C
/* 473404 802ABB54 802A443C */ .word .LPAL_802A443C
/* 473408 802ABB58 802A443C */ .word .LPAL_802A443C
/* 47340C 802ABB5C 802A443C */ .word .LPAL_802A443C
/* 473410 802ABB60 802A443C */ .word .LPAL_802A443C
/* 473414 802ABB64 802A443C */ .word .LPAL_802A443C
/* 473418 802ABB68 802A443C */ .word .LPAL_802A443C
/* 47341C 802ABB6C 802A3D00 */ .word .LPAL_802A3D00
/* 473420 802ABB70 802A443C */ .word .LPAL_802A443C
/* 473424 802ABB74 802A443C */ .word .LPAL_802A443C
/* 473428 802ABB78 802A443C */ .word .LPAL_802A443C
/* 47342C 802ABB7C 802A443C */ .word .LPAL_802A443C
/* 473430 802ABB80 802A443C */ .word .LPAL_802A443C
/* 473434 802ABB84 802A443C */ .word .LPAL_802A443C
/* 473438 802ABB88 802A443C */ .word .LPAL_802A443C
/* 47343C 802ABB8C 802A443C */ .word .LPAL_802A443C
/* 473440 802ABB90 802A443C */ .word .LPAL_802A443C
/* 473444 802ABB94 802A3D00 */ .word .LPAL_802A3D00
/* 473448 802ABB98 802A3D00 */ .word .LPAL_802A3D00
/* 47344C 802ABB9C 00000000 */ .word 0x00000000


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel func_802A3C98
/* 46B548 802A3C98 3C02802B */  lui        $v0, %hi(D_802AD348)
/* 46B54C 802A3C9C 9042D348 */  lbu        $v0, %lo(D_802AD348)($v0)
/* 46B550 802A3CA0 27BDFFB8 */  addiu      $sp, $sp, -0x48
/* 46B554 802A3CA4 AFBF0044 */  sw         $ra, 0x44($sp)
/* 46B558 802A3CA8 AFBE0040 */  sw         $fp, 0x40($sp)
/* 46B55C 802A3CAC AFB7003C */  sw         $s7, 0x3C($sp)
/* 46B560 802A3CB0 AFB60038 */  sw         $s6, 0x38($sp)
/* 46B564 802A3CB4 AFB50034 */  sw         $s5, 0x34($sp)
/* 46B568 802A3CB8 AFB40030 */  sw         $s4, 0x30($sp)
/* 46B56C 802A3CBC AFB3002C */  sw         $s3, 0x2C($sp)
/* 46B570 802A3CC0 AFB20028 */  sw         $s2, 0x28($sp)
/* 46B574 802A3CC4 AFB10024 */  sw         $s1, 0x24($sp)
/* 46B578 802A3CC8 AFB00020 */  sw         $s0, 0x20($sp)
/* 46B57C 802A3CCC AFA5004C */  sw         $a1, 0x4C($sp)
/* 46B580 802A3CD0 24420001 */  addiu      $v0, $v0, 0x1
/* 46B584 802A3CD4 00021600 */  sll        $v0, $v0, 24
/* 46B588 802A3CD8 00021E03 */  sra        $v1, $v0, 24
/* 46B58C 802A3CDC 2C62002B */  sltiu      $v0, $v1, 0x2B
/* 46B590 802A3CE0 104001D6 */  beqz       $v0, .LPAL_802A443C
/* 46B594 802A3CE4 AFA60050 */   sw        $a2, 0x50($sp)
/* 46B598 802A3CE8 00031080 */  sll        $v0, $v1, 2
/* 46B59C 802A3CEC 3C01802B */  lui        $at, %hi(jtbl_PAL_802ABAF0)
/* 46B5A0 802A3CF0 00220821 */  addu       $at, $at, $v0
/* 46B5A4 802A3CF4 8C22BAF0 */  lw         $v0, %lo(jtbl_PAL_802ABAF0)($at)
/* 46B5A8 802A3CF8 00400008 */  jr         $v0
/* 46B5AC 802A3CFC 00000000 */   nop
.LPAL_802A3D00:
/* 46B5B0 802A3D00 3C03802B */  lui        $v1, %hi(D_802AD34C)
/* 46B5B4 802A3D04 8063D34C */  lb         $v1, %lo(D_802AD34C)($v1)
/* 46B5B8 802A3D08 3C08802B */  lui        $t0, %hi(D_802AD350)
/* 46B5BC 802A3D0C 8508D350 */  lh         $t0, %lo(D_802AD350)($t0)
/* 46B5C0 802A3D10 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
/* 46B5C4 802A3D14 44811800 */  mtc1       $at, $f3
/* 46B5C8 802A3D18 44801000 */  mtc1       $zero, $f2
/* 46B5CC 802A3D1C 00031823 */  negu       $v1, $v1
/* 46B5D0 802A3D20 00031040 */  sll        $v0, $v1, 1
/* 46B5D4 802A3D24 00431021 */  addu       $v0, $v0, $v1
/* 46B5D8 802A3D28 00021080 */  sll        $v0, $v0, 2
/* 46B5DC 802A3D2C 00438821 */  addu       $s1, $v0, $v1
/* 46B5E0 802A3D30 02281023 */  subu       $v0, $s1, $t0
/* 46B5E4 802A3D34 44820000 */  mtc1       $v0, $f0
/* 46B5E8 802A3D38 00000000 */  nop
/* 46B5EC 802A3D3C 46800021 */  cvt.d.w    $f0, $f0
/* 46B5F0 802A3D40 46220002 */  mul.d      $f0, $f0, $f2
/* 46B5F4 802A3D44 00000000 */  nop
/* 46B5F8 802A3D48 4620018D */  trunc.w.d  $f6, $f0
/* 46B5FC 802A3D4C 44023000 */  mfc1       $v0, $f6
/* 46B600 802A3D50 00000000 */  nop
/* 46B604 802A3D54 14400002 */  bnez       $v0, .LPAL_802A3D60
/* 46B608 802A3D58 01024021 */   addu      $t0, $t0, $v0
/* 46B60C 802A3D5C 0220402D */  daddu      $t0, $s1, $zero
.LPAL_802A3D60:
/* 46B610 802A3D60 0000982D */  daddu      $s3, $zero, $zero
/* 46B614 802A3D64 3C068009 */  lui        $a2, %hi(D_80096A44)
/* 46B618 802A3D68 24C66A44 */  addiu      $a2, $a2, %lo(D_80096A44)
/* 46B61C 802A3D6C 3C05802B */  lui        $a1, %hi(D_802AD350)
/* 46B620 802A3D70 24A5D350 */  addiu      $a1, $a1, %lo(D_802AD350)
/* 46B624 802A3D74 8FA9004C */  lw         $t1, 0x4C($sp)
/* 46B628 802A3D78 8CC40000 */  lw         $a0, 0x0($a2)
/* 46B62C 802A3D7C 3C03802B */  lui        $v1, %hi(D_802AD34E)
/* 46B630 802A3D80 8063D34E */  lb         $v1, %lo(D_802AD34E)($v1)
/* 46B634 802A3D84 3C014080 */  lui        $at, (0x40800000 >> 16)
/* 46B638 802A3D88 44812000 */  mtc1       $at, $f4
/* 46B63C 802A3D8C 25350002 */  addiu      $s5, $t1, 0x2
/* 46B640 802A3D90 44951000 */  mtc1       $s5, $f2
/* 46B644 802A3D94 00000000 */  nop
/* 46B648 802A3D98 468010A0 */  cvt.s.w    $f2, $f2
/* 46B64C 802A3D9C 00031040 */  sll        $v0, $v1, 1
/* 46B650 802A3DA0 00431021 */  addu       $v0, $v0, $v1
/* 46B654 802A3DA4 00021080 */  sll        $v0, $v0, 2
/* 46B658 802A3DA8 00431021 */  addu       $v0, $v0, $v1
/* 46B65C 802A3DAC 24420001 */  addiu      $v0, $v0, 0x1
/* 46B660 802A3DB0 0080382D */  daddu      $a3, $a0, $zero
/* 46B664 802A3DB4 8FA90050 */  lw         $t1, 0x50($sp)
/* 46B668 802A3DB8 46041082 */  mul.s      $f2, $f2, $f4
/* 46B66C 802A3DBC 00000000 */  nop
/* 46B670 802A3DC0 25310012 */  addiu      $s1, $t1, 0x12
/* 46B674 802A3DC4 8FA9004C */  lw         $t1, 0x4C($sp)
/* 46B678 802A3DC8 24840008 */  addiu      $a0, $a0, 0x8
/* 46B67C 802A3DCC A4A80000 */  sh         $t0, 0x0($a1)
/* 46B680 802A3DD0 02224021 */  addu       $t0, $s1, $v0
/* 46B684 802A3DD4 44910000 */  mtc1       $s1, $f0
/* 46B688 802A3DD8 00000000 */  nop
/* 46B68C 802A3DDC 46800020 */  cvt.s.w    $f0, $f0
/* 46B690 802A3DE0 46040002 */  mul.s      $f0, $f0, $f4
/* 46B694 802A3DE4 00000000 */  nop
/* 46B698 802A3DE8 84A20000 */  lh         $v0, 0x0($a1)
/* 46B69C 802A3DEC 2535001F */  addiu      $s5, $t1, 0x1F
/* 46B6A0 802A3DF0 8FA90050 */  lw         $t1, 0x50($sp)
/* 46B6A4 802A3DF4 24420013 */  addiu      $v0, $v0, 0x13
/* 46B6A8 802A3DF8 ACC40000 */  sw         $a0, 0x0($a2)
/* 46B6AC 802A3DFC 01228821 */  addu       $s1, $t1, $v0
/* 46B6B0 802A3E00 4600118D */  trunc.w.s  $f6, $f2
/* 46B6B4 802A3E04 44033000 */  mfc1       $v1, $f6
/* 46B6B8 802A3E08 00000000 */  nop
/* 46B6BC 802A3E0C 30630FFF */  andi       $v1, $v1, 0xFFF
/* 46B6C0 802A3E10 00031B00 */  sll        $v1, $v1, 12
/* 46B6C4 802A3E14 4600018D */  trunc.w.s  $f6, $f0
/* 46B6C8 802A3E18 44043000 */  mfc1       $a0, $f6
/* 46B6CC 802A3E1C 00000000 */  nop
/* 46B6D0 802A3E20 30840FFF */  andi       $a0, $a0, 0xFFF
/* 46B6D4 802A3E24 8FA9004C */  lw         $t1, 0x4C($sp)
/* 46B6D8 802A3E28 44880000 */  mtc1       $t0, $f0
/* 46B6DC 802A3E2C 00000000 */  nop
/* 46B6E0 802A3E30 46800020 */  cvt.s.w    $f0, $f0
/* 46B6E4 802A3E34 252200A9 */  addiu      $v0, $t1, 0xA9
/* 46B6E8 802A3E38 44821000 */  mtc1       $v0, $f2
/* 46B6EC 802A3E3C 00000000 */  nop
/* 46B6F0 802A3E40 468010A0 */  cvt.s.w    $f2, $f2
/* 46B6F4 802A3E44 46041082 */  mul.s      $f2, $f2, $f4
/* 46B6F8 802A3E48 00000000 */  nop
/* 46B6FC 802A3E4C 3C02ED00 */  lui        $v0, (0xED000000 >> 16)
/* 46B700 802A3E50 00822025 */  or         $a0, $a0, $v0
/* 46B704 802A3E54 00641825 */  or         $v1, $v1, $a0
/* 46B708 802A3E58 3C04802B */  lui        $a0, %hi(D_802AD6E4)
/* 46B70C 802A3E5C 8C84D6E4 */  lw         $a0, %lo(D_802AD6E4)($a0)
/* 46B710 802A3E60 46040002 */  mul.s      $f0, $f0, $f4
/* 46B714 802A3E64 00000000 */  nop
/* 46B718 802A3E68 ACE30000 */  sw         $v1, 0x0($a3)
/* 46B71C 802A3E6C 4600118D */  trunc.w.s  $f6, $f2
/* 46B720 802A3E70 44023000 */  mfc1       $v0, $f6
/* 46B724 802A3E74 00000000 */  nop
/* 46B728 802A3E78 30420FFF */  andi       $v0, $v0, 0xFFF
/* 46B72C 802A3E7C 00021300 */  sll        $v0, $v0, 12
/* 46B730 802A3E80 4600018D */  trunc.w.s  $f6, $f0
/* 46B734 802A3E84 44033000 */  mfc1       $v1, $f6
/* 46B738 802A3E88 00000000 */  nop
/* 46B73C 802A3E8C 30630FFF */  andi       $v1, $v1, 0xFFF
/* 46B740 802A3E90 00431025 */  or         $v0, $v0, $v1
/* 46B744 802A3E94 188000E0 */  blez       $a0, .LPAL_802A4218
/* 46B748 802A3E98 ACE20004 */   sw        $v0, 0x4($a3)
/* 46B74C 802A3E9C 3C16802B */  lui        $s6, %hi(D_802AD750)
/* 46B750 802A3EA0 26D6D750 */  addiu      $s6, $s6, %lo(D_802AD750)
/* 46B754 802A3EA4 3C178015 */  lui        $s7, %hi(gCurrentLanguage)
/* 46B758 802A3EA8 26F7AE4C */  addiu      $s7, $s7, %lo(gCurrentLanguage)
/* 46B75C 802A3EAC 3C14802B */  lui        $s4, %hi(D_802AD438)
/* 46B760 802A3EB0 2694D438 */  addiu      $s4, $s4, %lo(D_802AD438)
/* 46B764 802A3EB4 0260F02D */  daddu      $fp, $s3, $zero
.LPAL_802A3EB8:
/* 46B768 802A3EB8 3C03802B */  lui        $v1, %hi(D_802AD34C)
/* 46B76C 802A3EBC 8063D34C */  lb         $v1, %lo(D_802AD34C)($v1)
/* 46B770 802A3EC0 2462FFFF */  addiu      $v0, $v1, -0x1
/* 46B774 802A3EC4 0262102A */  slt        $v0, $s3, $v0
/* 46B778 802A3EC8 544000CB */  bnel       $v0, $zero, .LPAL_802A41F8
/* 46B77C 802A3ECC 2631000D */   addiu     $s1, $s1, 0xD
/* 46B780 802A3ED0 3C02802B */  lui        $v0, %hi(D_802AD34E)
/* 46B784 802A3ED4 8042D34E */  lb         $v0, %lo(D_802AD34E)($v0)
/* 46B788 802A3ED8 00621021 */  addu       $v0, $v1, $v0
/* 46B78C 802A3EDC 0053102A */  slt        $v0, $v0, $s3
/* 46B790 802A3EE0 544000C5 */  bnel       $v0, $zero, .LPAL_802A41F8
/* 46B794 802A3EE4 2631000D */   addiu     $s1, $s1, 0xD
/* 46B798 802A3EE8 8E820000 */  lw         $v0, 0x0($s4)
/* 46B79C 802A3EEC 00022080 */  sll        $a0, $v0, 2
/* 46B7A0 802A3EF0 00961021 */  addu       $v0, $a0, $s6
/* 46B7A4 802A3EF4 8C420000 */  lw         $v0, 0x0($v0)
/* 46B7A8 802A3EF8 3C08802B */  lui        $t0, %hi(D_802AD354)
/* 46B7AC 802A3EFC 8508D354 */  lh         $t0, %lo(D_802AD354)($t0)
/* 46B7B0 802A3F00 58400001 */  blezl      $v0, .LPAL_802A3F08
/* 46B7B4 802A3F04 2408000B */   addiu     $t0, $zero, 0xB
.LPAL_802A3F08:
/* 46B7B8 802A3F08 3C02802B */  lui        $v0, %hi(D_802AD500)
/* 46B7BC 802A3F0C 2442D500 */  addiu      $v0, $v0, %lo(D_802AD500)
/* 46B7C0 802A3F10 00822021 */  addu       $a0, $a0, $v0
/* 46B7C4 802A3F14 8C820000 */  lw         $v0, 0x0($a0)
/* 46B7C8 802A3F18 04400009 */  bltz       $v0, .LPAL_802A3F40
/* 46B7CC 802A3F1C 02A0282D */   daddu     $a1, $s5, $zero
/* 46B7D0 802A3F20 3C07802B */  lui        $a3, %hi(D_802AD356)
/* 46B7D4 802A3F24 84E7D356 */  lh         $a3, %lo(D_802AD356)($a3)
/* 46B7D8 802A3F28 24020001 */  addiu      $v0, $zero, 0x1
/* 46B7DC 802A3F2C AFA80010 */  sw         $t0, 0x10($sp)
/* 46B7E0 802A3F30 AFA20014 */  sw         $v0, 0x14($sp)
/* 46B7E4 802A3F34 8C840000 */  lw         $a0, 0x0($a0)
/* 46B7E8 802A3F38 0C049403 */  jal        func_PAL_8012500C
/* 46B7EC 802A3F3C 0220302D */   daddu     $a2, $s1, $zero
.LPAL_802A3F40:
/* 46B7F0 802A3F40 8E820000 */  lw         $v0, 0x0($s4)
/* 46B7F4 802A3F44 00021880 */  sll        $v1, $v0, 2
/* 46B7F8 802A3F48 3C04802B */  lui        $a0, %hi(D_802AD5C0)
/* 46B7FC 802A3F4C 00832021 */  addu       $a0, $a0, $v1
/* 46B800 802A3F50 8C84D5C0 */  lw         $a0, %lo(D_802AD5C0)($a0)
/* 46B804 802A3F54 3C09802B */  lui        $t1, %hi(D_802AD560)
/* 46B808 802A3F58 2529D560 */  addiu      $t1, $t1, %lo(D_802AD560)
/* 46B80C 802A3F5C 00691021 */  addu       $v0, $v1, $t1
/* 46B810 802A3F60 8C420000 */  lw         $v0, 0x0($v0)
/* 46B814 802A3F64 10400003 */  beqz       $v0, .LPAL_802A3F74
/* 46B818 802A3F68 00449023 */   subu      $s2, $v0, $a0
/* 46B81C 802A3F6C 5A400001 */  blezl      $s2, .LPAL_802A3F74
/* 46B820 802A3F70 24120001 */   addiu     $s2, $zero, 0x1
.LPAL_802A3F74:
/* 46B824 802A3F74 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B828 802A3F78 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B82C 802A3F7C 14400015 */  bnez       $v0, .LPAL_802A3FD4
/* 46B830 802A3F80 00000000 */   nop
/* 46B834 802A3F84 3C02802B */  lui        $v0, %hi(D_802AD349)
/* 46B838 802A3F88 8042D349 */  lb         $v0, %lo(D_802AD349)($v0)
/* 46B83C 802A3F8C 16620027 */  bne        $s3, $v0, .LPAL_802A402C
/* 46B840 802A3F90 00131080 */   sll       $v0, $s3, 2
/* 46B844 802A3F94 12400007 */  beqz       $s2, .LPAL_802A3FB4
/* 46B848 802A3F98 00000000 */   nop
/* 46B84C 802A3F9C 8E820000 */  lw         $v0, 0x0($s4)
/* 46B850 802A3FA0 00021080 */  sll        $v0, $v0, 2
/* 46B854 802A3FA4 00561021 */  addu       $v0, $v0, $s6
/* 46B858 802A3FA8 8C420000 */  lw         $v0, 0x0($v0)
/* 46B85C 802A3FAC 1C400005 */  bgtz       $v0, .LPAL_802A3FC4
/* 46B860 802A3FB0 00000000 */   nop
.LPAL_802A3FB4:
/* 46B864 802A3FB4 0C03988A */  jal        func_PAL_800E6228
/* 46B868 802A3FB8 00000000 */   nop
/* 46B86C 802A3FBC 080A900B */  j          .LPAL_802A402C
/* 46B870 802A3FC0 00131080 */   sll       $v0, $s3, 2
.LPAL_802A3FC4:
/* 46B874 802A3FC4 0C039879 */  jal        func_PAL_800E61E4
/* 46B878 802A3FC8 00000000 */   nop
/* 46B87C 802A3FCC 080A900B */  j          .LPAL_802A402C
/* 46B880 802A3FD0 00131080 */   sll       $v0, $s3, 2
.LPAL_802A3FD4:
/* 46B884 802A3FD4 3C02802B */  lui        $v0, %hi(D_802AD349)
/* 46B888 802A3FD8 8042D349 */  lb         $v0, %lo(D_802AD349)($v0)
/* 46B88C 802A3FDC 16620013 */  bne        $s3, $v0, .LPAL_802A402C
/* 46B890 802A3FE0 00131080 */   sll       $v0, $s3, 2
/* 46B894 802A3FE4 12400007 */  beqz       $s2, .LPAL_802A4004
/* 46B898 802A3FE8 00000000 */   nop
/* 46B89C 802A3FEC 8E820000 */  lw         $v0, 0x0($s4)
/* 46B8A0 802A3FF0 00021880 */  sll        $v1, $v0, 2
/* 46B8A4 802A3FF4 00761021 */  addu       $v0, $v1, $s6
/* 46B8A8 802A3FF8 8C420000 */  lw         $v0, 0x0($v0)
/* 46B8AC 802A3FFC 1C400005 */  bgtz       $v0, .LPAL_802A4014
/* 46B8B0 802A4000 00000000 */   nop
.LPAL_802A4004:
/* 46B8B4 802A4004 0C0398BB */  jal        func_PAL_800E62EC
/* 46B8B8 802A4008 00000000 */   nop
/* 46B8BC 802A400C 080A900B */  j          .LPAL_802A402C
/* 46B8C0 802A4010 00131080 */   sll       $v0, $s3, 2
.LPAL_802A4014:
/* 46B8C4 802A4014 3C09802B */  lui        $t1, %hi(D_802AD560)
/* 46B8C8 802A4018 2529D560 */  addiu      $t1, $t1, %lo(D_802AD560)
/* 46B8CC 802A401C 00691021 */  addu       $v0, $v1, $t1
/* 46B8D0 802A4020 0C0398C4 */  jal        func_PAL_800E6310
/* 46B8D4 802A4024 8C440000 */   lw        $a0, 0x0($v0)
/* 46B8D8 802A4028 00131080 */  sll        $v0, $s3, 2
.LPAL_802A402C:
/* 46B8DC 802A402C 3C03802B */  lui        $v1, %hi(D_802AD620)
/* 46B8E0 802A4030 00621821 */  addu       $v1, $v1, $v0
/* 46B8E4 802A4034 8C63D620 */  lw         $v1, %lo(D_802AD620)($v1)
/* 46B8E8 802A4038 10600005 */  beqz       $v1, .LPAL_802A4050
/* 46B8EC 802A403C 24020001 */   addiu     $v0, $zero, 0x1
/* 46B8F0 802A4040 10620005 */  beq        $v1, $v0, .LPAL_802A4058
/* 46B8F4 802A4044 24080038 */   addiu     $t0, $zero, 0x38
/* 46B8F8 802A4048 080A9017 */  j          .LPAL_802A405C
/* 46B8FC 802A404C 00000000 */   nop
.LPAL_802A4050:
/* 46B900 802A4050 080A9017 */  j          .LPAL_802A405C
/* 46B904 802A4054 2408000A */   addiu     $t0, $zero, 0xA
.LPAL_802A4058:
/* 46B908 802A4058 24080037 */  addiu      $t0, $zero, 0x37
.LPAL_802A405C:
/* 46B90C 802A405C 8E820000 */  lw         $v0, 0x0($s4)
/* 46B910 802A4060 00021880 */  sll        $v1, $v0, 2
/* 46B914 802A4064 00761021 */  addu       $v0, $v1, $s6
/* 46B918 802A4068 8C420000 */  lw         $v0, 0x0($v0)
/* 46B91C 802A406C 58400001 */  blezl      $v0, .LPAL_802A4074
/* 46B920 802A4070 2408000B */   addiu     $t0, $zero, 0xB
.LPAL_802A4074:
/* 46B924 802A4074 3C09802B */  lui        $t1, %hi(D_802AD560)
/* 46B928 802A4078 2529D560 */  addiu      $t1, $t1, %lo(D_802AD560)
/* 46B92C 802A407C 00691021 */  addu       $v0, $v1, $t1
/* 46B930 802A4080 8C420000 */  lw         $v0, 0x0($v0)
/* 46B934 802A4084 5040005C */  beql       $v0, $zero, .LPAL_802A41F8
/* 46B938 802A4088 2631000D */   addiu     $s1, $s1, 0xD
/* 46B93C 802A408C 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46B940 802A4090 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46B944 802A4094 3C10802B */  lui        $s0, %hi(D_802AD3D0)
/* 46B948 802A4098 021E8021 */  addu       $s0, $s0, $fp
/* 46B94C 802A409C 8E10D3D0 */  lw         $s0, %lo(D_802AD3D0)($s0)
/* 46B950 802A40A0 14400027 */  bnez       $v0, .LPAL_802A4140
/* 46B954 802A40A4 0240202D */   daddu     $a0, $s2, $zero
/* 46B958 802A40A8 0220302D */  daddu      $a2, $s1, $zero
/* 46B95C 802A40AC 8EE20000 */  lw         $v0, 0x0($s7)
/* 46B960 802A40B0 3C09802B */  lui        $t1, %hi(D_PAL_802AB4E8)
/* 46B964 802A40B4 2529B4E8 */  addiu      $t1, $t1, %lo(D_PAL_802AB4E8)
/* 46B968 802A40B8 00491021 */  addu       $v0, $v0, $t1
/* 46B96C 802A40BC 90450000 */  lbu        $a1, 0x0($v0)
/* 46B970 802A40C0 3C02802B */  lui        $v0, %hi(D_802AD356)
/* 46B974 802A40C4 8442D356 */  lh         $v0, %lo(D_802AD356)($v0)
/* 46B978 802A40C8 24070001 */  addiu      $a3, $zero, 0x1
/* 46B97C 802A40CC AFA80010 */  sw         $t0, 0x10($sp)
/* 46B980 802A40D0 AFA20014 */  sw         $v0, 0x14($sp)
/* 46B984 802A40D4 24020003 */  addiu      $v0, $zero, 0x3
/* 46B988 802A40D8 24A5006C */  addiu      $a1, $a1, 0x6C
/* 46B98C 802A40DC 02A52821 */  addu       $a1, $s5, $a1
/* 46B990 802A40E0 0C04986F */  jal        func_PAL_801261BC
/* 46B994 802A40E4 AFA20018 */   sw        $v0, 0x18($sp)
/* 46B998 802A40E8 8E820000 */  lw         $v0, 0x0($s4)
/* 46B99C 802A40EC 00021080 */  sll        $v0, $v0, 2
/* 46B9A0 802A40F0 00561021 */  addu       $v0, $v0, $s6
/* 46B9A4 802A40F4 8C420000 */  lw         $v0, 0x0($v0)
/* 46B9A8 802A40F8 5C400009 */  bgtzl      $v0, .LPAL_802A4120
/* 46B9AC 802A40FC 0200202D */   daddu     $a0, $s0, $zero
/* 46B9B0 802A4100 8EE20000 */  lw         $v0, 0x0($s7)
/* 46B9B4 802A4104 00021080 */  sll        $v0, $v0, 2
/* 46B9B8 802A4108 3C05802B */  lui        $a1, %hi(D_PAL_802AB52C)
/* 46B9BC 802A410C 00A22821 */  addu       $a1, $a1, $v0
/* 46B9C0 802A4110 8CA5B52C */  lw         $a1, %lo(D_PAL_802AB52C)($a1)
/* 46B9C4 802A4114 0C050CEB */  jal        func_PAL_801433AC
/* 46B9C8 802A4118 0200202D */   daddu     $a0, $s0, $zero
/* 46B9CC 802A411C 0200202D */  daddu      $a0, $s0, $zero
.LPAL_802A4120:
/* 46B9D0 802A4120 8EE20000 */  lw         $v0, 0x0($s7)
/* 46B9D4 802A4124 3C09802B */  lui        $t1, %hi(D_PAL_802AB4E8)
/* 46B9D8 802A4128 2529B4E8 */  addiu      $t1, $t1, %lo(D_PAL_802AB4E8)
/* 46B9DC 802A412C 00491021 */  addu       $v0, $v0, $t1
/* 46B9E0 802A4130 90450000 */  lbu        $a1, 0x0($v0)
/* 46B9E4 802A4134 26260007 */  addiu      $a2, $s1, 0x7
/* 46B9E8 802A4138 080A9075 */  j          .LPAL_802A41D4
/* 46B9EC 802A413C 24A50074 */   addiu     $a1, $a1, 0x74
.LPAL_802A4140:
/* 46B9F0 802A4140 0220302D */  daddu      $a2, $s1, $zero
/* 46B9F4 802A4144 8EE20000 */  lw         $v0, 0x0($s7)
/* 46B9F8 802A4148 3C09802B */  lui        $t1, %hi(D_PAL_802AB4D0)
/* 46B9FC 802A414C 2529B4D0 */  addiu      $t1, $t1, %lo(D_PAL_802AB4D0)
/* 46BA00 802A4150 00491021 */  addu       $v0, $v0, $t1
/* 46BA04 802A4154 90450000 */  lbu        $a1, 0x0($v0)
/* 46BA08 802A4158 3C02802B */  lui        $v0, %hi(D_802AD356)
/* 46BA0C 802A415C 8442D356 */  lh         $v0, %lo(D_802AD356)($v0)
/* 46BA10 802A4160 24070001 */  addiu      $a3, $zero, 0x1
/* 46BA14 802A4164 AFA80010 */  sw         $t0, 0x10($sp)
/* 46BA18 802A4168 AFA20014 */  sw         $v0, 0x14($sp)
/* 46BA1C 802A416C 24020003 */  addiu      $v0, $zero, 0x3
/* 46BA20 802A4170 24A5005D */  addiu      $a1, $a1, 0x5D
/* 46BA24 802A4174 02A52821 */  addu       $a1, $s5, $a1
/* 46BA28 802A4178 0C04986F */  jal        func_PAL_801261BC
/* 46BA2C 802A417C AFA20018 */   sw        $v0, 0x18($sp)
/* 46BA30 802A4180 8E820000 */  lw         $v0, 0x0($s4)
/* 46BA34 802A4184 00021080 */  sll        $v0, $v0, 2
/* 46BA38 802A4188 00561021 */  addu       $v0, $v0, $s6
/* 46BA3C 802A418C 8C420000 */  lw         $v0, 0x0($v0)
/* 46BA40 802A4190 5C400009 */  bgtzl      $v0, .LPAL_802A41B8
/* 46BA44 802A4194 0200202D */   daddu     $a0, $s0, $zero
/* 46BA48 802A4198 8EE20000 */  lw         $v0, 0x0($s7)
/* 46BA4C 802A419C 00021080 */  sll        $v0, $v0, 2
/* 46BA50 802A41A0 3C05802B */  lui        $a1, %hi(D_PAL_802AB56C)
/* 46BA54 802A41A4 00A22821 */  addu       $a1, $a1, $v0
/* 46BA58 802A41A8 8CA5B56C */  lw         $a1, %lo(D_PAL_802AB56C)($a1)
/* 46BA5C 802A41AC 0C050CEB */  jal        func_PAL_801433AC
/* 46BA60 802A41B0 0200202D */   daddu     $a0, $s0, $zero
/* 46BA64 802A41B4 0200202D */  daddu      $a0, $s0, $zero
.LPAL_802A41B8:
/* 46BA68 802A41B8 8EE20000 */  lw         $v0, 0x0($s7)
/* 46BA6C 802A41BC 3C09802B */  lui        $t1, %hi(D_PAL_802AB4D0)
/* 46BA70 802A41C0 2529B4D0 */  addiu      $t1, $t1, %lo(D_PAL_802AB4D0)
/* 46BA74 802A41C4 00491021 */  addu       $v0, $v0, $t1
/* 46BA78 802A41C8 90450000 */  lbu        $a1, 0x0($v0)
/* 46BA7C 802A41CC 26260007 */  addiu      $a2, $s1, 0x7
/* 46BA80 802A41D0 24A50066 */  addiu      $a1, $a1, 0x66
.LPAL_802A41D4:
/* 46BA84 802A41D4 0C050D4D */  jal        func_PAL_80143534
/* 46BA88 802A41D8 02A52821 */   addu      $a1, $s5, $a1
/* 46BA8C 802A41DC 3C05802B */  lui        $a1, %hi(D_802AD356)
/* 46BA90 802A41E0 84A5D356 */  lh         $a1, %lo(D_802AD356)($a1)
/* 46BA94 802A41E4 0C050E98 */  jal        func_PAL_80143A60
/* 46BA98 802A41E8 0200202D */   daddu     $a0, $s0, $zero
/* 46BA9C 802A41EC 0C050CE4 */  jal        func_PAL_80143390
/* 46BAA0 802A41F0 0200202D */   daddu     $a0, $s0, $zero
/* 46BAA4 802A41F4 2631000D */  addiu      $s1, $s1, 0xD
.LPAL_802A41F8:
/* 46BAA8 802A41F8 26730001 */  addiu      $s3, $s3, 0x1
/* 46BAAC 802A41FC 26940004 */  addiu      $s4, $s4, 0x4
/* 46BAB0 802A4200 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46BAB4 802A4204 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46BAB8 802A4208 0262102A */  slt        $v0, $s3, $v0
/* 46BABC 802A420C 1440FF2A */  bnez       $v0, .LPAL_802A3EB8
/* 46BAC0 802A4210 27DE0004 */   addiu     $fp, $fp, 0x4
/* 46BAC4 802A4214 0000982D */  daddu      $s3, $zero, $zero
.LPAL_802A4218:
/* 46BAC8 802A4218 8FA9004C */  lw         $t1, 0x4C($sp)
/* 46BACC 802A421C 3C02802B */  lui        $v0, %hi(D_802AD350)
/* 46BAD0 802A4220 8442D350 */  lh         $v0, %lo(D_802AD350)($v0)
/* 46BAD4 802A4224 25350018 */  addiu      $s5, $t1, 0x18
/* 46BAD8 802A4228 8FA90050 */  lw         $t1, 0x50($sp)
/* 46BADC 802A422C 3C03802B */  lui        $v1, %hi(D_802AD6E4)
/* 46BAE0 802A4230 8C63D6E4 */  lw         $v1, %lo(D_802AD6E4)($v1)
/* 46BAE4 802A4234 00491021 */  addu       $v0, $v0, $t1
/* 46BAE8 802A4238 18600022 */  blez       $v1, .LPAL_802A42C4
/* 46BAEC 802A423C 24510018 */   addiu     $s1, $v0, 0x18
/* 46BAF0 802A4240 3C12802B */  lui        $s2, %hi(D_802AD368)
/* 46BAF4 802A4244 2652D368 */  addiu      $s2, $s2, %lo(D_802AD368)
.LPAL_802A4248:
/* 46BAF8 802A4248 3C03802B */  lui        $v1, %hi(D_802AD34C)
/* 46BAFC 802A424C 8063D34C */  lb         $v1, %lo(D_802AD34C)($v1)
/* 46BB00 802A4250 2462FFFF */  addiu      $v0, $v1, -0x1
/* 46BB04 802A4254 0262102A */  slt        $v0, $s3, $v0
/* 46BB08 802A4258 54400014 */  bnel       $v0, $zero, .LPAL_802A42AC
/* 46BB0C 802A425C 2631000D */   addiu     $s1, $s1, 0xD
/* 46BB10 802A4260 3C02802B */  lui        $v0, %hi(D_802AD34E)
/* 46BB14 802A4264 8042D34E */  lb         $v0, %lo(D_802AD34E)($v0)
/* 46BB18 802A4268 00621021 */  addu       $v0, $v1, $v0
/* 46BB1C 802A426C 0053102A */  slt        $v0, $v0, $s3
/* 46BB20 802A4270 10400003 */  beqz       $v0, .LPAL_802A4280
/* 46BB24 802A4274 02A0282D */   daddu     $a1, $s5, $zero
/* 46BB28 802A4278 080A90AB */  j          .LPAL_802A42AC
/* 46BB2C 802A427C 2631000D */   addiu     $s1, $s1, 0xD
.LPAL_802A4280:
/* 46BB30 802A4280 0220302D */  daddu      $a2, $s1, $zero
/* 46BB34 802A4284 8E500000 */  lw         $s0, 0x0($s2)
/* 46BB38 802A4288 2631000D */  addiu      $s1, $s1, 0xD
/* 46BB3C 802A428C 0C050D4D */  jal        func_PAL_80143534
/* 46BB40 802A4290 0200202D */   daddu     $a0, $s0, $zero
/* 46BB44 802A4294 3C05802B */  lui        $a1, %hi(D_802AD356)
/* 46BB48 802A4298 84A5D356 */  lh         $a1, %lo(D_802AD356)($a1)
/* 46BB4C 802A429C 0C050E98 */  jal        func_PAL_80143A60
/* 46BB50 802A42A0 0200202D */   daddu     $a0, $s0, $zero
/* 46BB54 802A42A4 0C050CE4 */  jal        func_PAL_80143390
/* 46BB58 802A42A8 0200202D */   daddu     $a0, $s0, $zero
.LPAL_802A42AC:
/* 46BB5C 802A42AC 26730001 */  addiu      $s3, $s3, 0x1
/* 46BB60 802A42B0 3C02802B */  lui        $v0, %hi(D_802AD6E4)
/* 46BB64 802A42B4 8C42D6E4 */  lw         $v0, %lo(D_802AD6E4)($v0)
/* 46BB68 802A42B8 0262102A */  slt        $v0, $s3, $v0
/* 46BB6C 802A42BC 1440FFE2 */  bnez       $v0, .LPAL_802A4248
/* 46BB70 802A42C0 26520004 */   addiu     $s2, $s2, 0x4
.LPAL_802A42C4:
/* 46BB74 802A42C4 8FA9004C */  lw         $t1, 0x4C($sp)
/* 46BB78 802A42C8 3C03802B */  lui        $v1, %hi(D_802AD349)
/* 46BB7C 802A42CC 8063D349 */  lb         $v1, %lo(D_802AD349)($v1)
/* 46BB80 802A42D0 3C02802B */  lui        $v0, %hi(D_802AD34C)
/* 46BB84 802A42D4 8042D34C */  lb         $v0, %lo(D_802AD34C)($v0)
/* 46BB88 802A42D8 3C08802B */  lui        $t0, %hi(D_802AD352)
/* 46BB8C 802A42DC 8508D352 */  lh         $t0, %lo(D_802AD352)($t0)
/* 46BB90 802A42E0 2535000A */  addiu      $s5, $t1, 0xA
/* 46BB94 802A42E4 00621823 */  subu       $v1, $v1, $v0
/* 46BB98 802A42E8 00031040 */  sll        $v0, $v1, 1
/* 46BB9C 802A42EC 00431021 */  addu       $v0, $v0, $v1
/* 46BBA0 802A42F0 00021080 */  sll        $v0, $v0, 2
/* 46BBA4 802A42F4 00438821 */  addu       $s1, $v0, $v1
/* 46BBA8 802A42F8 02281023 */  subu       $v0, $s1, $t0
/* 46BBAC 802A42FC 44820000 */  mtc1       $v0, $f0
/* 46BBB0 802A4300 00000000 */  nop
/* 46BBB4 802A4304 46800021 */  cvt.d.w    $f0, $f0
/* 46BBB8 802A4308 4620018D */  trunc.w.d  $f6, $f0
/* 46BBBC 802A430C 44023000 */  mfc1       $v0, $f6
/* 46BBC0 802A4310 00000000 */  nop
/* 46BBC4 802A4314 14400002 */  bnez       $v0, .LPAL_802A4320
/* 46BBC8 802A4318 01024021 */   addu      $t0, $t0, $v0
/* 46BBCC 802A431C 0220402D */  daddu      $t0, $s1, $zero
.LPAL_802A4320:
/* 46BBD0 802A4320 02A0282D */  daddu      $a1, $s5, $zero
/* 46BBD4 802A4324 00083400 */  sll        $a2, $t0, 16
/* 46BBD8 802A4328 00063403 */  sra        $a2, $a2, 16
/* 46BBDC 802A432C 3C10802B */  lui        $s0, %hi(D_802AD358)
/* 46BBE0 802A4330 8E10D358 */  lw         $s0, %lo(D_802AD358)($s0)
/* 46BBE4 802A4334 8FA90050 */  lw         $t1, 0x50($sp)
/* 46BBE8 802A4338 24C6001A */  addiu      $a2, $a2, 0x1A
/* 46BBEC 802A433C 3C01802B */  lui        $at, %hi(D_802AD352)
/* 46BBF0 802A4340 A428D352 */  sh         $t0, %lo(D_802AD352)($at)
/* 46BBF4 802A4344 01263021 */  addu       $a2, $t1, $a2
/* 46BBF8 802A4348 0C050D4D */  jal        func_PAL_80143534
/* 46BBFC 802A434C 0200202D */   daddu     $a0, $s0, $zero
/* 46BC00 802A4350 3C11802B */  lui        $s1, %hi(D_802AD356)
/* 46BC04 802A4354 2631D356 */  addiu      $s1, $s1, %lo(D_802AD356)
/* 46BC08 802A4358 86250000 */  lh         $a1, 0x0($s1)
/* 46BC0C 802A435C 0C050E98 */  jal        func_PAL_80143A60
/* 46BC10 802A4360 0200202D */   daddu     $a0, $s0, $zero
/* 46BC14 802A4364 0C050CE4 */  jal        func_PAL_80143390
/* 46BC18 802A4368 0200202D */   daddu     $a0, $s0, $zero
/* 46BC1C 802A436C 3C02802B */  lui        $v0, %hi(D_802AD34C)
/* 46BC20 802A4370 8042D34C */  lb         $v0, %lo(D_802AD34C)($v0)
/* 46BC24 802A4374 1840000E */  blez       $v0, .LPAL_802A43B0
/* 46BC28 802A4378 00000000 */   nop
/* 46BC2C 802A437C 8FA9004C */  lw         $t1, 0x4C($sp)
/* 46BC30 802A4380 3C10802B */  lui        $s0, %hi(D_802AD35C)
/* 46BC34 802A4384 8E10D35C */  lw         $s0, %lo(D_802AD35C)($s0)
/* 46BC38 802A4388 25250048 */  addiu      $a1, $t1, 0x48
/* 46BC3C 802A438C 8FA90050 */  lw         $t1, 0x50($sp)
/* 46BC40 802A4390 0200202D */  daddu      $a0, $s0, $zero
/* 46BC44 802A4394 0C050D4D */  jal        func_PAL_80143534
/* 46BC48 802A4398 2526000F */   addiu     $a2, $t1, 0xF
/* 46BC4C 802A439C 86250000 */  lh         $a1, 0x0($s1)
/* 46BC50 802A43A0 0C050E98 */  jal        func_PAL_80143A60
/* 46BC54 802A43A4 0200202D */   daddu     $a0, $s0, $zero
/* 46BC58 802A43A8 0C050CD6 */  jal        func_PAL_80143358
/* 46BC5C 802A43AC 0200202D */   daddu     $a0, $s0, $zero
.LPAL_802A43B0:
/* 46BC60 802A43B0 3C02802B */  lui        $v0, %hi(D_802AD34D)
/* 46BC64 802A43B4 8042D34D */  lb         $v0, %lo(D_802AD34D)($v0)
/* 46BC68 802A43B8 3C03802B */  lui        $v1, %hi(D_802AD6E4)
/* 46BC6C 802A43BC 8C63D6E4 */  lw         $v1, %lo(D_802AD6E4)($v1)
/* 46BC70 802A43C0 0043102A */  slt        $v0, $v0, $v1
/* 46BC74 802A43C4 1040000E */  beqz       $v0, .LPAL_802A4400
/* 46BC78 802A43C8 00000000 */   nop
/* 46BC7C 802A43CC 8FA9004C */  lw         $t1, 0x4C($sp)
/* 46BC80 802A43D0 3C10802B */  lui        $s0, %hi(D_802AD360)
/* 46BC84 802A43D4 8E10D360 */  lw         $s0, %lo(D_802AD360)($s0)
/* 46BC88 802A43D8 25250048 */  addiu      $a1, $t1, 0x48
/* 46BC8C 802A43DC 8FA90050 */  lw         $t1, 0x50($sp)
/* 46BC90 802A43E0 0200202D */  daddu      $a0, $s0, $zero
/* 46BC94 802A43E4 0C050D4D */  jal        func_PAL_80143534
/* 46BC98 802A43E8 25260064 */   addiu     $a2, $t1, 0x64
/* 46BC9C 802A43EC 86250000 */  lh         $a1, 0x0($s1)
/* 46BCA0 802A43F0 0C050E98 */  jal        func_PAL_80143A60
/* 46BCA4 802A43F4 0200202D */   daddu     $a0, $s0, $zero
/* 46BCA8 802A43F8 0C050CD6 */  jal        func_PAL_80143358
/* 46BCAC 802A43FC 0200202D */   daddu     $a0, $s0, $zero
.LPAL_802A4400:
/* 46BCB0 802A4400 3C03802B */  lui        $v1, %hi(D_802AD348)
/* 46BCB4 802A4404 8063D348 */  lb         $v1, %lo(D_802AD348)($v1)
/* 46BCB8 802A4408 2402FFFF */  addiu      $v0, $zero, -0x1
/* 46BCBC 802A440C 1462000B */  bne        $v1, $v0, .LPAL_802A443C
/* 46BCC0 802A4410 00000000 */   nop
/* 46BCC4 802A4414 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46BCC8 802A4418 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46BCCC 802A441C 14400005 */  bnez       $v0, .LPAL_802A4434
/* 46BCD0 802A4420 00000000 */   nop
/* 46BCD4 802A4424 0C03988A */  jal        func_PAL_800E6228
/* 46BCD8 802A4428 00000000 */   nop
/* 46BCDC 802A442C 080A910F */  j          .LPAL_802A443C
/* 46BCE0 802A4430 00000000 */   nop
.LPAL_802A4434:
/* 46BCE4 802A4434 0C0398BB */  jal        func_PAL_800E62EC
/* 46BCE8 802A4438 00000000 */   nop
.LPAL_802A443C:
/* 46BCEC 802A443C 8FBF0044 */  lw         $ra, 0x44($sp)
/* 46BCF0 802A4440 8FBE0040 */  lw         $fp, 0x40($sp)
/* 46BCF4 802A4444 8FB7003C */  lw         $s7, 0x3C($sp)
/* 46BCF8 802A4448 8FB60038 */  lw         $s6, 0x38($sp)
/* 46BCFC 802A444C 8FB50034 */  lw         $s5, 0x34($sp)
/* 46BD00 802A4450 8FB40030 */  lw         $s4, 0x30($sp)
/* 46BD04 802A4454 8FB3002C */  lw         $s3, 0x2C($sp)
/* 46BD08 802A4458 8FB20028 */  lw         $s2, 0x28($sp)
/* 46BD0C 802A445C 8FB10024 */  lw         $s1, 0x24($sp)
/* 46BD10 802A4460 8FB00020 */  lw         $s0, 0x20($sp)
/* 46BD14 802A4464 03E00008 */  jr         $ra
/* 46BD18 802A4468 27BD0048 */   addiu     $sp, $sp, 0x48
