.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_802A43DC
/* 46BD1C 802A446C 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 46BD20 802A4470 3C02802B */  lui        $v0, %hi(D_802AD6E0)
/* 46BD24 802A4474 8C42D6E0 */  lw         $v0, %lo(D_802AD6E0)($v0)
/* 46BD28 802A4478 00A0182D */  daddu      $v1, $a1, $zero
/* 46BD2C 802A447C 1440000D */  bnez       $v0, .LPAL_802A44B4
/* 46BD30 802A4480 AFBF0018 */   sw        $ra, 0x18($sp)
/* 46BD34 802A4484 3C04001D */  lui        $a0, (0x1D0045 >> 16)
/* 46BD38 802A4488 34840045 */  ori        $a0, $a0, (0x1D0045 & 0xFFFF)
/* 46BD3C 802A448C 24C60002 */  addiu      $a2, $a2, 0x2
/* 46BD40 802A4490 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 46BD44 802A4494 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 46BD48 802A4498 3C07802B */  lui        $a3, %hi(D_802AD356)
/* 46BD4C 802A449C 84E7D356 */  lh         $a3, %lo(D_802AD356)($a3)
/* 46BD50 802A44A0 3C05802B */  lui        $a1, %hi(D_PAL_802AB4F4)
/* 46BD54 802A44A4 00A22821 */  addu       $a1, $a1, $v0
/* 46BD58 802A44A8 90A5B4F4 */  lbu        $a1, %lo(D_PAL_802AB4F4)($a1)
/* 46BD5C 802A44AC 080A9138 */  j          .LPAL_802A44E0
/* 46BD60 802A44B0 24020030 */   addiu     $v0, $zero, 0x30
.LPAL_802A44B4:
/* 46BD64 802A44B4 3C04001D */  lui        $a0, (0x1D003A >> 16)
/* 46BD68 802A44B8 3484003A */  ori        $a0, $a0, (0x1D003A & 0xFFFF)
/* 46BD6C 802A44BC 24C60002 */  addiu      $a2, $a2, 0x2
/* 46BD70 802A44C0 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 46BD74 802A44C4 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 46BD78 802A44C8 3C07802B */  lui        $a3, %hi(D_802AD356)
/* 46BD7C 802A44CC 84E7D356 */  lh         $a3, %lo(D_802AD356)($a3)
/* 46BD80 802A44D0 3C05802B */  lui        $a1, %hi(D_PAL_802AB4E0)
/* 46BD84 802A44D4 00A22821 */  addu       $a1, $a1, $v0
/* 46BD88 802A44D8 90A5B4E0 */  lbu        $a1, %lo(D_PAL_802AB4E0)($a1)
/* 46BD8C 802A44DC 24020031 */  addiu      $v0, $zero, 0x31
.LPAL_802A44E0:
/* 46BD90 802A44E0 AFA20010 */  sw         $v0, 0x10($sp)
/* 46BD94 802A44E4 24020001 */  addiu      $v0, $zero, 0x1
/* 46BD98 802A44E8 AFA20014 */  sw         $v0, 0x14($sp)
/* 46BD9C 802A44EC 0C049403 */  jal        func_PAL_8012500C
/* 46BDA0 802A44F0 00652821 */   addu      $a1, $v1, $a1
/* 46BDA4 802A44F4 8FBF0018 */  lw         $ra, 0x18($sp)
/* 46BDA8 802A44F8 03E00008 */  jr         $ra
/* 46BDAC 802A44FC 27BD0020 */   addiu     $sp, $sp, 0x20
