.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_pal_80248018
/* 170A38 80248018 3C028016 */  lui        $v0, %hi(D_80158910)
/* 170A3C 8024801C 24428910 */  addiu      $v0, $v0, %lo(D_80158910)
/* 170A40 80248020 00041940 */  sll        $v1, $a0, 5
/* 170A44 80248024 00624021 */  addu       $t0, $v1, $v0
/* 170A48 80248028 9107001C */  lbu        $a3, 0x1C($t0)
/* 170A4C 8024802C 24020039 */  addiu      $v0, $zero, 0x39
/* 170A50 80248030 1082000A */  beq        $a0, $v0, .Lfilemenu_8024805C
/* 170A54 80248034 0000282D */   daddu     $a1, $zero, $zero
/* 170A58 80248038 2882003A */  slti       $v0, $a0, 0x3A
/* 170A5C 8024803C 1440000A */  bnez       $v0, .Lfilemenu_80248068
/* 170A60 80248040 2402003A */   addiu     $v0, $zero, 0x3A
/* 170A64 80248044 10820007 */  beq        $a0, $v0, .Lfilemenu_80248064
/* 170A68 80248048 2402003B */   addiu     $v0, $zero, 0x3B
/* 170A6C 8024804C 50820006 */  beql       $a0, $v0, .Lfilemenu_80248068
/* 170A70 80248050 24050003 */   addiu     $a1, $zero, 0x3
/* 170A74 80248054 0809201A */  j          .Lfilemenu_80248068
/* 170A78 80248058 00000000 */   nop
.Lfilemenu_8024805C:
/* 170A7C 8024805C 0809201A */  j          .Lfilemenu_80248068
/* 170A80 80248060 24050001 */   addiu     $a1, $zero, 0x1
.Lfilemenu_80248064:
/* 170A84 80248064 24050002 */  addiu      $a1, $zero, 0x2
.Lfilemenu_80248068:
/* 170A88 80248068 3C038015 */  lui        $v1, %hi(D_PAL_8014AE4C)
/* 170A8C 8024806C 8C63AE4C */  lw         $v1, %lo(D_PAL_8014AE4C)($v1)
/* 170A90 80248070 00651823 */  subu       $v1, $v1, $a1
/* 170A94 80248074 04620001 */  bltzl      $v1, .Lfilemenu_8024807C
/* 170A98 80248078 00031823 */   negu      $v1, $v1
.Lfilemenu_8024807C:
/* 170A9C 8024807C 00031040 */  sll        $v0, $v1, 1
/* 170AA0 80248080 00431021 */  addu       $v0, $v0, $v1
/* 170AA4 80248084 00E23823 */  subu       $a3, $a3, $v0
/* 170AA8 80248088 04E20001 */  bltzl      $a3, .Lfilemenu_80248090
/* 170AAC 8024808C 0000382D */   daddu     $a3, $zero, $zero
.Lfilemenu_80248090:
/* 170AB0 80248090 28E20012 */  slti       $v0, $a3, 0x12
/* 170AB4 80248094 10400008 */  beqz       $v0, .Lfilemenu_802480B8
/* 170AB8 80248098 00071040 */   sll       $v0, $a3, 1
/* 170ABC 8024809C 3C038025 */  lui        $v1, %hi(D_filemenu_8024EB80)
/* 170AC0 802480A0 00621821 */  addu       $v1, $v1, $v0
/* 170AC4 802480A4 8463EB80 */  lh         $v1, %lo(D_filemenu_8024EB80)($v1)
/* 170AC8 802480A8 8CC20000 */  lw         $v0, 0x0($a2)
/* 170ACC 802480AC 00431023 */  subu       $v0, $v0, $v1
/* 170AD0 802480B0 08092037 */  j          .Lfilemenu_802480DC
/* 170AD4 802480B4 ACC20000 */   sw        $v0, 0x0($a2)
.Lfilemenu_802480B8:
/* 170AD8 802480B8 3C028025 */  lui        $v0, %hi(D_filemenu_8024EBA2)
/* 170ADC 802480BC 8442EBA2 */  lh         $v0, %lo(D_filemenu_8024EBA2)($v0)
/* 170AE0 802480C0 8CC30000 */  lw         $v1, 0x0($a2)
/* 170AE4 802480C4 00621823 */  subu       $v1, $v1, $v0
/* 170AE8 802480C8 ACC30000 */  sw         $v1, 0x0($a2)
/* 170AEC 802480CC 91020000 */  lbu        $v0, 0x0($t0)
/* 170AF0 802480D0 304200F7 */  andi       $v0, $v0, 0xF7
/* 170AF4 802480D4 34420004 */  ori        $v0, $v0, 0x4
/* 170AF8 802480D8 A1020000 */  sb         $v0, 0x0($t0)
.Lfilemenu_802480DC:
/* 170AFC 802480DC 28E20010 */  slti       $v0, $a3, 0x10
/* 170B00 802480E0 14400003 */  bnez       $v0, .Lfilemenu_802480F0
/* 170B04 802480E4 00000000 */   nop
/* 170B08 802480E8 3C018025 */  lui        $at, %hi(D_filemenu_8024E9A0)
/* 170B0C 802480EC AC20E9A0 */  sw         $zero, %lo(D_filemenu_8024E9A0)($at)
.Lfilemenu_802480F0:
/* 170B10 802480F0 03E00008 */  jr         $ra
/* 170B14 802480F4 00000000 */   nop
