.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel filemenu_pal_80247f40
/* 170960 80247F40 3C028016 */  lui        $v0, %hi(D_80158910)
/* 170964 80247F44 24428910 */  addiu      $v0, $v0, %lo(D_80158910)
/* 170968 80247F48 00041940 */  sll        $v1, $a0, 5
/* 17096C 80247F4C 00624021 */  addu       $t0, $v1, $v0
/* 170970 80247F50 9105001C */  lbu        $a1, 0x1C($t0)
/* 170974 80247F54 24020039 */  addiu      $v0, $zero, 0x39
/* 170978 80247F58 1082000A */  beq        $a0, $v0, .Lfilemenu_80247F84
/* 17097C 80247F5C 0000382D */   daddu     $a3, $zero, $zero
/* 170980 80247F60 2882003A */  slti       $v0, $a0, 0x3A
/* 170984 80247F64 1440000A */  bnez       $v0, .Lfilemenu_80247F90
/* 170988 80247F68 2402003A */   addiu     $v0, $zero, 0x3A
/* 17098C 80247F6C 10820007 */  beq        $a0, $v0, .Lfilemenu_80247F8C
/* 170990 80247F70 2402003B */   addiu     $v0, $zero, 0x3B
/* 170994 80247F74 50820006 */  beql       $a0, $v0, .Lfilemenu_80247F90
/* 170998 80247F78 24070003 */   addiu     $a3, $zero, 0x3
/* 17099C 80247F7C 08091FE4 */  j          .Lfilemenu_80247F90
/* 1709A0 80247F80 00000000 */   nop
.Lfilemenu_80247F84:
/* 1709A4 80247F84 08091FE4 */  j          .Lfilemenu_80247F90
/* 1709A8 80247F88 24070001 */   addiu     $a3, $zero, 0x1
.Lfilemenu_80247F8C:
/* 1709AC 80247F8C 24070002 */  addiu      $a3, $zero, 0x2
.Lfilemenu_80247F90:
/* 1709B0 80247F90 3C038015 */  lui        $v1, %hi(D_PAL_8014AE4C)
/* 1709B4 80247F94 8C63AE4C */  lw         $v1, %lo(D_PAL_8014AE4C)($v1)
/* 1709B8 80247F98 00671823 */  subu       $v1, $v1, $a3
/* 1709BC 80247F9C 04620001 */  bltzl      $v1, .Lfilemenu_80247FA4
/* 1709C0 80247FA0 00031823 */   negu      $v1, $v1
.Lfilemenu_80247FA4:
/* 1709C4 80247FA4 00031040 */  sll        $v0, $v1, 1
/* 1709C8 80247FA8 00431021 */  addu       $v0, $v0, $v1
/* 1709CC 80247FAC 00A22823 */  subu       $a1, $a1, $v0
/* 1709D0 80247FB0 04A20001 */  bltzl      $a1, .Lfilemenu_80247FB8
/* 1709D4 80247FB4 0000282D */   daddu     $a1, $zero, $zero
.Lfilemenu_80247FB8:
/* 1709D8 80247FB8 14A00005 */  bnez       $a1, .Lfilemenu_80247FD0
/* 1709DC 80247FBC 28A20011 */   slti      $v0, $a1, 0x11
/* 1709E0 80247FC0 91020000 */  lbu        $v0, 0x0($t0)
/* 1709E4 80247FC4 304200FB */  andi       $v0, $v0, 0xFB
/* 1709E8 80247FC8 A1020000 */  sb         $v0, 0x0($t0)
/* 1709EC 80247FCC 28A20011 */  slti       $v0, $a1, 0x11
.Lfilemenu_80247FD0:
/* 1709F0 80247FD0 10400008 */  beqz       $v0, .Lfilemenu_80247FF4
/* 1709F4 80247FD4 00051040 */   sll       $v0, $a1, 1
/* 1709F8 80247FD8 3C038025 */  lui        $v1, %hi(D_filemenu_8024EB5C)
/* 1709FC 80247FDC 00621821 */  addu       $v1, $v1, $v0
/* 170A00 80247FE0 8463EB5C */  lh         $v1, %lo(D_filemenu_8024EB5C)($v1)
/* 170A04 80247FE4 8CC20000 */  lw         $v0, 0x0($a2)
/* 170A08 80247FE8 00431023 */  subu       $v0, $v0, $v1
/* 170A0C 80247FEC 03E00008 */  jr         $ra
/* 170A10 80247FF0 ACC20000 */   sw        $v0, 0x0($a2)
.Lfilemenu_80247FF4:
/* 170A14 80247FF4 3C028025 */  lui        $v0, %hi(D_filemenu_8024EB7C)
/* 170A18 80247FF8 8442EB7C */  lh         $v0, %lo(D_filemenu_8024EB7C)($v0)
/* 170A1C 80247FFC 8CC30000 */  lw         $v1, 0x0($a2)
/* 170A20 80248000 00621823 */  subu       $v1, $v1, $v0
/* 170A24 80248004 ACC30000 */  sw         $v1, 0x0($a2)
/* 170A28 80248008 91020000 */  lbu        $v0, 0x0($t0)
/* 170A2C 8024800C 304200F7 */  andi       $v0, $v0, 0xF7
/* 170A30 80248010 03E00008 */  jr         $ra
/* 170A34 80248014 A1020000 */   sb        $v0, 0x0($t0)
