.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
glabel jtbl_PAL_800947A0
/* 6FBA0 800947A0 800375E4 */ .word .LPAL_800375E4
/* 6FBA4 800947A4 8003766C */ .word .LPAL_8003766C
/* 6FBA8 800947A8 80037614 */ .word .LPAL_80037614
/* 6FBAC 800947AC 80037674 */ .word .LPAL_80037674
/* 6FBB0 800947B0 80037644 */ .word .LPAL_80037644
/* 6FBB4 800947B4 80037644 */ .word .LPAL_80037644


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel state_drawUI_title_screen
/* 129B0 800375B0 3C028007 */  lui        $v0, %hi(gGameStatusPtr)
/* 129B4 800375B4 8C4214AC */  lw         $v0, %lo(gGameStatusPtr)($v0)
/* 129B8 800375B8 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 129BC 800375BC AFBF0010 */  sw         $ra, 0x10($sp)
/* 129C0 800375C0 804300AC */  lb         $v1, 0xAC($v0)
/* 129C4 800375C4 2C620006 */  sltiu      $v0, $v1, 0x6
/* 129C8 800375C8 1040002A */  beqz       $v0, .LPAL_80037674
/* 129CC 800375CC 00031080 */   sll       $v0, $v1, 2
/* 129D0 800375D0 3C018009 */  lui        $at, %hi(jtbl_PAL_800947A0)
/* 129D4 800375D4 00220821 */  addu       $at, $at, $v0
/* 129D8 800375D8 8C2247A0 */  lw         $v0, %lo(jtbl_PAL_800947A0)($at)
/* 129DC 800375DC 00400008 */  jr         $v0
/* 129E0 800375E0 00000000 */   nop
.LPAL_800375E4:
/* 129E4 800375E4 3C018007 */  lui        $at, %hi(D_80077A28)
/* 129E8 800375E8 AC203D78 */  sw         $zero, %lo(D_80077A28)($at)
/* 129EC 800375EC 3C018007 */  lui        $at, %hi(D_80077A2C)
/* 129F0 800375F0 AC203D7C */  sw         $zero, %lo(D_80077A2C)($at)
/* 129F4 800375F4 3C018007 */  lui        $at, %hi(D_80077A30)
/* 129F8 800375F8 AC203D80 */  sw         $zero, %lo(D_80077A30)($at)
/* 129FC 800375FC 3C01800A */  lui        $at, %hi(D_PAL_8009F0F4)
/* 12A00 80037600 AC20F0F4 */  sw         $zero, %lo(D_PAL_8009F0F4)($at)
/* 12A04 80037604 3C01800A */  lui        $at, %hi(D_PAL_8009F0F8)
/* 12A08 80037608 AC20F0F8 */  sw         $zero, %lo(D_PAL_8009F0F8)($at)
/* 12A0C 8003760C 0800DD9B */  j          .LPAL_8003766C
/* 12A10 80037610 00000000 */   nop
.LPAL_80037614:
/* 12A14 80037614 0C00DE6A */  jal        draw_title_screen_NOP
/* 12A18 80037618 00000000 */   nop
/* 12A1C 8003761C 3C028007 */  lui        $v0, %hi(gGameStatusPtr)
/* 12A20 80037620 8C4214AC */  lw         $v0, %lo(gGameStatusPtr)($v0)
/* 12A24 80037624 90420073 */  lbu        $v0, 0x73($v0)
/* 12A28 80037628 30420001 */  andi       $v0, $v0, 0x1
/* 12A2C 8003762C 10400011 */  beqz       $v0, .LPAL_80037674
/* 12A30 80037630 00000000 */   nop
/* 12A34 80037634 0C00DF04 */  jal        title_screen_draw_press_start
/* 12A38 80037638 00000000 */   nop
/* 12A3C 8003763C 0800DD9D */  j          .LPAL_80037674
/* 12A40 80037640 00000000 */   nop
.LPAL_80037644:
/* 12A44 80037644 3C028007 */  lui        $v0, %hi(gGameStatusPtr)
/* 12A48 80037648 8C4214AC */  lw         $v0, %lo(gGameStatusPtr)($v0)
/* 12A4C 8003764C 90420073 */  lbu        $v0, 0x73($v0)
/* 12A50 80037650 30420001 */  andi       $v0, $v0, 0x1
/* 12A54 80037654 10400003 */  beqz       $v0, .LPAL_80037664
/* 12A58 80037658 24020002 */   addiu     $v0, $zero, 0x2
/* 12A5C 8003765C 3C018007 */  lui        $at, %hi(D_80077A2C)
/* 12A60 80037660 AC223D7C */  sw         $v0, %lo(D_80077A2C)($at)
.LPAL_80037664:
/* 12A64 80037664 0C00DF04 */  jal        title_screen_draw_press_start
/* 12A68 80037668 00000000 */   nop
.LPAL_8003766C:
/* 12A6C 8003766C 0C00DE6A */  jal        draw_title_screen_NOP
/* 12A70 80037670 00000000 */   nop
.LPAL_80037674:
/* 12A74 80037674 8FBF0010 */  lw         $ra, 0x10($sp)
/* 12A78 80037678 03E00008 */  jr         $ra
/* 12A7C 8003767C 27BD0018 */   addiu     $sp, $sp, 0x18
