.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
glabel D_PAL_80094768
/* 6FB68 80094768 */ .asciz "title_data"
                      .balign 4

glabel D_PAL_80094774
/* 6FB74 80094774 */ .asciz "title_bg"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel state_init_title_screen
/* 120F0 80036CF0 27BDFFC8 */  addiu      $sp, $sp, -0x38
/* 120F4 80036CF4 AFB20028 */  sw         $s2, 0x28($sp)
/* 120F8 80036CF8 3C128009 */  lui        $s2, %hi(gOverrideFlags)
/* 120FC 80036CFC 26526A28 */  addiu      $s2, $s2, %lo(gOverrideFlags)
/* 12100 80036D00 24020001 */  addiu      $v0, $zero, 0x1
/* 12104 80036D04 AFBF002C */  sw         $ra, 0x2C($sp)
/* 12108 80036D08 AFB10024 */  sw         $s1, 0x24($sp)
/* 1210C 80036D0C AFB00020 */  sw         $s0, 0x20($sp)
/* 12110 80036D10 F7B40030 */  sdc1       $f20, 0x30($sp)
/* 12114 80036D14 AE400000 */  sw         $zero, 0x0($s2)
/* 12118 80036D18 3C018009 */  lui        $at, %hi(timeFreezeMode)
/* 1211C 80036D1C AC2069AC */  sw         $zero, %lo(timeFreezeMode)($at)
/* 12120 80036D20 3C018015 */  lui        $at, %hi(D_PAL_8014ADF8)
/* 12124 80036D24 A022ADF8 */  sb         $v0, %lo(D_PAL_8014ADF8)($at)
/* 12128 80036D28 0C00AAE0 */  jal        general_heap_create
/* 1212C 80036D2C 00000000 */   nop
/* 12130 80036D30 0C04885D */  jal        clear_printers
/* 12134 80036D34 00000000 */   nop
/* 12138 80036D38 0C0520EB */  jal        sfx_set_reverb_mode
/* 1213C 80036D3C 0000202D */   daddu     $a0, $zero, $zero
/* 12140 80036D40 3C038007 */  lui        $v1, %hi(gGameStatusPtr)
/* 12144 80036D44 246314AC */  addiu      $v1, $v1, %lo(gGameStatusPtr)
/* 12148 80036D48 8C620000 */  lw         $v0, 0x0($v1)
/* 1214C 80036D4C A04000AC */  sb         $zero, 0xAC($v0)
/* 12150 80036D50 8C620000 */  lw         $v0, 0x0($v1)
/* 12154 80036D54 A04000AD */  sb         $zero, 0xAD($v0)
/* 12158 80036D58 8C620000 */  lw         $v0, 0x0($v1)
/* 1215C 80036D5C A0400070 */  sb         $zero, 0x70($v0)
/* 12160 80036D60 8C630000 */  lw         $v1, 0x0($v1)
/* 12164 80036D64 2402FFFF */  addiu      $v0, $zero, -0x1
/* 12168 80036D68 0C00CEED */  jal        intro_logos_update_fade
/* 1216C 80036D6C A06200A8 */   sb        $v0, 0xA8($v1)
/* 12170 80036D70 3C048009 */  lui        $a0, %hi(D_PAL_80094768)
/* 12174 80036D74 24844768 */  addiu      $a0, $a0, %lo(D_PAL_80094768)
/* 12178 80036D78 0C016D02 */  jal        load_asset_by_name
/* 1217C 80036D7C 27A50018 */   addiu     $a1, $sp, 0x18
/* 12180 80036D80 8FA40018 */  lw         $a0, 0x18($sp)
/* 12184 80036D84 0C00AB19 */  jal        heap_malloc
/* 12188 80036D88 0040882D */   daddu     $s1, $v0, $zero
/* 1218C 80036D8C 0220202D */  daddu      $a0, $s1, $zero
/* 12190 80036D90 0040282D */  daddu      $a1, $v0, $zero
/* 12194 80036D94 3C10800A */  lui        $s0, %hi(D_8009F0D4)
/* 12198 80036D98 2610F0D4 */  addiu      $s0, $s0, %lo(D_8009F0D4)
/* 1219C 80036D9C 0C01BF64 */  jal        decode_yay0
/* 121A0 80036DA0 AE050000 */   sw        $a1, 0x0($s0)
/* 121A4 80036DA4 0C00AAFE */  jal        general_heap_free
/* 121A8 80036DA8 0220202D */   daddu     $a0, $s1, $zero
/* 121AC 80036DAC 8E050000 */  lw         $a1, 0x0($s0)
/* 121B0 80036DB0 3C040000 */  lui        $a0, %hi(D_2EE0)
/* 121B4 80036DB4 24842EE0 */  addiu      $a0, $a0, %lo(D_2EE0)
/* 121B8 80036DB8 8CA20000 */  lw         $v0, 0x0($a1)
/* 121BC 80036DBC 8CA30008 */  lw         $v1, 0x8($a1)
/* 121C0 80036DC0 00451021 */  addu       $v0, $v0, $a1
/* 121C4 80036DC4 3C01800A */  lui        $at, %hi(D_800A0978)
/* 121C8 80036DC8 AC22F0D8 */  sw         $v0, %lo(D_800A0978)($at)
/* 121CC 80036DCC 8CA20004 */  lw         $v0, 0x4($a1)
/* 121D0 80036DD0 00651821 */  addu       $v1, $v1, $a1
/* 121D4 80036DD4 3C01800A */  lui        $at, %hi(D_8009F0E0)
/* 121D8 80036DD8 AC23F0E0 */  sw         $v1, %lo(D_8009F0E0)($at)
/* 121DC 80036DDC 00451021 */  addu       $v0, $v0, $a1
/* 121E0 80036DE0 3C01800A */  lui        $at, %hi(D_800A097C)
/* 121E4 80036DE4 AC22F0DC */  sw         $v0, %lo(D_800A097C)($at)
/* 121E8 80036DE8 0C00AB19 */  jal        heap_malloc
/* 121EC 80036DEC 00000000 */   nop
/* 121F0 80036DF0 3C040026 */  lui        $a0, %hi(D_2596C0)
/* 121F4 80036DF4 248496C0 */  addiu      $a0, $a0, %lo(D_2596C0)
/* 121F8 80036DF8 3C050026 */  lui        $a1, %hi(D_25C5A0)
/* 121FC 80036DFC 24A5C5A0 */  addiu      $a1, $a1, %lo(D_25C5A0)
/* 12200 80036E00 0040302D */  daddu      $a2, $v0, $zero
/* 12204 80036E04 3C10800A */  lui        $s0, %hi(D_PAL_8009F0E4)
/* 12208 80036E08 2610F0E4 */  addiu      $s0, $s0, %lo(D_PAL_8009F0E4)
/* 1220C 80036E0C 0C00A5AF */  jal        dma_copy
/* 12210 80036E10 AE060000 */   sw        $a2, 0x0($s0)
/* 12214 80036E14 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 12218 80036E18 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 1221C 80036E1C 8E040000 */  lw         $a0, 0x0($s0)
/* 12220 80036E20 000210C0 */  sll        $v0, $v0, 3
/* 12224 80036E24 00441021 */  addu       $v0, $v0, $a0
/* 12228 80036E28 8C430000 */  lw         $v1, 0x0($v0)
/* 1222C 80036E2C 8C420004 */  lw         $v0, 0x4($v0)
/* 12230 80036E30 00641821 */  addu       $v1, $v1, $a0
/* 12234 80036E34 00441021 */  addu       $v0, $v0, $a0
/* 12238 80036E38 3C01800A */  lui        $at, %hi(D_PAL_8009F0E8)
/* 1223C 80036E3C AC23F0E8 */  sw         $v1, %lo(D_PAL_8009F0E8)($at)
/* 12240 80036E40 3C01800A */  lui        $at, %hi(D_PAL_8009F0EC)
/* 12244 80036E44 AC22F0EC */  sw         $v0, %lo(D_PAL_8009F0EC)($at)
/* 12248 80036E48 0C00B885 */  jal        create_cameras_a
/* 1224C 80036E4C 00000000 */   nop
/* 12250 80036E50 0000202D */  daddu      $a0, $zero, $zero
/* 12254 80036E54 2405000C */  addiu      $a1, $zero, 0xC
/* 12258 80036E58 2406001C */  addiu      $a2, $zero, 0x1C
/* 1225C 80036E5C 24070128 */  addiu      $a3, $zero, 0x128
/* 12260 80036E60 3C10800B */  lui        $s0, %hi(gCameras)
/* 12264 80036E64 26100460 */  addiu      $s0, $s0, %lo(gCameras)
/* 12268 80036E68 3C0141C8 */  lui        $at, (0x41C80000 >> 16)
/* 1226C 80036E6C 4481A000 */  mtc1       $at, $f20
/* 12270 80036E70 24020006 */  addiu      $v0, $zero, 0x6
/* 12274 80036E74 A6020004 */  sh         $v0, 0x4($s0)
/* 12278 80036E78 24020001 */  addiu      $v0, $zero, 0x1
/* 1227C 80036E7C A6020006 */  sh         $v0, 0x6($s0)
/* 12280 80036E80 24020010 */  addiu      $v0, $zero, 0x10
/* 12284 80036E84 A6020012 */  sh         $v0, 0x12($s0)
/* 12288 80036E88 24021000 */  addiu      $v0, $zero, 0x1000
/* 1228C 80036E8C A6020014 */  sh         $v0, 0x14($s0)
/* 12290 80036E90 240200B8 */  addiu      $v0, $zero, 0xB8
/* 12294 80036E94 3C018007 */  lui        $at, %hi(gCurrentCameraID)
/* 12298 80036E98 AC203730 */  sw         $zero, %lo(gCurrentCameraID)($at)
/* 1229C 80036E9C E6140018 */  swc1       $f20, 0x18($s0)
/* 122A0 80036EA0 AFA20010 */  sw         $v0, 0x10($sp)
/* 122A4 80036EA4 96020000 */  lhu        $v0, 0x0($s0)
/* 122A8 80036EA8 96030558 */  lhu        $v1, 0x558($s0)
/* 122AC 80036EAC 34420002 */  ori        $v0, $v0, 0x2
/* 122B0 80036EB0 A6020000 */  sh         $v0, 0x0($s0)
/* 122B4 80036EB4 96020AB0 */  lhu        $v0, 0xAB0($s0)
/* 122B8 80036EB8 34630002 */  ori        $v1, $v1, 0x2
/* 122BC 80036EBC A6030558 */  sh         $v1, 0x558($s0)
/* 122C0 80036EC0 96031008 */  lhu        $v1, 0x1008($s0)
/* 122C4 80036EC4 34420002 */  ori        $v0, $v0, 0x2
/* 122C8 80036EC8 34630002 */  ori        $v1, $v1, 0x2
/* 122CC 80036ECC A6020AB0 */  sh         $v0, 0xAB0($s0)
/* 122D0 80036ED0 0C00B98D */  jal        set_cam_viewport
/* 122D4 80036ED4 A6031008 */   sh        $v1, 0x1008($s0)
/* 122D8 80036ED8 3C0143FA */  lui        $at, (0x43FA0000 >> 16)
/* 122DC 80036EDC 44810000 */  mtc1       $at, $f0
/* 122E0 80036EE0 3C01447A */  lui        $at, (0x447A0000 >> 16)
/* 122E4 80036EE4 44811000 */  mtc1       $at, $f2
/* 122E8 80036EE8 3C0144BB */  lui        $at, (0x44BB8000 >> 16)
/* 122EC 80036EEC 34218000 */  ori        $at, $at, (0x44BB8000 & 0xFFFF)
/* 122F0 80036EF0 44812000 */  mtc1       $at, $f4
/* 122F4 80036EF4 3C014316 */  lui        $at, (0x43160000 >> 16)
/* 122F8 80036EF8 44813000 */  mtc1       $at, $f6
/* 122FC 80036EFC 24020028 */  addiu      $v0, $zero, 0x28
/* 12300 80036F00 A602001E */  sh         $v0, 0x1E($s0)
/* 12304 80036F04 24020064 */  addiu      $v0, $zero, 0x64
/* 12308 80036F08 A600002C */  sh         $zero, 0x2C($s0)
/* 1230C 80036F0C A600002E */  sh         $zero, 0x2E($s0)
/* 12310 80036F10 A6000030 */  sh         $zero, 0x30($s0)
/* 12314 80036F14 E6140054 */  swc1       $f20, 0x54($s0)
/* 12318 80036F18 E6140058 */  swc1       $f20, 0x58($s0)
/* 1231C 80036F1C A600001C */  sh         $zero, 0x1C($s0)
/* 12320 80036F20 A6020020 */  sh         $v0, 0x20($s0)
/* 12324 80036F24 A6000022 */  sh         $zero, 0x22($s0)
/* 12328 80036F28 E600003C */  swc1       $f0, 0x3C($s0)
/* 1232C 80036F2C E6020040 */  swc1       $f2, 0x40($s0)
/* 12330 80036F30 E6040044 */  swc1       $f4, 0x44($s0)
/* 12334 80036F34 0C0B1877 */  jal        clear_script_list
/* 12338 80036F38 E606005C */   swc1      $f6, 0x5C($s0)
/* 1233C 80036F3C 0C0486EE */  jal        clear_worker_list
/* 12340 80036F40 00000000 */   nop
/* 12344 80036F44 0C0470E4 */  jal        clear_render_tasks
/* 12348 80036F48 00000000 */   nop
/* 1234C 80036F4C 0C0B8EF6 */  jal        spr_init_sprites
/* 12350 80036F50 0000202D */   daddu     $a0, $zero, $zero
/* 12354 80036F54 0C047349 */  jal        clear_animator_list
/* 12358 80036F58 00000000 */   nop
/* 1235C 80036F5C 0C047DAC */  jal        clear_entity_models
/* 12360 80036F60 00000000 */   nop
/* 12364 80036F64 0C00E26B */  jal        clear_npcs
/* 12368 80036F68 00000000 */   nop
/* 1236C 80036F6C 0C04FF28 */  jal        hud_element_clear_cache
/* 12370 80036F70 00000000 */   nop
/* 12374 80036F74 0C05126A */  jal        reset_background_settings
/* 12378 80036F78 00000000 */   nop
/* 1237C 80036F7C 0C043DEE */  jal        clear_entity_data
/* 12380 80036F80 24040001 */   addiu     $a0, $zero, 0x1
/* 12384 80036F84 0C01689F */  jal        clear_effect_data
/* 12388 80036F88 00000000 */   nop
/* 1238C 80036F8C 8E420000 */  lw         $v0, 0x0($s2)
/* 12390 80036F90 34420002 */  ori        $v0, $v0, 0x2
/* 12394 80036F94 0C038EC4 */  jal        clear_player_data
/* 12398 80036F98 AE420000 */   sw        $v0, 0x0($s2)
/* 1239C 80036F9C 0000202D */  daddu      $a0, $zero, $zero
/* 123A0 80036FA0 3C058003 */  lui        $a1, %hi(appendGfx_title_screen)
/* 123A4 80036FA4 24A57680 */  addiu      $a1, $a1, %lo(appendGfx_title_screen)
/* 123A8 80036FA8 8E420000 */  lw         $v0, 0x0($s2)
/* 123AC 80036FAC 2403FFF7 */  addiu      $v1, $zero, -0x9
/* 123B0 80036FB0 00431024 */  and        $v0, $v0, $v1
/* 123B4 80036FB4 0C044621 */  jal        game_mode_set_fpDrawAuxUI
/* 123B8 80036FB8 AE420000 */   sw        $v0, 0x0($s2)
/* 123BC 80036FBC 3C048009 */  lui        $a0, %hi(D_PAL_80094774)
/* 123C0 80036FC0 0C051248 */  jal        load_map_bg
/* 123C4 80036FC4 24844774 */   addiu     $a0, $a0, %lo(D_PAL_80094774)
/* 123C8 80036FC8 3C048020 */  lui        $a0, %hi(D_80200000)
/* 123CC 80036FCC 24840000 */  addiu      $a0, $a0, %lo(D_80200000)
/* 123D0 80036FD0 0C051276 */  jal        read_background_size
/* 123D4 80036FD4 00000000 */   nop
/* 123D8 80036FD8 0000202D */  daddu      $a0, $zero, $zero
/* 123DC 80036FDC 2405006A */  addiu      $a1, $zero, 0x6A
/* 123E0 80036FE0 0080302D */  daddu      $a2, $a0, $zero
/* 123E4 80036FE4 240701F4 */  addiu      $a3, $zero, 0x1F4
/* 123E8 80036FE8 24020008 */  addiu      $v0, $zero, 0x8
/* 123EC 80036FEC 0C052532 */  jal        bgm_set_song
/* 123F0 80036FF0 AFA20010 */   sw        $v0, 0x10($sp)
/* 123F4 80036FF4 8FBF002C */  lw         $ra, 0x2C($sp)
/* 123F8 80036FF8 8FB20028 */  lw         $s2, 0x28($sp)
/* 123FC 80036FFC 8FB10024 */  lw         $s1, 0x24($sp)
/* 12400 80037000 8FB00020 */  lw         $s0, 0x20($sp)
/* 12404 80037004 D7B40030 */  ldc1       $f20, 0x30($sp)
/* 12408 80037008 24020190 */  addiu      $v0, $zero, 0x190
/* 1240C 8003700C 3C01800A */  lui        $at, %hi(D_PAL_8009F0F0)
/* 12410 80037010 A422F0F0 */  sh         $v0, %lo(D_PAL_8009F0F0)($at)
/* 12414 80037014 03E00008 */  jr         $ra
/* 12418 80037018 27BD0038 */   addiu     $sp, $sp, 0x38
