.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel shop_owner_continue_speech_with_quantity
/* 84D130 80280220 3C028007 */  lui        $v0, %hi(gGameStatusPtr)
/* 84D134 80280224 8C4214AC */  lw         $v0, %lo(gGameStatusPtr)($v0)
/* 84D138 80280228 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 84D13C 8028022C AFB00010 */  sw         $s0, 0x10($sp)
/* 84D140 80280230 00A0802D */  daddu      $s0, $a1, $zero
/* 84D144 80280234 AFBF001C */  sw         $ra, 0x1C($sp)
/* 84D148 80280238 AFB20018 */  sw         $s2, 0x18($sp)
/* 84D14C 8028023C AFB10014 */  sw         $s1, 0x14($sp)
/* 84D150 80280240 8C510144 */  lw         $s1, 0x144($v0)
/* 84D154 80280244 0000282D */  daddu      $a1, $zero, $zero
/* 84D158 80280248 8E230010 */  lw         $v1, 0x10($s1)
/* 84D15C 8028024C 00041080 */  sll        $v0, $a0, 2
/* 84D160 80280250 8C630018 */  lw         $v1, 0x18($v1)
/* 84D164 80280254 00431021 */  addu       $v0, $v0, $v1
/* 84D168 80280258 8C520000 */  lw         $s2, 0x0($v0)
/* 84D16C 8028025C 0C0491C2 */  jal        set_message_value
/* 84D170 80280260 0200202D */   daddu     $a0, $s0, $zero
/* 84D174 80280264 3C048015 */  lui        $a0, %hi(MessagePlural)
/* 84D178 80280268 2484AE40 */  addiu      $a0, $a0, %lo(MessagePlural)
/* 84D17C 8028026C 24020001 */  addiu      $v0, $zero, 0x1
/* 84D180 80280270 16020003 */  bne        $s0, $v0, .LPAL_80280280
/* 84D184 80280274 00000000 */   nop
/* 84D188 80280278 3C048015 */  lui        $a0, %hi(D_8014AE48)
/* 84D18C 8028027C 2484AE48 */  addiu      $a0, $a0, %lo(D_8014AE48)
.LPAL_80280280:
/* 84D190 80280280 0C049197 */  jal        set_message_msg
/* 84D194 80280284 24050001 */   addiu     $a1, $zero, 0x1
/* 84D198 80280288 3C048028 */  lui        $a0, %hi(D_PAL_80283EC0)
/* 84D19C 8028028C 24843EC0 */  addiu      $a0, $a0, %lo(D_PAL_80283EC0)
/* 84D1A0 80280290 24050001 */  addiu      $a1, $zero, 0x1
/* 84D1A4 80280294 0C0B18F8 */  jal        start_script
/* 84D1A8 80280298 0000302D */   daddu     $a2, $zero, $zero
/* 84D1AC 8028029C 0040202D */  daddu      $a0, $v0, $zero
/* 84D1B0 802802A0 AC920084 */  sw         $s2, 0x84($a0)
/* 84D1B4 802802A4 8E220010 */  lw         $v0, 0x10($s1)
/* 84D1B8 802802A8 8C420000 */  lw         $v0, 0x0($v0)
/* 84D1BC 802802AC AC820088 */  sw         $v0, 0x88($a0)
/* 84D1C0 802802B0 8E220010 */  lw         $v0, 0x10($s1)
/* 84D1C4 802802B4 8C420008 */  lw         $v0, 0x8($v0)
/* 84D1C8 802802B8 AC82008C */  sw         $v0, 0x8C($a0)
/* 84D1CC 802802BC 8E230010 */  lw         $v1, 0x10($s1)
/* 84D1D0 802802C0 8C820144 */  lw         $v0, 0x144($a0)
/* 84D1D4 802802C4 8C630004 */  lw         $v1, 0x4($v1)
/* 84D1D8 802802C8 AC830090 */  sw         $v1, 0x90($a0)
/* 84D1DC 802802CC AC83007C */  sw         $v1, 0x7C($a0)
/* 84D1E0 802802D0 8FBF001C */  lw         $ra, 0x1C($sp)
/* 84D1E4 802802D4 8FB20018 */  lw         $s2, 0x18($sp)
/* 84D1E8 802802D8 8FB10014 */  lw         $s1, 0x14($sp)
/* 84D1EC 802802DC 8FB00010 */  lw         $s0, 0x10($sp)
/* 84D1F0 802802E0 03E00008 */  jr         $ra
/* 84D1F4 802802E4 27BD0020 */   addiu     $sp, $sp, 0x20
