.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel shop_owner_buy_dialog
/* 84CF98 80280088 3C028007 */  lui        $v0, %hi(gGameStatusPtr)
/* 84CF9C 8028008C 8C4214AC */  lw         $v0, %lo(gGameStatusPtr)($v0)
/* 84CFA0 80280090 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 84CFA4 80280094 AFB3001C */  sw         $s3, 0x1C($sp)
/* 84CFA8 80280098 00C0982D */  daddu      $s3, $a2, $zero
/* 84CFAC 8028009C AFB10014 */  sw         $s1, 0x14($sp)
/* 84CFB0 802800A0 00E0882D */  daddu      $s1, $a3, $zero
/* 84CFB4 802800A4 AFBF0020 */  sw         $ra, 0x20($sp)
/* 84CFB8 802800A8 AFB20018 */  sw         $s2, 0x18($sp)
/* 84CFBC 802800AC AFB00010 */  sw         $s0, 0x10($sp)
/* 84CFC0 802800B0 8C500144 */  lw         $s0, 0x144($v0)
/* 84CFC4 802800B4 00041080 */  sll        $v0, $a0, 2
/* 84CFC8 802800B8 8E030010 */  lw         $v1, 0x10($s0)
/* 84CFCC 802800BC 00A0202D */  daddu      $a0, $a1, $zero
/* 84CFD0 802800C0 8C630018 */  lw         $v1, 0x18($v1)
/* 84CFD4 802800C4 00431021 */  addu       $v0, $v0, $v1
/* 84CFD8 802800C8 8C520000 */  lw         $s2, 0x0($v0)
/* 84CFDC 802800CC 0C049197 */  jal        set_message_msg
/* 84CFE0 802800D0 0000282D */   daddu     $a1, $zero, $zero
/* 84CFE4 802800D4 0260202D */  daddu      $a0, $s3, $zero
/* 84CFE8 802800D8 0C0491C2 */  jal        set_message_value
/* 84CFEC 802800DC 24050001 */   addiu     $a1, $zero, 0x1
/* 84CFF0 802800E0 1A200005 */  blez       $s1, .LPAL_802800F8
/* 84CFF4 802800E4 0220202D */   daddu     $a0, $s1, $zero
/* 84CFF8 802800E8 0C0491C2 */  jal        set_message_value
/* 84CFFC 802800EC 24050002 */   addiu     $a1, $zero, 0x2
/* 84D000 802800F0 080A004D */  j          .LPAL_80280134
/* 84D004 802800F4 00000000 */   nop
.LPAL_802800F8:
/* 84D008 802800F8 3C048015 */  lui        $a0, %hi(MessagePlural)
/* 84D00C 802800FC 2484AE40 */  addiu      $a0, $a0, %lo(MessagePlural)
/* 84D010 80280100 3C028015 */  lui        $v0, %hi(gCurrentLanguage)
/* 84D014 80280104 8C42AE4C */  lw         $v0, %lo(gCurrentLanguage)($v0)
/* 84D018 80280108 24030001 */  addiu      $v1, $zero, 0x1
/* 84D01C 8028010C 14430003 */  bne        $v0, $v1, .LPAL_8028011C
/* 84D020 80280110 00000000 */   nop
/* 84D024 80280114 3C048015 */  lui        $a0, %hi(MessagePlural_de)
/* 84D028 80280118 2484AE44 */  addiu      $a0, $a0, %lo(MessagePlural_de)
.LPAL_8028011C:
/* 84D02C 8028011C 16630003 */  bne        $s3, $v1, .LPAL_8028012C
/* 84D030 80280120 00000000 */   nop
/* 84D034 80280124 3C048015 */  lui        $a0, %hi(D_8014AE48)
/* 84D038 80280128 2484AE48 */  addiu      $a0, $a0, %lo(D_8014AE48)
.LPAL_8028012C:
/* 84D03C 8028012C 0C049197 */  jal        set_message_msg
/* 84D040 80280130 24050002 */   addiu     $a1, $zero, 0x2
.LPAL_80280134:
/* 84D044 80280134 3C048028 */  lui        $a0, %hi(D_PAL_80283E90)
/* 84D048 80280138 24843E90 */  addiu      $a0, $a0, %lo(D_PAL_80283E90)
/* 84D04C 8028013C 24050001 */  addiu      $a1, $zero, 0x1
/* 84D050 80280140 0C0B18F8 */  jal        start_script
/* 84D054 80280144 0000302D */   daddu     $a2, $zero, $zero
/* 84D058 80280148 0040202D */  daddu      $a0, $v0, $zero
/* 84D05C 8028014C AC920084 */  sw         $s2, 0x84($a0)
/* 84D060 80280150 8E020010 */  lw         $v0, 0x10($s0)
/* 84D064 80280154 8C420000 */  lw         $v0, 0x0($v0)
/* 84D068 80280158 AC820088 */  sw         $v0, 0x88($a0)
/* 84D06C 8028015C 8E020010 */  lw         $v0, 0x10($s0)
/* 84D070 80280160 8C420008 */  lw         $v0, 0x8($v0)
/* 84D074 80280164 AC82008C */  sw         $v0, 0x8C($a0)
/* 84D078 80280168 8E030010 */  lw         $v1, 0x10($s0)
/* 84D07C 8028016C 8C820144 */  lw         $v0, 0x144($a0)
/* 84D080 80280170 8C630004 */  lw         $v1, 0x4($v1)
/* 84D084 80280174 AC830090 */  sw         $v1, 0x90($a0)
/* 84D088 80280178 8FBF0020 */  lw         $ra, 0x20($sp)
/* 84D08C 8028017C 8FB3001C */  lw         $s3, 0x1C($sp)
/* 84D090 80280180 8FB20018 */  lw         $s2, 0x18($sp)
/* 84D094 80280184 8FB10014 */  lw         $s1, 0x14($sp)
/* 84D098 80280188 8FB00010 */  lw         $s0, 0x10($sp)
/* 84D09C 8028018C 03E00008 */  jr         $ra
/* 84D0A0 80280190 27BD0028 */   addiu     $sp, $sp, 0x28
