.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel create_audio_system
/* 264E0 8004B0E0 27BDFFC0 */  addiu      $sp, $sp, -0x40
/* 264E4 8004B0E4 AFB00030 */  sw         $s0, 0x30($sp)
/* 264E8 8004B0E8 3C10800D */  lui        $s0, %hi(D_800D59A0)
/* 264EC 8004B0EC 261059A0 */  addiu      $s0, $s0, %lo(D_800D59A0)
/* 264F0 8004B0F0 0200202D */  daddu      $a0, $s0, $zero
/* 264F4 8004B0F4 3C05801A */  lui        $a1, %hi(D_801A5000)
/* 264F8 8004B0F8 24A55000 */  addiu      $a1, $a1, %lo(D_801A5000)
/* 264FC 8004B0FC 3C060005 */  lui        $a2, (0x5B000 >> 16)
/* 26500 8004B100 24020001 */  addiu      $v0, $zero, 0x1
/* 26504 8004B104 AFBF003C */  sw         $ra, 0x3C($sp)
/* 26508 8004B108 AFB20038 */  sw         $s2, 0x38($sp)
/* 2650C 8004B10C AFB10034 */  sw         $s1, 0x34($sp)
/* 26510 8004B110 3C018007 */  lui        $at, %hi(nuAuTaskStop)
/* 26514 8004B114 A0224520 */  sb         $v0, %lo(nuAuTaskStop)($at)
/* 26518 8004B118 3C018007 */  lui        $at, %hi(nuAuPreNMI)
/* 2651C 8004B11C A0204510 */  sb         $zero, %lo(nuAuPreNMI)($at)
/* 26520 8004B120 0C016140 */  jal        alHeapInit
/* 26524 8004B124 34C6B000 */   ori       $a2, $a2, (0x5B000 & 0xFFFF)
/* 26528 8004B128 24047D00 */  addiu      $a0, $zero, 0x7D00
/* 2652C 8004B12C 24020018 */  addiu      $v0, $zero, 0x18
/* 26530 8004B130 AFA20018 */  sw         $v0, 0x18($sp)
/* 26534 8004B134 24020004 */  addiu      $v0, $zero, 0x4
/* 26538 8004B138 0C0188F4 */  jal        osAiSetFrequency
/* 2653C 8004B13C AFA2001C */   sw        $v0, 0x1C($sp)
/* 26540 8004B140 3C03800D */  lui        $v1, %hi(D_800D7228)
/* 26544 8004B144 8C637228 */  lw         $v1, %lo(D_800D7228)($v1)
/* 26548 8004B148 00620018 */  mult       $v1, $v0
/* 2654C 8004B14C 3C0451EB */  lui        $a0, (0x51EB851F >> 16)
/* 26550 8004B150 00001812 */  mflo       $v1
/* 26554 8004B154 3484851F */  ori        $a0, $a0, (0x51EB851F & 0xFFFF)
/* 26558 8004B158 24630031 */  addiu      $v1, $v1, 0x31
/* 2655C 8004B15C 00640019 */  multu      $v1, $a0
/* 26560 8004B160 0000882D */  daddu      $s1, $zero, $zero
/* 26564 8004B164 3C12800A */  lui        $s2, %hi(AlCmdListBuffers)
/* 26568 8004B168 26521C80 */  addiu      $s2, $s2, %lo(AlCmdListBuffers)
/* 2656C 8004B16C AFA20020 */  sw         $v0, 0x20($sp)
/* 26570 8004B170 00001810 */  mfhi       $v1
/* 26574 8004B174 3C02B216 */  lui        $v0, (0xB21642C9 >> 16)
/* 26578 8004B178 344242C9 */  ori        $v0, $v0, (0xB21642C9 & 0xFFFF)
/* 2657C 8004B17C 00031902 */  srl        $v1, $v1, 4
/* 26580 8004B180 00620019 */  multu      $v1, $v0
/* 26584 8004B184 A3A00024 */  sb         $zero, 0x24($sp)
/* 26588 8004B188 AFB0002C */  sw         $s0, 0x2C($sp)
/* 2658C 8004B18C 3C028005 */  lui        $v0, %hi(nuAuDmaNew)
/* 26590 8004B190 2442B804 */  addiu      $v0, $v0, %lo(nuAuDmaNew)
/* 26594 8004B194 AFA20028 */  sw         $v0, 0x28($sp)
/* 26598 8004B198 00001810 */  mfhi       $v1
/* 2659C 8004B19C 000319C2 */  srl        $v1, $v1, 7
/* 265A0 8004B1A0 24630001 */  addiu      $v1, $v1, 0x1
/* 265A4 8004B1A4 00031040 */  sll        $v0, $v1, 1
/* 265A8 8004B1A8 00431021 */  addu       $v0, $v0, $v1
/* 265AC 8004B1AC 000210C0 */  sll        $v0, $v0, 3
/* 265B0 8004B1B0 00431023 */  subu       $v0, $v0, $v1
/* 265B4 8004B1B4 000210C0 */  sll        $v0, $v0, 3
/* 265B8 8004B1B8 3C01800A */  lui        $at, %hi(AlFrameSize)
/* 265BC 8004B1BC AC221DA4 */  sw         $v0, %lo(AlFrameSize)($at)
/* 265C0 8004B1C0 2442FE90 */  addiu      $v0, $v0, -0x170
/* 265C4 8004B1C4 3C01800A */  lui        $at, %hi(AlMinFrameSize)
/* 265C8 8004B1C8 AC221DA8 */  sw         $v0, %lo(AlMinFrameSize)($at)
.LPAL_8004B1CC:
/* 265CC 8004B1CC 24050001 */  addiu      $a1, $zero, 0x1
/* 265D0 8004B1D0 24065558 */  addiu      $a2, $zero, 0x5558
/* 265D4 8004B1D4 8FA4002C */  lw         $a0, 0x2C($sp)
/* 265D8 8004B1D8 0C01615C */  jal        alHeapAlloc
/* 265DC 8004B1DC 02258821 */   addu      $s1, $s1, $a1
/* 265E0 8004B1E0 AE420000 */  sw         $v0, 0x0($s2)
/* 265E4 8004B1E4 2E220003 */  sltiu      $v0, $s1, 0x3
/* 265E8 8004B1E8 1440FFF8 */  bnez       $v0, .LPAL_8004B1CC
/* 265EC 8004B1EC 26520004 */   addiu     $s2, $s2, 0x4
/* 265F0 8004B1F0 0000882D */  daddu      $s1, $zero, $zero
/* 265F4 8004B1F4 24090002 */  addiu      $t1, $zero, 0x2
/* 265F8 8004B1F8 3C08800D */  lui        $t0, %hi(rspbootUcodeBuffer)
/* 265FC 8004B1FC 25085EF0 */  addiu      $t0, $t0, %lo(rspbootUcodeBuffer)
/* 26600 8004B200 24070100 */  addiu      $a3, $zero, 0x100
/* 26604 8004B204 3C068007 */  lui        $a2, %hi(n_aspMain_text_bin)
/* 26608 8004B208 24C604B0 */  addiu      $a2, $a2, %lo(n_aspMain_text_bin)
/* 2660C 8004B20C 3C058009 */  lui        $a1, %hi(n_aspMain_data_bin)
/* 26610 8004B210 24A53E70 */  addiu      $a1, $a1, %lo(n_aspMain_data_bin)
/* 26614 8004B214 24040800 */  addiu      $a0, $zero, 0x800
/* 26618 8004B218 3C03800A */  lui        $v1, %hi(nuAuTasks)
/* 2661C 8004B21C 24631C90 */  addiu      $v1, $v1, %lo(nuAuTasks)
.LPAL_8004B220:
/* 26620 8004B220 AC600000 */  sw         $zero, 0x0($v1)
/* 26624 8004B224 AC600054 */  sw         $zero, 0x54($v1)
/* 26628 8004B228 AC690010 */  sw         $t1, 0x10($v1)
/* 2662C 8004B22C AC680018 */  sw         $t0, 0x18($v1)
/* 26630 8004B230 AC67001C */  sw         $a3, 0x1C($v1)
/* 26634 8004B234 AC660020 */  sw         $a2, 0x20($v1)
/* 26638 8004B238 AC650028 */  sw         $a1, 0x28($v1)
/* 2663C 8004B23C AC64002C */  sw         $a0, 0x2C($v1)
/* 26640 8004B240 AC600030 */  sw         $zero, 0x30($v1)
/* 26644 8004B244 AC600034 */  sw         $zero, 0x34($v1)
/* 26648 8004B248 AC600038 */  sw         $zero, 0x38($v1)
/* 2664C 8004B24C AC60003C */  sw         $zero, 0x3C($v1)
/* 26650 8004B250 AC600048 */  sw         $zero, 0x48($v1)
/* 26654 8004B254 AC60004C */  sw         $zero, 0x4C($v1)
/* 26658 8004B258 26310001 */  addiu      $s1, $s1, 0x1
/* 2665C 8004B25C 2E220003 */  sltiu      $v0, $s1, 0x3
/* 26660 8004B260 1440FFEF */  bnez       $v0, .LPAL_8004B220
/* 26664 8004B264 24630058 */   addiu     $v1, $v1, 0x58
/* 26668 8004B268 0000882D */  daddu      $s1, $zero, $zero
/* 2666C 8004B26C 3C10800A */  lui        $s0, %hi(D_800A3628)
/* 26670 8004B270 26101D98 */  addiu      $s0, $s0, %lo(D_800A3628)
.LPAL_8004B274:
/* 26674 8004B274 24050001 */  addiu      $a1, $zero, 0x1
/* 26678 8004B278 02258821 */  addu       $s1, $s1, $a1
/* 2667C 8004B27C 3C06800A */  lui        $a2, %hi(AlFrameSize)
/* 26680 8004B280 8CC61DA4 */  lw         $a2, %lo(AlFrameSize)($a2)
/* 26684 8004B284 8FA4002C */  lw         $a0, 0x2C($sp)
/* 26688 8004B288 0C01615C */  jal        alHeapAlloc
/* 2668C 8004B28C 00063080 */   sll       $a2, $a2, 2
/* 26690 8004B290 AE020000 */  sw         $v0, 0x0($s0)
/* 26694 8004B294 2E220003 */  sltiu      $v0, $s1, 0x3
/* 26698 8004B298 1440FFF6 */  bnez       $v0, .LPAL_8004B274
/* 2669C 8004B29C 26100004 */   addiu     $s0, $s0, 0x4
/* 266A0 8004B2A0 0000882D */  daddu      $s1, $zero, $zero
/* 266A4 8004B2A4 3C02800A */  lui        $v0, %hi(nuAuDmaBufList)
/* 266A8 8004B2A8 24422350 */  addiu      $v0, $v0, %lo(nuAuDmaBufList)
/* 266AC 8004B2AC 0040802D */  daddu      $s0, $v0, $zero
/* 266B0 8004B2B0 26120014 */  addiu      $s2, $s0, 0x14
/* 266B4 8004B2B4 AE000004 */  sw         $zero, 0x4($s0)
/* 266B8 8004B2B8 AE000000 */  sw         $zero, 0x0($s0)
.LPAL_8004B2BC:
/* 266BC 8004B2BC 0240202D */  daddu      $a0, $s2, $zero
/* 266C0 8004B2C0 0C012E73 */  jal        alLink
/* 266C4 8004B2C4 0200282D */   daddu     $a1, $s0, $zero
/* 266C8 8004B2C8 24050001 */  addiu      $a1, $zero, 0x1
/* 266CC 8004B2CC 24060500 */  addiu      $a2, $zero, 0x500
/* 266D0 8004B2D0 26520014 */  addiu      $s2, $s2, 0x14
/* 266D4 8004B2D4 8FA4002C */  lw         $a0, 0x2C($sp)
/* 266D8 8004B2D8 0C01615C */  jal        alHeapAlloc
/* 266DC 8004B2DC 02258821 */   addu      $s1, $s1, $a1
/* 266E0 8004B2E0 AE020010 */  sw         $v0, 0x10($s0)
/* 266E4 8004B2E4 2E220031 */  sltiu      $v0, $s1, 0x31
/* 266E8 8004B2E8 1440FFF4 */  bnez       $v0, .LPAL_8004B2BC
/* 266EC 8004B2EC 26100014 */   addiu     $s0, $s0, 0x14
/* 266F0 8004B2F0 24050001 */  addiu      $a1, $zero, 0x1
/* 266F4 8004B2F4 8FA4002C */  lw         $a0, 0x2C($sp)
/* 266F8 8004B2F8 0C01615C */  jal        alHeapAlloc
/* 266FC 8004B2FC 24060500 */   addiu     $a2, $zero, 0x500
/* 26700 8004B300 3C04800A */  lui        $a0, %hi(nuAuDmaMesgQ)
/* 26704 8004B304 24841DB0 */  addiu      $a0, $a0, %lo(nuAuDmaMesgQ)
/* 26708 8004B308 3C05800A */  lui        $a1, %hi(D_PAL_800A1DC8)
/* 2670C 8004B30C 24A51DC8 */  addiu      $a1, $a1, %lo(D_PAL_800A1DC8)
/* 26710 8004B310 00111880 */  sll        $v1, $s1, 2
/* 26714 8004B314 00711821 */  addu       $v1, $v1, $s1
/* 26718 8004B318 00031880 */  sll        $v1, $v1, 2
/* 2671C 8004B31C 3C01800A */  lui        $at, %hi(D_800A2360)
/* 26720 8004B320 00230821 */  addu       $at, $at, $v1
/* 26724 8004B324 AC222360 */  sw         $v0, %lo(D_800A2360)($at)
/* 26728 8004B328 0C0198FC */  jal        osCreateMesgQueue
/* 2672C 8004B32C 24060032 */   addiu     $a2, $zero, 0x32
/* 26730 8004B330 3C04800B */  lui        $a0, %hi(D_800B5880)
/* 26734 8004B334 24845880 */  addiu      $a0, $a0, %lo(D_800B5880)
/* 26738 8004B338 3C028005 */  lui        $v0, %hi(nuAuPreNMIProc)
/* 2673C 8004B33C 2442B908 */  addiu      $v0, $v0, %lo(nuAuPreNMIProc)
/* 26740 8004B340 3C018007 */  lui        $at, %hi(nuAuPreNMIFunc)
/* 26744 8004B344 AC224514 */  sw         $v0, %lo(nuAuPreNMIFunc)($at)
/* 26748 8004B348 0C015A0C */  jal        au_driver_init
/* 2674C 8004B34C 27A50018 */   addiu     $a1, $sp, 0x18
/* 26750 8004B350 8FA40020 */  lw         $a0, 0x20($sp)
/* 26754 8004B354 0C014D0F */  jal        au_engine_init
/* 26758 8004B358 00000000 */   nop
/* 2675C 8004B35C 3C10800A */  lui        $s0, %hi(D_PAL_8009F6C8)
/* 26760 8004B360 2610F6C8 */  addiu      $s0, $s0, %lo(D_PAL_8009F6C8)
/* 26764 8004B364 0200202D */  daddu      $a0, $s0, $zero
/* 26768 8004B368 24050003 */  addiu      $a1, $zero, 0x3
/* 2676C 8004B36C 3C068005 */  lui        $a2, %hi(nuAuMgr)
/* 26770 8004B370 24C6B3E8 */  addiu      $a2, $a2, %lo(nuAuMgr)
/* 26774 8004B374 3C02800A */  lui        $v0, %hi(AlCmdListBuffers)
/* 26778 8004B378 24421C80 */  addiu      $v0, $v0, %lo(AlCmdListBuffers)
/* 2677C 8004B37C AFA20010 */  sw         $v0, 0x10($sp)
/* 26780 8004B380 24020046 */  addiu      $v0, $zero, 0x46
/* 26784 8004B384 0000382D */  daddu      $a3, $zero, $zero
/* 26788 8004B388 0C019B34 */  jal        osCreateThread
/* 2678C 8004B38C AFA20014 */   sw        $v0, 0x14($sp)
/* 26790 8004B390 0C019BA4 */  jal        osStartThread
/* 26794 8004B394 0200202D */   daddu     $a0, $s0, $zero
/* 26798 8004B398 8FBF003C */  lw         $ra, 0x3C($sp)
/* 2679C 8004B39C 8FB20038 */  lw         $s2, 0x38($sp)
/* 267A0 8004B3A0 8FB10034 */  lw         $s1, 0x34($sp)
/* 267A4 8004B3A4 8FB00030 */  lw         $s0, 0x30($sp)
/* 267A8 8004B3A8 03E00008 */  jr         $ra
/* 267AC 8004B3AC 27BD0040 */   addiu     $sp, $sp, 0x40
