.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel func_802619E8
/* 19DE58 80261CF8 27BDFFB8 */  addiu      $sp, $sp, -0x48
/* 19DE5C 80261CFC AFB3003C */  sw         $s3, 0x3C($sp)
/* 19DE60 80261D00 0080982D */  daddu      $s3, $a0, $zero
/* 19DE64 80261D04 AFBF0040 */  sw         $ra, 0x40($sp)
/* 19DE68 80261D08 AFB20038 */  sw         $s2, 0x38($sp)
/* 19DE6C 80261D0C AFB10034 */  sw         $s1, 0x34($sp)
/* 19DE70 80261D10 AFB00030 */  sw         $s0, 0x30($sp)
/* 19DE74 80261D14 8E70000C */  lw         $s0, 0xC($s3)
/* 19DE78 80261D18 8E050000 */  lw         $a1, 0x0($s0)
/* 19DE7C 80261D1C 0C0B2AAF */  jal        func_PAL_802CAABC
/* 19DE80 80261D20 26100004 */   addiu     $s0, $s0, 0x4
/* 19DE84 80261D24 8E050000 */  lw         $a1, 0x0($s0)
/* 19DE88 80261D28 26100004 */  addiu      $s0, $s0, 0x4
/* 19DE8C 80261D2C 0260202D */  daddu      $a0, $s3, $zero
/* 19DE90 80261D30 0C0B2AAF */  jal        func_PAL_802CAABC
/* 19DE94 80261D34 0040882D */   daddu     $s1, $v0, $zero
/* 19DE98 80261D38 0260202D */  daddu      $a0, $s3, $zero
/* 19DE9C 80261D3C 8E050000 */  lw         $a1, 0x0($s0)
/* 19DEA0 80261D40 0C0B2AAF */  jal        func_PAL_802CAABC
/* 19DEA4 80261D44 0040802D */   daddu     $s0, $v0, $zero
/* 19DEA8 80261D48 44910000 */  mtc1       $s1, $f0
/* 19DEAC 80261D4C 00000000 */  nop
/* 19DEB0 80261D50 46800020 */  cvt.s.w    $f0, $f0
/* 19DEB4 80261D54 44050000 */  mfc1       $a1, $f0
/* 19DEB8 80261D58 44900000 */  mtc1       $s0, $f0
/* 19DEBC 80261D5C 00000000 */  nop
/* 19DEC0 80261D60 46800020 */  cvt.s.w    $f0, $f0
/* 19DEC4 80261D64 44060000 */  mfc1       $a2, $f0
/* 19DEC8 80261D68 44820000 */  mtc1       $v0, $f0
/* 19DECC 80261D6C 00000000 */  nop
/* 19DED0 80261D70 46800020 */  cvt.s.w    $f0, $f0
/* 19DED4 80261D74 3C048007 */  lui        $a0, %hi(D_PAL_80073730)
/* 19DED8 80261D78 8C843730 */  lw         $a0, %lo(D_PAL_80073730)($a0)
/* 19DEDC 80261D7C 44070000 */  mfc1       $a3, $f0
/* 19DEE0 80261D80 27A30020 */  addiu      $v1, $sp, 0x20
/* 19DEE4 80261D84 AFA30010 */  sw         $v1, 0x10($sp)
/* 19DEE8 80261D88 27A30024 */  addiu      $v1, $sp, 0x24
/* 19DEEC 80261D8C AFA30014 */  sw         $v1, 0x14($sp)
/* 19DEF0 80261D90 27A30028 */  addiu      $v1, $sp, 0x28
/* 19DEF4 80261D94 0C00BA16 */  jal        func_PAL_8002E858
/* 19DEF8 80261D98 AFA30018 */   sw        $v1, 0x18($sp)
/* 19DEFC 80261D9C 8FA20020 */  lw         $v0, 0x20($sp)
/* 19DF00 80261DA0 2442001E */  addiu      $v0, $v0, 0x1E
/* 19DF04 80261DA4 AFA20020 */  sw         $v0, 0x20($sp)
/* 19DF08 80261DA8 8FA20024 */  lw         $v0, 0x24($sp)
/* 19DF0C 80261DAC 8E6300AC */  lw         $v1, 0xAC($s3)
/* 19DF10 80261DB0 2442FFED */  addiu      $v0, $v0, -0x13
/* 19DF14 80261DB4 1860002C */  blez       $v1, .LPAL_80261E68
/* 19DF18 80261DB8 AFA20024 */   sw        $v0, 0x24($sp)
/* 19DF1C 80261DBC 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 19DF20 80261DC0 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 19DF24 80261DC4 24020001 */  addiu      $v0, $zero, 0x1
/* 19DF28 80261DC8 10620011 */  beq        $v1, $v0, .LPAL_80261E10
/* 19DF2C 80261DCC 28620002 */   slti      $v0, $v1, 0x2
/* 19DF30 80261DD0 10400005 */  beqz       $v0, .LPAL_80261DE8
/* 19DF34 80261DD4 24020002 */   addiu     $v0, $zero, 0x2
/* 19DF38 80261DD8 10600009 */  beqz       $v1, .LPAL_80261E00
/* 19DF3C 80261DDC 00000000 */   nop
/* 19DF40 80261DE0 08098793 */  j          .LPAL_80261E4C
/* 19DF44 80261DE4 00000000 */   nop
.LPAL_80261DE8:
/* 19DF48 80261DE8 1062000D */  beq        $v1, $v0, .LPAL_80261E20
/* 19DF4C 80261DEC 24020003 */   addiu     $v0, $zero, 0x3
/* 19DF50 80261DF0 1062000F */  beq        $v1, $v0, .LPAL_80261E30
/* 19DF54 80261DF4 00000000 */   nop
/* 19DF58 80261DF8 08098793 */  j          .LPAL_80261E4C
/* 19DF5C 80261DFC 00000000 */   nop
.LPAL_80261E00:
/* 19DF60 80261E00 3C048010 */  lui        $a0, %hi(D_801072D4)
/* 19DF64 80261E04 248472D4 */  addiu      $a0, $a0, %lo(D_801072D4)
/* 19DF68 80261E08 0809878E */  j          .LPAL_80261E38
/* 19DF6C 80261E0C 00000000 */   nop
.LPAL_80261E10:
/* 19DF70 80261E10 3C048010 */  lui        $a0, %hi(D_8010740C)
/* 19DF74 80261E14 2484740C */  addiu      $a0, $a0, %lo(D_8010740C)
/* 19DF78 80261E18 0809878E */  j          .LPAL_80261E38
/* 19DF7C 80261E1C 00000000 */   nop
.LPAL_80261E20:
/* 19DF80 80261E20 3C048010 */  lui        $a0, %hi(D_80107544)
/* 19DF84 80261E24 24847544 */  addiu      $a0, $a0, %lo(D_80107544)
/* 19DF88 80261E28 0809878E */  j          .LPAL_80261E38
/* 19DF8C 80261E2C 00000000 */   nop
.LPAL_80261E30:
/* 19DF90 80261E30 3C048010 */  lui        $a0, %hi(D_8010767C)
/* 19DF94 80261E34 2484767C */  addiu      $a0, $a0, %lo(D_8010767C)
.LPAL_80261E38:
/* 19DF98 80261E38 0C050015 */  jal        func_PAL_80140054
/* 19DF9C 80261E3C 00000000 */   nop
/* 19DFA0 80261E40 0040902D */  daddu      $s2, $v0, $zero
/* 19DFA4 80261E44 3C01802A */  lui        $at, %hi(D_802A01FC)
/* 19DFA8 80261E48 AC3201FC */  sw         $s2, %lo(D_802A01FC)($at)
.LPAL_80261E4C:
/* 19DFAC 80261E4C 8FA50020 */  lw         $a1, 0x20($sp)
/* 19DFB0 80261E50 8FA60024 */  lw         $a2, 0x24($sp)
/* 19DFB4 80261E54 0C050D4D */  jal        func_PAL_80143534
/* 19DFB8 80261E58 0240202D */   daddu     $a0, $s2, $zero
/* 19DFBC 80261E5C 8FA20024 */  lw         $v0, 0x24($sp)
/* 19DFC0 80261E60 24420009 */  addiu      $v0, $v0, 0x9
/* 19DFC4 80261E64 AFA20024 */  sw         $v0, 0x24($sp)
.LPAL_80261E68:
/* 19DFC8 80261E68 8E6200B0 */  lw         $v0, 0xB0($s3)
/* 19DFCC 80261E6C 1C400004 */  bgtz       $v0, .LPAL_80261E80
/* 19DFD0 80261E70 00000000 */   nop
/* 19DFD4 80261E74 8E6200B4 */  lw         $v0, 0xB4($s3)
/* 19DFD8 80261E78 18400029 */  blez       $v0, .LPAL_80261F20
/* 19DFDC 80261E7C 00000000 */   nop
.LPAL_80261E80:
/* 19DFE0 80261E80 3C038015 */  lui        $v1, %hi(gCurrentLanguage)
/* 19DFE4 80261E84 8C63AE4C */  lw         $v1, %lo(gCurrentLanguage)($v1)
/* 19DFE8 80261E88 24020001 */  addiu      $v0, $zero, 0x1
/* 19DFEC 80261E8C 10620011 */  beq        $v1, $v0, .LPAL_80261ED4
/* 19DFF0 80261E90 28620002 */   slti      $v0, $v1, 0x2
/* 19DFF4 80261E94 10400005 */  beqz       $v0, .LPAL_80261EAC
/* 19DFF8 80261E98 24020002 */   addiu     $v0, $zero, 0x2
/* 19DFFC 80261E9C 10600009 */  beqz       $v1, .LPAL_80261EC4
/* 19E000 80261EA0 00000000 */   nop
/* 19E004 80261EA4 080987C4 */  j          .LPAL_80261F10
/* 19E008 80261EA8 00000000 */   nop
.LPAL_80261EAC:
/* 19E00C 80261EAC 1062000D */  beq        $v1, $v0, .LPAL_80261EE4
/* 19E010 80261EB0 24020003 */   addiu     $v0, $zero, 0x3
/* 19E014 80261EB4 1062000F */  beq        $v1, $v0, .LPAL_80261EF4
/* 19E018 80261EB8 00000000 */   nop
/* 19E01C 80261EBC 080987C4 */  j          .LPAL_80261F10
/* 19E020 80261EC0 00000000 */   nop
.LPAL_80261EC4:
/* 19E024 80261EC4 3C048010 */  lui        $a0, %hi(D_801072AC)
/* 19E028 80261EC8 248472AC */  addiu      $a0, $a0, %lo(D_801072AC)
/* 19E02C 80261ECC 080987BF */  j          .LPAL_80261EFC
/* 19E030 80261ED0 00000000 */   nop
.LPAL_80261ED4:
/* 19E034 80261ED4 3C048010 */  lui        $a0, %hi(D_801073E4)
/* 19E038 80261ED8 248473E4 */  addiu      $a0, $a0, %lo(D_801073E4)
/* 19E03C 80261EDC 080987BF */  j          .LPAL_80261EFC
/* 19E040 80261EE0 00000000 */   nop
.LPAL_80261EE4:
/* 19E044 80261EE4 3C048010 */  lui        $a0, %hi(D_8010751C)
/* 19E048 80261EE8 2484751C */  addiu      $a0, $a0, %lo(D_8010751C)
/* 19E04C 80261EEC 080987BF */  j          .LPAL_80261EFC
/* 19E050 80261EF0 00000000 */   nop
.LPAL_80261EF4:
/* 19E054 80261EF4 3C048010 */  lui        $a0, %hi(D_80107654)
/* 19E058 80261EF8 24847654 */  addiu      $a0, $a0, %lo(D_80107654)
.LPAL_80261EFC:
/* 19E05C 80261EFC 0C050015 */  jal        func_PAL_80140054
/* 19E060 80261F00 00000000 */   nop
/* 19E064 80261F04 0040902D */  daddu      $s2, $v0, $zero
/* 19E068 80261F08 3C01802A */  lui        $at, %hi(D_802A01F8)
/* 19E06C 80261F0C AC3201F8 */  sw         $s2, %lo(D_802A01F8)($at)
.LPAL_80261F10:
/* 19E070 80261F10 8FA50020 */  lw         $a1, 0x20($sp)
/* 19E074 80261F14 8FA60024 */  lw         $a2, 0x24($sp)
/* 19E078 80261F18 0C050D4D */  jal        func_PAL_80143534
/* 19E07C 80261F1C 0240202D */   daddu     $a0, $s2, $zero
.LPAL_80261F20:
/* 19E080 80261F20 8FBF0040 */  lw         $ra, 0x40($sp)
/* 19E084 80261F24 8FB3003C */  lw         $s3, 0x3C($sp)
/* 19E088 80261F28 8FB20038 */  lw         $s2, 0x38($sp)
/* 19E08C 80261F2C 8FB10034 */  lw         $s1, 0x34($sp)
/* 19E090 80261F30 8FB00030 */  lw         $s0, 0x30($sp)
/* 19E094 80261F34 24020002 */  addiu      $v0, $zero, 0x2
/* 19E098 80261F38 03E00008 */  jr         $ra
/* 19E09C 80261F3C 27BD0048 */   addiu     $sp, $sp, 0x48
