.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

/* Generated by spimdisasm 1.11.1 */

glabel initialize_status_menu
/* 7D1B4 800E40A4 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 7D1B8 800E40A8 AFB20018 */  sw         $s2, 0x18($sp)
/* 7D1BC 800E40AC 3C128011 */  lui        $s2, %hi(D_8010DA58)
/* 7D1C0 800E40B0 2652DA58 */  addiu      $s2, $s2, %lo(D_8010DA58)
/* 7D1C4 800E40B4 2402000C */  addiu      $v0, $zero, 0xC
/* 7D1C8 800E40B8 AFBF001C */  sw         $ra, 0x1C($sp)
/* 7D1CC 800E40BC AFB10014 */  sw         $s1, 0x14($sp)
/* 7D1D0 800E40C0 AFB00010 */  sw         $s0, 0x10($sp)
/* 7D1D4 800E40C4 A6420034 */  sh         $v0, 0x34($s2)
/* 7D1D8 800E40C8 2402FF9C */  addiu      $v0, $zero, -0x64
/* 7D1DC 800E40CC 3C038011 */  lui        $v1, %hi(D_8010DD90)
/* 7D1E0 800E40D0 2463DD90 */  addiu      $v1, $v1, %lo(D_8010DD90)
/* 7D1E4 800E40D4 3C018011 */  lui        $at, %hi(D_8010B810)
/* 7D1E8 800E40D8 A420B810 */  sh         $zero, %lo(D_8010B810)($at)
/* 7D1EC 800E40DC 3C018011 */  lui        $at, %hi(D_8010B812)
/* 7D1F0 800E40E0 A420B812 */  sh         $zero, %lo(D_8010B812)($at)
/* 7D1F4 800E40E4 A6420036 */  sh         $v0, 0x36($s2)
/* 7D1F8 800E40E8 A240003A */  sb         $zero, 0x3A($s2)
/* 7D1FC 800E40EC 90640010 */  lbu        $a0, 0x10($v1)
/* 7D200 800E40F0 240200D2 */  addiu      $v0, $zero, 0xD2
/* 7D204 800E40F4 A6420038 */  sh         $v0, 0x38($s2)
/* 7D208 800E40F8 A240003B */  sb         $zero, 0x3B($s2)
/* 7D20C 800E40FC A2400044 */  sb         $zero, 0x44($s2)
/* 7D210 800E4100 A2400045 */  sb         $zero, 0x45($s2)
/* 7D214 800E4104 A2400046 */  sb         $zero, 0x46($s2)
/* 7D218 800E4108 A240004A */  sb         $zero, 0x4A($s2)
/* 7D21C 800E410C A240004B */  sb         $zero, 0x4B($s2)
/* 7D220 800E4110 A240004C */  sb         $zero, 0x4C($s2)
/* 7D224 800E4114 A240004D */  sb         $zero, 0x4D($s2)
/* 7D228 800E4118 A240004E */  sb         $zero, 0x4E($s2)
/* 7D22C 800E411C A240004F */  sb         $zero, 0x4F($s2)
/* 7D230 800E4120 A2400050 */  sb         $zero, 0x50($s2)
/* 7D234 800E4124 A2400051 */  sb         $zero, 0x51($s2)
/* 7D238 800E4128 A2400054 */  sb         $zero, 0x54($s2)
/* 7D23C 800E412C A2400055 */  sb         $zero, 0x55($s2)
/* 7D240 800E4130 A2400056 */  sb         $zero, 0x56($s2)
/* 7D244 800E4134 A2400047 */  sb         $zero, 0x47($s2)
/* 7D248 800E4138 A2400052 */  sb         $zero, 0x52($s2)
/* 7D24C 800E413C 90620002 */  lbu        $v0, 0x2($v1)
/* 7D250 800E4140 90650005 */  lbu        $a1, 0x5($v1)
/* 7D254 800E4144 9466000C */  lhu        $a2, 0xC($v1)
/* 7D258 800E4148 94630290 */  lhu        $v1, 0x290($v1)
/* 7D25C 800E414C 00042600 */  sll        $a0, $a0, 24
/* 7D260 800E4150 00042603 */  sra        $a0, $a0, 24
/* 7D264 800E4154 A242003D */  sb         $v0, 0x3D($s2)
/* 7D268 800E4158 2402FFFF */  addiu      $v0, $zero, -0x1
/* 7D26C 800E415C A245003E */  sb         $a1, 0x3E($s2)
/* 7D270 800E4160 A6460040 */  sh         $a2, 0x40($s2)
/* 7D274 800E4164 A6440042 */  sh         $a0, 0x42($s2)
/* 7D278 800E4168 A6430048 */  sh         $v1, 0x48($s2)
/* 7D27C 800E416C A2400053 */  sb         $zero, 0x53($s2)
/* 7D280 800E4170 A242006E */  sb         $v0, 0x6E($s2)
/* 7D284 800E4174 2402FFFF */  addiu      $v0, $zero, -0x1
/* 7D288 800E4178 A240003C */  sb         $zero, 0x3C($s2)
/* 7D28C 800E417C A2400057 */  sb         $zero, 0x57($s2)
/* 7D290 800E4180 A2400058 */  sb         $zero, 0x58($s2)
/* 7D294 800E4184 A2400059 */  sb         $zero, 0x59($s2)
/* 7D298 800E4188 A240005A */  sb         $zero, 0x5A($s2)
/* 7D29C 800E418C A240006C */  sb         $zero, 0x6C($s2)
/* 7D2A0 800E4190 A240006D */  sb         $zero, 0x6D($s2)
/* 7D2A4 800E4194 0C039804 */  jal        func_800E6010
/* 7D2A8 800E4198 AE420064 */   sw        $v0, 0x64($s2)
/* 7D2AC 800E419C 3C038015 */  lui        $v1, %hi(D_8014AE4C)
/* 7D2B0 800E41A0 8C63AE4C */  lw         $v1, %lo(D_8014AE4C)($v1)
/* 7D2B4 800E41A4 24020001 */  addiu      $v0, $zero, 0x1
/* 7D2B8 800E41A8 10620011 */  beq        $v1, $v0, .L800E41F0
/* 7D2BC 800E41AC 28620002 */   slti      $v0, $v1, 0x2
/* 7D2C0 800E41B0 10400005 */  beqz       $v0, .L800E41C8
/* 7D2C4 800E41B4 24020002 */   addiu     $v0, $zero, 0x2
/* 7D2C8 800E41B8 10600009 */  beqz       $v1, .L800E41E0
/* 7D2CC 800E41BC 0220202D */   daddu     $a0, $s1, $zero
/* 7D2D0 800E41C0 0803908B */  j          .L800E422C
/* 7D2D4 800E41C4 00000000 */   nop
.L800E41C8:
/* 7D2D8 800E41C8 1062000D */  beq        $v1, $v0, .L800E4200
/* 7D2DC 800E41CC 24020003 */   addiu     $v0, $zero, 0x3
/* 7D2E0 800E41D0 1062000F */  beq        $v1, $v0, .L800E4210
/* 7D2E4 800E41D4 0220202D */   daddu     $a0, $s1, $zero
/* 7D2E8 800E41D8 0803908B */  j          .L800E422C
/* 7D2EC 800E41DC 00000000 */   nop
.L800E41E0:
/* 7D2F0 800E41E0 3C048010 */  lui        $a0, %hi(D_80106958)
/* 7D2F4 800E41E4 24846958 */  addiu      $a0, $a0, %lo(D_80106958)
/* 7D2F8 800E41E8 08039086 */  j          .L800E4218
/* 7D2FC 800E41EC 00000000 */   nop
.L800E41F0:
/* 7D300 800E41F0 3C048010 */  lui        $a0, %hi(D_801069A8)
/* 7D304 800E41F4 248469A8 */  addiu      $a0, $a0, %lo(D_801069A8)
/* 7D308 800E41F8 08039086 */  j          .L800E4218
/* 7D30C 800E41FC 00000000 */   nop
.L800E4200:
/* 7D310 800E4200 3C048010 */  lui        $a0, %hi(D_801069F8)
/* 7D314 800E4204 248469F8 */  addiu      $a0, $a0, %lo(D_801069F8)
/* 7D318 800E4208 08039086 */  j          .L800E4218
/* 7D31C 800E420C 00000000 */   nop
.L800E4210:
/* 7D320 800E4210 3C048010 */  lui        $a0, %hi(D_80106A48)
/* 7D324 800E4214 24846A48 */  addiu      $a0, $a0, %lo(D_80106A48)
.L800E4218:
/* 7D328 800E4218 0C050015 */  jal        func_80140054
/* 7D32C 800E421C 00000000 */   nop
/* 7D330 800E4220 AE420000 */  sw         $v0, 0x0($s2)
/* 7D334 800E4224 0040882D */  daddu      $s1, $v0, $zero
/* 7D338 800E4228 0220202D */  daddu      $a0, $s1, $zero
.L800E422C:
/* 7D33C 800E422C 0C050D6C */  jal        func_801435B0
/* 7D340 800E4230 24050080 */   addiu     $a1, $zero, 0x80
/* 7D344 800E4234 0220202D */  daddu      $a0, $s1, $zero
/* 7D348 800E4238 0C050D77 */  jal        func_801435DC
/* 7D34C 800E423C 34058000 */   ori       $a1, $zero, 0x8000
/* 7D350 800E4240 3C048010 */  lui        $a0, %hi(D_80106D18)
/* 7D354 800E4244 24846D18 */  addiu      $a0, $a0, %lo(D_80106D18)
/* 7D358 800E4248 0C050015 */  jal        func_80140054
/* 7D35C 800E424C 00000000 */   nop
/* 7D360 800E4250 0040882D */  daddu      $s1, $v0, $zero
/* 7D364 800E4254 0220202D */  daddu      $a0, $s1, $zero
/* 7D368 800E4258 24050080 */  addiu      $a1, $zero, 0x80
/* 7D36C 800E425C 0C050D6C */  jal        func_801435B0
/* 7D370 800E4260 AE510004 */   sw        $s1, 0x4($s2)
/* 7D374 800E4264 0220202D */  daddu      $a0, $s1, $zero
/* 7D378 800E4268 0C050D77 */  jal        func_801435DC
/* 7D37C 800E426C 34058000 */   ori       $a1, $zero, 0x8000
/* 7D380 800E4270 3C038015 */  lui        $v1, %hi(D_8014AE4C)
/* 7D384 800E4274 8C63AE4C */  lw         $v1, %lo(D_8014AE4C)($v1)
/* 7D388 800E4278 24020001 */  addiu      $v0, $zero, 0x1
/* 7D38C 800E427C 10620011 */  beq        $v1, $v0, .L800E42C4
/* 7D390 800E4280 28620002 */   slti      $v0, $v1, 0x2
/* 7D394 800E4284 10400005 */  beqz       $v0, .L800E429C
/* 7D398 800E4288 24020002 */   addiu     $v0, $zero, 0x2
/* 7D39C 800E428C 10600009 */  beqz       $v1, .L800E42B4
/* 7D3A0 800E4290 00000000 */   nop
/* 7D3A4 800E4294 080390C0 */  j          .L800E4300
/* 7D3A8 800E4298 0220202D */   daddu     $a0, $s1, $zero
.L800E429C:
/* 7D3AC 800E429C 1062000D */  beq        $v1, $v0, .L800E42D4
/* 7D3B0 800E42A0 24020003 */   addiu     $v0, $zero, 0x3
/* 7D3B4 800E42A4 1062000F */  beq        $v1, $v0, .L800E42E4
/* 7D3B8 800E42A8 00000000 */   nop
/* 7D3BC 800E42AC 080390C0 */  j          .L800E4300
/* 7D3C0 800E42B0 0220202D */   daddu     $a0, $s1, $zero
.L800E42B4:
/* 7D3C4 800E42B4 3C048010 */  lui        $a0, %hi(D_80106980)
/* 7D3C8 800E42B8 24846980 */  addiu      $a0, $a0, %lo(D_80106980)
/* 7D3CC 800E42BC 080390BB */  j          .L800E42EC
/* 7D3D0 800E42C0 00000000 */   nop
.L800E42C4:
/* 7D3D4 800E42C4 3C048010 */  lui        $a0, %hi(D_801069D0)
/* 7D3D8 800E42C8 248469D0 */  addiu      $a0, $a0, %lo(D_801069D0)
/* 7D3DC 800E42CC 080390BB */  j          .L800E42EC
/* 7D3E0 800E42D0 00000000 */   nop
.L800E42D4:
/* 7D3E4 800E42D4 3C048010 */  lui        $a0, %hi(D_80106A20)
/* 7D3E8 800E42D8 24846A20 */  addiu      $a0, $a0, %lo(D_80106A20)
/* 7D3EC 800E42DC 080390BB */  j          .L800E42EC
/* 7D3F0 800E42E0 00000000 */   nop
.L800E42E4:
/* 7D3F4 800E42E4 3C048010 */  lui        $a0, %hi(D_80106A70)
/* 7D3F8 800E42E8 24846A70 */  addiu      $a0, $a0, %lo(D_80106A70)
.L800E42EC:
/* 7D3FC 800E42EC 0C050015 */  jal        func_80140054
/* 7D400 800E42F0 00000000 */   nop
/* 7D404 800E42F4 AE420008 */  sw         $v0, 0x8($s2)
/* 7D408 800E42F8 0040882D */  daddu      $s1, $v0, $zero
/* 7D40C 800E42FC 0220202D */  daddu      $a0, $s1, $zero
.L800E4300:
/* 7D410 800E4300 0C050D6C */  jal        func_801435B0
/* 7D414 800E4304 24050080 */   addiu     $a1, $zero, 0x80
/* 7D418 800E4308 0220202D */  daddu      $a0, $s1, $zero
/* 7D41C 800E430C 0C050D77 */  jal        func_801435DC
/* 7D420 800E4310 34058000 */   ori       $a1, $zero, 0x8000
/* 7D424 800E4314 3C048010 */  lui        $a0, %hi(D_80106D38)
/* 7D428 800E4318 24846D38 */  addiu      $a0, $a0, %lo(D_80106D38)
/* 7D42C 800E431C 0C050015 */  jal        func_80140054
/* 7D430 800E4320 00000000 */   nop
/* 7D434 800E4324 0040882D */  daddu      $s1, $v0, $zero
/* 7D438 800E4328 0220202D */  daddu      $a0, $s1, $zero
/* 7D43C 800E432C 24050080 */  addiu      $a1, $zero, 0x80
/* 7D440 800E4330 0C050D6C */  jal        func_801435B0
/* 7D444 800E4334 AE51000C */   sw        $s1, 0xC($s2)
/* 7D448 800E4338 0220202D */  daddu      $a0, $s1, $zero
/* 7D44C 800E433C 0C050D77 */  jal        func_801435DC
/* 7D450 800E4340 34058000 */   ori       $a1, $zero, 0x8000
/* 7D454 800E4344 3C048010 */  lui        $a0, %hi(D_80106D58)
/* 7D458 800E4348 24846D58 */  addiu      $a0, $a0, %lo(D_80106D58)
/* 7D45C 800E434C 0C050015 */  jal        func_80140054
/* 7D460 800E4350 00000000 */   nop
/* 7D464 800E4354 0040882D */  daddu      $s1, $v0, $zero
/* 7D468 800E4358 0220202D */  daddu      $a0, $s1, $zero
/* 7D46C 800E435C 24050080 */  addiu      $a1, $zero, 0x80
/* 7D470 800E4360 0C050D6C */  jal        func_801435B0
/* 7D474 800E4364 AE510010 */   sw        $s1, 0x10($s2)
/* 7D478 800E4368 0220202D */  daddu      $a0, $s1, $zero
/* 7D47C 800E436C 0C050D77 */  jal        func_801435DC
/* 7D480 800E4370 34058000 */   ori       $a1, $zero, 0x8000
/* 7D484 800E4374 3C048008 */  lui        $a0, %hi(D_8007D364)
/* 7D488 800E4378 2484D364 */  addiu      $a0, $a0, %lo(D_8007D364)
/* 7D48C 800E437C 0C050015 */  jal        func_80140054
/* 7D490 800E4380 00000000 */   nop
/* 7D494 800E4384 0040882D */  daddu      $s1, $v0, $zero
/* 7D498 800E4388 0220202D */  daddu      $a0, $s1, $zero
/* 7D49C 800E438C 24050080 */  addiu      $a1, $zero, 0x80
/* 7D4A0 800E4390 0C050D6C */  jal        func_801435B0
/* 7D4A4 800E4394 AE510014 */   sw        $s1, 0x14($s2)
/* 7D4A8 800E4398 0220202D */  daddu      $a0, $s1, $zero
/* 7D4AC 800E439C 0C050D77 */  jal        func_801435DC
/* 7D4B0 800E43A0 34058000 */   ori       $a1, $zero, 0x8000
/* 7D4B4 800E43A4 3C048010 */  lui        $a0, %hi(D_80106EAC)
/* 7D4B8 800E43A8 24846EAC */  addiu      $a0, $a0, %lo(D_80106EAC)
/* 7D4BC 800E43AC 0C050015 */  jal        func_80140054
/* 7D4C0 800E43B0 00000000 */   nop
/* 7D4C4 800E43B4 0040882D */  daddu      $s1, $v0, $zero
/* 7D4C8 800E43B8 0220202D */  daddu      $a0, $s1, $zero
/* 7D4CC 800E43BC 24050080 */  addiu      $a1, $zero, 0x80
/* 7D4D0 800E43C0 0C050D6C */  jal        func_801435B0
/* 7D4D4 800E43C4 AE510018 */   sw        $s1, 0x18($s2)
/* 7D4D8 800E43C8 0220202D */  daddu      $a0, $s1, $zero
/* 7D4DC 800E43CC 0C050D77 */  jal        func_801435DC
/* 7D4E0 800E43D0 34058000 */   ori       $a1, $zero, 0x8000
/* 7D4E4 800E43D4 3C048010 */  lui        $a0, %hi(D_80102EDC)
/* 7D4E8 800E43D8 24842EDC */  addiu      $a0, $a0, %lo(D_80102EDC)
/* 7D4EC 800E43DC 0C050015 */  jal        func_80140054
/* 7D4F0 800E43E0 00000000 */   nop
/* 7D4F4 800E43E4 0040882D */  daddu      $s1, $v0, $zero
/* 7D4F8 800E43E8 0220202D */  daddu      $a0, $s1, $zero
/* 7D4FC 800E43EC 24050080 */  addiu      $a1, $zero, 0x80
/* 7D500 800E43F0 0C050D6C */  jal        func_801435B0
/* 7D504 800E43F4 AE51001C */   sw        $s1, 0x1C($s2)
/* 7D508 800E43F8 0220202D */  daddu      $a0, $s1, $zero
/* 7D50C 800E43FC 0C050D77 */  jal        func_801435DC
/* 7D510 800E4400 34058000 */   ori       $a1, $zero, 0x8000
/* 7D514 800E4404 3C108010 */  lui        $s0, %hi(D_80106778)
/* 7D518 800E4408 26106778 */  addiu      $s0, $s0, %lo(D_80106778)
/* 7D51C 800E440C 0C050015 */  jal        func_80140054
/* 7D520 800E4410 0200202D */   daddu     $a0, $s0, $zero
/* 7D524 800E4414 0040882D */  daddu      $s1, $v0, $zero
/* 7D528 800E4418 0220202D */  daddu      $a0, $s1, $zero
/* 7D52C 800E441C 24050082 */  addiu      $a1, $zero, 0x82
/* 7D530 800E4420 0C050D6C */  jal        func_801435B0
/* 7D534 800E4424 AE510020 */   sw        $s1, 0x20($s2)
/* 7D538 800E4428 0220202D */  daddu      $a0, $s1, $zero
/* 7D53C 800E442C 0C050D77 */  jal        func_801435DC
/* 7D540 800E4430 34058000 */   ori       $a1, $zero, 0x8000
/* 7D544 800E4434 0C050015 */  jal        func_80140054
/* 7D548 800E4438 0200202D */   daddu     $a0, $s0, $zero
/* 7D54C 800E443C 0040882D */  daddu      $s1, $v0, $zero
/* 7D550 800E4440 0220202D */  daddu      $a0, $s1, $zero
/* 7D554 800E4444 24050082 */  addiu      $a1, $zero, 0x82
/* 7D558 800E4448 0C050D6C */  jal        func_801435B0
/* 7D55C 800E444C AE510024 */   sw        $s1, 0x24($s2)
/* 7D560 800E4450 0220202D */  daddu      $a0, $s1, $zero
/* 7D564 800E4454 0C050D77 */  jal        func_801435DC
/* 7D568 800E4458 34058000 */   ori       $a1, $zero, 0x8000
/* 7D56C 800E445C 0C050015 */  jal        func_80140054
/* 7D570 800E4460 0200202D */   daddu     $a0, $s0, $zero
/* 7D574 800E4464 0040882D */  daddu      $s1, $v0, $zero
/* 7D578 800E4468 0220202D */  daddu      $a0, $s1, $zero
/* 7D57C 800E446C 24050082 */  addiu      $a1, $zero, 0x82
/* 7D580 800E4470 0C050D6C */  jal        func_801435B0
/* 7D584 800E4474 AE510028 */   sw        $s1, 0x28($s2)
/* 7D588 800E4478 0220202D */  daddu      $a0, $s1, $zero
/* 7D58C 800E447C 0C050D77 */  jal        func_801435DC
/* 7D590 800E4480 34058000 */   ori       $a1, $zero, 0x8000
/* 7D594 800E4484 0C050015 */  jal        func_80140054
/* 7D598 800E4488 0200202D */   daddu     $a0, $s0, $zero
/* 7D59C 800E448C 0040882D */  daddu      $s1, $v0, $zero
/* 7D5A0 800E4490 0220202D */  daddu      $a0, $s1, $zero
/* 7D5A4 800E4494 24050082 */  addiu      $a1, $zero, 0x82
/* 7D5A8 800E4498 0C050D6C */  jal        func_801435B0
/* 7D5AC 800E449C AE51002C */   sw        $s1, 0x2C($s2)
/* 7D5B0 800E44A0 0220202D */  daddu      $a0, $s1, $zero
/* 7D5B4 800E44A4 0C050D77 */  jal        func_801435DC
/* 7D5B8 800E44A8 34058000 */   ori       $a1, $zero, 0x8000
/* 7D5BC 800E44AC 3C048010 */  lui        $a0, %hi(D_80106BD8)
/* 7D5C0 800E44B0 24846BD8 */  addiu      $a0, $a0, %lo(D_80106BD8)
/* 7D5C4 800E44B4 0C050015 */  jal        func_80140054
/* 7D5C8 800E44B8 00000000 */   nop
/* 7D5CC 800E44BC 0040882D */  daddu      $s1, $v0, $zero
/* 7D5D0 800E44C0 0220202D */  daddu      $a0, $s1, $zero
/* 7D5D4 800E44C4 24050080 */  addiu      $a1, $zero, 0x80
/* 7D5D8 800E44C8 0C050D6C */  jal        func_801435B0
/* 7D5DC 800E44CC AE510030 */   sw        $s1, 0x30($s2)
/* 7D5E0 800E44D0 0220202D */  daddu      $a0, $s1, $zero
/* 7D5E4 800E44D4 0C050D77 */  jal        func_801435DC
/* 7D5E8 800E44D8 34058000 */   ori       $a1, $zero, 0x8000
/* 7D5EC 800E44DC 0C03B56B */  jal        func_800ED5AC
/* 7D5F0 800E44E0 00000000 */   nop
/* 7D5F4 800E44E4 8FBF001C */  lw         $ra, 0x1C($sp)
/* 7D5F8 800E44E8 8FB20018 */  lw         $s2, 0x18($sp)
/* 7D5FC 800E44EC 8FB10014 */  lw         $s1, 0x14($sp)
/* 7D600 800E44F0 8FB00010 */  lw         $s0, 0x10($sp)
/* 7D604 800E44F4 03E00008 */  jr         $ra
/* 7D608 800E44F8 27BD0020 */   addiu     $sp, $sp, 0x20
